<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Three20UI/Headers/TTMessageController.h Source File</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&nbsp;List</span></a></li>
      <li><a href="globals.php"><span>File&nbsp;Members</span></a></li>
    </ul>
  </div>
<div class="header">
  <div class="headertitle">
<h1>Three20UI/Headers/TTMessageController.h</h1>  </div>
</div>
<div class="contents">
<div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">//</span>
<a name="l00002"></a>00002 <span class="comment">// Copyright 2009-2010 Facebook</span>
<a name="l00003"></a>00003 <span class="comment">//</span>
<a name="l00004"></a>00004 <span class="comment">// Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);</span>
<a name="l00005"></a>00005 <span class="comment">// you may not use this file except in compliance with the License.</span>
<a name="l00006"></a>00006 <span class="comment">// You may obtain a copy of the License at</span>
<a name="l00007"></a>00007 <span class="comment">//</span>
<a name="l00008"></a>00008 <span class="comment">//    http://www.apache.org/licenses/LICENSE-2.0</span>
<a name="l00009"></a>00009 <span class="comment">//</span>
<a name="l00010"></a>00010 <span class="comment">// Unless required by applicable law or agreed to in writing, software</span>
<a name="l00011"></a>00011 <span class="comment">// distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span>
<a name="l00012"></a>00012 <span class="comment">// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span>
<a name="l00013"></a>00013 <span class="comment">// See the License for the specific language governing permissions and</span>
<a name="l00014"></a>00014 <span class="comment">// limitations under the License.</span>
<a name="l00015"></a>00015 <span class="comment">//</span>
<a name="l00016"></a>00016 
<a name="l00017"></a>00017 <span class="comment">// UI</span>
<a name="l00018"></a>00018 <span class="preprocessor">#import &quot;Three20UI/TTViewController.h&quot;</span>
<a name="l00019"></a>00019 <span class="preprocessor">#import &quot;Three20UI/TTTextEditorDelegate.h&quot;</span>
<a name="l00020"></a>00020 
<a name="l00021"></a>00021 <span class="keyword">@protocol </span><a class="code" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a>;
<a name="l00022"></a>00022 <span class="keyword">@protocol </span><a class="code" href="protocol_t_t_message_controller_delegate-p.php" title="A protocol for the object that implements the backend logic for the TTMessageController.">TTMessageControllerDelegate</a>;
<a name="l00023"></a>00023 <span class="keyword">@class</span> <a class="code" href="interface_t_t_picker_text_field.php">TTPickerTextField</a>;
<a name="l00024"></a>00024 <span class="keyword">@class</span> <a class="code" href="interface_t_t_activity_label.php">TTActivityLabel</a>;
<a name="l00025"></a>00025 <span class="keyword">@class</span> <a class="code" href="interface_t_t_text_editor.php">TTTextEditor</a>;
<a name="l00026"></a>00026 
<a name="l00041"></a><a class="code" href="interface_t_t_message_controller.php">00041</a> <span class="keyword">@interface </span><a class="code" href="interface_t_t_message_controller.php" title="A view controller for composing email like messages, which is visually similar to Apple&amp;#39;s in-app ...">TTMessageController</a> : <a class="code" href="interface_t_t_view_controller.php" title="A view controller with some useful additions.">TTViewController</a> &lt;UITextFieldDelegate, <a class="code" href="protocol_t_t_text_editor_delegate-p.php">TTTextEditorDelegate</a>&gt; {
<a name="l00042"></a>00042 <span class="keyword">@protected</span>
<a name="l00043"></a>00043   <a class="code" href="class_n_s_array.php" title="Additions.">NSArray</a>*          _fields;
<a name="l00044"></a>00044   <a class="code" href="class_n_s_mutable_array.php" title="Additions.">NSMutableArray</a>*   _fieldViews;
<a name="l00045"></a>00045   UIScrollView*     _scrollView;
<a name="l00046"></a>00046   <a class="code" href="interface_t_t_text_editor.php">TTTextEditor</a>*     _textEditor;
<a name="l00047"></a>00047   <a class="code" href="interface_t_t_activity_label.php">TTActivityLabel</a>*  _activityView;
<a name="l00048"></a>00048   <a class="code" href="class_n_s_array.php" title="Additions.">NSArray</a>*          _initialRecipients;
<a name="l00049"></a>00049 
<a name="l00050"></a>00050   BOOL _showsRecipientPicker;
<a name="l00051"></a>00051   BOOL _isModified;
<a name="l00052"></a>00052 
<a name="l00053"></a>00053   id&lt;TTTableViewDataSource&gt;       _dataSource;
<a name="l00054"></a>00054   id&lt;TTMessageControllerDelegate&gt; _delegate;
<a name="l00055"></a>00055 }
<a name="l00056"></a>00056 
<a name="l00061"></a><a class="code" href="interface_t_t_message_controller.php#a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed">00061</a> @property (nonatomic, assign) id&lt;<a class="code" href="protocol_t_t_message_controller_delegate-p.php" title="A protocol for the object that implements the backend logic for the TTMessageController.">TTMessageControllerDelegate</a>&gt; delegate;
<a name="l00062"></a>00062 
<a name="l00068"></a><a class="code" href="interface_t_t_message_controller.php#a577f1d8cad6e8591a4759f11d36aad2d">00068</a> @property (nonatomic, retain) <span class="keywordtype">id</span>&lt;<a class="code" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a>&gt; dataSource;
<a name="l00069"></a>00069 
<a name="l00074"></a><a class="code" href="interface_t_t_message_controller.php#a81c2daf27f3f8f21cecf0a92fa45b1d3">00074</a> @property (nonatomic, retain) <a class="code" href="class_n_s_array.php" title="Additions.">NSArray</a>* fields;
<a name="l00075"></a>00075 
<a name="l00081"></a><a class="code" href="interface_t_t_message_controller.php#a8414169377f297b9fcb41bbc9c0a058d">00081</a> @property (nonatomic, retain) <a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>* subject;
<a name="l00082"></a>00082 
<a name="l00087"></a><a class="code" href="interface_t_t_message_controller.php#a179539948de0b4377b0559e9ef2c57e6">00087</a> @property (nonatomic, retain) <a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>* body;
<a name="l00088"></a>00088 
<a name="l00093"></a><a class="code" href="interface_t_t_message_controller.php#a81e95b4725b4c6ad3bb9a534fa045660">00093</a> @property (nonatomic) BOOL showsRecipientPicker;
<a name="l00094"></a>00094 
<a name="l00100"></a><a class="code" href="interface_t_t_message_controller.php#aa41f369642a1ce1afcfc381972d79d68">00100</a> @property (nonatomic, readonly) BOOL isModified;
<a name="l00101"></a>00101 
<a name="l00102"></a>00102 
<a name="l00111"></a>00111 - (<span class="keywordtype">id</span>)initWithRecipients:(<a class="code" href="class_n_s_array.php" title="Additions.">NSArray</a>*)recipients;
<a name="l00112"></a>00112 
<a name="l00123"></a>00123 - (<span class="keywordtype">void</span>)addRecipient:(<span class="keywordtype">id</span>)recipient forFieldAtIndex:(NSUInteger)fieldIndex;
<a name="l00124"></a>00124 
<a name="l00131"></a>00131 - (<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)textForFieldAtIndex:(NSUInteger)fieldIndex;
<a name="l00132"></a>00132 
<a name="l00137"></a>00137 - (<span class="keywordtype">void</span>)setText:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)text forFieldAtIndex:(NSUInteger)fieldIndex;
<a name="l00138"></a>00138 
<a name="l00144"></a>00144 - (BOOL)fieldHasValueAtIndex:(NSUInteger)fieldIndex;
<a name="l00145"></a>00145 
<a name="l00150"></a>00150 - (<a class="code" href="class_u_i_view.php">UIView</a>*)viewForFieldAtIndex:(NSUInteger)fieldIndex;
<a name="l00151"></a>00151 
<a name="l00157"></a>00157 - (<span class="keywordtype">void</span>)showActivityView:(BOOL)show;
<a name="l00158"></a>00158 
<a name="l00164"></a>00164 - (<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)titleForSending;
<a name="l00165"></a>00165 
<a name="l00169"></a>00169 - (<span class="keywordtype">void</span>)send;
<a name="l00170"></a>00170 
<a name="l00174"></a>00174 - (<span class="keywordtype">void</span>)cancel:(BOOL)confirmIfNecessary;
<a name="l00175"></a>00175 
<a name="l00179"></a>00179 - (<span class="keywordtype">void</span>)confirmCancellation;
<a name="l00180"></a>00180 
<a name="l00185"></a>00185 - (<span class="keywordtype">void</span>)messageWillSend:(<a class="code" href="class_n_s_array.php" title="Additions.">NSArray</a>*)fields;
<a name="l00186"></a>00186 
<a name="l00191"></a>00191 - (<span class="keywordtype">void</span>)messageWillShowRecipientPicker;
<a name="l00192"></a>00192 
<a name="l00197"></a>00197 - (<span class="keywordtype">void</span>)messageDidSend;
<a name="l00198"></a>00198 
<a name="l00205"></a>00205 - (BOOL)messageShouldCancel;
<a name="l00206"></a>00206 
<a name="l00207"></a>00207 @end
</pre></div></div>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
