<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: Three20UINavigator/Headers/TTBaseNavigator.h Source File</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&nbsp;List</span></a></li>
      <li><a href="globals.php"><span>File&nbsp;Members</span></a></li>
    </ul>
  </div>
<div class="header">
  <div class="headertitle">
<h1>Three20UINavigator/Headers/TTBaseNavigator.h</h1>  </div>
</div>
<div class="contents">
<div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">//</span>
<a name="l00002"></a>00002 <span class="comment">// Copyright 2009-2011 Facebook</span>
<a name="l00003"></a>00003 <span class="comment">//</span>
<a name="l00004"></a>00004 <span class="comment">// Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);</span>
<a name="l00005"></a>00005 <span class="comment">// you may not use this file except in compliance with the License.</span>
<a name="l00006"></a>00006 <span class="comment">// You may obtain a copy of the License at</span>
<a name="l00007"></a>00007 <span class="comment">//</span>
<a name="l00008"></a>00008 <span class="comment">//    http://www.apache.org/licenses/LICENSE-2.0</span>
<a name="l00009"></a>00009 <span class="comment">//</span>
<a name="l00010"></a>00010 <span class="comment">// Unless required by applicable law or agreed to in writing, software</span>
<a name="l00011"></a>00011 <span class="comment">// distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span>
<a name="l00012"></a>00012 <span class="comment">// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span>
<a name="l00013"></a>00013 <span class="comment">// See the License for the specific language governing permissions and</span>
<a name="l00014"></a>00014 <span class="comment">// limitations under the License.</span>
<a name="l00015"></a>00015 <span class="comment">//</span>
<a name="l00016"></a>00016 
<a name="l00017"></a>00017 <span class="preprocessor">#import &lt;Foundation/Foundation.h&gt;</span>
<a name="l00018"></a>00018 <span class="preprocessor">#import &lt;UIKit/UIKit.h&gt;</span>
<a name="l00019"></a>00019 
<a name="l00020"></a>00020 <span class="preprocessor">#import &quot;Three20UINavigator/TTNavigatorPersistenceMode.h&quot;</span>
<a name="l00021"></a>00021 
<a name="l00022"></a>00022 <span class="keyword">@protocol </span><a class="code" href="protocol_t_t_navigator_delegate-p.php">TTNavigatorDelegate</a>;
<a name="l00023"></a>00023 <span class="keyword">@protocol </span><a class="code" href="protocol_t_t_navigator_root_container-p.php">TTNavigatorRootContainer</a>;
<a name="l00024"></a>00024 <span class="keyword">@class</span> <a class="code" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&amp;#39;s openURLAction...">TTURLAction</a>;
<a name="l00025"></a>00025 <span class="keyword">@class</span> <a class="code" href="interface_t_t_u_r_l_map.php">TTURLMap</a>;
<a name="l00026"></a>00026 <span class="keyword">@class</span> <a class="code" href="interface_t_t_u_r_l_pattern.php">TTURLPattern</a>;
<a name="l00027"></a>00027 
<a name="l00031"></a><a class="code" href="interface_t_t_base_navigator.php">00031</a> <span class="keyword">@interface </span><a class="code" href="interface_t_t_base_navigator.php" title="A URL-based navigation system with built-in persistence.">TTBaseNavigator</a> : <a class="code" href="class_n_s_object.php" title="Additions.">NSObject</a> &lt;
<a name="l00032"></a>00032   UIPopoverControllerDelegate
<a name="l00033"></a>00033 &gt; {
<a name="l00034"></a>00034   <a class="code" href="interface_t_t_u_r_l_map.php">TTURLMap</a>*                   _URLMap;
<a name="l00035"></a>00035 
<a name="l00036"></a>00036   <a class="code" href="class_u_i_window.php" title="Additions.">UIWindow</a>*                   _window;
<a name="l00037"></a>00037 
<a name="l00038"></a>00038   <a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*           _rootViewController;
<a name="l00039"></a>00039   <a class="code" href="class_n_s_mutable_array.php" title="Additions.">NSMutableArray</a>*             _delayedControllers;
<a name="l00040"></a>00040   UIPopoverController*        _popoverController;
<a name="l00041"></a>00041 
<a name="l00042"></a>00042   <a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*                   _persistenceKey;
<a name="l00043"></a>00043   TTNavigatorPersistenceMode  _persistenceMode;
<a name="l00044"></a>00044   NSTimeInterval              _persistenceExpirationAge;
<a name="l00045"></a>00045 
<a name="l00046"></a>00046   BOOL                        _delayCount;
<a name="l00047"></a>00047 
<a name="l00048"></a>00048   BOOL                        _supportsShakeToReload;
<a name="l00049"></a>00049   BOOL                        _opensExternalURLs;
<a name="l00050"></a>00050 
<a name="l00051"></a>00051   id&lt;TTNavigatorDelegate&gt;       _delegate;
<a name="l00052"></a>00052   id&lt;TTNavigatorRootContainer&gt;  _rootContainer;
<a name="l00053"></a>00053 }
<a name="l00054"></a>00054 
<a name="l00060"></a><a class="code" href="interface_t_t_base_navigator.php#a584f4a80461eea29d39b085acb023704">00060</a> @property (nonatomic, readonly) <a class="code" href="interface_t_t_u_r_l_map.php">TTURLMap</a>* URLMap;
<a name="l00061"></a>00061 
<a name="l00068"></a>00068 @property (nonatomic, retain) <a class="code" href="class_u_i_window.php" title="Additions.">UIWindow</a>* window;
<a name="l00069"></a>00069 
<a name="l00077"></a><a class="code" href="interface_t_t_base_navigator.php#a060fe6a28f50c4eac1753965a153077c">00077</a> @property (nonatomic, assign) <span class="keywordtype">id</span>&lt;<a class="code" href="protocol_t_t_navigator_root_container-p.php">TTNavigatorRootContainer</a>&gt; rootContainer;
<a name="l00078"></a>00078 
<a name="l00082"></a><a class="code" href="interface_t_t_base_navigator.php#a5568a0c8e0a19d26306e9d160d302b6e">00082</a> @property (nonatomic, readonly) <a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>* rootViewController;
<a name="l00083"></a>00083 
<a name="l00087"></a><a class="code" href="interface_t_t_base_navigator.php#abe08b1203a02a91fe9b81f8dbb6cbda1">00087</a> @property (nonatomic, readonly) <a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>* visibleViewController;
<a name="l00088"></a>00088 
<a name="l00095"></a><a class="code" href="interface_t_t_base_navigator.php#a9d5c8ea878103dd007eb3012d3749210">00095</a> @property (nonatomic, readonly) <a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>* topViewController;
<a name="l00096"></a>00096 
<a name="l00102"></a><a class="code" href="interface_t_t_base_navigator.php#a1ffbcfbcbefed8badea9d3bcbe21681a">00102</a> @property (nonatomic, copy) <a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>* URL;
<a name="l00103"></a>00103 
<a name="l00114"></a><a class="code" href="interface_t_t_base_navigator.php#afc067091161086784d8c2d95be39083a">00114</a> @property (nonatomic, copy) <a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>* persistenceKey;
<a name="l00115"></a>00115 
<a name="l00121"></a><a class="code" href="interface_t_t_base_navigator.php#af4584c3f244a628f9986960f5973cb92">00121</a> @property (nonatomic) TTNavigatorPersistenceMode persistenceMode;
<a name="l00122"></a>00122 
<a name="l00134"></a><a class="code" href="interface_t_t_base_navigator.php#abe6d7ee14fd1147201694ffdfdb3228d">00134</a> @property (nonatomic) NSTimeInterval persistenceExpirationAge;
<a name="l00135"></a>00135 
<a name="l00141"></a><a class="code" href="interface_t_t_base_navigator.php#ad49b7a6c9a4820d955a7eaf3687c05f2">00141</a> @property (nonatomic) BOOL supportsShakeToReload;
<a name="l00142"></a>00142 
<a name="l00148"></a><a class="code" href="interface_t_t_base_navigator.php#a093b7725f813a2819977991b416df181">00148</a> @property (nonatomic) BOOL opensExternalURLs;
<a name="l00149"></a>00149 
<a name="l00155"></a><a class="code" href="interface_t_t_base_navigator.php#aaaa44f8ff42826f21da0fa61bc55e22e">00155</a> @property (nonatomic, readonly) BOOL isDelayed;
<a name="l00156"></a>00156 
<a name="l00157"></a>00157 @property (nonatomic, assign) <span class="keywordtype">id</span>&lt;<a class="code" href="protocol_t_t_navigator_delegate-p.php">TTNavigatorDelegate</a>&gt; delegate;
<a name="l00158"></a>00158 
<a name="l00168"></a>00168 + (<a class="code" href="interface_t_t_base_navigator.php" title="A URL-based navigation system with built-in persistence.">TTBaseNavigator</a>*)navigatorForView:(<a class="code" href="class_u_i_view.php" title="Additions.">UIView</a>*)view;
<a name="l00169"></a>00169 
<a name="l00170"></a>00170 + (<a class="code" href="interface_t_t_base_navigator.php" title="A URL-based navigation system with built-in persistence.">TTBaseNavigator</a>*)globalNavigator;
<a name="l00171"></a>00171 + (<span class="keywordtype">void</span>)setGlobalNavigator:(<a class="code" href="interface_t_t_base_navigator.php" title="A URL-based navigation system with built-in persistence.">TTBaseNavigator</a>*)navigator;
<a name="l00172"></a>00172 
<a name="l00191"></a>00191 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)openURLAction:(<a class="code" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&amp;#39;s openURLAction...">TTURLAction</a>*)URLAction;
<a name="l00192"></a>00192 
<a name="l00198"></a>00198 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)openURLs:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)URL,...;
<a name="l00199"></a>00199 
<a name="l00205"></a>00205 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)viewControllerForURL:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)URL;
<a name="l00206"></a>00206 
<a name="l00212"></a>00212 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)viewControllerForURL:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)URL query:(<a class="code" href="class_n_s_dictionary.php">NSDictionary</a>*)query;
<a name="l00213"></a>00213 
<a name="l00219"></a>00219 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)viewControllerForURL:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)URL query:(<a class="code" href="class_n_s_dictionary.php">NSDictionary</a>*)query
<a name="l00220"></a>00220                                   pattern:(<a class="code" href="interface_t_t_u_r_l_pattern.php">TTURLPattern</a>**)pattern;
<a name="l00221"></a>00221 
<a name="l00229"></a>00229 - (<span class="keywordtype">void</span>)beginDelay;
<a name="l00230"></a>00230 
<a name="l00234"></a>00234 - (<span class="keywordtype">void</span>)endDelay;
<a name="l00235"></a>00235 
<a name="l00239"></a>00239 - (<span class="keywordtype">void</span>)cancelDelay;
<a name="l00240"></a>00240 
<a name="l00244"></a>00244 - (<span class="keywordtype">void</span>)persistViewControllers;
<a name="l00245"></a>00245 
<a name="l00249"></a>00249 - (<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)restoreViewControllers;
<a name="l00250"></a>00250 
<a name="l00257"></a>00257 - (<span class="keywordtype">void</span>)persistController:(<a class="code" href="class_u_i_view_controller.php" title="Additions.">UIViewController</a>*)controller path:(<a class="code" href="class_n_s_mutable_array.php" title="Additions.">NSMutableArray</a>*)path;
<a name="l00258"></a>00258 
<a name="l00262"></a>00262 - (<span class="keywordtype">void</span>)removeAllViewControllers;
<a name="l00263"></a>00263 
<a name="l00267"></a>00267 - (<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)pathForObject:(<span class="keywordtype">id</span>)<span class="keywordtype">object</span>;
<a name="l00268"></a>00268 
<a name="l00272"></a>00272 - (<span class="keywordtype">id</span>)objectForPath:(<a class="code" href="class_n_s_string.php" title="Additions.">NSString</a>*)path;
<a name="l00273"></a>00273 
<a name="l00277"></a>00277 - (<span class="keywordtype">void</span>)resetDefaults;
<a name="l00278"></a>00278 
<a name="l00279"></a>00279 @end
</pre></div></div>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
