<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Member List</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>TTMessageController Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_activityView</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_autoresizesForKeyboard</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_dataSource</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delegate</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_fields</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_fieldViews</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_frozenState</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_hasViewAppeared</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_initialRecipients</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_isModified</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_isViewAppearing</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_navigationBarStyle</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_navigationBarTintColor</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_scrollView</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_searchController</b> (defined in <a class="el" href="interface_t_t_view_controller.php">TTViewController</a>)</td><td><a class="el" href="interface_t_t_view_controller.php">TTViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_showsRecipientPicker</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_statusBarStyle</b> (defined in <a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a>)</td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_textEditor</b> (defined in <a class="el" href="interface_t_t_message_controller.php">TTMessageController</a>)</td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td><code> [protected]</code></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#af1a2fb598f715126dae56b41d57cdd4a">addRecipient:forFieldAtIndex:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#a9c53a69ddcc3e4d4f8eef61d51d98c75">autoresizesForKeyboard</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a179539948de0b4377b0559e9ef2c57e6">body</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#aa164519b99a08d60155c75fe422f3489">cancel:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a930b60b957c1c6b8a70f5ba2c39e4cce">confirmCancellation</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a577f1d8cad6e8591a4759f11d36aad2d">dataSource</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed">delegate</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>+&nbsp;</td><td><a class="el" href="interface_t_t_view_controller.php#a0e5fe2b34de8a02a7f3f0dccd5156958">doGarbageCollection</a></td><td><a class="el" href="interface_t_t_view_controller.php">TTViewController</a></td><td><code> [static]</code></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a84cf08a943476bf4df1f15f93a972f49">fieldHasValueAtIndex:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a81c2daf27f3f8f21cecf0a92fa45b1d3">fields</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#aba404e0d3d915055ce87f45191c2be8d">hasViewAppeared</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a47cf65af782ef1f172bf3187295bbb01">initWithRecipients:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#aa41f369642a1ce1afcfc381972d79d68">isModified</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#afeb4bf49b4efd4199f03e32dc793c87d">isViewAppearing</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_view_controller.php#a1405d3b2f2c3d4e1db7c7e29226c2e74">keyboardDidAppear:withBounds:</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_view_controller.php#ad27dfcbbc6587b779af6231825679be0">keyboardDidDisappear:withBounds:</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_view_controller.php#ae517ac05a60aff4c64dadfdf5e0be548">keyboardWillAppear:withBounds:</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_view_controller.php#a3b370029749e85fe261726375ba13289">keyboardWillDisappear:withBounds:</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a3e9dcb9a2a11041b1694d0da3b135d71">messageDidSend</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#af47187c50e2e1b382841fa4be783c0ba">messageShouldCancel</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#ae493ee3a5016a6b30a30bb7c704aac4e">messageWillSend:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a761a9ceb7a704fbb5e6c902a3faf500c">messageWillShowRecipientPicker</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#a0d8ab3d6c6b655258293c2df842d161b">navigationBarStyle</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#af9f360ea82a7008a4cdb785765ca368d">navigationBarTintColor</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_view_controller.php#aee5cb350b30e5feefffd3f118df21f86">searchViewController</a></td><td><a class="el" href="interface_t_t_view_controller.php">TTViewController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a2dccad9fc77b13fffe1e5f4e1e867a79">send</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#af2842bad2f6cc983845fd06b6aaaaa0d">setText:forFieldAtIndex:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a28d5a259e0d174feec29a11400094173">showActivityView:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a81e95b4725b4c6ad3bb9a534fa045660">showsRecipientPicker</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_view_controller.php#a9fbdc64e7c1d0e33c6e5c18c637484f7">statusBarStyle</a></td><td><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_message_controller.php#a8414169377f297b9fcb41bbc9c0a058d">subject</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditor:shouldChangeTextInRange:replacementText:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditor:shouldResizeBy:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorDidBeginEditing:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorDidChange:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorDidEndEditing:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorShouldBeginEditing:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorShouldEndEditing:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textEditorShouldReturn:</b> (defined in <a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#ab7d2ca53fae85cc98f75b509879c2754">textForFieldAtIndex:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a48fd3ef54fda0dfaeac75317b71e6d84">titleForSending</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_message_controller.php#a9d61201cf2b42c9f21c3f4474c0a4083">viewForFieldAtIndex:</a></td><td><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></td><td></td></tr>
</table></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
