<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Member List</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="/documentation">Documentation</a></li> 
  <li><a href="/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="/">Three20</a></h1> 
  <h2><a href="/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>TTImageView Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_t_t_image_view.php">TTImageView</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_autoresizesToImage</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_defaultImage</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delegate</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_image</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_layout</b> (defined in <a class="el" href="interface_t_t_view.php">TTView</a>)</td><td><a class="el" href="interface_t_t_view.php">TTView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_request</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_style</b> (defined in <a class="el" href="interface_t_t_view.php">TTView</a>)</td><td><a class="el" href="interface_t_t_view.php">TTView</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_urlPath</b> (defined in <a class="el" href="interface_t_t_image_view.php">TTImageView</a>)</td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td><code> [protected]</code></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a550deee45ef3cf4f72eba737f38d0924">autoresizesToImage</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#ac0806da2d2e376974fe0af0242e8635a">defaultImage</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a28a5a7c4401e82b11b9266ae4fb4c414">delegate</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>drawContent:</b> (defined in <a class="el" href="interface_t_t_view.php">TTView</a>)</td><td><a class="el" href="interface_t_t_view.php">TTView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>drawLayer:withStyle:</b> (defined in <a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a5a282b09c9dc2ae0fc3bb2d0dcbe165c">image</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>imageForLayerWithStyle:</b> (defined in <a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#a6257f74a8a335ea56eed95f5b33f62e6">imageViewDidFailLoadWithError:</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#af0feb022797654f5468d375dc8cd57d6">imageViewDidLoadImage:</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#aeb434f2a23554c10cc7f01d861fe841f">imageViewDidStartLoad</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a771abb9049776ede10ec6db7a667e9fc">isLoaded</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a665f800cac80e9b94521e68adf7f06e8">isLoading</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>layout</b> (defined in <a class="el" href="interface_t_t_view.php">TTView</a>)</td><td><a class="el" href="interface_t_t_view.php">TTView</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#acabfc9494cda1e296dfe5395adfa1ded">reload</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a1a8bc501340864cd0d96cb8a5bc14364">request:didFailLoadWithError:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a04aedf8b7c34959441ffc6c896682b01">request:didReceiveAuthenticationChallenge:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a208cacf0d2427a1f23d8d56b5536e358">requestDidCancelLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a82d97cb6c6b7b9fa1d57da6a7493fdeb">requestDidFinishLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#ae20fc15de596fef702c47a38343ccec6">requestDidStartLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a9c831806650a4b887f5cf963f6bbba1c">requestDidUploadData:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#ad2b661168892cc606dff75d436858171">setImage:</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView(TTInternal)</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#ab726aee4cb2dd60276eae933607366cf">stopLoading</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>style</b> (defined in <a class="el" href="interface_t_t_view.php">TTView</a>)</td><td><a class="el" href="interface_t_t_view.php">TTView</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>textForLayerWithStyle:</b> (defined in <a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a>)</td><td><a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_image_view.php#a45f01356d13b9a4feb16a7d0dfc11dd6">unsetImage</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_image_view.php#a037c253134647eeb0dec16dc5bd8f7f6">urlPath</a></td><td><a class="el" href="interface_t_t_image_view.php">TTImageView</a></td><td></td></tr>
</table></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
