<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: Pbxproj::Pbxproj Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fthree20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath">
    <ul>
      <li><b>Pbxproj</b>      </li>
      <li><a class="el" href="class_pbxproj_1_1_pbxproj.php">Pbxproj::Pbxproj</a>      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="#pri-attribs">Private Attributes</a>  </div>
  <div class="headertitle">
<h1>Pbxproj::Pbxproj Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="Pbxproj::Pbxproj" -->
<p><a href="class_pbxproj_1_1_pbxproj-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a728be4bc137e6769e19ba1be53225df1"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_pbxproj_by_name" ref="a728be4bc137e6769e19ba1be53225df1" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_pbxproj_by_name</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a37313e7e6e81ab2b25377d1f2f5db341"></a><!-- doxytag: member="Pbxproj::Pbxproj::__init__" ref="a37313e7e6e81ab2b25377d1f2f5db341" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>__init__</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a893a1038ce955f70f9b5aa5e75f6eda9"></a><!-- doxytag: member="Pbxproj::Pbxproj::__str__" ref="a893a1038ce955f70f9b5aa5e75f6eda9" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>__str__</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a49e96197283ecd8019c8df08af8b1a4c"></a><!-- doxytag: member="Pbxproj::Pbxproj::uniqueid" ref="a49e96197283ecd8019c8df08af8b1a4c" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>uniqueid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a46437b9828cf2e2e65242325d24fa337"></a><!-- doxytag: member="Pbxproj::Pbxproj::path" ref="a46437b9828cf2e2e65242325d24fa337" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>path</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa1e6a50678ebe38bc13d2c9c89c6502a"></a><!-- doxytag: member="Pbxproj::Pbxproj::xcodeprojpath" ref="aa1e6a50678ebe38bc13d2c9c89c6502a" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>xcodeprojpath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a991656bf3f6eca0acb2aa90a70a04861"></a><!-- doxytag: member="Pbxproj::Pbxproj::guid" ref="a991656bf3f6eca0acb2aa90a70a04861" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>guid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a08f78751c01bba31aa88d8827180f91e"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_project_data" ref="a08f78751c01bba31aa88d8827180f91e" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_project_data</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a32e70b1bbcbd76b270750002e06928a5"></a><!-- doxytag: member="Pbxproj::Pbxproj::set_project_data" ref="a32e70b1bbcbd76b270750002e06928a5" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>set_project_data</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9eb49f80488519cb9011d36d386f5837"></a><!-- doxytag: member="Pbxproj::Pbxproj::dependencies" ref="a9eb49f80488519cb9011d36d386f5837" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>dependencies</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1eeca968780d1e66129843a76096b83"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_buildfile" ref="ac1eeca968780d1e66129843a76096b83" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_buildfile</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8f8a76b39246ff4607cae506050cf1cc"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_filereference" ref="a8f8a76b39246ff4607cae506050cf1cc" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_filereference</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8553ebc84c522d4a48dc94e47aad1d41"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_group" ref="a8553ebc84c522d4a48dc94e47aad1d41" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_group</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afdc917a96e59241a2daed15977bce51a"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_frameworks" ref="afdc917a96e59241a2daed15977bce51a" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_frameworks</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a83c20677a3791a394575663cb8769bb5"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_resources" ref="a83c20677a3791a394575663cb8769bb5" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_resources</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1ef4e24397cce90583a71f8bd3cbc37a"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_phase" ref="a1ef4e24397cce90583a71f8bd3cbc37a" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_phase</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab91cbf1e7f5508279382f056a0ca7dca"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_rel_path_to_products_dir" ref="ab91cbf1e7f5508279382f056a0ca7dca" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_rel_path_to_products_dir</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae0c97ca2996e655d574afc5b786ad7e1"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_frameworks_phase" ref="ae0c97ca2996e655d574afc5b786ad7e1" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_frameworks_phase</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8e4d650b536dbd96b0ba301c67987b78"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_file_to_resources_phase" ref="a8e4d650b536dbd96b0ba301c67987b78" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_file_to_resources_phase</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae9183a76e166af338697e3aed4151919"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_header_search_path" ref="ae9183a76e166af338697e3aed4151919" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_header_search_path</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa9ceb839b7053988faa8e6cece5cd1d7"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_build_setting" ref="aa9ceb839b7053988faa8e6cece5cd1d7" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_build_setting</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad2a401ae7926e75ac0b7a3279ed5c98f"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_hash_base" ref="ad2a401ae7926e75ac0b7a3279ed5c98f" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_hash_base</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a867701e6e1f4bab0e42b1a2d8f4a612e"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_framework" ref="a867701e6e1f4bab0e42b1a2d8f4a612e" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_framework</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3813329cfc8442993c89b6b999493a95"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_bundle" ref="a3813329cfc8442993c89b6b999493a95" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_bundle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a41bc39e1493c2d1463067e22584a6280"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_filerefguid_from_buildfileguid" ref="a41bc39e1493c2d1463067e22584a6280" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_filerefguid_from_buildfileguid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1ae819fa7ab8e6e0fe88500bd1b0070e"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_filepath_from_filerefguid" ref="a1ae819fa7ab8e6e0fe88500bd1b0070e" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_filepath_from_filerefguid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24963e2c07562b7286c3899e1a4d0fdd"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_built_sources" ref="a24963e2c07562b7286c3899e1a4d0fdd" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_built_sources</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1f26f5352e8b3252dd625b9e97cb9d34"></a><!-- doxytag: member="Pbxproj::Pbxproj::get_built_headers" ref="a1f26f5352e8b3252dd625b9e97cb9d34" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>get_built_headers</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae59efd4cb43a34879b4531d6f98dc731"></a><!-- doxytag: member="Pbxproj::Pbxproj::add_dependency" ref="ae59efd4cb43a34879b4531d6f98dc731" args="" -->
def&nbsp;</td><td class="memItemRight" valign="bottom"><b>add_dependency</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa810e55ded7e30492b7774ae3a4e3855"></a><!-- doxytag: member="Pbxproj::Pbxproj::name" ref="aa810e55ded7e30492b7774ae3a4e3855" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>name</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad3e8a0792ab7dda0f8b9b3bf664270f4"></a><!-- doxytag: member="Pbxproj::Pbxproj::target" ref="ad3e8a0792ab7dda0f8b9b3bf664270f4" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>target</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abfbde683fa5be77a74f5442c4d5cb038"></a><!-- doxytag: member="Pbxproj::Pbxproj::configurationListGuid" ref="abfbde683fa5be77a74f5442c4d5cb038" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>configurationListGuid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8c5dff5cc17887dce878e2f06f444f43"></a><!-- doxytag: member="Pbxproj::Pbxproj::configurations" ref="a8c5dff5cc17887dce878e2f06f444f43" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>configurations</b></td></tr>
<tr><td colspan="2"><h2><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0837b17c85c40cf82193d0a95f0a97ae"></a><!-- doxytag: member="Pbxproj::Pbxproj::_project_data" ref="a0837b17c85c40cf82193d0a95f0a97ae" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>_project_data</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a34226bc7e9e85c4ba2ff791592200f99"></a><!-- doxytag: member="Pbxproj::Pbxproj::_project_name" ref="a34226bc7e9e85c4ba2ff791592200f99" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>_project_name</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a765a25962fe1930038ef422f3f73f895"></a><!-- doxytag: member="Pbxproj::Pbxproj::_guid" ref="a765a25962fe1930038ef422f3f73f895" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>_guid</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4b17133607b857ea0cb525961c052578"></a><!-- doxytag: member="Pbxproj::Pbxproj::_deps" ref="a4b17133607b857ea0cb525961c052578" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>_deps</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0065171b8617d3726d71dda13216f190"></a><!-- doxytag: member="Pbxproj::Pbxproj::_resources_guid" ref="a0065171b8617d3726d71dda13216f190" args="" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>_resources_guid</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>scripts/Pbxproj.py</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
