<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Member List</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>TTNavigator Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_t_t_navigator.php">TTNavigator</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delayCount</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delayedControllers</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delegate</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_opensExternalURLs</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_persistenceExpirationAge</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_persistenceMode</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_rootViewController</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_supportsShakeToReload</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_URLMap</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_window</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [protected]</code></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#acf439ce30fcfff1ae9e9a52a95064424">beginDelay</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a7bf628d499c8d8f974cfca8a7dbc7931">cancelDelay</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>delegate</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a4c72e1ee89fdefde0a70794fe95f6463">endDelay</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>getVisibleChildController:</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator(TTInternal)</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>+&nbsp;</td><td><b>globalNavigator</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [static]</code></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#aaaa44f8ff42826f21da0fa61bc55e22e">isDelayed</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>navigationControllerClass</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator(TTInternal)</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>+&nbsp;</td><td><b>navigator</b> (defined in <a class="el" href="interface_t_t_navigator.php">TTNavigator</a>)</td><td><a class="el" href="interface_t_t_navigator.php">TTNavigator</a></td><td><code> [static]</code></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a70c3aaa39d43c33f22d3450781d8d769">objectForPath:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a093b7725f813a2819977991b416df181">opensExternalURLs</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a456b09e2237308cac626409c6833d743">openURLAction:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a6bdefc8377db8b250867dd75b244e2b8">openURLs:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#ada711e28c02762b11d133f495f7a1c36">pathForObject:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a9070bac173ad1468315a77e8596d85f5">persistController:path:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#abe6d7ee14fd1147201694ffdfdb3228d">persistenceExpirationAge</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#af4584c3f244a628f9986960f5973cb92">persistenceMode</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#ad4c27d2bff652889d9a7e3aec2d5cb76">persistViewControllers</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>-&nbsp;</td><td><b>presentDependantController:parentController:mode:animated:transition:</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator(TTInternal)</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_navigator.php#aada2f20a7b635a6fb5592b148483c491">reload</a></td><td><a class="el" href="interface_t_t_navigator.php">TTNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#aa97fc83e955f8248d6232471be30c00c">removeAllViewControllers</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a8f7c64c4418ca2f3b95840894e659f40">resetDefaults</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#ae16f367fb06aedc2232817c081541d59">restoreViewControllers</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a5568a0c8e0a19d26306e9d160d302b6e">rootViewController</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr bgcolor="#f0f0f0"><td>+&nbsp;</td><td><b>setGlobalNavigator:</b> (defined in <a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a>)</td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td><code> [static]</code></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#ad49b7a6c9a4820d955a7eaf3687c05f2">supportsShakeToReload</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a9d5c8ea878103dd007eb3012d3749210">topViewController</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a1ffbcfbcbefed8badea9d3bcbe21681a">URL</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a3017d22aba919b66969e863484bb2168">URLMap</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#afa745e4007cd0bbf1da9012649cd1ab0">viewControllerForURL:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#abef44cafee785f081ddc01db4957c8f6">viewControllerForURL:query:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_base_navigator.php#a14b4dec5a3b177b66b4003c8c32a1b16">viewControllerForURL:query:pattern:</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#abe08b1203a02a91fe9b81f8dbb6cbda1">visibleViewController</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_base_navigator.php#a584f4a80461eea29d39b085acb023704">window</a></td><td><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a></td><td></td></tr>
</table></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
