<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Member List</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>TTURLRequestModel Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>, including all inherited members.<table>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_cacheKey</b> (defined in <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>)</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_delegates</b> (defined in <a class="el" href="interface_t_t_model.php">TTModel</a>)</td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_hasNoMore</b> (defined in <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>)</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_isLoadingMore</b> (defined in <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>)</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_loadedTime</b> (defined in <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>)</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td><code> [protected]</code></td></tr>
  <tr bgcolor="#f0f0f0"><td></td><td><b>_loadingRequest</b> (defined in <a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a>)</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td><code> [protected]</code></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#aafb43ebb3bfec2f63be76cfeccb6b1e0">beginUpdates</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php#a2127dc12c0ef3b45dd099f37f6337d2b">cacheKey</a></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#ab1a78579b78649df0061aabd384db721">cancel</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a75f0ad85113d05134ed5e79b37b5827e">delegates</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#a3e774c650e1106f3a0c281b7021c95d0">didCancelLoad</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#ade47f3250e00f0809ca3e7da405bcdf2">didChange</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#af1dcd69944ae2470483fd8375e3cc421">didDeleteObject:atIndexPath:</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#ab9c90625dc2cd0496a77f4c3a3c6142a">didFailLoadWithError:</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#adc24f173e80034b8c27378f95dba5fda">didFinishLoad</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#a340d54a605f5270d6fabb262c862b6b5">didInsertObject:atIndexPath:</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#ab631e110ec681d86158a8895061a5885">didStartLoad</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#a838de41069159b5af22e3f7b4a6028a6">didUpdateObject:atIndexPath:</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_model.php#a72177e30bb905e113450e8ab5183f04a">endUpdates</a></td><td><a class="el" href="interface_t_t_model.php">TTModel</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php#a408188443e720d09d66bd526d9a669b1">hasNoMore</a></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a13efe0c75b14ded343cd95bc84ed65f6">invalidate:</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a0717855b556f4efac8de7571f1d38cea">isLoaded</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a68b9d49ad095a221c82ec0d13b6038ec">isLoading</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a41b1268d87a53c51aa8b22bbeeb29d07">isLoadingMore</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#adbf2fa828a24a0428695f4cd708d9db6">isOutdated</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_model-p.php#a7b6152507942206e12aa6889a0ed8b8c">load:more:</a></td><td><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a></td><td></td></tr>
  <tr class="memlist"><td></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php#ace587f260d01aaf0e3e9f885e578689a">loadedTime</a></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a1a8bc501340864cd0d96cb8a5bc14364">request:didFailLoadWithError:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a04aedf8b7c34959441ffc6c896682b01">request:didReceiveAuthenticationChallenge:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a208cacf0d2427a1f23d8d56b5536e358">requestDidCancelLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a82d97cb6c6b7b9fa1d57da6a7493fdeb">requestDidFinishLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#ae20fc15de596fef702c47a38343ccec6">requestDidStartLoad:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php#a9c831806650a4b887f5cf963f6bbba1c">requestDidUploadData:</a></td><td><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a></td><td></td></tr>
  <tr class="memlist"><td>-&nbsp;</td><td><a class="el" href="interface_t_t_u_r_l_request_model.php#a29ebf5997eb74ac247bc416e5e90d14a">reset</a></td><td><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></td><td></td></tr>
</table></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
