<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: Class Members</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_prop.php"><span>Properties</span></a></li>
    </ul>
  </div>
  <div class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index__"><span>_</span></a></li>
      <li><a href="functions_0x61.php#index_a"><span>a</span></a></li>
      <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
      <li><a href="functions_0x63.php#index_c"><span>c</span></a></li>
      <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
      <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
      <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
      <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
      <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
      <li class="current"><a href="functions_0x69.php#index_i"><span>i</span></a></li>
      <li><a href="functions_0x6a.php#index_j"><span>j</span></a></li>
      <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
      <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
      <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
      <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
      <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
      <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
      <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
      <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
      <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
      <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
      <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x77.php#index_w"><span>w</span></a></li>
      <li><a href="functions_0x79.php#index_y"><span>y</span></a></li>
      <li><a href="functions_0x7a.php#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
Here is a list of all documented class members with links to the class documentation for each member:

<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>image
: <a class="el" href="interface_t_t_image_view.php#a5a282b09c9dc2ae0fc3bb2d0dcbe165c">TTImageView</a>
</li>
<li>imageCompressionQuality
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#aa6818e451230a069a53bcb2026d14fa0">TTURLRequestQueue</a>
</li>
<li>imageForURL:
: <a class="el" href="interface_t_t_u_r_l_cache.php#a6724011388079896acfc7dec95415f81">TTURLCache</a>
</li>
<li>imageNode
: <a class="el" href="interface_t_t_styled_image_frame.php#abe27e03646d5ce7877a8e8d128de3d2c">TTStyledImageFrame</a>
</li>
<li>imageView:didFailLoadWithError:
: <a class="el" href="protocol_t_t_image_view_delegate-p.php#a5358b7ac3902e702dcd6bf53d346b942">&lt;TTImageViewDelegate&gt;</a>
</li>
<li>imageView:didLoadImage:
: <a class="el" href="protocol_t_t_image_view_delegate-p.php#ab5d16a19a3dcd15f5d8da934899ab15b">&lt;TTImageViewDelegate&gt;</a>
</li>
<li>imageViewDidFailLoadWithError:
: <a class="el" href="interface_t_t_image_view.php#a6257f74a8a335ea56eed95f5b33f62e6">TTImageView</a>
</li>
<li>imageViewDidLoadImage:
: <a class="el" href="interface_t_t_image_view.php#af0feb022797654f5468d375dc8cd57d6">TTImageView</a>
</li>
<li>imageViewDidStartLoad
: <a class="el" href="interface_t_t_image_view.php#aeb434f2a23554c10cc7f01d861fe841f">TTImageView</a>
</li>
<li>imageViewDidStartLoad:
: <a class="el" href="protocol_t_t_image_view_delegate-p.php#a0b886d3ccd4d38761c9def1a6bd728a7">&lt;TTImageViewDelegate&gt;</a>
</li>
<li>indentString
: <a class="el" href="structyajl__gen__config.php#aa260f86485635c65ab7cf7bbb6f34107">yajl_gen_config</a>
</li>
<li>index
: <a class="el" href="protocol_t_t_photo-p.php#a49bf1bbc9c64c3fc03aa3c8af41a437c">&lt;TTPhoto&gt;</a>
</li>
<li>initWithData:parserOptions:error:
: <a class="el" href="interface_y_a_j_l_document.php#a9b206b6d99ed1edd0cbec744ec75ff1b">YAJLDocument</a>
</li>
<li>initWithGenOptions:indentString:
: <a class="el" href="interface_y_a_j_l_gen.php#af7ec25a4613926fbe1c680a5e1e35382">YAJLGen</a>
</li>
<li>initWithParserOptions:
: <a class="el" href="interface_y_a_j_l_parser.php#a3cddbd758c51a3cfbcdabe67f82ea151">YAJLParser</a>
, <a class="el" href="interface_y_a_j_l_document.php#a5244e742acee8498bbc4b488ed63ad0c">YAJLDocument</a>
</li>
<li>initWithRecipients:
: <a class="el" href="interface_t_t_message_controller.php#a47cf65af782ef1f172bf3187295bbb01">TTMessageController</a>
</li>
<li>initWithStyle:
: <a class="el" href="interface_t_t_table_view_controller.php#a09b950a1320f154fc629f30c2039c3dc">TTTableViewController</a>
</li>
<li>initWithTitle:
: <a class="el" href="interface_t_t_action_sheet_controller.php#a57a02f9f813b40b6764753b90b1a40b5">TTActionSheetController</a>
</li>
<li>initWithTitle:delegate:
: <a class="el" href="interface_t_t_action_sheet_controller.php#a814432f4f61eb9e263a5e2e52a766746">TTActionSheetController</a>
</li>
<li>initWithURLPath:
: <a class="el" href="interface_t_t_you_tube_view.php#a4cf9ba4c9d437a2caf0572b2cee7dec8">TTYouTubeView</a>
, <a class="el" href="interface_t_t_u_r_l_action.php#a6b4e366c94a2175e67a166975d4e788a">TTURLAction</a>
</li>
<li>invalidate:
: <a class="el" href="protocol_t_t_model-p.php#a13efe0c75b14ded343cd95bc84ed65f6">&lt;TTModel&gt;</a>
</li>
<li>invalidateAll
: <a class="el" href="interface_t_t_u_r_l_cache.php#a85ccfcd327dd7701bb05ad061dda2bb7">TTURLCache</a>
</li>
<li>invalidateModel
: <a class="el" href="interface_t_t_model_view_controller.php#afe989215479fe730579aa2836f477850">TTModelViewController</a>
</li>
<li>invalidateURL:
: <a class="el" href="interface_t_t_u_r_l_cache.php#ada216804c3476267e995502d62388f6f">TTURLCache</a>
</li>
<li>invalidateView
: <a class="el" href="interface_t_t_model_view_controller.php#aa035befabec5a8713ea9026f570ac5bd">TTModelViewController</a>
</li>
<li>invalidationAge
: <a class="el" href="interface_t_t_u_r_l_cache.php#a2bec99453fca73fc8e4942737a9ad263">TTURLCache</a>
</li>
<li>invalidImages
: <a class="el" href="interface_t_t_styled_text.php#a93ea4b1f79865be5ec33b701eb11a509">TTStyledText</a>
</li>
<li>isAppURL:
: <a class="el" href="interface_t_t_u_r_l_map.php#a067fd51f5d8088bdbc39890497e22126">TTURLMap</a>
</li>
<li>isDelayed
: <a class="el" href="interface_t_t_base_navigator.php#aaaa44f8ff42826f21da0fa61bc55e22e">TTBaseNavigator</a>
</li>
<li>isLoaded
: <a class="el" href="interface_t_t_image_view.php#a771abb9049776ede10ec6db7a667e9fc">TTImageView</a>
, <a class="el" href="protocol_t_t_model-p.php#a0717855b556f4efac8de7571f1d38cea">&lt;TTModel&gt;</a>
</li>
<li>isLoading
: <a class="el" href="interface_t_t_request_loader.php#a26e45bc2d7677cfbae03d6a20905f78a">TTRequestLoader</a>
, <a class="el" href="interface_t_t_image_view.php#a665f800cac80e9b94521e68adf7f06e8">TTImageView</a>
, <a class="el" href="protocol_t_t_model-p.php#a68b9d49ad095a221c82ec0d13b6038ec">&lt;TTModel&gt;</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#a25d8560d31c9df8a7a274e2ad1825081">TTURLRequest</a>
</li>
<li>isLoadingMore
: <a class="el" href="protocol_t_t_model-p.php#a41b1268d87a53c51aa8b22bbeeb29d07">&lt;TTModel&gt;</a>
</li>
<li>isModelCreated
: <a class="el" href="interface_t_t_model_view_controller.php#aefb8faff3f2ee24d25868d538603bef0">TTModelViewController</a>
</li>
<li>isModified
: <a class="el" href="interface_t_t_message_controller.php#aa41f369642a1ce1afcfc381972d79d68">TTMessageController</a>
</li>
<li>iso88591
: <a class="el" href="interface_t_t_entity_tables.php#ada8848109697d4df052bf2b9a72eb187">TTEntityTables</a>
</li>
<li>isOutdated
: <a class="el" href="protocol_t_t_model-p.php#adbf2fa828a24a0428695f4cd708d9db6">&lt;TTModel&gt;</a>
</li>
<li>isRssFeed
: <a class="el" href="interface_t_t_u_r_l_x_m_l_response.php#a85303d558d10edd4f17e6b87bc5abd42">TTURLXMLResponse</a>
</li>
<li>isSchemeSupported:
: <a class="el" href="interface_t_t_u_r_l_map.php#a249b0ac66dbb6986eb48145dd15945d1">TTURLMap</a>
</li>
<li>isViewAppearing
: <a class="el" href="interface_t_t_base_view_controller.php#afeb4bf49b4efd4199f03e32dc793c87d">TTBaseViewController</a>
</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
