<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Class Members - Properties</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li class="current"><a href="functions_prop.php"><span>Properties</span></a></li>
    </ul>
  </div>
  <div class="tabs3">
    <ul class="tablist">
      <li><a href="#index__"><span>_</span></a></li>
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_b"><span>b</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_h"><span>h</span></a></li>
      <li><a href="#index_i"><span>i</span></a></li>
      <li><a href="#index_l"><span>l</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_n"><span>n</span></a></li>
      <li><a href="#index_o"><span>o</span></a></li>
      <li><a href="#index_p"><span>p</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li><a href="#index_t"><span>t</span></a></li>
      <li><a href="#index_u"><span>u</span></a></li>
      <li><a href="#index_v"><span>v</span></a></li>
      <li><a href="#index_w"><span>w</span></a></li>
      <li><a href="#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
&nbsp;

<h3><a class="anchor" id="index__"></a>- _ -</h3><ul>
<li>__TTDEPRECATED_METHOD
: <a class="el" href="interface_t_t_request_loader.php#aec8806d4912142a8fef5a28e8be5c089">TTRequestLoader</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#ac8412fff243d33553ac0c20800e604ed">TTURLRequest</a>
</li>
</ul>


<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>autoresizesForKeyboard
: <a class="el" href="interface_t_t_base_view_controller.php#a9c53a69ddcc3e4d4f8eef61d51d98c75">TTBaseViewController</a>
</li>
<li>autoresizesToImage
: <a class="el" href="interface_t_t_image_view.php#a550deee45ef3cf4f72eba737f38d0924">TTImageView</a>
</li>
</ul>


<h3><a class="anchor" id="index_b"></a>- b -</h3><ul>
<li>body
: <a class="el" href="interface_t_t_message_controller.php#a179539948de0b4377b0559e9ef2c57e6">TTMessageController</a>
</li>
<li>bounds
: <a class="el" href="interface_t_t_styled_frame.php#ab0bd9f22c306b1983ffe3889a3057971">TTStyledFrame</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>cacheExpirationAge
: <a class="el" href="interface_t_t_request_loader.php#a91e393e0d058d3a789e3d782bbd02357">TTRequestLoader</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#aa0f7d2b7001143d1b9f1d3635449a4f1">TTURLRequest</a>
</li>
<li>cacheKey
: <a class="el" href="interface_t_t_u_r_l_request.php#ace472f23740be06aa40dffdbdca99953">TTURLRequest</a>
, <a class="el" href="interface_t_t_u_r_l_request_model.php#a2127dc12c0ef3b45dd099f37f6337d2b">TTURLRequestModel</a>
, <a class="el" href="interface_t_t_request_loader.php#afc70c6b8ef860ee13fef091dae10ca41">TTRequestLoader</a>
</li>
<li>cachePath
: <a class="el" href="interface_t_t_u_r_l_cache.php#a52da998d5df61ba519db1469597a54a3">TTURLCache</a>
</li>
<li>cachePolicy
: <a class="el" href="interface_t_t_u_r_l_request.php#a34ad517e5d5fe222baec6702b9eb4cde">TTURLRequest</a>
, <a class="el" href="interface_t_t_request_loader.php#a73a04e9934fd4e34b369c60c31578227">TTRequestLoader</a>
</li>
<li>caption
: <a class="el" href="protocol_t_t_photo-p.php#ae7dbc655e54ac2f77c7b0b5addf9cb47">&lt;TTPhoto&gt;</a>
</li>
<li>captionStyle
: <a class="el" href="interface_t_t_photo_view_controller.php#a2e04d249898456d712dd25ac1a2b42a1">TTPhotoViewController</a>
</li>
<li>centerPageIndex
: <a class="el" href="interface_t_t_scroll_view.php#a78d5e647a3cadb39d064eab51ba67e31">TTScrollView</a>
</li>
<li>centerPhoto
: <a class="el" href="interface_t_t_photo_view_controller.php#ae4080daae3eb4cbb4c87162d178c3449">TTPhotoViewController</a>
</li>
<li>centerPhotoIndex
: <a class="el" href="interface_t_t_photo_view_controller.php#a8a4e41837254638e66304de521e7de5a">TTPhotoViewController</a>
</li>
<li>charsetForMultipart
: <a class="el" href="interface_t_t_u_r_l_request.php#a8a432224b4b3c781a593f8512c124ec1">TTURLRequest</a>
</li>
<li>contentInset
: <a class="el" href="interface_t_t_styled_text_label.php#a82b3d4f94a46a347621ec4ed6bc03244">TTStyledTextLabel</a>
</li>
<li>contentType
: <a class="el" href="interface_t_t_u_r_l_request.php#a7cf514d3f3d6526b183220d9c21513fd">TTURLRequest</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>dataSource
: <a class="el" href="interface_t_t_message_controller.php#a577f1d8cad6e8591a4759f11d36aad2d">TTMessageController</a>
, <a class="el" href="interface_t_t_table_view_controller.php#a90e2864b19220113f2bbf93c0c79e10c">TTTableViewController</a>
</li>
<li>decelerating
: <a class="el" href="interface_t_t_scroll_view.php#ad72bebb726e926baee671748334832e8">TTScrollView</a>
</li>
<li>decelerationRate
: <a class="el" href="interface_t_t_scroll_view.php#a48bdb272cb17fc9bd55d59967eb1bc28">TTScrollView</a>
</li>
<li>defaultImage
: <a class="el" href="interface_t_t_image_view.php#ac0806da2d2e376974fe0af0242e8635a">TTImageView</a>
, <a class="el" href="interface_t_t_photo_view_controller.php#a982625320715d2e51c0f75bae607aeff">TTPhotoViewController</a>
</li>
<li>delegate
: <a class="el" href="interface_t_t_message_controller.php#a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed">TTMessageController</a>
, <a class="el" href="interface_t_t_recursive_progress.php#a997fa2b9da25fe52d45742f5d1700466">TTRecursiveProgress</a>
, <a class="el" href="interface_t_t_web_controller.php#ab9a2dd7b03546df421e5dcae2e094799">TTWebController</a>
, <a class="el" href="interface_t_t_image_view.php#a28a5a7c4401e82b11b9266ae4fb4c414">TTImageView</a>
</li>
<li>delegates
: <a class="el" href="interface_t_t_u_r_l_request.php#a71bb6bdcc1bc9699a0babfd2b8a398db">TTURLRequest</a>
</li>
<li>disableDiskCache
: <a class="el" href="interface_t_t_u_r_l_cache.php#a2d1220ae6f57ec0c86f5f93351dc0a1b">TTURLCache</a>
</li>
<li>disableImageCache
: <a class="el" href="interface_t_t_u_r_l_cache.php#adbfcc7dd613e62be6a8930f146a2c2bf">TTURLCache</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>element
: <a class="el" href="interface_t_t_styled_frame.php#a67cc15e5eeaca5b7ad03e29bed795168">TTStyledFrame</a>
</li>
<li>errorTrace
: <a class="el" href="interface_s_b_json_base.php#aa83f0ee5efade2fd26ddf6591ffd8dc0">SBJsonBase</a>
</li>
<li>etagCachePath
: <a class="el" href="interface_t_t_u_r_l_cache.php#ad4c768d564e500fb4a2744244e274fab">TTURLCache</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>fields
: <a class="el" href="interface_t_t_message_controller.php#a81c2daf27f3f8f21cecf0a92fa45b1d3">TTMessageController</a>
</li>
<li>filterPasswordLogging
: <a class="el" href="interface_t_t_u_r_l_request.php#a01c9b278379d6fe161e156a986ab845b">TTURLRequest</a>
</li>
<li>firstPercent
: <a class="el" href="interface_t_t_recursive_progress.php#ac5fdc2742be5f63580410b793e7cfa79">TTRecursiveProgress</a>
</li>
<li>font
: <a class="el" href="interface_t_t_styled_text.php#ab20e516d3150b8f45f7834099cb2a38b">TTStyledText</a>
, <a class="el" href="interface_t_t_styled_text_frame.php#a12d302d0ad05c8154e16185c006a6c17">TTStyledTextFrame</a>
, <a class="el" href="interface_t_t_styled_text_label.php#a66b01655ce2c546fbb0569cedab75682">TTStyledTextLabel</a>
</li>
</ul>


<h3><a class="anchor" id="index_h"></a>- h -</h3><ul>
<li>hasNoMore
: <a class="el" href="interface_t_t_u_r_l_request_model.php#a408188443e720d09d66bd526d9a669b1">TTURLRequestModel</a>
</li>
<li>hasViewAppeared
: <a class="el" href="interface_t_t_base_view_controller.php#aba404e0d3d915055ce87f45191c2be8d">TTBaseViewController</a>
</li>
<li>headers
: <a class="el" href="interface_t_t_u_r_l_request.php#a2e0a8de578fffdf0e14f38b00e2f7116">TTURLRequest</a>
</li>
<li>headerView
: <a class="el" href="interface_t_t_web_controller.php#a7da4748d4f6ac4591ac171b77954f3a6">TTWebController</a>
</li>
<li>height
: <a class="el" href="interface_t_t_styled_text.php#ab6a78cf16173257d8d03cbeccf9f7054">TTStyledText</a>
</li>
<li>highlighted
: <a class="el" href="interface_t_t_styled_text_label.php#a22f1bf6aa775f236297edfb6f7566be7">TTStyledTextLabel</a>
</li>
<li>highlightedNode
: <a class="el" href="interface_t_t_styled_text_label.php#a90eb7083143c1eda259201e40cc12d29">TTStyledTextLabel</a>
</li>
<li>highlightedTextColor
: <a class="el" href="interface_t_t_styled_text_label.php#a7da51569ea90cc99f9f918f6ce92d1bc">TTStyledTextLabel</a>
</li>
<li>holdsAfterTouchingForInterval
: <a class="el" href="interface_t_t_scroll_view.php#ab7e204fd45c41a63feaf1e3453fe382f">TTScrollView</a>
</li>
<li>html
: <a class="el" href="interface_t_t_styled_text_label.php#acf37305f00bfbabf152a42b31c262a0d">TTStyledTextLabel</a>
</li>
<li>httpBody
: <a class="el" href="interface_t_t_u_r_l_request.php#a81363a89ad2263f875252fa65cacf8ec">TTURLRequest</a>
</li>
<li>humanReadable
: <a class="el" href="protocol_s_b_json_writer-p.php#a69f531597668b4b3c20aabee1e3d4558">&lt;SBJsonWriter&gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>image
: <a class="el" href="interface_t_t_image_view.php#a5a282b09c9dc2ae0fc3bb2d0dcbe165c">TTImageView</a>
</li>
<li>imageCompressionQuality
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#aa6818e451230a069a53bcb2026d14fa0">TTURLRequestQueue</a>
</li>
<li>imageNode
: <a class="el" href="interface_t_t_styled_image_frame.php#abe27e03646d5ce7877a8e8d128de3d2c">TTStyledImageFrame</a>
</li>
<li>index
: <a class="el" href="protocol_t_t_photo-p.php#a49bf1bbc9c64c3fc03aa3c8af41a437c">&lt;TTPhoto&gt;</a>
</li>
<li>invalidationAge
: <a class="el" href="interface_t_t_u_r_l_cache.php#a2bec99453fca73fc8e4942737a9ad263">TTURLCache</a>
</li>
<li>invalidImages
: <a class="el" href="interface_t_t_styled_text.php#a93ea4b1f79865be5ec33b701eb11a509">TTStyledText</a>
</li>
<li>isDelayed
: <a class="el" href="interface_t_t_base_navigator.php#aaaa44f8ff42826f21da0fa61bc55e22e">TTBaseNavigator</a>
</li>
<li>isLoaded
: <a class="el" href="interface_t_t_image_view.php#a771abb9049776ede10ec6db7a667e9fc">TTImageView</a>
</li>
<li>isLoading
: <a class="el" href="interface_t_t_request_loader.php#a26e45bc2d7677cfbae03d6a20905f78a">TTRequestLoader</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#a25d8560d31c9df8a7a274e2ad1825081">TTURLRequest</a>
, <a class="el" href="interface_t_t_image_view.php#a665f800cac80e9b94521e68adf7f06e8">TTImageView</a>
</li>
<li>isModified
: <a class="el" href="interface_t_t_message_controller.php#aa41f369642a1ce1afcfc381972d79d68">TTMessageController</a>
</li>
<li>iso88591
: <a class="el" href="interface_t_t_entity_tables.php#ada8848109697d4df052bf2b9a72eb187">TTEntityTables</a>
</li>
<li>isRssFeed
: <a class="el" href="interface_t_t_u_r_l_x_m_l_response.php#a85303d558d10edd4f17e6b87bc5abd42">TTURLXMLResponse</a>
</li>
<li>isViewAppearing
: <a class="el" href="interface_t_t_base_view_controller.php#afeb4bf49b4efd4199f03e32dc793c87d">TTBaseViewController</a>
</li>
</ul>


<h3><a class="anchor" id="index_l"></a>- l -</h3><ul>
<li>lastPercent
: <a class="el" href="interface_t_t_recursive_progress.php#a15e84f0afc7806138f6aa525a96e097b">TTRecursiveProgress</a>
</li>
<li>loadedTime
: <a class="el" href="interface_t_t_u_r_l_request_model.php#ace587f260d01aaf0e3e9f885e578689a">TTURLRequestModel</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>maxContentLength
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#ac12fd4da800c6c86a1c9c8cf22a5906f">TTURLRequestQueue</a>
</li>
<li>maxDepth
: <a class="el" href="interface_s_b_json_base.php#abe3e47517711570a9a57e2d92a15055b">SBJsonBase</a>
</li>
<li>maximumZoomScale
: <a class="el" href="interface_t_t_scroll_view.php#a32450ee169df9c2062407aa39d55af00">TTScrollView</a>
</li>
<li>maxPhotoIndex
: <a class="el" href="protocol_t_t_photo_source-p.php#a17cae32c2b4e235047a9852418c7ab5e">&lt;TTPhotoSource&gt;</a>
</li>
<li>maxPixelCount
: <a class="el" href="interface_t_t_u_r_l_cache.php#a6dc964b9bbbd1b7c99af928faaf01992">TTURLCache</a>
</li>
<li>model
: <a class="el" href="protocol_t_t_table_view_data_source-p.php#aeb1d63fdb51ebb1608817e3d43a64ab6">&lt;TTTableViewDataSource&gt;</a>
</li>
<li>modelError
: <a class="el" href="interface_t_t_model_view_controller.php#abf74cd2086bd97dfa34f6e250598bd8f">TTModelViewController</a>
</li>
</ul>


<h3><a class="anchor" id="index_n"></a>- n -</h3><ul>
<li>navigationBarStyle
: <a class="el" href="interface_t_t_base_view_controller.php#a0d8ab3d6c6b655258293c2df842d161b">TTBaseViewController</a>
</li>
<li>navigationBarTintColor
: <a class="el" href="interface_t_t_base_view_controller.php#af9f360ea82a7008a4cdb785765ca368d">TTBaseViewController</a>
</li>
<li>needsLayout
: <a class="el" href="interface_t_t_styled_text.php#a53591b5b6593143c6d57511c19d6ca73">TTStyledText</a>
</li>
<li>nextFrame
: <a class="el" href="interface_t_t_styled_frame.php#ac766ee3e369aade645baa3f93cec4867">TTStyledFrame</a>
</li>
<li>node
: <a class="el" href="interface_t_t_styled_text_frame.php#a3ce67624e8967f49f65f25febbb77e3f">TTStyledTextFrame</a>
</li>
<li>numberOfPhotos
: <a class="el" href="protocol_t_t_photo_source-p.php#a4645c0189b59ee12f85e081577a56250">&lt;TTPhotoSource&gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_o"></a>- o -</h3><ul>
<li>opensExternalURLs
: <a class="el" href="interface_t_t_base_navigator.php#a093b7725f813a2819977991b416df181">TTBaseNavigator</a>
</li>
</ul>


<h3><a class="anchor" id="index_p"></a>- p -</h3><ul>
<li>pageSpacing
: <a class="el" href="interface_t_t_scroll_view.php#a777db57c6cbc8f27acf1a57815c39a63">TTScrollView</a>
</li>
<li>parameters
: <a class="el" href="interface_t_t_u_r_l_request.php#ab7b6a26183ddcb2d0ff3ff17d3da4441">TTURLRequest</a>
</li>
<li>parserStatus
: <a class="el" href="interface_y_a_j_l_document.php#a3ef4dae31a36129f29cc48046cdfd97e">YAJLDocument</a>
</li>
<li>percent
: <a class="el" href="interface_t_t_recursive_progress.php#a68e1177170f66d9a8a19b23ac0f224f9">TTRecursiveProgress</a>
</li>
<li>persistenceExpirationAge
: <a class="el" href="interface_t_t_base_navigator.php#abe6d7ee14fd1147201694ffdfdb3228d">TTBaseNavigator</a>
</li>
<li>persistenceMode
: <a class="el" href="interface_t_t_base_navigator.php#af4584c3f244a628f9986960f5973cb92">TTBaseNavigator</a>
</li>
<li>photoSource
: <a class="el" href="protocol_t_t_photo-p.php#a3ef13b8beb0149ba7c03f7b96d9b0a33">&lt;TTPhoto&gt;</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>requests
: <a class="el" href="interface_t_t_request_loader.php#a812d3c16cac62020a431ac4e46853041">TTRequestLoader</a>
</li>
<li>required
: <a class="el" href="interface_t_t_message_field.php#aa0f70cbfe47c719bb44790c8e138d254">TTMessageField</a>
</li>
<li>respondedFromCache
: <a class="el" href="interface_t_t_u_r_l_request.php#a4276b8e633d614eab0fd649775d75e7a">TTURLRequest</a>
</li>
<li>response
: <a class="el" href="interface_t_t_u_r_l_request.php#ae5480dad46898eb6007913b6746e706c">TTURLRequest</a>
</li>
<li>rootFrame
: <a class="el" href="interface_t_t_styled_text.php#ac6883624b3950d6df12acef4d4d379e3">TTStyledText</a>
</li>
<li>rootNode
: <a class="el" href="interface_t_t_styled_text.php#a92eafb991c1457c7131b01d17a28781b">TTStyledText</a>
</li>
<li>rootObject
: <a class="el" href="interface_t_t_x_m_l_parser.php#aa7429a4815521a3a988f572e61054151">TTXMLParser</a>
</li>
<li>rootViewController
: <a class="el" href="interface_t_t_base_navigator.php#a5568a0c8e0a19d26306e9d160d302b6e">TTBaseNavigator</a>
</li>
<li>rotateEnabled
: <a class="el" href="interface_t_t_scroll_view.php#a8cdc1e74e550eb1c09be05921ebff95d">TTScrollView</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>scrollEnabled
: <a class="el" href="interface_t_t_scroll_view.php#a198f1263d9d4469d064a4c68ef32ee48">TTScrollView</a>
</li>
<li>searchViewController
: <a class="el" href="interface_t_t_view_controller.php#aee5cb350b30e5feefffd3f118df21f86">TTViewController</a>
</li>
<li>shouldHandleCookies
: <a class="el" href="interface_t_t_u_r_l_request.php#aa421862494ee35a9bdb29102044d4301">TTURLRequest</a>
</li>
<li>showsRecipientPicker
: <a class="el" href="interface_t_t_message_controller.php#a81e95b4725b4c6ad3bb9a534fa045660">TTMessageController</a>
</li>
<li>showTableShadows
: <a class="el" href="interface_t_t_table_view_controller.php#a5a615ab4a6f2faf8a51eabcaf5664afd">TTTableViewController</a>
</li>
<li>size
: <a class="el" href="protocol_t_t_photo-p.php#af3f9f350defa57ccad9dfd3fa3379065">&lt;TTPhoto&gt;</a>
</li>
<li>sortKeys
: <a class="el" href="protocol_s_b_json_writer-p.php#ad424f1c19aead35d04509bfa549f7290">&lt;SBJsonWriter&gt;</a>
</li>
<li>statusBarStyle
: <a class="el" href="interface_t_t_base_view_controller.php#a9fbdc64e7c1d0e33c6e5c18c637484f7">TTBaseViewController</a>
</li>
<li>style
: <a class="el" href="interface_t_t_styled_box_frame.php#a5d525ddd5702d1cc8aeeef17a01c51eb">TTStyledBoxFrame</a>
, <a class="el" href="interface_t_t_styled_image_frame.php#a4419840410dcc3f63169692800591469">TTStyledImageFrame</a>
</li>
<li>subject
: <a class="el" href="interface_t_t_message_controller.php#a8414169377f297b9fcb41bbc9c0a058d">TTMessageController</a>
</li>
<li>supportsShakeToReload
: <a class="el" href="interface_t_t_base_navigator.php#ad49b7a6c9a4820d955a7eaf3687c05f2">TTBaseNavigator</a>
</li>
<li>suspended
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#a8addd08d2cef4fa320cf0930b4c8c591">TTURLRequestQueue</a>
</li>
</ul>


<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>tableBannerView
: <a class="el" href="interface_t_t_table_view_controller.php#a2c0c397163b1b4241e870d0bf997ee98">TTTableViewController</a>
</li>
<li>tableOverlayView
: <a class="el" href="interface_t_t_table_view_controller.php#a35a639881b27ff56a726d13ee23ebc5a">TTTableViewController</a>
</li>
<li>tableViewStyle
: <a class="el" href="interface_t_t_table_view_controller.php#ad1f016f908279a337da8fe69bdac9816">TTTableViewController</a>
</li>
<li>text
: <a class="el" href="interface_t_t_styled_text_frame.php#a0d7471c650b7cdccf0e83e1bde156ce7">TTStyledTextFrame</a>
, <a class="el" href="interface_t_t_styled_text_label.php#ad655d2cbb66cae2438275f9861e13766">TTStyledTextLabel</a>
</li>
<li>textAlignment
: <a class="el" href="interface_t_t_styled_text_label.php#a5f7b638fa4b8443134435cfd09c17d3a">TTStyledTextLabel</a>
</li>
<li>textColor
: <a class="el" href="interface_t_t_styled_text_label.php#afd11f17950467bcff3c50122a21e9bb3">TTStyledTextLabel</a>
</li>
<li>title
: <a class="el" href="interface_t_t_message_field.php#a494006ed1c012efd8082287c38212f4b">TTMessageField</a>
, <a class="el" href="protocol_t_t_photo_source-p.php#acfc9f3efc7b8a7dc672a147d99b6bea3">&lt;TTPhotoSource&gt;</a>
</li>
<li>topViewController
: <a class="el" href="interface_t_t_base_navigator.php#a9d5c8ea878103dd007eb3012d3749210">TTBaseNavigator</a>
</li>
<li>totalBytesExpected
: <a class="el" href="interface_t_t_u_r_l_request.php#a52951bb86cb8979e357db311468fce2b">TTURLRequest</a>
</li>
<li>totalBytesLoaded
: <a class="el" href="interface_t_t_u_r_l_request.php#a8021fb197041175383a69f20e0e471bc">TTURLRequest</a>
</li>
<li>treatDuplicateKeysAsArrayItems
: <a class="el" href="interface_t_t_x_m_l_parser.php#aa2ffa5a06a6b5f25cc4301777544c128">TTXMLParser</a>
</li>
</ul>


<h3><a class="anchor" id="index_u"></a>- u -</h3><ul>
<li>URL
: <a class="el" href="interface_t_t_link.php#a411a2104db6c430c46a6cbe687f5ac42">TTLink</a>
, <a class="el" href="interface_t_t_web_controller.php#a30b8fa744369bcd1066fb6a386e775ef">TTWebController</a>
, <a class="el" href="interface_t_t_base_navigator.php#a1ffbcfbcbefed8badea9d3bcbe21681a">TTBaseNavigator</a>
</li>
<li>URLAction
: <a class="el" href="interface_t_t_link.php#acac5fc4e17c49e878bd9e25df4fa1780">TTLink</a>
</li>
<li>URLMap
: <a class="el" href="interface_t_t_base_navigator.php#a3017d22aba919b66969e863484bb2168">TTBaseNavigator</a>
</li>
<li>urlPath
: <a class="el" href="interface_t_t_u_r_l_request.php#a4ad107c41d501a5666e65ad357842a4a">TTURLRequest</a>
, <a class="el" href="interface_t_t_image_view.php#a037c253134647eeb0dec16dc5bd8f7f6">TTImageView</a>
, <a class="el" href="interface_t_t_request_loader.php#ae05ab957f8610bdf6d8dc6c55561cf18">TTRequestLoader</a>
</li>
<li>URLValue
: <a class="el" href="protocol_t_t_u_r_l_object-p.php#a618b16ff58bc21afb3d6fc427a96a2ab">&lt;TTURLObject&gt;</a>
</li>
<li>userAgent
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#af57cab87b15e0b1c7fa7b6b90e6aa3aa">TTURLRequestQueue</a>
</li>
<li>userInfo
: <a class="el" href="interface_t_t_u_r_l_request.php#af0b3b2400e591b6e5d6f535ee6d63207">TTURLRequest</a>
</li>
</ul>


<h3><a class="anchor" id="index_v"></a>- v -</h3><ul>
<li>variableHeightRows
: <a class="el" href="interface_t_t_table_view_controller.php#a835ee43621a28a17cce38e2914ba9d98">TTTableViewController</a>
</li>
<li>visiblePages
: <a class="el" href="interface_t_t_scroll_view.php#ac5b71472eb1caa1b3b85ee54a1813e85">TTScrollView</a>
</li>
<li>visibleViewController
: <a class="el" href="interface_t_t_base_navigator.php#abe08b1203a02a91fe9b81f8dbb6cbda1">TTBaseNavigator</a>
</li>
</ul>


<h3><a class="anchor" id="index_w"></a>- w -</h3><ul>
<li>width
: <a class="el" href="interface_t_t_styled_text.php#a719c07b001bf7853437801889b755d8b">TTStyledText</a>
</li>
<li>window
: <a class="el" href="interface_t_t_base_navigator.php#a584f4a80461eea29d39b085acb023704">TTBaseNavigator</a>
</li>
</ul>


<h3><a class="anchor" id="index_z"></a>- z -</h3><ul>
<li>zoomed
: <a class="el" href="interface_t_t_scroll_view.php#a843c399a929d2e84777fd739c69ad2ca">TTScrollView</a>
</li>
<li>zoomEnabled
: <a class="el" href="interface_t_t_scroll_view.php#ab3888e4794b6633c4e0993cadd71057f">TTScrollView</a>
</li>
<li>zooming
: <a class="el" href="interface_t_t_scroll_view.php#a14d37707f3944ecbe72802496e3633e6">TTScrollView</a>
</li>
<li>zoomScale
: <a class="el" href="interface_t_t_scroll_view.php#ad5862684346ce52bbf57937a68ecb250">TTScrollView</a>
</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
