<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: Class Members</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="/documentation">Documentation</a></li> 
  <li><a href="/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="/">Three20</a></h1> 
  <h2><a href="/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_prop.php"><span>Properties</span></a></li>
    </ul>
  </div>
  <div class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index__"><span>_</span></a></li>
      <li><a href="functions_0x61.php#index_a"><span>a</span></a></li>
      <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
      <li class="current"><a href="functions_0x63.php#index_c"><span>c</span></a></li>
      <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
      <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
      <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
      <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
      <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
      <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
      <li><a href="functions_0x6a.php#index_j"><span>j</span></a></li>
      <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
      <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
      <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
      <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
      <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
      <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
      <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
      <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
      <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
      <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
      <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x77.php#index_w"><span>w</span></a></li>
      <li><a href="functions_0x79.php#index_y"><span>y</span></a></li>
      <li><a href="functions_0x7a.php#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
Here is a list of all documented class members with links to the class documentation for each member:

<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>cacheExpirationAge
: <a class="el" href="interface_t_t_request_loader.php#a91e393e0d058d3a789e3d782bbd02357">TTRequestLoader</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#aa0f7d2b7001143d1b9f1d3635449a4f1">TTURLRequest</a>
</li>
<li>cacheKey
: <a class="el" href="interface_t_t_u_r_l_request.php#ace472f23740be06aa40dffdbdca99953">TTURLRequest</a>
, <a class="el" href="interface_t_t_u_r_l_request_model.php#a2127dc12c0ef3b45dd099f37f6337d2b">TTURLRequestModel</a>
, <a class="el" href="interface_t_t_request_loader.php#afc70c6b8ef860ee13fef091dae10ca41">TTRequestLoader</a>
</li>
<li>cachePath
: <a class="el" href="interface_t_t_u_r_l_cache.php#a52da998d5df61ba519db1469597a54a3">TTURLCache</a>
</li>
<li>cachePathForKey:
: <a class="el" href="interface_t_t_u_r_l_cache.php#a2b1cb4ca924ee2144bdcabdac4f6ee74">TTURLCache</a>
</li>
<li>cachePathForURL:
: <a class="el" href="interface_t_t_u_r_l_cache.php#a5d5753453f34e8004d4f718e003ac8d2">TTURLCache</a>
</li>
<li>cachePolicy
: <a class="el" href="interface_t_t_request_loader.php#a73a04e9934fd4e34b369c60c31578227">TTRequestLoader</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#a34ad517e5d5fe222baec6702b9eb4cde">TTURLRequest</a>
</li>
<li>cacheWithName:
: <a class="el" href="interface_t_t_u_r_l_cache.php#ae99fab5ff227b3cb42a6fc3544932ab9">TTURLCache</a>
</li>
<li>cancel
: <a class="el" href="protocol_t_t_model-p.php#ab1a78579b78649df0061aabd384db721">&lt;TTModel&gt;</a>
, <a class="el" href="interface_t_t_u_r_l_request.php#ac0962ff3e7ebc9fb7982ffe56f875f34">TTURLRequest</a>
, <a class="el" href="interface_t_t_post_controller.php#a7a84a582d29106bd08ffc0a7bd419eb0">TTPostController</a>
, <a class="el" href="interface_t_t_text_bar_controller.php#aa6b36727b7d8959bd2475e31c6b0f127">TTTextBarController</a>
</li>
<li>cancel:
: <a class="el" href="interface_t_t_request_loader.php#a41f21a57f28ebf81b3ce99343c5e8ea7">TTRequestLoader</a>
, <a class="el" href="interface_t_t_message_controller.php#aa164519b99a08d60155c75fe422f3489">TTMessageController</a>
</li>
<li>cancelAllRequests
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#a42f6150b9df2681783bc7c534f43abc2">TTURLRequestQueue</a>
</li>
<li>cancelDelay
: <a class="el" href="interface_t_t_base_navigator.php#a7bf628d499c8d8f974cfca8a7dbc7931">TTBaseNavigator</a>
</li>
<li>cancelRequest:
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#a008ecf13892baab45a69f8051637aa51">TTURLRequestQueue</a>
</li>
<li>cancelRequestsWithDelegate:
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#a263596b58314c7ea6c14f8b5718f7b26">TTURLRequestQueue</a>
</li>
<li>cancelTouches
: <a class="el" href="interface_t_t_scroll_view.php#a0355b8acf924ee8a50be198cf7c9388f">TTScrollView</a>
</li>
<li>canShowModel
: <a class="el" href="interface_t_t_model_view_controller.php#a1648848389e0e716f42cbab7ba1bad94">TTModelViewController</a>
</li>
<li>caption
: <a class="el" href="protocol_t_t_photo-p.php#ae7dbc655e54ac2f77c7b0b5addf9cb47">&lt;TTPhoto&gt;</a>
</li>
<li>captionStyle
: <a class="el" href="interface_t_t_photo_view_controller.php#a2e04d249898456d712dd25ac1a2b42a1">TTPhotoViewController</a>
</li>
<li>centerPageIndex
: <a class="el" href="interface_t_t_scroll_view.php#a78d5e647a3cadb39d064eab51ba67e31">TTScrollView</a>
</li>
<li>centerPhoto
: <a class="el" href="interface_t_t_photo_view_controller.php#ae4080daae3eb4cbb4c87162d178c3449">TTPhotoViewController</a>
</li>
<li>centerPhotoIndex
: <a class="el" href="interface_t_t_photo_view_controller.php#a8a4e41837254638e66304de521e7de5a">TTPhotoViewController</a>
</li>
<li>charsetForMultipart
: <a class="el" href="interface_t_t_u_r_l_request.php#a8a432224b4b3c781a593f8512c124ec1">TTURLRequest</a>
</li>
<li>checkUTF8
: <a class="el" href="structyajl__parser__config.php#a33f7ab7fb27bf626441f15d649dea5d9">yajl_parser_config</a>
</li>
<li>colorWithCssSelector:forState:
: <a class="el" href="interface_t_t_c_s_s_style_sheet.php#a61047c7d2218ef3225ecd797e49ead9e">TTCSSStyleSheet</a>
</li>
<li>composeController:didSendFields:
: <a class="el" href="protocol_t_t_message_controller_delegate-p.php#a2829ad907cea2d4ecdb71961bdb2da66">&lt;TTMessageControllerDelegate&gt;</a>
</li>
<li>composeControllerShowRecipientPicker:
: <a class="el" href="protocol_t_t_message_controller_delegate-p.php#a25f3cd0ff06f702c2122178ce2838733">&lt;TTMessageControllerDelegate&gt;</a>
</li>
<li>composeControllerWillCancel:
: <a class="el" href="protocol_t_t_message_controller_delegate-p.php#a60bdf7191024e537e4eff3d18fc7f219">&lt;TTMessageControllerDelegate&gt;</a>
</li>
<li>confirmCancellation
: <a class="el" href="interface_t_t_message_controller.php#a930b60b957c1c6b8a70f5ba2c39e4cce">TTMessageController</a>
</li>
<li>contentInset
: <a class="el" href="interface_t_t_styled_text_label.php#a82b3d4f94a46a347621ec4ed6bc03244">TTStyledTextLabel</a>
</li>
<li>contentType
: <a class="el" href="interface_t_t_u_r_l_request.php#a7cf514d3f3d6526b183220d9c21513fd">TTURLRequest</a>
</li>
<li>createDelegate
: <a class="el" href="interface_t_t_table_view_controller.php#a52626a5ea529445ca0edf79f1c3d9dbb">TTTableViewController</a>
</li>
<li>createModel
: <a class="el" href="interface_t_t_model_view_controller.php#a277731e4a0b2afacef0f50d052f5a6ee">TTModelViewController</a>
</li>
<li>createNSURLRequest:URL:
: <a class="el" href="interface_t_t_u_r_l_request_queue.php#abf973b89da8bd792e80f4d545f72325d">TTURLRequestQueue</a>
</li>
<li>createPhotoView
: <a class="el" href="interface_t_t_photo_view_controller.php#a424ae934956c1e1d35666a17e55a9f72">TTPhotoViewController</a>
</li>
<li>createThumbsViewController
: <a class="el" href="interface_t_t_photo_view_controller.php#a31e0f57e5133442a296d12d7eb6da125">TTPhotoViewController</a>
</li>
<li>ctx
: <a class="el" href="structyajl__alloc__funcs.php#afa64c0d73d185a6fdabd648e9746f6b5">yajl_alloc_funcs</a>
</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
