<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: Class Members</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fthree20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_prop.php"><span>Properties</span></a></li>
    </ul>
  </div>
  <div class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index__"><span>_</span></a></li>
      <li><a href="functions_0x61.php#index_a"><span>a</span></a></li>
      <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
      <li><a href="functions_0x63.php#index_c"><span>c</span></a></li>
      <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
      <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
      <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
      <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
      <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
      <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
      <li><a href="functions_0x6a.php#index_j"><span>j</span></a></li>
      <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
      <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
      <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
      <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
      <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
      <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
      <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
      <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
      <li class="current"><a href="functions_0x74.php#index_t"><span>t</span></a></li>
      <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
      <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x77.php#index_w"><span>w</span></a></li>
      <li><a href="functions_0x79.php#index_y"><span>y</span></a></li>
      <li><a href="functions_0x7a.php#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
Here is a list of all documented class members with links to the class documentation for each member:

<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>tableBannerView
: <a class="el" href="interface_t_t_table_view_controller.php#a2c0c397163b1b4241e870d0bf997ee98">TTTableViewController</a>
</li>
<li>tableOverlayView
: <a class="el" href="interface_t_t_table_view_controller.php#a35a639881b27ff56a726d13ee23ebc5a">TTTableViewController</a>
</li>
<li>tableView:rowHeightForObject:
: <a class="el" href="interface_t_t_table_view_cell.php#a50a7006ec9fb5bb4533b6100f4f56dbb">TTTableViewCell</a>
</li>
<li>tableViewDidLoadModel:
: <a class="el" href="protocol_t_t_table_view_data_source-p.php#a96aa481ecfee16bc78f32bc1ba3128d7">&lt;TTTableViewDataSource&gt;</a>
</li>
<li>tableViewStyle
: <a class="el" href="interface_t_t_table_view_controller.php#ad1f016f908279a337da8fe69bdac9816">TTTableViewController</a>
</li>
<li>text
: <a class="el" href="interface_t_t_styled_text_frame.php#a0d7471c650b7cdccf0e83e1bde156ce7">TTStyledTextFrame</a>
, <a class="el" href="interface_t_t_styled_text_label.php#ad655d2cbb66cae2438275f9861e13766">TTStyledTextLabel</a>
</li>
<li>textAlignment
: <a class="el" href="interface_t_t_styled_text_label.php#a5f7b638fa4b8443134435cfd09c17d3a">TTStyledTextLabel</a>
</li>
<li>textBar:didPostText:withResult:
: <a class="el" href="protocol_t_t_text_bar_delegate-p.php#a6dfb8795542c53cfb0f7a6b093b51c65">&lt;TTTextBarDelegate&gt;</a>
</li>
<li>textBar:willPostText:
: <a class="el" href="protocol_t_t_text_bar_delegate-p.php#a21a2ff9f7a56c55c321e067093e1749d">&lt;TTTextBarDelegate&gt;</a>
</li>
<li>textBarDidCancel:
: <a class="el" href="protocol_t_t_text_bar_delegate-p.php#a906a33de435852df6e9a31a08d0497fc">&lt;TTTextBarDelegate&gt;</a>
</li>
<li>textColor
: <a class="el" href="interface_t_t_styled_text_label.php#afd11f17950467bcff3c50122a21e9bb3">TTStyledTextLabel</a>
</li>
<li>textForFieldAtIndex:
: <a class="el" href="interface_t_t_message_controller.php#ab7d2ca53fae85cc98f75b509879c2754">TTMessageController</a>
</li>
<li>textFromXHTML:
: <a class="el" href="interface_t_t_styled_text.php#ad75363ae16d23a7823f00adb79aa0636">TTStyledText</a>
</li>
<li>textShadowColorWithCssSelector:forState:
: <a class="el" href="interface_t_t_c_s_s_style_sheet.php#a93fdfb60df8dfc3c257675a97c0a9b0a">TTCSSStyleSheet</a>
</li>
<li>textShadowOffsetWithCssSelector:forState:
: <a class="el" href="interface_t_t_c_s_s_style_sheet.php#a66888cb43b562feb647dad43be74e534">TTCSSStyleSheet</a>
</li>
<li>textWithURLs:
: <a class="el" href="interface_t_t_styled_text.php#aebee0ebff20c99816f976c99d9fc7889">TTStyledText</a>
</li>
<li>title
: <a class="el" href="interface_t_t_message_field.php#a494006ed1c012efd8082287c38212f4b">TTMessageField</a>
, <a class="el" href="protocol_t_t_photo_source-p.php#acfc9f3efc7b8a7dc672a147d99b6bea3">&lt;TTPhotoSource&gt;</a>
</li>
<li>titleForSending
: <a class="el" href="interface_t_t_message_controller.php#a48fd3ef54fda0dfaeac75317b71e6d84">TTMessageController</a>
</li>
<li>topViewController
: <a class="el" href="interface_t_t_base_navigator.php#a9d5c8ea878103dd007eb3012d3749210">TTBaseNavigator</a>
</li>
<li>totalBytesDownloaded
: <a class="el" href="interface_t_t_u_r_l_request.php#a57e7e58d55768b6f55f809ed7540f188">TTURLRequest</a>
</li>
<li>totalBytesExpected
: <a class="el" href="interface_t_t_u_r_l_request.php#a52951bb86cb8979e357db311468fce2b">TTURLRequest</a>
</li>
<li>totalBytesLoaded
: <a class="el" href="interface_t_t_u_r_l_request.php#a8021fb197041175383a69f20e0e471bc">TTURLRequest</a>
</li>
<li>totalContentLength
: <a class="el" href="interface_t_t_u_r_l_request.php#a56d883edac9ce53e50062dc782c59d19">TTURLRequest</a>
</li>
<li>transitionForURL:
: <a class="el" href="interface_t_t_u_r_l_map.php#a0afe15c0ead5f0b9074a4bba8ebf980c">TTURLMap</a>
</li>
<li>treatDuplicateKeysAsArrayItems
: <a class="el" href="interface_t_t_x_m_l_parser.php#aa2ffa5a06a6b5f25cc4301777544c128">TTXMLParser</a>
</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
