<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: Hierarchical Index</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fthree20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li class="current"><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Class Hierarchy</h1>  </div>
</div>
<div class="contents">
This inheritance list is sorted roughly, but not completely, alphabetically:<ul>
<li><a class="el" href="interface_basic_tests.php">BasicTests</a></li>
<li><a class="el" href="interface_core_addition_tests.php">CoreAdditionTests</a></li>
<li><a class="el" href="interface_core_global_tests.php">CoreGlobalTests</a></li>
<li><a class="el" href="interface_core_markup_stripper_tests.php">CoreMarkupStripperTests</a></li>
<li><a class="el" href="interface_css_parser_tests.php">CssParserTests</a></li>
<li><a class="el" href="interface_css_style_sheet_tests.php">CssStyleSheetTests</a></li>
<li><a class="el" href="interfaceext_j_s_o_n_tests.php">extJSONTests</a></li>
<li><a class="el" href="interfaceext_x_m_l_tests.php">extXMLTests</a></li>
<li><a class="el" href="interface_network_model_tests.php">NetworkModelTests</a></li>
<li><a class="el" href="interface_network_u_r_l_cache_tests.php">NetworkURLCacheTests</a></li>
<li><a class="el" href="class_n_s_array.php">NSArray</a></li>
<li><a class="el" href="class_n_s_data.php">NSData</a></li>
<li><a class="el" href="class_n_s_date.php">NSDate</a></li>
<li><a class="el" href="class_n_s_dictionary.php">NSDictionary</a></li>
<li><a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a></li>
<li><a class="el" href="class_n_s_mutable_dictionary.php">NSMutableDictionary</a></li>
<li><a class="el" href="class_n_s_object.php">NSObject</a><ul>
<li><a class="el" href="interface_g_s_event_fake.php">GSEventFake</a></li>
<li><a class="el" href="interface_mock_model_delegate.php">MockModelDelegate</a></li>
<li><a class="el" href="interface_s_b_json_base.php">SBJsonBase</a><ul>
<li><a class="el" href="interface_s_b_json_parser.php">SBJsonParser</a></li>
<li><a class="el" href="interface_s_b_json_writer.php">SBJsonWriter</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a><ul>
<li><a class="el" href="interface_t_t_navigator.php">TTNavigator</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_button_content.php">TTButtonContent</a></li>
<li><a class="el" href="interface_t_t_c_s_s_parser.php">TTCSSParser</a></li>
<li><a class="el" href="interface_t_t_c_s_s_style_sheet.php">TTCSSStyleSheet</a></li>
<li><a class="el" href="interface_t_t_entity_tables.php">TTEntityTables</a></li>
<li><a class="el" href="interface_t_t_extension_author.php">TTExtensionAuthor</a></li>
<li><a class="el" href="interface_t_t_extension_info.php">TTExtensionInfo</a></li>
<li><a class="el" href="class_t_t_extension_loader.php">TTExtensionLoader</a></li>
<li><a class="el" href="interface_t_t_launcher_item.php">TTLauncherItem</a></li>
<li><a class="el" href="interface_t_t_layout.php">TTLayout</a><ul>
<li><a class="el" href="interface_t_t_flow_layout.php">TTFlowLayout</a></li>
<li><a class="el" href="interface_t_t_grid_layout.php">TTGridLayout</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_markup_stripper.php">TTMarkupStripper</a></li>
<li><a class="el" href="interface_t_t_message_field.php">TTMessageField</a><ul>
<li><a class="el" href="interface_t_t_message_recipient_field.php">TTMessageRecipientField</a></li>
<li><a class="el" href="interface_t_t_message_text_field.php">TTMessageTextField</a><ul>
<li><a class="el" href="interface_t_t_message_subject_field.php">TTMessageSubjectField</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_model.php">TTModel</a><ul>
<li><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_recursive_progress.php">TTRecursiveProgress</a></li>
<li><a class="el" href="interface_t_t_request_loader.php">TTRequestLoader</a></li>
<li><a class="el" href="interface_t_t_search_text_field_internal.php">TTSearchTextFieldInternal</a></li>
<li><a class="el" href="interface_t_t_shape.php">TTShape</a><ul>
<li><a class="el" href="interface_t_t_rectangle_shape.php">TTRectangleShape</a></li>
<li><a class="el" href="interface_t_t_rounded_left_arrow_shape.php">TTRoundedLeftArrowShape</a></li>
<li><a class="el" href="interface_t_t_rounded_rectangle_shape.php">TTRoundedRectangleShape</a></li>
<li><a class="el" href="interface_t_t_rounded_right_arrow_shape.php">TTRoundedRightArrowShape</a></li>
<li><a class="el" href="interface_t_t_speech_bubble_shape.php">TTSpeechBubbleShape</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_style.php">TTStyle</a><ul>
<li><a class="el" href="interface_t_t_bevel_border_style.php">TTBevelBorderStyle</a></li>
<li><a class="el" href="interface_t_t_blend_style.php">TTBlendStyle</a></li>
<li><a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a></li>
<li><a class="el" href="interface_t_t_content_style.php">TTContentStyle</a></li>
<li><a class="el" href="interface_t_t_four_border_style.php">TTFourBorderStyle</a></li>
<li><a class="el" href="interface_t_t_highlight_border_style.php">TTHighlightBorderStyle</a></li>
<li><a class="el" href="interface_t_t_image_style.php">TTImageStyle</a></li>
<li><a class="el" href="interface_t_t_inset_style.php">TTInsetStyle</a></li>
<li><a class="el" href="interface_t_t_linear_gradient_border_style.php">TTLinearGradientBorderStyle</a></li>
<li><a class="el" href="interface_t_t_linear_gradient_fill_style.php">TTLinearGradientFillStyle</a></li>
<li><a class="el" href="interface_t_t_mask_style.php">TTMaskStyle</a></li>
<li><a class="el" href="interface_t_t_part_style.php">TTPartStyle</a></li>
<li><a class="el" href="interface_t_t_reflective_fill_style.php">TTReflectiveFillStyle</a></li>
<li><a class="el" href="interface_t_t_shadow_style.php">TTShadowStyle</a><ul>
<li><a class="el" href="interface_t_t_inner_shadow_style.php">TTInnerShadowStyle</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_shape_style.php">TTShapeStyle</a></li>
<li><a class="el" href="interface_t_t_solid_border_style.php">TTSolidBorderStyle</a></li>
<li><a class="el" href="interface_t_t_solid_fill_style.php">TTSolidFillStyle</a></li>
<li><a class="el" href="interface_t_t_text_style.php">TTTextStyle</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_style_context.php">TTStyleContext</a></li>
<li><a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a><ul>
<li><a class="el" href="interface_t_t_styled_box_frame.php">TTStyledBoxFrame</a><ul>
<li><a class="el" href="interface_t_t_styled_inline_frame.php">TTStyledInlineFrame</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_image_frame.php">TTStyledImageFrame</a></li>
<li><a class="el" href="interface_t_t_styled_text_frame.php">TTStyledTextFrame</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_layout.php">TTStyledLayout</a></li>
<li><a class="el" href="interface_t_t_styled_node.php">TTStyledNode</a><ul>
<li><a class="el" href="interface_t_t_styled_element.php">TTStyledElement</a><ul>
<li><a class="el" href="interface_t_t_styled_block.php">TTStyledBlock</a><ul>
<li><a class="el" href="interface_t_t_styled_line_break_node.php">TTStyledLineBreakNode</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_image_node.php">TTStyledImageNode</a></li>
<li><a class="el" href="interface_t_t_styled_inline.php">TTStyledInline</a><ul>
<li><a class="el" href="interface_t_t_styled_bold_node.php">TTStyledBoldNode</a></li>
<li><a class="el" href="interface_t_t_styled_italic_node.php">TTStyledItalicNode</a></li>
<li><a class="el" href="interface_t_t_styled_link_node.php">TTStyledLinkNode</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_inline_block.php">TTStyledInlineBlock</a><ul>
<li><a class="el" href="interface_t_t_styled_button_node.php">TTStyledButtonNode</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_text_node.php">TTStyledTextNode</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_text.php">TTStyledText</a></li>
<li><a class="el" href="interface_t_t_styled_text_parser.php">TTStyledTextParser</a></li>
<li><a class="el" href="interface_t_t_style_sheet.php">TTStyleSheet</a><ul>
<li><a class="el" href="interface_t_t_default_style_sheet.php">TTDefaultStyleSheet</a><ul>
<li><a class="el" href="interface_t_t_default_c_s_s_style_sheet.php">TTDefaultCSSStyleSheet</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_tab_item.php">TTTabItem</a></li>
<li><a class="el" href="interface_t_t_table_item.php">TTTableItem</a><ul>
<li><a class="el" href="interface_t_t_table_activity_item.php">TTTableActivityItem</a></li>
<li><a class="el" href="interface_t_t_table_control_item.php">TTTableControlItem</a></li>
<li><a class="el" href="interface_t_t_table_linked_item.php">TTTableLinkedItem</a><ul>
<li><a class="el" href="interface_t_t_table_styled_text_item.php">TTTableStyledTextItem</a></li>
<li><a class="el" href="interface_t_t_table_text_item.php">TTTableTextItem</a><ul>
<li><a class="el" href="interface_t_t_table_button.php">TTTableButton</a></li>
<li><a class="el" href="interface_t_t_table_caption_item.php">TTTableCaptionItem</a><ul>
<li><a class="el" href="interface_t_t_table_right_caption_item.php">TTTableRightCaptionItem</a></li>
<li><a class="el" href="interface_t_t_table_subtext_item.php">TTTableSubtextItem</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_gray_text_item.php">TTTableGrayTextItem</a></li>
<li><a class="el" href="interface_t_t_table_image_item.php">TTTableImageItem</a><ul>
<li><a class="el" href="interface_t_t_table_right_image_item.php">TTTableRightImageItem</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_link.php">TTTableLink</a></li>
<li><a class="el" href="interface_t_t_table_long_text_item.php">TTTableLongTextItem</a></li>
<li><a class="el" href="interface_t_t_table_message_item.php">TTTableMessageItem</a></li>
<li><a class="el" href="interface_t_t_table_subtitle_item.php">TTTableSubtitleItem</a><ul>
<li><a class="el" href="interface_t_t_table_more_button.php">TTTableMoreButton</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_summary_item.php">TTTableSummaryItem</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_view_item.php">TTTableViewItem</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a><ul>
<li><a class="el" href="interface_t_t_list_data_source.php">TTListDataSource</a></li>
<li><a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a></li>
<li><a class="el" href="interface_t_t_table_view_interstitial_data_source.php">TTTableViewInterstitialDataSource</a></li>
<li><a class="el" href="interface_t_t_thumbs_data_source.php">TTThumbsDataSource</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_view_delegate.php">TTTableViewDelegate</a><ul>
<li><a class="el" href="interface_t_t_table_view_plain_delegate.php">TTTableViewPlainDelegate</a></li>
<li><a class="el" href="interface_t_t_table_view_var_height_delegate.php">TTTableViewVarHeightDelegate</a><ul>
<li><a class="el" href="interface_t_t_table_view_drag_refresh_delegate.php">TTTableViewDragRefreshDelegate</a></li>
<li><a class="el" href="interface_t_t_table_view_grouped_var_height_delegate.php">TTTableViewGroupedVarHeightDelegate</a></li>
<li><a class="el" href="interface_t_t_table_view_network_enabled_delegate.php">TTTableViewNetworkEnabledDelegate</a></li>
<li><a class="el" href="interface_t_t_table_view_plain_var_height_delegate.php">TTTableViewPlainVarHeightDelegate</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_text_editor_internal.php">TTTextEditorInternal</a></li>
<li><a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a></li>
<li><a class="el" href="interface_t_t_u_r_l_cache.php">TTURLCache</a></li>
<li><a class="el" href="interface_t_t_u_r_l_data_response.php">TTURLDataResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_image_response.php">TTURLImageResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_j_s_o_n_response.php">TTURLJSONResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_literal.php">TTURLLiteral</a></li>
<li><a class="el" href="interface_t_t_u_r_l_map.php">TTURLMap</a></li>
<li><a class="el" href="interface_t_t_u_r_l_pattern.php">TTURLPattern</a><ul>
<li><a class="el" href="interface_t_t_u_r_l_generator_pattern.php">TTURLGeneratorPattern</a></li>
<li><a class="el" href="interface_t_t_u_r_l_navigator_pattern.php">TTURLNavigatorPattern</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_u_r_l_request.php">TTURLRequest</a></li>
<li><a class="el" href="interface_t_t_u_r_l_request_queue.php">TTURLRequestQueue</a></li>
<li><a class="el" href="interface_t_t_u_r_l_selector.php">TTURLSelector</a></li>
<li><a class="el" href="interface_t_t_u_r_l_wildcard.php">TTURLWildcard</a></li>
<li><a class="el" href="interface_t_t_u_r_l_x_m_l_response.php">TTURLXMLResponse</a></li>
<li><a class="el" href="interface_t_t_user_info.php">TTUserInfo</a></li>
<li><a class="el" href="interface_u_i_event_fake.php">UIEventFake</a></li>
<li><a class="el" href="interface_y_a_j_l___g_t_m_base64.php">YAJL_GTMBase64</a></li>
<li><a class="el" href="interface_y_a_j_l_document.php">YAJLDocument</a></li>
<li><a class="el" href="interface_y_a_j_l_gen.php">YAJLGen</a></li>
<li><a class="el" href="interface_y_a_j_l_parser.php">YAJLParser</a></li>
</ul>
</li>
<li><a class="el" href="class_n_s_string.php">NSString</a></li>
<li><a class="el" href="class_pbxproj_1_1_pbxproj.php">Pbxproj::Pbxproj</a></li>
<li><a class="el" href="interface_t_t_action_sheet.php">TTActionSheet</a></li>
<li><a class="el" href="protocol_t_t_action_sheet_controller_delegate-p.php">&lt;TTActionSheetControllerDelegate&gt;</a></li>
<li><a class="el" href="interface_t_t_alert_view.php">TTAlertView</a></li>
<li><a class="el" href="protocol_t_t_alert_view_controller_delegate-p.php">&lt;TTAlertViewControllerDelegate&gt;</a></li>
<li><a class="el" href="interface_t_t_image_layer.php">TTImageLayer</a></li>
<li><a class="el" href="protocol_t_t_image_view_delegate-p.php">&lt;TTImageViewDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_photo_view.php">TTPhotoView</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_launcher_scroll_view.php">TTLauncherScrollView</a></li>
<li><a class="el" href="protocol_t_t_launcher_view_delegate-p.php">&lt;TTLauncherViewDelegate&gt;</a></li>
<li><a class="el" href="interface_t_t_link.php">TTLink</a></li>
<li><a class="el" href="protocol_t_t_message_controller_delegate-p.php">&lt;TTMessageControllerDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_model-p.php">&lt;TTModel&gt;</a><ul>
<li><a class="el" href="interface_t_t_model.php">TTModel</a></li>
<li><a class="el" href="protocol_t_t_photo_source-p.php">&lt;TTPhotoSource&gt;</a></li>
<li><a class="el" href="protocol_t_t_table_view_data_source-p.php">&lt;TTTableViewDataSource&gt;</a><ul>
<li><a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_view_interstitial_data_source.php">TTTableViewInterstitialDataSource</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_model_delegate-p.php">&lt;TTModelDelegate&gt;</a><ul>
<li><a class="el" href="interface_mock_model_delegate.php">MockModelDelegate</a></li>
<li><a class="el" href="interface_t_t_model_view_controller.php">TTModelViewController</a><ul>
<li><a class="el" href="interface_t_t_photo_view_controller.php">TTPhotoViewController</a></li>
<li><a class="el" href="interface_t_t_popup_view_controller.php">TTPopupViewController</a><ul>
<li><a class="el" href="interface_t_t_action_sheet_controller.php">TTActionSheetController</a></li>
<li><a class="el" href="interface_t_t_alert_view_controller.php">TTAlertViewController</a></li>
<li><a class="el" href="interface_t_t_post_controller.php">TTPostController</a></li>
<li><a class="el" href="interface_t_t_text_bar_controller.php">TTTextBarController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_view_controller.php">TTTableViewController</a><ul>
<li><a class="el" href="interface_t_t_extension_info_controller.php">TTExtensionInfoController</a></li>
<li><a class="el" href="interface_t_t_extensions_controller.php">TTExtensionsController</a></li>
<li><a class="el" href="interface_t_t_thumbs_view_controller.php">TTThumbsViewController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_web_controller.php">TTWebController</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_navigator_delegate-p.php">&lt;TTNavigatorDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_navigator_root_container-p.php">&lt;TTNavigatorRootContainer&gt;</a><ul>
<li><a class="el" href="interface_t_t_split_view_controller.php">TTSplitViewController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_page_control.php">TTPageControl</a></li>
<li><a class="el" href="protocol_t_t_post_controller_delegate-p.php">&lt;TTPostControllerDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_recursive_progress_delegate-p.php">&lt;TTRecursiveProgressDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_scroll_view_data_source-p.php">&lt;TTScrollViewDataSource&gt;</a><ul>
<li><a class="el" href="interface_t_t_photo_view_controller.php">TTPhotoViewController</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_scroll_view_delegate-p.php">&lt;TTScrollViewDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_photo_view_controller.php">TTPhotoViewController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_search_display_controller.php">TTSearchDisplayController</a></li>
<li><a class="el" href="interface_t_t_search_text_field.php">TTSearchTextField</a><ul>
<li><a class="el" href="interface_t_t_picker_text_field.php">TTPickerTextField</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_search_text_field_delegate-p.php">&lt;TTSearchTextFieldDelegate&gt;</a><ul>
<li><a class="el" href="protocol_t_t_picker_text_field_delegate-p.php">&lt;TTPickerTextFieldDelegate&gt;</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_style_delegate-p.php">&lt;TTStyleDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_button.php">TTButton</a><ul>
<li><a class="el" href="interface_t_t_launcher_button.php">TTLauncherButton</a></li>
<li><a class="el" href="interface_t_t_tab.php">TTTab</a></li>
<li><a class="el" href="interface_t_t_thumb_view.php">TTThumbView</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_styled_box_frame.php">TTStyledBoxFrame</a></li>
<li><a class="el" href="interface_t_t_styled_image_frame.php">TTStyledImageFrame</a></li>
<li><a class="el" href="interface_t_t_view.php">TTView</a><ul>
<li><a class="el" href="interface_t_t_button_bar.php">TTButtonBar</a></li>
<li><a class="el" href="interface_t_t_image_view.php">TTImageView</a><ul>
<li><a class="el" href="interface_t_t_photo_view.php">TTPhotoView</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_label.php">TTLabel</a></li>
<li><a class="el" href="interface_t_t_picker_view_cell.php">TTPickerViewCell</a></li>
<li><a class="el" href="interface_t_t_search_bar.php">TTSearchBar</a></li>
<li><a class="el" href="interface_t_t_tab_bar.php">TTTabBar</a><ul>
<li><a class="el" href="interface_t_t_tab_grid.php">TTTabGrid</a></li>
<li><a class="el" href="interface_t_t_tab_strip.php">TTTabStrip</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_header_view.php">TTTableHeaderView</a></li>
<li><a class="el" href="interface_t_t_text_editor.php">TTTextEditor</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_styled_text_delegate-p.php">&lt;TTStyledTextDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_styled_text_label.php">TTStyledTextLabel</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_tab_delegate-p.php">&lt;TTTabDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_table_network_enabled_table_view_controller-p.php">&lt;TTTableNetworkEnabledTableViewController&gt;</a></li>
<li><a class="el" href="interface_t_t_table_view_cell.php">TTTableViewCell</a><ul>
<li><a class="el" href="interface_t_t_styled_text_table_cell.php">TTStyledTextTableCell</a></li>
<li><a class="el" href="interface_t_t_table_activity_item_cell.php">TTTableActivityItemCell</a></li>
<li><a class="el" href="interface_t_t_table_control_cell.php">TTTableControlCell</a></li>
<li><a class="el" href="interface_t_t_table_flush_view_cell.php">TTTableFlushViewCell</a></li>
<li><a class="el" href="interface_t_t_table_linked_item_cell.php">TTTableLinkedItemCell</a><ul>
<li><a class="el" href="interface_t_t_styled_text_table_item_cell.php">TTStyledTextTableItemCell</a></li>
<li><a class="el" href="interface_t_t_table_caption_item_cell.php">TTTableCaptionItemCell</a></li>
<li><a class="el" href="interface_t_t_table_message_item_cell.php">TTTableMessageItemCell</a></li>
<li><a class="el" href="interface_t_t_table_right_caption_item_cell.php">TTTableRightCaptionItemCell</a></li>
<li><a class="el" href="interface_t_t_table_subtext_item_cell.php">TTTableSubtextItemCell</a></li>
<li><a class="el" href="interface_t_t_table_subtitle_item_cell.php">TTTableSubtitleItemCell</a><ul>
<li><a class="el" href="interface_t_t_table_more_button_cell.php">TTTableMoreButtonCell</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_table_text_item_cell.php">TTTableTextItemCell</a><ul>
<li><a class="el" href="interface_t_t_table_image_item_cell.php">TTTableImageItemCell</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_t_t_thumbs_table_view_cell.php">TTThumbsTableViewCell</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_table_view_delegate-p.php">&lt;TTTableViewDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_text_bar_delegate-p.php">&lt;TTTextBarDelegate&gt;</a></li>
<li><a class="el" href="protocol_t_t_text_editor_delegate-p.php">&lt;TTTextEditorDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></li>
<li><a class="el" href="interface_t_t_text_bar_controller.php">TTTextBarController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_text_view.php">TTTextView</a></li>
<li><a class="el" href="protocol_t_t_thumbs_table_view_cell_delegate-p.php">&lt;TTThumbsTableViewCellDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_thumbs_view_controller.php">TTThumbsViewController</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_thumbs_view_controller_delegate-p.php">&lt;TTThumbsViewControllerDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_photo_view_controller.php">TTPhotoViewController</a></li>
</ul>
</li>
<li><a class="el" href="interface_t_t_u_r_l_action_tests.php">TTURLActionTests</a></li>
<li><a class="el" href="protocol_t_t_u_r_l_object-p.php">&lt;TTURLObject&gt;</a><ul>
<li><a class="el" href="protocol_t_t_photo-p.php">&lt;TTPhoto&gt;</a></li>
<li><a class="el" href="protocol_t_t_photo_source-p.php">&lt;TTPhotoSource&gt;</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_u_r_l_pattern_text-p.php">&lt;TTURLPatternText&gt;</a><ul>
<li><a class="el" href="interface_t_t_u_r_l_literal.php">TTURLLiteral</a></li>
<li><a class="el" href="interface_t_t_u_r_l_wildcard.php">TTURLWildcard</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_u_r_l_request_delegate-p.php">&lt;TTURLRequestDelegate&gt;</a><ul>
<li><a class="el" href="interface_t_t_button_content.php">TTButtonContent</a></li>
<li><a class="el" href="interface_t_t_image_view.php">TTImageView</a></li>
<li><a class="el" href="interface_t_t_styled_text.php">TTStyledText</a></li>
<li><a class="el" href="interface_t_t_u_r_l_request_model.php">TTURLRequestModel</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_u_r_l_response-p.php">&lt;TTURLResponse&gt;</a><ul>
<li><a class="el" href="interface_t_t_u_r_l_data_response.php">TTURLDataResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_image_response.php">TTURLImageResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_j_s_o_n_response.php">TTURLJSONResponse</a></li>
<li><a class="el" href="interface_t_t_u_r_l_x_m_l_response.php">TTURLXMLResponse</a></li>
</ul>
</li>
<li><a class="el" href="protocol_t_t_web_controller_delegate-p.php">&lt;TTWebControllerDelegate&gt;</a></li>
<li><a class="el" href="interface_t_t_x_m_l_parser.php">TTXMLParser</a></li>
<li><a class="el" href="interface_u_i_addition_tests.php">UIAdditionTests</a></li>
<li><a class="el" href="class_u_i_color.php">UIColor</a></li>
<li><a class="el" href="interface_u_i_common_tests.php">UICommonTests</a></li>
<li><a class="el" href="class_u_i_event.php">UIEvent</a></li>
<li><a class="el" href="class_u_i_font.php">UIFont</a></li>
<li><a class="el" href="interface_u_i_global_tests.php">UIGlobalTests</a></li>
<li><a class="el" href="class_u_i_image.php">UIImage</a></li>
<li><a class="el" href="class_u_i_navigation_controller.php">UINavigationController</a><ul>
<li><a class="el" href="interface_t_t_base_navigation_controller.php">TTBaseNavigationController</a><ul>
<li><a class="el" href="interface_t_t_navigation_controller.php">TTNavigationController</a></li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="class_u_i_split_view_controller.php">UISplitViewController</a><ul>
<li><a class="el" href="interface_t_t_split_view_controller.php">TTSplitViewController</a></li>
</ul>
</li>
<li><a class="el" href="class_u_i_tab_bar_controller.php">UITabBarController</a></li>
<li><a class="el" href="class_u_i_table_view.php">UITableView</a><ul>
<li><a class="el" href="interface_t_t_table_view.php">TTTableView</a></li>
</ul>
</li>
<li><a class="el" href="class_u_i_toolbar.php">UIToolbar</a></li>
<li><a class="el" href="class_u_i_touch.php">UITouch</a></li>
<li><a class="el" href="class_u_i_view.php">UIView</a><ul>
<li><a class="el" href="interface_t_t_activity_label.php">TTActivityLabel</a></li>
<li><a class="el" href="interface_t_t_error_view.php">TTErrorView</a></li>
<li><a class="el" href="interface_t_t_launcher_highlight_view.php">TTLauncherHighlightView</a></li>
<li><a class="el" href="interface_t_t_launcher_view.php">TTLauncherView</a></li>
<li><a class="el" href="interface_t_t_scroll_view.php">TTScrollView</a></li>
<li><a class="el" href="interface_t_t_searchlight_label.php">TTSearchlightLabel</a></li>
<li><a class="el" href="interface_t_t_table_footer_infinite_scroll_view.php">TTTableFooterInfiniteScrollView</a></li>
<li><a class="el" href="interface_t_t_table_header_drag_refresh_view.php">TTTableHeaderDragRefreshView</a></li>
<li><a class="el" href="interface_t_t_unclipped_view.php">TTUnclippedView</a></li>
<li><a class="el" href="interface_t_t_view.php">TTView</a></li>
</ul>
</li>
<li><a class="el" href="class_u_i_view_controller.php">UIViewController</a><ul>
<li><a class="el" href="interface_t_t_base_view_controller.php">TTBaseViewController</a><ul>
<li><a class="el" href="interface_t_t_navigator_view_controller.php">TTNavigatorViewController</a><ul>
<li><a class="el" href="interface_t_t_view_controller.php">TTViewController</a><ul>
<li><a class="el" href="interface_t_t_message_controller.php">TTMessageController</a></li>
<li><a class="el" href="interface_t_t_model_view_controller.php">TTModelViewController</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li><a class="el" href="interface_u_i_view_controller_addition_tests.php">UIViewControllerAdditionTests</a></li>
<li><a class="el" href="class_u_i_web_view.php">UIWebView</a><ul>
<li><a class="el" href="interface_t_t_you_tube_view.php">TTYouTubeView</a></li>
</ul>
</li>
<li><a class="el" href="class_u_i_window.php">UIWindow</a><ul>
<li><a class="el" href="interface_t_t_navigator_window.php">TTNavigatorWindow</a></li>
</ul>
</li>
<li><a class="el" href="structyajl__alloc__funcs.php">yajl_alloc_funcs</a></li>
<li><a class="el" href="structyajl__bytestack__t.php">yajl_bytestack_t</a></li>
<li><a class="el" href="structyajl__callbacks.php">yajl_callbacks</a></li>
<li><a class="el" href="structyajl__gen__config.php">yajl_gen_config</a></li>
<li><a class="el" href="structyajl__handle__t.php">yajl_handle_t</a></li>
<li><a class="el" href="structyajl__parser__config.php">yajl_parser_config</a></li>
<li><a class="el" href="protocol_y_a_j_l_coding-p.php">&lt;YAJLCoding&gt;</a></li>
<li><a class="el" href="protocol_y_a_j_l_document_delegate-p.php">&lt;YAJLDocumentDelegate&gt;</a></li>
<li><a class="el" href="protocol_y_a_j_l_parser_delegate-p.php">&lt;YAJLParserDelegate&gt;</a><ul>
<li><a class="el" href="interface_y_a_j_l_document.php">YAJLDocument</a></li>
</ul>
</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
