<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTThumbsViewController Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
  <li><a href="http://forums.three20.info/">Forums</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTThumbsViewController Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTThumbsViewController" --><!-- doxytag: inherits="TTTableViewController,TTThumbsTableViewCellDelegate-p" --><div class="dynheader">
Inheritance diagram for TTThumbsViewController:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_thumbs_view_controller.png" usemap="#TTThumbsViewController_map" alt=""/>
  <map id="TTThumbsViewController_map" name="TTThumbsViewController_map">
<area href="interface_t_t_table_view_controller.php" alt="TTTableViewController" shape="rect" coords="112,280,326,304"/>
<area href="protocol_t_t_thumbs_table_view_cell_delegate-p.php" alt="&lt;TTThumbsTableViewCellDelegate&gt;" shape="rect" coords="336,280,550,304"/>
<area href="interface_t_t_model_view_controller.php" alt="TTModelViewController" shape="rect" coords="112,224,326,248"/>
<area href="interface_t_t_view_controller.php" alt="TTViewController" shape="rect" coords="0,168,214,192"/>
<area href="protocol_t_t_model_delegate-p.php" alt="&lt;TTModelDelegate&gt;" shape="rect" coords="224,168,438,192"/>
<area href="interface_t_t_navigator_view_controller.php" alt="TTNavigatorViewController" shape="rect" coords="0,112,214,136"/>
<area href="interface_t_t_base_view_controller.php" alt="TTBaseViewController" shape="rect" coords="0,56,214,80"/>
<area href="class_u_i_view_controller.php" alt="UIViewController" shape="rect" coords="0,0,214,24"/>
</map>
</div>

<p><a href="class_t_t_thumbs_view_controller-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aac2ba82ead99533c6658ff29562dcf81"></a><!-- doxytag: member="TTThumbsViewController::initWithDelegate:" ref="aac2ba82ead99533c6658ff29562dcf81" args="(id&lt; TTThumbsViewControllerDelegate &gt; delegate)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithDelegate:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a343b929298501890be0c0d0a3d5f93d0"></a><!-- doxytag: member="TTThumbsViewController::initWithQuery:" ref="a343b929298501890be0c0d0a3d5f93d0" args="(NSDictionary *query)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithQuery:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ada8c223e0d98a6e95d35931dc7dfd396"></a><!-- doxytag: member="TTThumbsViewController::createPhotoViewController" ref="ada8c223e0d98a6e95d35931dc7dfd396" args="()" -->
(<a class="el" href="interface_t_t_photo_view_controller.php">TTPhotoViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>createPhotoViewController</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ace2e06b5919198316b9eaa2034520423"></a><!-- doxytag: member="TTThumbsViewController::createDataSource" ref="ace2e06b5919198316b9eaa2034520423" args="()" -->
(id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>createDataSource</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae0238c94b36957bb5fb6c7578e9dea7d"></a><!-- doxytag: member="TTThumbsViewController::_photoSource" ref="ae0238c94b36957bb5fb6c7578e9dea7d" args="" -->
id&lt; <a class="el" href="protocol_t_t_photo_source-p.php">TTPhotoSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_photoSource</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a258372e007ade53fcdcc7cdfb9bfa316"></a><!-- doxytag: member="TTThumbsViewController::_delegate" ref="a258372e007ade53fcdcc7cdfb9bfa316" args="" -->
id<br class="typebreak"/>
&lt; <a class="el" href="protocol_t_t_thumbs_view_controller_delegate-p.php">TTThumbsViewControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af8d81c0a7d5bdf443fb1534ff53327bf"></a><!-- doxytag: member="TTThumbsViewController::photoSource" ref="af8d81c0a7d5bdf443fb1534ff53327bf" args="" -->
id&lt; <a class="el" href="protocol_t_t_photo_source-p.php">TTPhotoSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>photoSource</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a309739989aac6b720ff1afc7336ca42d"></a><!-- doxytag: member="TTThumbsViewController::delegate" ref="a309739989aac6b720ff1afc7336ca42d" args="" -->
id<br class="typebreak"/>
&lt; <a class="el" href="protocol_t_t_thumbs_view_controller_delegate-p.php">TTThumbsViewControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_thumbs_view_controller_8h_source.php">TTThumbsViewController.h</a></li>
<li>Three20UI/Sources/TTThumbsViewController.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
