<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTLinearGradientBorderStyle Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
  <li><a href="http://forums.three20.info/">Forums</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTLinearGradientBorderStyle Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTLinearGradientBorderStyle" --><!-- doxytag: inherits="TTStyle" --><div class="dynheader">
Inheritance diagram for TTLinearGradientBorderStyle:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_linear_gradient_border_style.png" usemap="#TTLinearGradientBorderStyle_map" alt=""/>
  <map id="TTLinearGradientBorderStyle_map" name="TTLinearGradientBorderStyle_map">
<area href="interface_t_t_style.php" alt="TTStyle" shape="rect" coords="0,56,177,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,177,24"/>
</map>
</div>

<p><a href="class_t_t_linear_gradient_border_style-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab7adbd5a608e1075886e01aa73649582"></a><!-- doxytag: member="TTLinearGradientBorderStyle::styleWithColor1:color2:width:next:" ref="ab7adbd5a608e1075886e01aa73649582" args="(UIColor *color1,[color2] UIColor *color2,[width] CGFloat width,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_linear_gradient_border_style.php">TTLinearGradientBorderStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithColor1:color2:width:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aae7fa2b222bc5709df752fa8d5f519c6"></a><!-- doxytag: member="TTLinearGradientBorderStyle::styleWithColor1:location1:color2:location2:width:next:" ref="aae7fa2b222bc5709df752fa8d5f519c6" args="(UIColor *color1,[location1] CGFloat location1,[color2] UIColor *color2,[location2] CGFloat location2,[width] CGFloat width,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_linear_gradient_border_style.php">TTLinearGradientBorderStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithColor1:location1:color2:location2:width:next:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4a52988334db36da76b16b344b2b9a79"></a><!-- doxytag: member="TTLinearGradientBorderStyle::_color1" ref="a4a52988334db36da76b16b344b2b9a79" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_color1</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a031e0509ece8814cae63ea5fa1adde72"></a><!-- doxytag: member="TTLinearGradientBorderStyle::_color2" ref="a031e0509ece8814cae63ea5fa1adde72" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_color2</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a53d6b9e88822018ecb9bf8afbafd6a14"></a><!-- doxytag: member="TTLinearGradientBorderStyle::_location1" ref="a53d6b9e88822018ecb9bf8afbafd6a14" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_location1</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca4786c6bc5adccae911f551811bd39a"></a><!-- doxytag: member="TTLinearGradientBorderStyle::_location2" ref="aca4786c6bc5adccae911f551811bd39a" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_location2</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a829d8c2d8b423a417ae07c83e995622a"></a><!-- doxytag: member="TTLinearGradientBorderStyle::_width" ref="a829d8c2d8b423a417ae07c83e995622a" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_width</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6a8523ff622d29870c02bd8c002ba077"></a><!-- doxytag: member="TTLinearGradientBorderStyle::color1" ref="a6a8523ff622d29870c02bd8c002ba077" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>color1</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a75b1bc1ae8db3d7629078fe4f140c511"></a><!-- doxytag: member="TTLinearGradientBorderStyle::color2" ref="a75b1bc1ae8db3d7629078fe4f140c511" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>color2</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abf1c33a6c9254127738632b371d3dcaa"></a><!-- doxytag: member="TTLinearGradientBorderStyle::location1" ref="abf1c33a6c9254127738632b371d3dcaa" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>location1</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5d79dcdaee4e8dcc2175840ee36f9740"></a><!-- doxytag: member="TTLinearGradientBorderStyle::location2" ref="a5d79dcdaee4e8dcc2175840ee36f9740" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>location2</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac5ed9ace4bd0c8b70934a85e089f069c"></a><!-- doxytag: member="TTLinearGradientBorderStyle::width" ref="ac5ed9ace4bd0c8b70934a85e089f069c" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>width</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_linear_gradient_border_style_8h_source.php">TTLinearGradientBorderStyle.h</a></li>
<li>Three20Style/Sources/TTLinearGradientBorderStyle.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
