<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTURLRequestModel Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTURLRequestModel Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTURLRequestModel" --><!-- doxytag: inherits="TTModel,TTURLRequestDelegate-p" -->
<p>An implementation of <a class="el" href="interface_t_t_model.php" title="A default implementation of TTModel does nothing other than appear to be loaded.">TTModel</a> which is built to work with TTURLRequests.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_u_r_l_request_model_8h_source.php">TTURLRequestModel.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTURLRequestModel:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_u_r_l_request_model.png" usemap="#TTURLRequestModel_map" alt=""/>
  <map id="TTURLRequestModel_map" name="TTURLRequestModel_map">
<area href="interface_t_t_model.php" alt="TTModel" shape="rect" coords="83,56,240,80"/>
<area href="protocol_t_t_u_r_l_request_delegate-p.php" alt="&lt;TTURLRequestDelegate&gt;" shape="rect" coords="250,56,407,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,157,24"/>
<area href="protocol_t_t_model-p.php" alt="&lt;TTModel&gt;" shape="rect" coords="167,0,324,24"/>
</map>
</div>

<p><a href="class_t_t_u_r_l_request_model-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a29ebf5997eb74ac247bc416e5e90d14a"></a><!-- doxytag: member="TTURLRequestModel::reset" ref="a29ebf5997eb74ac247bc416e5e90d14a" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_request_model.php#a29ebf5997eb74ac247bc416e5e90d14a">reset</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Resets the model to its original state before any data was loaded. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(float)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_request_model.php#a5b03ff5e9cfaff1cadc7a7cf48356d61">downloadProgress</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Valid while loading.  <a href="#a5b03ff5e9cfaff1cadc7a7cf48356d61"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a72353bc2e79d5e0275a4cb5dbfee9142"></a><!-- doxytag: member="TTURLRequestModel::_loadingRequest" ref="a72353bc2e79d5e0275a4cb5dbfee9142" args="" -->
<a class="el" href="interface_t_t_u_r_l_request.php">TTURLRequest</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_loadingRequest</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa060ac3d200e5fa2022319365a97e0af"></a><!-- doxytag: member="TTURLRequestModel::_loadedTime" ref="aa060ac3d200e5fa2022319365a97e0af" args="" -->
<a class="el" href="class_n_s_date.php">NSDate</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_loadedTime</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a552e08485abea083ec427d10b46f5dcb"></a><!-- doxytag: member="TTURLRequestModel::_cacheKey" ref="a552e08485abea083ec427d10b46f5dcb" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cacheKey</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acd76b2fffb83a28b1049b55342c26845"></a><!-- doxytag: member="TTURLRequestModel::_isLoadingMore" ref="acd76b2fffb83a28b1049b55342c26845" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_isLoadingMore</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a037ea0103171f09be9791d8aa9120ad4"></a><!-- doxytag: member="TTURLRequestModel::_hasNoMore" ref="a037ea0103171f09be9791d8aa9120ad4" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_hasNoMore</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_date.php">NSDate</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_request_model.php#ace587f260d01aaf0e3e9f885e578689a">loadedTime</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Valid upon completion of the URL request.  <a href="#ace587f260d01aaf0e3e9f885e578689a"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_request_model.php#a2127dc12c0ef3b45dd099f37f6337d2b">cacheKey</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Valid upon completion of the URL request.  <a href="#a2127dc12c0ef3b45dd099f37f6337d2b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a408188443e720d09d66bd526d9a669b1"></a><!-- doxytag: member="TTURLRequestModel::hasNoMore" ref="a408188443e720d09d66bd526d9a669b1" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_request_model.php#a408188443e720d09d66bd526d9a669b1">hasNoMore</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Not used internally, but intended for book-keeping purposes when making requests. <br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>An implementation of <a class="el" href="interface_t_t_model.php" title="A default implementation of TTModel does nothing other than appear to be loaded.">TTModel</a> which is built to work with TTURLRequests. </p>
<p>If you use a <a class="el" href="interface_t_t_u_r_l_request_model.php" title="An implementation of TTModel which is built to work with TTURLRequests.">TTURLRequestModel</a> as the delegate of your TTURLRequests, it will automatically manage many of the <a class="el" href="interface_t_t_model.php" title="A default implementation of TTModel does nothing other than appear to be loaded.">TTModel</a> properties based on the state of your requests. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a5b03ff5e9cfaff1cadc7a7cf48356d61"></a><!-- doxytag: member="TTURLRequestModel::downloadProgress" ref="a5b03ff5e9cfaff1cadc7a7cf48356d61" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (float) downloadProgress </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Valid while loading. </p>
<p>Returns download progress as between 0 and 1. </p>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="a2127dc12c0ef3b45dd099f37f6337d2b"></a><!-- doxytag: member="TTURLRequestModel::cacheKey" ref="a2127dc12c0ef3b45dd099f37f6337d2b" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a>*) cacheKey<code> [read, write, copy]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Valid upon completion of the URL request. </p>
<p>Represents the request's cache key. </p>

</div>
</div>
<a class="anchor" id="ace587f260d01aaf0e3e9f885e578689a"></a><!-- doxytag: member="TTURLRequestModel::loadedTime" ref="ace587f260d01aaf0e3e9f885e578689a" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_date.php">NSDate</a>*) loadedTime<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Valid upon completion of the URL request. </p>
<p>Represents the timestamp of the completed request. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Network/Headers/<a class="el" href="_t_t_u_r_l_request_model_8h_source.php">TTURLRequestModel.h</a></li>
<li>Three20Network/Sources/TTURLRequestModel.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
