<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTLauncherView Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://dev.three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fdev.three20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTLauncherView Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTLauncherView" --><!-- doxytag: inherits="UIView" --><div class="dynheader">
Inheritance diagram for TTLauncherView:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_launcher_view.png" usemap="#TTLauncherView_map" alt=""/>
  <map id="TTLauncherView_map" name="TTLauncherView_map">
<area href="class_u_i_view.php" alt="UIView" shape="rect" coords="0,0,108,24"/>
</map>
</div>

<p><a href="class_t_t_launcher_view-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a589161f8ac241280efea72ebd1b67606"></a><!-- doxytag: member="TTLauncherView::addItem:animated:" ref="a589161f8ac241280efea72ebd1b67606" args="(TTLauncherItem *item,[animated] BOOL animated)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addItem:animated:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a55d5550ea4787449ed025e4cfb79c9b7"></a><!-- doxytag: member="TTLauncherView::removeItem:animated:" ref="a55d5550ea4787449ed025e4cfb79c9b7" args="(TTLauncherItem *item,[animated] BOOL animated)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeItem:animated:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a54be686aa4192a1d7666c123707acb58"></a><!-- doxytag: member="TTLauncherView::itemWithURL:" ref="a54be686aa4192a1d7666c123707acb58" args="(NSString *URL)" -->
(<a class="el" href="interface_t_t_launcher_item.php">TTLauncherItem</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>itemWithURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afc025e15c763a9360e2e524cd1bd7b90"></a><!-- doxytag: member="TTLauncherView::indexPathOfItem:" ref="afc025e15c763a9360e2e524cd1bd7b90" args="(TTLauncherItem *item)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>indexPathOfItem:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab2a1eb6e8492258de5d76f053415b838"></a><!-- doxytag: member="TTLauncherView::scrollToItem:animated:" ref="ab2a1eb6e8492258de5d76f053415b838" args="(TTLauncherItem *item,[animated] BOOL animated)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollToItem:animated:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a778b23957cc040745539bbf14716896e"></a><!-- doxytag: member="TTLauncherView::beginEditing" ref="a778b23957cc040745539bbf14716896e" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>beginEditing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a31b66521b8449aaf7d627dc70c01945f"></a><!-- doxytag: member="TTLauncherView::endEditing" ref="a31b66521b8449aaf7d627dc70c01945f" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>endEditing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_launcher_view.php#a94fd37f6f6ee925010dcddcd23df1f32">beginHighlightItem:withText:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Dims the launcher view except for a transparent circle around the given item.  <a href="#a94fd37f6f6ee925010dcddcd23df1f32"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_launcher_view.php#ab28f4928ecc921a0f94745037a6d863d">endHighlightItem:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Removes the highlighting overlay introduced by -beginHighlightItem:withText:.  <a href="#ab28f4928ecc921a0f94745037a6d863d"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a04e4c0a2bf1b44694aee8b704a48328f"></a><!-- doxytag: member="TTLauncherView::_pages" ref="a04e4c0a2bf1b44694aee8b704a48328f" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_pages</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac6b878a6a0c8fc268ab2973fdceaa5b3"></a><!-- doxytag: member="TTLauncherView::_columnCount" ref="ac6b878a6a0c8fc268ab2973fdceaa5b3" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_columnCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac0ab6dd4af114188b3b970ff1133ca13"></a><!-- doxytag: member="TTLauncherView::_rowCount" ref="ac0ab6dd4af114188b3b970ff1133ca13" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rowCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ade73ddc437fcc8499502acb9fae4a98e"></a><!-- doxytag: member="TTLauncherView::_prompt" ref="ade73ddc437fcc8499502acb9fae4a98e" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_prompt</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a54f240b6842f6372811cbd34cffac7e1"></a><!-- doxytag: member="TTLauncherView::_buttons" ref="a54f240b6842f6372811cbd34cffac7e1" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_buttons</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8078a233eb2fbc85c62165bcd7f44643"></a><!-- doxytag: member="TTLauncherView::_scrollView" ref="a8078a233eb2fbc85c62165bcd7f44643" args="" -->
UIScrollView *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_scrollView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a26df773b21c28a3071a2a9ec82fa5b6b"></a><!-- doxytag: member="TTLauncherView::_pager" ref="a26df773b21c28a3071a2a9ec82fa5b6b" args="" -->
<a class="el" href="interface_t_t_page_control.php">TTPageControl</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_pager</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a09f5e2e575438be7348e7c5d8d47818a"></a><!-- doxytag: member="TTLauncherView::_editHoldTimer" ref="a09f5e2e575438be7348e7c5d8d47818a" args="" -->
NSTimer *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_editHoldTimer</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af636df380d3f126222df2f9446aa0bf0"></a><!-- doxytag: member="TTLauncherView::_springLoadTimer" ref="af636df380d3f126222df2f9446aa0bf0" args="" -->
NSTimer *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_springLoadTimer</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24db0a962ee8f2b7b709e829b2bc84c1"></a><!-- doxytag: member="TTLauncherView::_dragButton" ref="a24db0a962ee8f2b7b709e829b2bc84c1" args="" -->
<a class="el" href="interface_t_t_launcher_button.php">TTLauncherButton</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_dragButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9b9d241e8d1d46b2b6fdfb2701e57652"></a><!-- doxytag: member="TTLauncherView::_dragTouch" ref="a9b9d241e8d1d46b2b6fdfb2701e57652" args="" -->
<a class="el" href="class_u_i_touch.php">UITouch</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_dragTouch</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9268d9dd1c898b938f98236aa283fea9"></a><!-- doxytag: member="TTLauncherView::_positionOrigin" ref="a9268d9dd1c898b938f98236aa283fea9" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_positionOrigin</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afd7737dce592544e6d13442a0e1dcbfb"></a><!-- doxytag: member="TTLauncherView::_dragOrigin" ref="afd7737dce592544e6d13442a0e1dcbfb" args="" -->
CGPoint&nbsp;</td><td class="memItemRight" valign="bottom"><b>_dragOrigin</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a682e9b202bcee98ca91d88ef80140786"></a><!-- doxytag: member="TTLauncherView::_touchOrigin" ref="a682e9b202bcee98ca91d88ef80140786" args="" -->
CGPoint&nbsp;</td><td class="memItemRight" valign="bottom"><b>_touchOrigin</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae63e152c0294c6faf704e5ca35fa3262"></a><!-- doxytag: member="TTLauncherView::_highlightView" ref="ae63e152c0294c6faf704e5ca35fa3262" args="" -->
<a class="el" href="interface_t_t_launcher_highlight_view.php">TTLauncherHighlightView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_highlightView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a14672f46dc838db8e5247ed6895f8425"></a><!-- doxytag: member="TTLauncherView::_editing" ref="a14672f46dc838db8e5247ed6895f8425" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_editing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9433e3e694b933545ddc81e2e52bd0ab"></a><!-- doxytag: member="TTLauncherView::_springing" ref="a9433e3e694b933545ddc81e2e52bd0ab" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_springing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa9f0f022fd55c6a648bba485960fa91c"></a><!-- doxytag: member="TTLauncherView::_delegate" ref="aa9f0f022fd55c6a648bba485960fa91c" args="" -->
id&lt; <a class="el" href="protocol_t_t_launcher_view_delegate-p.php">TTLauncherViewDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1484a31e79c939df2061f91a4a0d1c0"></a><!-- doxytag: member="TTLauncherView::delegate" ref="ac1484a31e79c939df2061f91a4a0d1c0" args="" -->
id&lt; <a class="el" href="protocol_t_t_launcher_view_delegate-p.php">TTLauncherViewDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad272b501c7666d314f00fd958834afe4"></a><!-- doxytag: member="TTLauncherView::pages" ref="ad272b501c7666d314f00fd958834afe4" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>pages</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aff4916500fa5de98835b074811ec0fed"></a><!-- doxytag: member="TTLauncherView::columnCount" ref="aff4916500fa5de98835b074811ec0fed" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>columnCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1ea78d42cf91fb82a5857a76becf5a7"></a><!-- doxytag: member="TTLauncherView::rowCount" ref="ac1ea78d42cf91fb82a5857a76becf5a7" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>rowCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a4a24548afbd94c683f31e947262da6"></a><!-- doxytag: member="TTLauncherView::pager" ref="a7a4a24548afbd94c683f31e947262da6" args="" -->
<a class="el" href="interface_t_t_page_control.php">TTPageControl</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>pager</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9e47f07f4bb53c04c747169331974504"></a><!-- doxytag: member="TTLauncherView::currentPageIndex" ref="a9e47f07f4bb53c04c747169331974504" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>currentPageIndex</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aab8b6642cf42f86c5d70061eb3cd7f97"></a><!-- doxytag: member="TTLauncherView::prompt" ref="aab8b6642cf42f86c5d70061eb3cd7f97" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>prompt</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61693fbd072397450d91f1ed518918e7"></a><!-- doxytag: member="TTLauncherView::editing" ref="a61693fbd072397450d91f1ed518918e7" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>editing</b></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a94fd37f6f6ee925010dcddcd23df1f32"></a><!-- doxytag: member="TTLauncherView::beginHighlightItem:withText:" ref="a94fd37f6f6ee925010dcddcd23df1f32" args="(TTLauncherItem *item,[withText] NSString *text)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) beginHighlightItem: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_t_t_launcher_item.php">TTLauncherItem</a>*)&nbsp;</td>
          <td class="paramname"> <em>item</em></td>
        </tr>
        <tr>
          <td class="paramkey">withText:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>text</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Dims the launcher view except for a transparent circle around the given item. </p>
<p>The given text will also be shown center-aligned below or above the circle, as appropriate. The item can be tapped while the overlay is up; tapping anywhere else on the overlay simply dismisses the overlay and does not pass the event through. </p>

</div>
</div>
<a class="anchor" id="ab28f4928ecc921a0f94745037a6d863d"></a><!-- doxytag: member="TTLauncherView::endHighlightItem:" ref="ab28f4928ecc921a0f94745037a6d863d" args="(TTLauncherItem *item)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) endHighlightItem: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_t_t_launcher_item.php">TTLauncherItem</a>*)&nbsp;</td>
          <td class="paramname"> <em>item</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Removes the highlighting overlay introduced by -beginHighlightItem:withText:. </p>
<p>This will be done automatically if the user taps anywhere on the overlay except the transparent circle. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_launcher_view_8h_source.php">TTLauncherView.h</a></li>
<li>Three20UI/Sources/TTLauncherView.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
