<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTMessageController Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTMessageController Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTMessageController" --><!-- doxytag: inherits="TTViewController,TTTextEditorDelegate-p" -->
<p>A view controller for composing email like messages, which is visually similar to Apple's in-app mail composer.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_message_controller_8h_source.php">TTMessageController.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTMessageController:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_message_controller.png" usemap="#TTMessageController_map" alt=""/>
  <map id="TTMessageController_map" name="TTMessageController_map">
<area href="interface_t_t_view_controller.php" alt="TTViewController" shape="rect" coords="0,168,165,192"/>
<area href="protocol_t_t_text_editor_delegate-p.php" alt="&lt;TTTextEditorDelegate&gt;" shape="rect" coords="175,168,340,192"/>
<area href="interface_t_t_navigator_view_controller.php" alt="TTNavigatorViewController" shape="rect" coords="0,112,165,136"/>
<area href="interface_t_t_base_view_controller.php" alt="TTBaseViewController" shape="rect" coords="0,56,165,80"/>
<area href="class_u_i_view_controller.php" alt="UIViewController" shape="rect" coords="0,0,165,24"/>
</map>
</div>

<p><a href="class_t_t_message_controller-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a47cf65af782ef1f172bf3187295bbb01">initWithRecipients:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Initializes the class with an array of recipients.  <a href="#a47cf65af782ef1f172bf3187295bbb01"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#af1a2fb598f715126dae56b41d57cdd4a">addRecipient:forFieldAtIndex:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Adds the supplied recipient to the field at the index provided.  <a href="#af1a2fb598f715126dae56b41d57cdd4a"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#ab7d2ca53fae85cc98f75b509879c2754">textForFieldAtIndex:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns the text value of the field at the supplied index.  <a href="#ab7d2ca53fae85cc98f75b509879c2754"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#af2842bad2f6cc983845fd06b6aaaaa0d">setText:forFieldAtIndex:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sets the text value for the field at fieldIndex.  <a href="#af2842bad2f6cc983845fd06b6aaaaa0d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a84cf08a943476bf4df1f15f93a972f49">fieldHasValueAtIndex:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns true if the field at the supplied index is not empty or has only whitespace.  <a href="#a84cf08a943476bf4df1f15f93a972f49"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view.php">UIView</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a9d61201cf2b42c9f21c3f4474c0a4083">viewForFieldAtIndex:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns the <a class="el" href="class_u_i_view.php">UIView</a> instance representing the field at fieldIndex.  <a href="#a9d61201cf2b42c9f21c3f4474c0a4083"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a28d5a259e0d174feec29a11400094173">showActivityView:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Causes a view used to indicate message activity to be shown or dismissed depending on the value of show.  <a href="#a28d5a259e0d174feec29a11400094173"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a48fd3ef54fda0dfaeac75317b71e6d84">titleForSending</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Returns the title for the activity view that is shown by showActivityView.  <a href="#a48fd3ef54fda0dfaeac75317b71e6d84"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2dccad9fc77b13fffe1e5f4e1e867a79"></a><!-- doxytag: member="TTMessageController::send" ref="a2dccad9fc77b13fffe1e5f4e1e867a79" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a2dccad9fc77b13fffe1e5f4e1e867a79">send</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Tells the delegate to send the message. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa164519b99a08d60155c75fe422f3489"></a><!-- doxytag: member="TTMessageController::cancel:" ref="aa164519b99a08d60155c75fe422f3489" args="(BOOL confirmIfNecessary)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#aa164519b99a08d60155c75fe422f3489">cancel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Cancel the message, but confirm first with the user if necessary. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a930b60b957c1c6b8a70f5ba2c39e4cce"></a><!-- doxytag: member="TTMessageController::confirmCancellation" ref="a930b60b957c1c6b8a70f5ba2c39e4cce" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a930b60b957c1c6b8a70f5ba2c39e4cce">confirmCancellation</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Confirms with the user that it is ok to cancel. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#ae493ee3a5016a6b30a30bb7c704aac4e">messageWillSend:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent before the delegate is informed that it should send the message.  <a href="#ae493ee3a5016a6b30a30bb7c704aac4e"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a761a9ceb7a704fbb5e6c902a3faf500c">messageWillShowRecipientPicker</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The user touched the recipient picker button.  <a href="#a761a9ceb7a704fbb5e6c902a3faf500c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#a3e9dcb9a2a11041b1694d0da3b135d71">messageDidSend</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent after the delegate has been informed that it should send the message.  <a href="#a3e9dcb9a2a11041b1694d0da3b135d71"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_message_controller.php#af47187c50e2e1b382841fa4be783c0ba">messageShouldCancel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if the message should cancel without confirming with the user.  <a href="#af47187c50e2e1b382841fa4be783c0ba"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae517ac05a60aff4c64dadfdf5e0be548"></a><!-- doxytag: member="TTMessageController::keyboardWillAppear:withBounds:" ref="ae517ac05a60aff4c64dadfdf5e0be548" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#ae517ac05a60aff4c64dadfdf5e0be548">keyboardWillAppear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller before the keyboard slides in. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3b370029749e85fe261726375ba13289"></a><!-- doxytag: member="TTMessageController::keyboardWillDisappear:withBounds:" ref="a3b370029749e85fe261726375ba13289" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#a3b370029749e85fe261726375ba13289">keyboardWillDisappear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller before the keyboard slides out. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1405d3b2f2c3d4e1db7c7e29226c2e74"></a><!-- doxytag: member="TTMessageController::keyboardDidAppear:withBounds:" ref="a1405d3b2f2c3d4e1db7c7e29226c2e74" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#a1405d3b2f2c3d4e1db7c7e29226c2e74">keyboardDidAppear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller after the keyboard has slid in. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad27dfcbbc6587b779af6231825679be0"></a><!-- doxytag: member="TTMessageController::keyboardDidDisappear:withBounds:" ref="ad27dfcbbc6587b779af6231825679be0" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#ad27dfcbbc6587b779af6231825679be0">keyboardDidDisappear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller after the keyboard has slid out. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a32e01b7570a4309f31af9dad40fbdf44"></a><!-- doxytag: member="TTMessageController::textEditorShouldBeginEditing:" ref="a32e01b7570a4309f31af9dad40fbdf44" args="(TTTextEditor *textEditor)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorShouldBeginEditing:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3cd382bdd0bc1a68404ec8ff2f45ec7b"></a><!-- doxytag: member="TTMessageController::textEditorShouldEndEditing:" ref="a3cd382bdd0bc1a68404ec8ff2f45ec7b" args="(TTTextEditor *textEditor)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorShouldEndEditing:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae9c7de44946d45463d983bfcf2a0371f"></a><!-- doxytag: member="TTMessageController::textEditorDidBeginEditing:" ref="ae9c7de44946d45463d983bfcf2a0371f" args="(TTTextEditor *textEditor)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorDidBeginEditing:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acda76c4826b4e6c2cbc0d211956aa06f"></a><!-- doxytag: member="TTMessageController::textEditorDidEndEditing:" ref="acda76c4826b4e6c2cbc0d211956aa06f" args="(TTTextEditor *textEditor)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorDidEndEditing:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4bc6752a27f4f996d7c3cdd489cc7b47"></a><!-- doxytag: member="TTMessageController::textEditor:shouldChangeTextInRange:replacementText:" ref="a4bc6752a27f4f996d7c3cdd489cc7b47" args="(TTTextEditor *textEditor,[shouldChangeTextInRange] NSRange range,[replacementText] NSString *replacementText)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditor:shouldChangeTextInRange:replacementText:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa8b7484f91b804294f2da65f754f64ef"></a><!-- doxytag: member="TTMessageController::textEditorDidChange:" ref="aa8b7484f91b804294f2da65f754f64ef" args="(TTTextEditor *textEditor)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorDidChange:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4942886317d9773499b2535330036164"></a><!-- doxytag: member="TTMessageController::textEditor:shouldResizeBy:" ref="a4942886317d9773499b2535330036164" args="(TTTextEditor *textEditor,[shouldResizeBy] CGFloat height)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditor:shouldResizeBy:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a41aa31bb51bc2b2a5189ef8492ce9ac2"></a><!-- doxytag: member="TTMessageController::textEditorShouldReturn:" ref="a41aa31bb51bc2b2a5189ef8492ce9ac2" args="(TTTextEditor *textEditor)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textEditorShouldReturn:</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_view_controller.php#a0e5fe2b34de8a02a7f3f0dccd5156958">doGarbageCollection</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Forcefully initiates garbage collection.  <a href="#a0e5fe2b34de8a02a7f3f0dccd5156958"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a65c84e8022e3fa76b01cb6dac5b5d4fc"></a><!-- doxytag: member="TTMessageController::_fields" ref="a65c84e8022e3fa76b01cb6dac5b5d4fc" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_fields</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a320f12bc5246a907ca3f1300266b0063"></a><!-- doxytag: member="TTMessageController::_fieldViews" ref="a320f12bc5246a907ca3f1300266b0063" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_fieldViews</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a163f017de11f96d7590f5f45efca822f"></a><!-- doxytag: member="TTMessageController::_scrollView" ref="a163f017de11f96d7590f5f45efca822f" args="" -->
UIScrollView *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_scrollView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a71aa42e4a30e618416c06ff784ef4a52"></a><!-- doxytag: member="TTMessageController::_textEditor" ref="a71aa42e4a30e618416c06ff784ef4a52" args="" -->
<a class="el" href="interface_t_t_text_editor.php">TTTextEditor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_textEditor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0902fec8a5668a1a81e82e1e28bf4a5c"></a><!-- doxytag: member="TTMessageController::_activityView" ref="a0902fec8a5668a1a81e82e1e28bf4a5c" args="" -->
<a class="el" href="interface_t_t_activity_label.php">TTActivityLabel</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_activityView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acda99d59fd8834730842c25c5624ddfb"></a><!-- doxytag: member="TTMessageController::_initialRecipients" ref="acda99d59fd8834730842c25c5624ddfb" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_initialRecipients</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a64b60a2095071b5b013478965b81f64e"></a><!-- doxytag: member="TTMessageController::_showsRecipientPicker" ref="a64b60a2095071b5b013478965b81f64e" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_showsRecipientPicker</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4b9736bf30efb27fbfe74187bfde9e42"></a><!-- doxytag: member="TTMessageController::_isModified" ref="a4b9736bf30efb27fbfe74187bfde9e42" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_isModified</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a38dde907590f2a443743fd1d91011eb2"></a><!-- doxytag: member="TTMessageController::_dataSource" ref="a38dde907590f2a443743fd1d91011eb2" args="" -->
id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_dataSource</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a47fca5147d52366682fdff075fefd5c8"></a><!-- doxytag: member="TTMessageController::_delegate" ref="a47fca5147d52366682fdff075fefd5c8" args="" -->
id&lt; <a class="el" href="protocol_t_t_message_controller_delegate-p.php">TTMessageControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a62bac03420a9ca3fe201915f64c710df"></a><!-- doxytag: member="TTMessageController::_searchController" ref="a62bac03420a9ca3fe201915f64c710df" args="" -->
<a class="el" href="interface_t_t_search_display_controller.php">TTSearchDisplayController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_searchController</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af73a75af4a8540e9a0824dfde0ff7ba9"></a><!-- doxytag: member="TTMessageController::_frozenState" ref="af73a75af4a8540e9a0824dfde0ff7ba9" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_frozenState</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a043ebeb2719175e6b4fd09ff8e6dc7eb"></a><!-- doxytag: member="TTMessageController::_navigationBarStyle" ref="a043ebeb2719175e6b4fd09ff8e6dc7eb" args="" -->
UIBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>_navigationBarStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9539b16b96e55313d37a24a517d91aa1"></a><!-- doxytag: member="TTMessageController::_navigationBarTintColor" ref="a9539b16b96e55313d37a24a517d91aa1" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_navigationBarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9ba256d9d10c48e1f20b5ec266186452"></a><!-- doxytag: member="TTMessageController::_statusBarStyle" ref="a9ba256d9d10c48e1f20b5ec266186452" args="" -->
UIStatusBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>_statusBarStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a92713568320087178a7ec813edd761fa"></a><!-- doxytag: member="TTMessageController::_isViewAppearing" ref="a92713568320087178a7ec813edd761fa" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_isViewAppearing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a78f0448e948f1157cf6ba0a2d2f21d59"></a><!-- doxytag: member="TTMessageController::_hasViewAppeared" ref="a78f0448e948f1157cf6ba0a2d2f21d59" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_hasViewAppeared</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6d7348edcd90eb5573452996da10b0c8"></a><!-- doxytag: member="TTMessageController::_autoresizesForKeyboard" ref="a6d7348edcd90eb5573452996da10b0c8" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_autoresizesForKeyboard</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed"></a><!-- doxytag: member="TTMessageController::delegate" ref="a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed" args="" -->
id&lt; <a class="el" href="protocol_t_t_message_controller_delegate-p.php">TTMessageControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a8cf1658e4a2cdbe7dc72f1c0e9e6b2ed">delegate</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The delegate that will receive messages from the <a class="el" href="protocol_t_t_message_controller_delegate-p.php" title="A protocol for the object that implements the backend logic for the TTMessageController.">TTMessageControllerDelegate</a> protocol. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a577f1d8cad6e8591a4759f11d36aad2d">dataSource</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The datasource used to autocomplete TTMessageRecipientFields.  <a href="#a577f1d8cad6e8591a4759f11d36aad2d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a81c2daf27f3f8f21cecf0a92fa45b1d3">fields</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">An array of <a class="el" href="interface_t_t_message_field.php" title="The base class for all fields used by the TTMessageController.">TTMessageField</a> instances representing the editable fields.  <a href="#a81c2daf27f3f8f21cecf0a92fa45b1d3"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a8414169377f297b9fcb41bbc9c0a058d">subject</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">A convenience property for editing the text value of the <a class="el" href="interface_t_t_message_subject_field.php" title="A field for the subject of the message.">TTMessageSubjectField</a>.  <a href="#a8414169377f297b9fcb41bbc9c0a058d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a179539948de0b4377b0559e9ef2c57e6">body</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The body of the message.  <a href="#a179539948de0b4377b0559e9ef2c57e6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81e95b4725b4c6ad3bb9a534fa045660"></a><!-- doxytag: member="TTMessageController::showsRecipientPicker" ref="a81e95b4725b4c6ad3bb9a534fa045660" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#a81e95b4725b4c6ad3bb9a534fa045660">showsRecipientPicker</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Controls whether a contact add button is shown in the views for <a class="el" href="interface_t_t_message_recipient_field.php" title="A field for holding recipients, typically found in an address book.">TTMessageRecipientField</a> instances. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_message_controller.php#aa41f369642a1ce1afcfc381972d79d68">isModified</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates if this message has been modified since it was originally shown.  <a href="#aa41f369642a1ce1afcfc381972d79d68"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="interface_t_t_table_view_controller.php">TTTableViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_view_controller.php#aee5cb350b30e5feefffd3f118df21f86">searchViewController</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">A view controller used to display the contents of the search display controller.  <a href="#aee5cb350b30e5feefffd3f118df21f86"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">UIBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a0d8ab3d6c6b655258293c2df842d161b">navigationBarStyle</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The style of the navigation bar when this view controller is pushed onto a navigation controller.  <a href="#a0d8ab3d6c6b655258293c2df842d161b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#af9f360ea82a7008a4cdb785765ca368d">navigationBarTintColor</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The color of the navigation bar when this view controller is pushed onto a navigation controller.  <a href="#af9f360ea82a7008a4cdb785765ca368d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">UIStatusBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a9fbdc64e7c1d0e33c6e5c18c637484f7">statusBarStyle</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The style of the status bar when this view controller is appearing.  <a href="#a9fbdc64e7c1d0e33c6e5c18c637484f7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aba404e0d3d915055ce87f45191c2be8d"></a><!-- doxytag: member="TTMessageController::hasViewAppeared" ref="aba404e0d3d915055ce87f45191c2be8d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#aba404e0d3d915055ce87f45191c2be8d">hasViewAppeared</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The view has appeared at least once and hasn't been removed due to a memory warning. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afeb4bf49b4efd4199f03e32dc793c87d"></a><!-- doxytag: member="TTMessageController::isViewAppearing" ref="afeb4bf49b4efd4199f03e32dc793c87d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#afeb4bf49b4efd4199f03e32dc793c87d">isViewAppearing</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The view is about to appear and has not appeared yet. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9c53a69ddcc3e4d4f8eef61d51d98c75"></a><!-- doxytag: member="TTMessageController::autoresizesForKeyboard" ref="a9c53a69ddcc3e4d4f8eef61d51d98c75" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a9c53a69ddcc3e4d4f8eef61d51d98c75">autoresizesForKeyboard</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if the view will be resized automatically to fit the keyboard. <br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>A view controller for composing email like messages, which is visually similar to Apple's in-app mail composer. </p>
<p>This class was originally implemented before iPhone OS 3.0, which introduced the MFMailComposeViewController. It's original purpose was to fill that gap in the SDK. If you want to allow users to send an email via their existing Mail.app accounts, you should use MFMailComposeViewController.</p>
<p>You may find this class useful if you need to present a visually similar view, but handle the delivery of the message yourself. This class is also useful when you want to customize the fields presented to the user. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="af1a2fb598f715126dae56b41d57cdd4a"></a><!-- doxytag: member="TTMessageController::addRecipient:forFieldAtIndex:" ref="af1a2fb598f715126dae56b41d57cdd4a" args="(id recipient,[forFieldAtIndex] NSUInteger fieldIndex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) addRecipient: </td>
          <td></td>
          <td class="paramtype">(id)&nbsp;</td>
          <td class="paramname"> <em>recipient</em></td>
        </tr>
        <tr>
          <td class="paramkey">forFieldAtIndex:</td>
          <td></td>
          <td class="paramtype">(NSUInteger)&nbsp;</td>
          <td class="paramname"> <em>fieldIndex</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Adds the supplied recipient to the field at the index provided. </p>
<p>That recipient will be rendered as a cell within that field's view. The cell's label will be determined by asking the datasource for a string label for the recipient object provided.</p>
<p>This method is a no-op if the datasource fails to provide a label for the cell, or if the fieldIndex provided does not refer to a <a class="el" href="interface_t_t_picker_text_field.php">TTPickerTextField</a>. </p>

</div>
</div>
<a class="anchor" id="a0e5fe2b34de8a02a7f3f0dccd5156958"></a><!-- doxytag: member="TTMessageController::doGarbageCollection" ref="a0e5fe2b34de8a02a7f3f0dccd5156958" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (void) doGarbageCollection </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Forcefully initiates garbage collection. </p>
<p>You may call this in your didReceiveMemoryWarning message if you are worried about garbage collection memory consumption.</p>
<p>See Articles/UI/GarbageCollection.mdown for a more detailed discussion. </p>

</div>
</div>
<a class="anchor" id="a84cf08a943476bf4df1f15f93a972f49"></a><!-- doxytag: member="TTMessageController::fieldHasValueAtIndex:" ref="a84cf08a943476bf4df1f15f93a972f49" args="(NSUInteger fieldIndex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) fieldHasValueAtIndex: </td>
          <td></td>
          <td class="paramtype">(NSUInteger)&nbsp;</td>
          <td class="paramname"> <em>fieldIndex</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns true if the field at the supplied index is not empty or has only whitespace. </p>
<p>Passing fields.count returns true if the body has any text, whitespace included. </p>

</div>
</div>
<a class="anchor" id="a47cf65af782ef1f172bf3187295bbb01"></a><!-- doxytag: member="TTMessageController::initWithRecipients:" ref="a47cf65af782ef1f172bf3187295bbb01" args="(NSArray *recipients)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) initWithRecipients: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_array.php">NSArray</a>*)&nbsp;</td>
          <td class="paramname"> <em>recipients</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Initializes the class with an array of recipients. </p>
<p>These recipients will be pre-filled in the TTMessageRecipientField's view.</p>
<p>If a non-empty recipients array is provided, <a class="el" href="interface_t_t_message_controller.php" title="A view controller for composing email like messages, which is visually similar to Apple&#39;s in-app ...">TTMessageController</a> expects the first field to be an instance of <a class="el" href="interface_t_t_message_recipient_field.php" title="A field for holding recipients, typically found in an address book.">TTMessageRecipientField</a>. You may pass nil if you do not wish to supply initial recipients. </p>

</div>
</div>
<a class="anchor" id="a3e9dcb9a2a11041b1694d0da3b135d71"></a><!-- doxytag: member="TTMessageController::messageDidSend" ref="a3e9dcb9a2a11041b1694d0da3b135d71" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) messageDidSend </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Sent after the delegate has been informed that it should send the message. </p>
<p>Subclasses can override this method to implement custom logic. </p>

</div>
</div>
<a class="anchor" id="af47187c50e2e1b382841fa4be783c0ba"></a><!-- doxytag: member="TTMessageController::messageShouldCancel" ref="af47187c50e2e1b382841fa4be783c0ba" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) messageShouldCancel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Determines if the message should cancel without confirming with the user. </p>
<p>The default implementation is to allow the user to cancel without confirmation if no required fields have been modified and they have not entered any subject or body text. </p>

</div>
</div>
<a class="anchor" id="ae493ee3a5016a6b30a30bb7c704aac4e"></a><!-- doxytag: member="TTMessageController::messageWillSend:" ref="ae493ee3a5016a6b30a30bb7c704aac4e" args="(NSArray *fields)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) messageWillSend: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_array.php">NSArray</a>*)&nbsp;</td>
          <td class="paramname"> <em>fields</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Sent before the delegate is informed that it should send the message. </p>
<p>Subclasses can override this method to implement custom logic. </p>

</div>
</div>
<a class="anchor" id="a761a9ceb7a704fbb5e6c902a3faf500c"></a><!-- doxytag: member="TTMessageController::messageWillShowRecipientPicker" ref="a761a9ceb7a704fbb5e6c902a3faf500c" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) messageWillShowRecipientPicker </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The user touched the recipient picker button. </p>
<p>Subclasses can override this method to implement custom logic. </p>

</div>
</div>
<a class="anchor" id="af2842bad2f6cc983845fd06b6aaaaa0d"></a><!-- doxytag: member="TTMessageController::setText:forFieldAtIndex:" ref="af2842bad2f6cc983845fd06b6aaaaa0d" args="(NSString *text,[forFieldAtIndex] NSUInteger fieldIndex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) setText: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>text</em></td>
        </tr>
        <tr>
          <td class="paramkey">forFieldAtIndex:</td>
          <td></td>
          <td class="paramtype">(NSUInteger)&nbsp;</td>
          <td class="paramname"> <em>fieldIndex</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Sets the text value for the field at fieldIndex. </p>
<p>Passing fields.count sets the body text. </p>

</div>
</div>
<a class="anchor" id="a28d5a259e0d174feec29a11400094173"></a><!-- doxytag: member="TTMessageController::showActivityView:" ref="a28d5a259e0d174feec29a11400094173" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showActivityView: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Causes a view used to indicate message activity to be shown or dismissed depending on the value of show. </p>
<p>This view obscures the editable field views. It is usually shown while the message is being sent. </p>

</div>
</div>
<a class="anchor" id="ab7d2ca53fae85cc98f75b509879c2754"></a><!-- doxytag: member="TTMessageController::textForFieldAtIndex:" ref="ab7d2ca53fae85cc98f75b509879c2754" args="(NSUInteger fieldIndex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) textForFieldAtIndex: </td>
          <td></td>
          <td class="paramtype">(NSUInteger)&nbsp;</td>
          <td class="paramname"> <em>fieldIndex</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns the text value of the field at the supplied index. </p>
<p>Passing fields.count returns the body contents.</p>
<p>Whitespace has been trimmed from the returned value. </p>

</div>
</div>
<a class="anchor" id="a48fd3ef54fda0dfaeac75317b71e6d84"></a><!-- doxytag: member="TTMessageController::titleForSending" ref="a48fd3ef54fda0dfaeac75317b71e6d84" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) titleForSending </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns the title for the activity view that is shown by showActivityView. </p>
<p>By default, the title is "Sending...", but subclasses may override this method to show a different title. The default title has been localized. </p>

</div>
</div>
<a class="anchor" id="a9d61201cf2b42c9f21c3f4474c0a4083"></a><!-- doxytag: member="TTMessageController::viewForFieldAtIndex:" ref="a9d61201cf2b42c9f21c3f4474c0a4083" args="(NSUInteger fieldIndex)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view.php">UIView</a> *) viewForFieldAtIndex: </td>
          <td></td>
          <td class="paramtype">(NSUInteger)&nbsp;</td>
          <td class="paramname"> <em>fieldIndex</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Returns the <a class="el" href="class_u_i_view.php">UIView</a> instance representing the field at fieldIndex. </p>
<p>Passing fields.count returns the view representing the body contents. </p>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="a179539948de0b4377b0559e9ef2c57e6"></a><!-- doxytag: member="TTMessageController::body" ref="a179539948de0b4377b0559e9ef2c57e6" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) body<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The body of the message. </p>
<p>The body is not required for the user to send a message. </p>

</div>
</div>
<a class="anchor" id="a577f1d8cad6e8591a4759f11d36aad2d"></a><!-- doxytag: member="TTMessageController::dataSource" ref="a577f1d8cad6e8591a4759f11d36aad2d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id&lt;<a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a>&gt;) dataSource<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The datasource used to autocomplete TTMessageRecipientFields. </p>
<p>This class is also responsible for determining how cells representing recipients are labeled. </p>

</div>
</div>
<a class="anchor" id="a81c2daf27f3f8f21cecf0a92fa45b1d3"></a><!-- doxytag: member="TTMessageController::fields" ref="a81c2daf27f3f8f21cecf0a92fa45b1d3" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_array.php">NSArray</a>*) fields<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>An array of <a class="el" href="interface_t_t_message_field.php" title="The base class for all fields used by the TTMessageController.">TTMessageField</a> instances representing the editable fields. </p>
<p>These fields are rendered in order using appropriate views for each field type. </p>

</div>
</div>
<a class="anchor" id="aa41f369642a1ce1afcfc381972d79d68"></a><!-- doxytag: member="TTMessageController::isModified" ref="aa41f369642a1ce1afcfc381972d79d68" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isModified<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates if this message has been modified since it was originally shown. </p>
<p>If the message has been modified, the user will be asked for confirmation before their cancel request is enacted. </p>

</div>
</div>
<a class="anchor" id="a0d8ab3d6c6b655258293c2df842d161b"></a><!-- doxytag: member="TTMessageController::navigationBarStyle" ref="a0d8ab3d6c6b655258293c2df842d161b" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (UIBarStyle) navigationBarStyle<code> [read, write, assign, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The style of the navigation bar when this view controller is pushed onto a navigation controller. </p>
<p>UIBarStyleDefault </p>

</div>
</div>
<a class="anchor" id="af9f360ea82a7008a4cdb785765ca368d"></a><!-- doxytag: member="TTMessageController::navigationBarTintColor" ref="af9f360ea82a7008a4cdb785765ca368d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_color.php">UIColor</a>*) navigationBarTintColor<code> [read, write, retain, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The color of the navigation bar when this view controller is pushed onto a navigation controller. </p>
<p>TTSTYLEVAR(navigationBarTintColor) </p>

</div>
</div>
<a class="anchor" id="aee5cb350b30e5feefffd3f118df21f86"></a><!-- doxytag: member="TTMessageController::searchViewController" ref="aee5cb350b30e5feefffd3f118df21f86" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="interface_t_t_table_view_controller.php">TTTableViewController</a> *) searchViewController<code> [read, write, retain, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>A view controller used to display the contents of the search display controller. </p>
<p>If you assign a view controller to this property, it will automatically create a search display controller which you can access through this view controller's searchDisplaController property. You can then take the searchBar from that controller and add it to your views. The search bar will then search the data source of the view controller that you assigned here. </p>

</div>
</div>
<a class="anchor" id="a9fbdc64e7c1d0e33c6e5c18c637484f7"></a><!-- doxytag: member="TTMessageController::statusBarStyle" ref="a9fbdc64e7c1d0e33c6e5c18c637484f7" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (UIStatusBarStyle) statusBarStyle<code> [read, write, assign, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The style of the status bar when this view controller is appearing. </p>
<p>UIStatusBarStyleDefault </p>

</div>
</div>
<a class="anchor" id="a8414169377f297b9fcb41bbc9c0a058d"></a><!-- doxytag: member="TTMessageController::subject" ref="a8414169377f297b9fcb41bbc9c0a058d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) subject<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>A convenience property for editing the text value of the <a class="el" href="interface_t_t_message_subject_field.php" title="A field for the subject of the message.">TTMessageSubjectField</a>. </p>
<p>If no <a class="el" href="interface_t_t_message_subject_field.php" title="A field for the subject of the message.">TTMessageSubjectField</a> is found in the fields array, nil will be returned from the getter and the setter will be a no-op. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_message_controller_8h_source.php">TTMessageController.h</a></li>
<li>Three20UI/Sources/TTMessageController.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
