<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTURLAction Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTURLAction Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTURLAction" --><!-- doxytag: inherits="NSObject" -->
<p>This object bundles up a set of parameters and ships them off to TTBasicNavigator's openURLAction method.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_u_r_l_action_8h_source.php">TTURLAction.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTURLAction:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_u_r_l_action.png" usemap="#TTURLAction_map" alt=""/>
  <map id="TTURLAction_map" name="TTURLAction_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,85,24"/>
</map>
</div>

<p><a href="class_t_t_u_r_l_action-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#a6b4e366c94a2175e67a166975d4e788a">initWithURLPath:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Initialize a <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object with a URL path.  <a href="#a6b4e366c94a2175e67a166975d4e788a"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aad8f6ce474886786cfc111c41f556cb5"></a><!-- doxytag: member="TTURLAction::applyParentURLPath:" ref="aad8f6ce474886786cfc111c41f556cb5" args="(NSString *parentURLPath)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#aad8f6ce474886786cfc111c41f556cb5">applyParentURLPath:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">nil <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acf71add67882f826a0cb135fda6a82c9"></a><!-- doxytag: member="TTURLAction::applyQuery:" ref="acf71add67882f826a0cb135fda6a82c9" args="(NSDictionary *query)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#acf71add67882f826a0cb135fda6a82c9">applyQuery:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">nil <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ade1d8e73c2ff3aa31e8086ad0e2fdc18"></a><!-- doxytag: member="TTURLAction::applyState:" ref="ade1d8e73c2ff3aa31e8086ad0e2fdc18" args="(NSDictionary *state)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#ade1d8e73c2ff3aa31e8086ad0e2fdc18">applyState:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">nil <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa7cdd76071a10d77315bdbc6f4b2407b"></a><!-- doxytag: member="TTURLAction::applyAnimated:" ref="aa7cdd76071a10d77315bdbc6f4b2407b" args="(BOOL animated)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#aa7cdd76071a10d77315bdbc6f4b2407b">applyAnimated:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">NO <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a780e109c55db1360345d05290378e199"></a><!-- doxytag: member="TTURLAction::applyWithDelay:" ref="a780e109c55db1360345d05290378e199" args="(BOOL withDelay)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#a780e109c55db1360345d05290378e199">applyWithDelay:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">NO <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac17d57fb9dafd4cf042f5bbf958664ef"></a><!-- doxytag: member="TTURLAction::applyTransition:" ref="ac17d57fb9dafd4cf042f5bbf958664ef" args="(UIViewAnimationTransition transition)" -->
(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_action.php#ac17d57fb9dafd4cf042f5bbf958664ef">applyTransition:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">UIViewAnimationTransitionNone <br/></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_u_r_l_action.php#a5f1a15f21d5a747f8dd4eafe4dbcdfdf">actionWithURLPath:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Create an autoreleased <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object with a URL path.  <a href="#a5f1a15f21d5a747f8dd4eafe4dbcdfdf"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae599096d72afde4f86f1eb4f268cda9f"></a><!-- doxytag: member="TTURLAction::_urlPath" ref="ae599096d72afde4f86f1eb4f268cda9f" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_urlPath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae78d9b089932389f004462330e66ea17"></a><!-- doxytag: member="TTURLAction::_parentURLPath" ref="ae78d9b089932389f004462330e66ea17" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_parentURLPath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa38bcbc06cedaf3ef9f12c0af70f9ef0"></a><!-- doxytag: member="TTURLAction::_query" ref="aa38bcbc06cedaf3ef9f12c0af70f9ef0" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_query</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afc04cb92f5bba0eb1e74ff7d9da545e4"></a><!-- doxytag: member="TTURLAction::_state" ref="afc04cb92f5bba0eb1e74ff7d9da545e4" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_state</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5f8343f02107a62acb5126e7487e2e1d"></a><!-- doxytag: member="TTURLAction::_animated" ref="a5f8343f02107a62acb5126e7487e2e1d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_animated</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4477015b71b5af3ec89e9ccbb238c885"></a><!-- doxytag: member="TTURLAction::_withDelay" ref="a4477015b71b5af3ec89e9ccbb238c885" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_withDelay</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0334bcef02420a92dfcad71adf639084"></a><!-- doxytag: member="TTURLAction::_transition" ref="a0334bcef02420a92dfcad71adf639084" args="" -->
UIViewAnimationTransition&nbsp;</td><td class="memItemRight" valign="bottom"><b>_transition</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a424e1dd0c6e5fa783c02f657e411421f"></a><!-- doxytag: member="TTURLAction::urlPath" ref="a424e1dd0c6e5fa783c02f657e411421f" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>urlPath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a251f2bb86b0857c3649a7f3043ff238c"></a><!-- doxytag: member="TTURLAction::parentURLPath" ref="a251f2bb86b0857c3649a7f3043ff238c" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>parentURLPath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2fa365bafe6db675d6186921b3273d4d"></a><!-- doxytag: member="TTURLAction::query" ref="a2fa365bafe6db675d6186921b3273d4d" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>query</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a60bbcaa38530efd6b2fd941f1cf6e3b2"></a><!-- doxytag: member="TTURLAction::state" ref="a60bbcaa38530efd6b2fd941f1cf6e3b2" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>state</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a09c9d60f04e8cc5b65ee6089aa34a4b2"></a><!-- doxytag: member="TTURLAction::animated" ref="a09c9d60f04e8cc5b65ee6089aa34a4b2" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>animated</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2606984acf7560f0f293eaef682404ec"></a><!-- doxytag: member="TTURLAction::withDelay" ref="a2606984acf7560f0f293eaef682404ec" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>withDelay</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad6a68c8b811dccca8a770bbc74d61f81"></a><!-- doxytag: member="TTURLAction::transition" ref="ad6a68c8b811dccca8a770bbc74d61f81" args="" -->
UIViewAnimationTransition&nbsp;</td><td class="memItemRight" valign="bottom"><b>transition</b></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>This object bundles up a set of parameters and ships them off to TTBasicNavigator's openURLAction method. </p>
<p>This object is designed with the chaining principle in mind. Once you've created a <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object, you can apply any other property to the object via the apply* methods. Each of these methods returns self, allowing you to chain them.</p>
<p>Example: [[<a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> actionWithURLPath:"tt://some/path"] applyAnimated:YES];
 Create an autoreleased URL action object with the path @"tt://some/path" that is animated.</p>
<p>For the default values, see the apply method documentation below. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a5f1a15f21d5a747f8dd4eafe4dbcdfdf"></a><!-- doxytag: member="TTURLAction::actionWithURLPath:" ref="a5f1a15f21d5a747f8dd4eafe4dbcdfdf" args="(NSString *urlPath)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (id) actionWithURLPath: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>urlPath</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Create an autoreleased <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object with a URL path. </p>
<p>The path is required. </p>

</div>
</div>
<a class="anchor" id="a6b4e366c94a2175e67a166975d4e788a"></a><!-- doxytag: member="TTURLAction::initWithURLPath:" ref="a6b4e366c94a2175e67a166975d4e788a" args="(NSString *urlPath)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) initWithURLPath: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>urlPath</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Initialize a <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object with a URL path. </p>
<p>The path is required.</p>
<p>Designated initializer. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UINavigator/Headers/<a class="el" href="_t_t_u_r_l_action_8h_source.php">TTURLAction.h</a></li>
<li>Three20UINavigator/Sources/TTURLAction.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
