<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTStyledFrame Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTStyledFrame Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTStyledFrame" --><!-- doxytag: inherits="NSObject" --><div class="dynheader">
Inheritance diagram for TTStyledFrame:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_styled_frame.png" usemap="#TTStyledFrame_map" alt=""/>
  <map id="TTStyledFrame_map" name="TTStyledFrame_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="140,0,270,24"/>
<area href="interface_t_t_styled_box_frame.php" alt="TTStyledBoxFrame" shape="rect" coords="0,112,130,136"/>
<area href="interface_t_t_styled_image_frame.php" alt="TTStyledImageFrame" shape="rect" coords="140,112,270,136"/>
<area href="interface_t_t_styled_text_frame.php" alt="TTStyledTextFrame" shape="rect" coords="280,112,410,136"/>
<area href="interface_t_t_styled_inline_frame.php" alt="TTStyledInlineFrame" shape="rect" coords="0,168,130,192"/>
</map>
</div>

<p><a href="class_t_t_styled_frame-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a93c91ef15228fa6ae4b7693f5e093979"></a><!-- doxytag: member="TTStyledFrame::font" ref="a93c91ef15228fa6ae4b7693f5e093979" args="()" -->
(<a class="el" href="class_u_i_font.php">UIFont</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abdd58f43dbce357ebf32748429e3196a"></a><!-- doxytag: member="TTStyledFrame::initWithElement:" ref="abdd58f43dbce357ebf32748429e3196a" args="(TTStyledElement *element)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithElement:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a303beb9208d9cc6368f0c6e0ff8db821"></a><!-- doxytag: member="TTStyledFrame::drawInRect:" ref="a303beb9208d9cc6368f0c6e0ff8db821" args="(CGRect rect)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_styled_frame.php#a303beb9208d9cc6368f0c6e0ff8db821">drawInRect:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Draws the frame. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6fff50b9be6a44d492ef1437dbbe43a2"></a><!-- doxytag: member="TTStyledFrame::hitTest:" ref="a6fff50b9be6a44d492ef1437dbbe43a2" args="(CGPoint point)" -->
(<a class="el" href="interface_t_t_styled_box_frame.php">TTStyledBoxFrame</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>hitTest:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad03f8db51cb723fc5e39421e6bb57aa5"></a><!-- doxytag: member="TTStyledFrame::_element" ref="ad03f8db51cb723fc5e39421e6bb57aa5" args="" -->
<a class="el" href="interface_t_t_styled_element.php">TTStyledElement</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_element</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5ae54400ddeca3d416f1fd3b9e3ddfb1"></a><!-- doxytag: member="TTStyledFrame::_nextFrame" ref="a5ae54400ddeca3d416f1fd3b9e3ddfb1" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_nextFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24cf68c1443114c196c041743b8ee39e"></a><!-- doxytag: member="TTStyledFrame::_bounds" ref="a24cf68c1443114c196c041743b8ee39e" args="" -->
CGRect&nbsp;</td><td class="memItemRight" valign="bottom"><b>_bounds</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a67cc15e5eeaca5b7ad03e29bed795168"></a><!-- doxytag: member="TTStyledFrame::element" ref="a67cc15e5eeaca5b7ad03e29bed795168" args="" -->
<a class="el" href="interface_t_t_styled_element.php">TTStyledElement</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_styled_frame.php#a67cc15e5eeaca5b7ad03e29bed795168">element</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The element that contains the frame. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac766ee3e369aade645baa3f93cec4867"></a><!-- doxytag: member="TTStyledFrame::nextFrame" ref="ac766ee3e369aade645baa3f93cec4867" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_styled_frame.php#ac766ee3e369aade645baa3f93cec4867">nextFrame</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The next in the linked list of frames. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0bd9f22c306b1983ffe3889a3057971"></a><!-- doxytag: member="TTStyledFrame::bounds" ref="ab0bd9f22c306b1983ffe3889a3057971" args="" -->
CGRect&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_styled_frame.php#ab0bd9f22c306b1983ffe3889a3057971">bounds</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The bounds of the content that is displayed by this frame. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2e4e82fffc643c459e0527325dcb6cda"></a><!-- doxytag: member="TTStyledFrame::x" ref="a2e4e82fffc643c459e0527325dcb6cda" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>x</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6dfa6d3f5a80762f9b0dda76a61ba9ac"></a><!-- doxytag: member="TTStyledFrame::y" ref="a6dfa6d3f5a80762f9b0dda76a61ba9ac" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>y</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac52f801db1357e38f7cfc785264e55ea"></a><!-- doxytag: member="TTStyledFrame::width" ref="ac52f801db1357e38f7cfc785264e55ea" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>width</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a01628cb8596f1b94b801484be6bb321c"></a><!-- doxytag: member="TTStyledFrame::height" ref="a01628cb8596f1b94b801484be6bb321c" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>height</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_styled_frame_8h_source.php">TTStyledFrame.h</a></li>
<li>Three20Style/Sources/TTStyledFrame.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
