<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTPickerTextField Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
  <li><a href="http://forums.three20.info/">Forums</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTPickerTextField Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTPickerTextField" --><!-- doxytag: inherits="TTSearchTextField" --><div class="dynheader">
Inheritance diagram for TTPickerTextField:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_picker_text_field.png" usemap="#TTPickerTextField_map" alt=""/>
  <map id="TTPickerTextField_map" name="TTPickerTextField_map">
<area href="interface_t_t_search_text_field.php" alt="TTSearchTextField" shape="rect" coords="0,0,118,24"/>
</map>
</div>

<p><a href="class_t_t_picker_text_field-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1c198577a69d1392fe0545c7b55b4dd"></a><!-- doxytag: member="TTPickerTextField::addCellWithObject:" ref="ac1c198577a69d1392fe0545c7b55b4dd" args="(id object)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addCellWithObject:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae003b86bf5019363a575272202f57fcf"></a><!-- doxytag: member="TTPickerTextField::removeCellWithObject:" ref="ae003b86bf5019363a575272202f57fcf" args="(id object)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeCellWithObject:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a420d633e3b54c044c4943003fbe3d4de"></a><!-- doxytag: member="TTPickerTextField::removeAllCells" ref="a420d633e3b54c044c4943003fbe3d4de" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeAllCells</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3ef2ad144241c86d8baad4b3dd401050"></a><!-- doxytag: member="TTPickerTextField::removeSelectedCell" ref="a3ef2ad144241c86d8baad4b3dd401050" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeSelectedCell</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a21ce641b324860579dda7cb7c028d453"></a><!-- doxytag: member="TTPickerTextField::scrollToVisibleLine:" ref="a21ce641b324860579dda7cb7c028d453" args="(BOOL animated)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollToVisibleLine:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9014255cc9357a00c3e75fce63244563"></a><!-- doxytag: member="TTPickerTextField::scrollToEditingLine:" ref="a9014255cc9357a00c3e75fce63244563" args="(BOOL animated)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollToEditingLine:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a26707a96c8b66470e59d21583bdda42c"></a><!-- doxytag: member="TTPickerTextField::_cellViews" ref="a26707a96c8b66470e59d21583bdda42c" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cellViews</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acf01f45b4b45fd1fd3b19c2c4fa602bb"></a><!-- doxytag: member="TTPickerTextField::_selectedCell" ref="acf01f45b4b45fd1fd3b19c2c4fa602bb" args="" -->
<a class="el" href="interface_t_t_picker_view_cell.php">TTPickerViewCell</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_selectedCell</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a39350088b4c7d38b45ce523547e08a0a"></a><!-- doxytag: member="TTPickerTextField::_lineCount" ref="a39350088b4c7d38b45ce523547e08a0a" args="" -->
int&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lineCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a501f433a793eaeac3021f7062752d1d2"></a><!-- doxytag: member="TTPickerTextField::_cursorOrigin" ref="a501f433a793eaeac3021f7062752d1d2" args="" -->
CGPoint&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cursorOrigin</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae15033a8ac4448b864407de20137f7a1"></a><!-- doxytag: member="TTPickerTextField::cellViews" ref="ae15033a8ac4448b864407de20137f7a1" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>cellViews</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61eab598d6164072c3681209d8a19c9e"></a><!-- doxytag: member="TTPickerTextField::cells" ref="a61eab598d6164072c3681209d8a19c9e" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>cells</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6b974bf1443fca934dc1d5869b29528e"></a><!-- doxytag: member="TTPickerTextField::selectedCell" ref="a6b974bf1443fca934dc1d5869b29528e" args="" -->
<a class="el" href="interface_t_t_picker_view_cell.php">TTPickerViewCell</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>selectedCell</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6c427ff7f820acbbaa541afc73ed6cea"></a><!-- doxytag: member="TTPickerTextField::lineCount" ref="a6c427ff7f820acbbaa541afc73ed6cea" args="" -->
int&nbsp;</td><td class="memItemRight" valign="bottom"><b>lineCount</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_picker_text_field_8h_source.php">TTPickerTextField.h</a></li>
<li>Three20UI/Sources/TTPickerTextField.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
