<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTTableViewDataSource Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTTableViewDataSource Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTTableViewDataSource" --><!-- doxytag: inherits="NSObject,TTTableViewDataSource-p" --><div class="dynheader">
Inheritance diagram for TTTableViewDataSource:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_table_view_data_source.png" usemap="#TTTableViewDataSource_map" alt=""/>
  <map id="TTTableViewDataSource_map" name="TTTableViewDataSource_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="215,56,420,80"/>
<area href="protocol_t_t_table_view_data_source-p.php" alt="&lt;TTTableViewDataSource&gt;" shape="rect" coords="430,56,635,80"/>
<area href="protocol_t_t_model-p.php" alt="&lt;TTModel&gt;" shape="rect" coords="430,0,635,24"/>
<area href="interface_t_t_list_data_source.php" alt="TTListDataSource" shape="rect" coords="0,168,205,192"/>
<area href="interface_t_t_sectioned_data_source.php" alt="TTSectionedDataSource" shape="rect" coords="215,168,420,192"/>
<area href="interface_t_t_table_view_interstitial_data_source.php" alt="TTTableViewInterstitialDataSource" shape="rect" coords="430,168,635,192"/>
<area href="interface_t_t_thumbs_data_source.php" alt="TTThumbsDataSource" shape="rect" coords="645,168,850,192"/>
</map>
</div>

<p><a href="class_t_t_table_view_data_source-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aba12e1d7bef111d6f5956b2fd6759faf"></a><!-- doxytag: member="TTTableViewDataSource::tableView:objectForRowAtIndexPath:" ref="aba12e1d7bef111d6f5956b2fd6759faf" args="(UITableView *tableView,[objectForRowAtIndexPath] NSIndexPath *indexPath)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:objectForRowAtIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac11f86bf7d0d42d5e20b0f89004a4c56"></a><!-- doxytag: member="TTTableViewDataSource::tableView:cellClassForObject:" ref="ac11f86bf7d0d42d5e20b0f89004a4c56" args="(UITableView *tableView,[cellClassForObject] id object)" -->
(Class)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:cellClassForObject:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac0ee4024f85437dedf7f256e5e00a3ee"></a><!-- doxytag: member="TTTableViewDataSource::tableView:labelForObject:" ref="ac0ee4024f85437dedf7f256e5e00a3ee" args="(UITableView *tableView,[labelForObject] id object)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:labelForObject:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa5179df0a147ee5170dfa7d5e0b6a996"></a><!-- doxytag: member="TTTableViewDataSource::tableView:indexPathForObject:" ref="aa5179df0a147ee5170dfa7d5e0b6a996" args="(UITableView *tableView,[indexPathForObject] id object)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:indexPathForObject:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af066c5f1bf3b623b0bc15d625a3dfefd"></a><!-- doxytag: member="TTTableViewDataSource::tableView:cell:willAppearAtIndexPath:" ref="af066c5f1bf3b623b0bc15d625a3dfefd" args="(UITableView *tableView,[cell] UITableViewCell *cell,[willAppearAtIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:cell:willAppearAtIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_table_view_data_source-p.php#a96aa481ecfee16bc78f32bc1ba3128d7">tableViewDidLoadModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the data source that its model loaded.  <a href="#a96aa481ecfee16bc78f32bc1ba3128d7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a432044702db503f758eb6fb93cebd032"></a><!-- doxytag: member="TTTableViewDataSource::titleForLoading:" ref="a432044702db503f758eb6fb93cebd032" args="(BOOL reloading)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>titleForLoading:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8d0d695ba46be9c20f58eb4fc3424fb9"></a><!-- doxytag: member="TTTableViewDataSource::imageForEmpty" ref="a8d0d695ba46be9c20f58eb4fc3424fb9" args="()" -->
(<a class="el" href="class_u_i_image.php">UIImage</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>imageForEmpty</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5f54b11f92cd485ac5dc4c81c26c978a"></a><!-- doxytag: member="TTTableViewDataSource::titleForEmpty" ref="a5f54b11f92cd485ac5dc4c81c26c978a" args="()" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>titleForEmpty</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a712c72db930b723c5bad64cc87b38644"></a><!-- doxytag: member="TTTableViewDataSource::subtitleForEmpty" ref="a712c72db930b723c5bad64cc87b38644" args="()" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>subtitleForEmpty</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab69cea7f2e4c174bd134b82782a523f2"></a><!-- doxytag: member="TTTableViewDataSource::imageForError:" ref="ab69cea7f2e4c174bd134b82782a523f2" args="(NSError *error)" -->
(<a class="el" href="class_u_i_image.php">UIImage</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>imageForError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae950d5e9343de3514b99f7dfcc9c8bca"></a><!-- doxytag: member="TTTableViewDataSource::titleForError:" ref="ae950d5e9343de3514b99f7dfcc9c8bca" args="(NSError *error)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>titleForError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad1326ecafd1eeb59e49ba9257b6b2ff8"></a><!-- doxytag: member="TTTableViewDataSource::subtitleForError:" ref="ad1326ecafd1eeb59e49ba9257b6b2ff8" args="(NSError *error)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>subtitleForError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a1979c7af6da8c2dc943d3e816a47bc"></a><!-- doxytag: member="TTTableViewDataSource::tableView:willUpdateObject:atIndexPath:" ref="a7a1979c7af6da8c2dc943d3e816a47bc" args="(UITableView *tableView,[willUpdateObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:willUpdateObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a981fc1cae11416c6497002ae4ef903af"></a><!-- doxytag: member="TTTableViewDataSource::tableView:willInsertObject:atIndexPath:" ref="a981fc1cae11416c6497002ae4ef903af" args="(UITableView *tableView,[willInsertObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:willInsertObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a663315fc2c2d144f773d57a16bb001c9"></a><!-- doxytag: member="TTTableViewDataSource::tableView:willRemoveObject:atIndexPath:" ref="a663315fc2c2d144f773d57a16bb001c9" args="(UITableView *tableView,[willRemoveObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>tableView:willRemoveObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a963c2771674e2dca920685e34fc20cce"></a><!-- doxytag: member="TTTableViewDataSource::search:" ref="a963c2771674e2dca920685e34fc20cce" args="(NSString *text)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>search:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a75f0ad85113d05134ed5e79b37b5827e"></a><!-- doxytag: member="TTTableViewDataSource::delegates" ref="a75f0ad85113d05134ed5e79b37b5827e" args="()" -->
(<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a75f0ad85113d05134ed5e79b37b5827e">delegates</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">An array of objects that conform to the <a class="el" href="protocol_t_t_model_delegate-p.php">TTModelDelegate</a> protocol. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a0717855b556f4efac8de7571f1d38cea">isLoaded</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the data has been loaded.  <a href="#a0717855b556f4efac8de7571f1d38cea"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a68b9d49ad095a221c82ec0d13b6038ec">isLoading</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the data is in the process of loading.  <a href="#a68b9d49ad095a221c82ec0d13b6038ec"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a41b1268d87a53c51aa8b22bbeeb29d07">isLoadingMore</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the data is in the process of loading additional data.  <a href="#a41b1268d87a53c51aa8b22bbeeb29d07"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#adbf2fa828a24a0428695f4cd708d9db6">isOutdated</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the model is of date and should be reloaded as soon as possible.  <a href="#adbf2fa828a24a0428695f4cd708d9db6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a7b6152507942206e12aa6889a0ed8b8c">load:more:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Loads the model.  <a href="#a7b6152507942206e12aa6889a0ed8b8c"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#ab1a78579b78649df0061aabd384db721">cancel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Cancels a load that is in progress.  <a href="#ab1a78579b78649df0061aabd384db721"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model-p.php#a13efe0c75b14ded343cd95bc84ed65f6">invalidate:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Invalidates data stored in the cache or optionally erases it.  <a href="#a13efe0c75b14ded343cd95bc84ed65f6"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a554b7a403f36a62957d3e7d10b89453e"></a><!-- doxytag: member="TTTableViewDataSource::lettersForSectionsWithSearch:summary:" ref="a554b7a403f36a62957d3e7d10b89453e" args="(BOOL search,[summary] BOOL summary)" -->
(<a class="el" href="class_n_s_array.php">NSArray</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>lettersForSectionsWithSearch:summary:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3a1846e4913a3193578eed27b0818d9b"></a><!-- doxytag: member="TTTableViewDataSource::_model" ref="a3a1846e4913a3193578eed27b0818d9b" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_model</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeb1d63fdb51ebb1608817e3d43a64ab6"></a><!-- doxytag: member="TTTableViewDataSource::model" ref="aeb1d63fdb51ebb1608817e3d43a64ab6" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="protocol_t_t_table_view_data_source-p.php#aeb1d63fdb51ebb1608817e3d43a64ab6">model</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Optional method to return a model object to delegate the <a class="el" href="interface_t_t_model.php" title="A default implementation of TTModel does nothing other than appear to be loaded.">TTModel</a> protocol to. <br/></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="ab1a78579b78649df0061aabd384db721"></a><!-- doxytag: member="TTTableViewDataSource::cancel" ref="ab1a78579b78649df0061aabd384db721" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) cancel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Cancels a load that is in progress. </p>
<p>Default implementation does nothing. </p>

</div>
</div>
<a class="anchor" id="a13efe0c75b14ded343cd95bc84ed65f6"></a><!-- doxytag: member="TTTableViewDataSource::invalidate:" ref="a13efe0c75b14ded343cd95bc84ed65f6" args="(BOOL erase)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) invalidate: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>erase</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Invalidates data stored in the cache or optionally erases it. </p>
<p>Default implementation does nothing. </p>

</div>
</div>
<a class="anchor" id="a0717855b556f4efac8de7571f1d38cea"></a><!-- doxytag: member="TTTableViewDataSource::isLoaded" ref="a0717855b556f4efac8de7571f1d38cea" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isLoaded </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that the data has been loaded. </p>
<p>Default implementation returns YES. </p>

</div>
</div>
<a class="anchor" id="a68b9d49ad095a221c82ec0d13b6038ec"></a><!-- doxytag: member="TTTableViewDataSource::isLoading" ref="a68b9d49ad095a221c82ec0d13b6038ec" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isLoading </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that the data is in the process of loading. </p>
<p>Default implementation returns NO. </p>

</div>
</div>
<a class="anchor" id="a41b1268d87a53c51aa8b22bbeeb29d07"></a><!-- doxytag: member="TTTableViewDataSource::isLoadingMore" ref="a41b1268d87a53c51aa8b22bbeeb29d07" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isLoadingMore </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that the data is in the process of loading additional data. </p>
<p>Default implementation returns NO. </p>

</div>
</div>
<a class="anchor" id="adbf2fa828a24a0428695f4cd708d9db6"></a><!-- doxytag: member="TTTableViewDataSource::isOutdated" ref="adbf2fa828a24a0428695f4cd708d9db6" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isOutdated </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that the model is of date and should be reloaded as soon as possible. </p>
<p>Default implementation returns NO. </p>

</div>
</div>
<a class="anchor" id="a7b6152507942206e12aa6889a0ed8b8c"></a><!-- doxytag: member="TTTableViewDataSource::load:more:" ref="a7b6152507942206e12aa6889a0ed8b8c" args="(TTURLRequestCachePolicy cachePolicy,[more] BOOL more)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) load: </td>
          <td></td>
          <td class="paramtype">(TTURLRequestCachePolicy)&nbsp;</td>
          <td class="paramname"> <em>cachePolicy</em></td>
        </tr>
        <tr>
          <td class="paramkey">more:</td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>more</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Loads the model. </p>
<p>Default implementation does nothing. </p>

</div>
</div>
<a class="anchor" id="a96aa481ecfee16bc78f32bc1ba3128d7"></a><!-- doxytag: member="TTTableViewDataSource::tableViewDidLoadModel:" ref="a96aa481ecfee16bc78f32bc1ba3128d7" args="(UITableView *tableView)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) tableViewDidLoadModel: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_u_i_table_view.php">UITableView</a> *)&nbsp;</td>
          <td class="paramname"> <em>tableView</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the data source that its model loaded. </p>
<p>That would be a good time to prepare the freshly loaded data for use in the table view. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_table_view_data_source_8h_source.php">TTTableViewDataSource.h</a></li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
