<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTURLNavigatorPattern Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<div id="header">
<div class="fixed-width">
<ul class="left-links">
  <li>&larr; <a href="http://new.three20.info/">Home</a></li>
</ul>
<ul class="right-links">
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul>
</div> <!-- .fixed-width -->
</div>

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTURLNavigatorPattern Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTURLNavigatorPattern" --><!-- doxytag: inherits="TTURLPattern" --><div class="dynheader">
Inheritance diagram for TTURLNavigatorPattern:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_u_r_l_navigator_pattern.png" usemap="#TTURLNavigatorPattern_map" alt=""/>
  <map id="TTURLNavigatorPattern_map" name="TTURLNavigatorPattern_map">
<area href="interface_t_t_u_r_l_pattern.php" alt="TTURLPattern" shape="rect" coords="0,56,144,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,144,24"/>
</map>
</div>

<p><a href="class_t_t_u_r_l_navigator_pattern-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac31a898c442564d0fbf88ffbdd31f2c6"></a><!-- doxytag: member="TTURLNavigatorPattern::initWithTarget:" ref="ac31a898c442564d0fbf88ffbdd31f2c6" args="(id target)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithTarget:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac87a2e99d4c818a42dc15203a98e5df8"></a><!-- doxytag: member="TTURLNavigatorPattern::initWithTarget:mode:" ref="ac87a2e99d4c818a42dc15203a98e5df8" args="(id target,[mode] TTNavigationMode navigationMode)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithTarget:mode:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a9677217f846057a97933ad6348b314"></a><!-- doxytag: member="TTURLNavigatorPattern::compile" ref="a7a9677217f846057a97933ad6348b314" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>compile</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a420b4f6c04c89df37f08b8699a089c87"></a><!-- doxytag: member="TTURLNavigatorPattern::matchURL:" ref="a420b4f6c04c89df37f08b8699a089c87" args="(NSURL *URL)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>matchURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aead5a028d1e0b800c891856d71d86161"></a><!-- doxytag: member="TTURLNavigatorPattern::invoke:withURL:query:" ref="aead5a028d1e0b800c891856d71d86161" args="(id target,[withURL] NSURL *URL,[query] NSDictionary *query)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>invoke:withURL:query:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae0acef58334385dfb02ae56c67acdcf0"></a><!-- doxytag: member="TTURLNavigatorPattern::createObjectFromURL:query:" ref="ae0acef58334385dfb02ae56c67acdcf0" args="(NSURL *URL,[query] NSDictionary *query)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>createObjectFromURL:query:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8c809505f7238bb4e794e015a290319b"></a><!-- doxytag: member="TTURLNavigatorPattern::setSelectorIfPossible:" ref="a8c809505f7238bb4e794e015a290319b" args="(SEL selector)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>setSelectorIfPossible:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa7f1639e3e9602cc6dea68b16539b492"></a><!-- doxytag: member="TTURLNavigatorPattern::compileURL" ref="aa7f1639e3e9602cc6dea68b16539b492" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>compileURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4c4737b51698f4044675b70877924b51"></a><!-- doxytag: member="TTURLNavigatorPattern::setSelectorWithNames:" ref="a4c4737b51698f4044675b70877924b51" args="(NSArray *names)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>setSelectorWithNames:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acf9ca4847941d234c4fb91942085745b"></a><!-- doxytag: member="TTURLNavigatorPattern::_targetClass" ref="acf9ca4847941d234c4fb91942085745b" args="" -->
Class&nbsp;</td><td class="memItemRight" valign="bottom"><b>_targetClass</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac82e3e3f39048500434870da37b02b3d"></a><!-- doxytag: member="TTURLNavigatorPattern::_targetObject" ref="ac82e3e3f39048500434870da37b02b3d" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>_targetObject</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1ddc374646c8b7b30003ee6ef1383f8e"></a><!-- doxytag: member="TTURLNavigatorPattern::_navigationMode" ref="a1ddc374646c8b7b30003ee6ef1383f8e" args="" -->
TTNavigationMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>_navigationMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a262aaa69cddea1c153051f8e6defa454"></a><!-- doxytag: member="TTURLNavigatorPattern::_parentURL" ref="a262aaa69cddea1c153051f8e6defa454" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_parentURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a62cac9f7491807424b20d065fbeb3344"></a><!-- doxytag: member="TTURLNavigatorPattern::_transition" ref="a62cac9f7491807424b20d065fbeb3344" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_transition</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1147ecef22627bca888d889f3f2868d5"></a><!-- doxytag: member="TTURLNavigatorPattern::_argumentCount" ref="a1147ecef22627bca888d889f3f2868d5" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_argumentCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2debd916354fcc41f4514c1c878a5064"></a><!-- doxytag: member="TTURLNavigatorPattern::_URL" ref="a2debd916354fcc41f4514c1c878a5064" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_URL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab88c4e37d5185935a25ce1040c9a6867"></a><!-- doxytag: member="TTURLNavigatorPattern::_scheme" ref="ab88c4e37d5185935a25ce1040c9a6867" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_scheme</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a96e77b0b462c7e0ebb4fb9bcbbd4a2bf"></a><!-- doxytag: member="TTURLNavigatorPattern::_path" ref="a96e77b0b462c7e0ebb4fb9bcbbd4a2bf" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_path</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab2316c7e669924aa12500adbe91ebf5d"></a><!-- doxytag: member="TTURLNavigatorPattern::_query" ref="ab2316c7e669924aa12500adbe91ebf5d" args="" -->
<a class="el" href="class_n_s_mutable_dictionary.php">NSMutableDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_query</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a75cd0e15dbeee75842056f1fb0766e0e"></a><!-- doxytag: member="TTURLNavigatorPattern::_fragment" ref="a75cd0e15dbeee75842056f1fb0766e0e" args="" -->
id&lt; <a class="el" href="protocol_t_t_u_r_l_pattern_text-p.php">TTURLPatternText</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_fragment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5e3378053e22887c521858250c125601"></a><!-- doxytag: member="TTURLNavigatorPattern::_specificity" ref="a5e3378053e22887c521858250c125601" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_specificity</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab61e39a652e580722083bc34033ef162"></a><!-- doxytag: member="TTURLNavigatorPattern::_selector" ref="ab61e39a652e580722083bc34033ef162" args="" -->
SEL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_selector</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aada428f0bb6085f91d4a665010f3dfaf"></a><!-- doxytag: member="TTURLNavigatorPattern::targetClass" ref="aada428f0bb6085f91d4a665010f3dfaf" args="" -->
Class&nbsp;</td><td class="memItemRight" valign="bottom"><b>targetClass</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9139d66398032de018d9c0558bd106c3"></a><!-- doxytag: member="TTURLNavigatorPattern::targetObject" ref="a9139d66398032de018d9c0558bd106c3" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>targetObject</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ace4ae6562536d27fda4be0b1abab9315"></a><!-- doxytag: member="TTURLNavigatorPattern::navigationMode" ref="ace4ae6562536d27fda4be0b1abab9315" args="" -->
TTNavigationMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>navigationMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a20b40919725627afffa0dc6c12f0e3c3"></a><!-- doxytag: member="TTURLNavigatorPattern::parentURL" ref="a20b40919725627afffa0dc6c12f0e3c3" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>parentURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac4eecf14fe2bb1df6e288a1cf52c774c"></a><!-- doxytag: member="TTURLNavigatorPattern::transition" ref="ac4eecf14fe2bb1df6e288a1cf52c774c" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>transition</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adb25c3ea3a3b081da573d45d25aba463"></a><!-- doxytag: member="TTURLNavigatorPattern::argumentCount" ref="adb25c3ea3a3b081da573d45d25aba463" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>argumentCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8356a43e5f3db88a55699232cade4764"></a><!-- doxytag: member="TTURLNavigatorPattern::isUniversal" ref="a8356a43e5f3db88a55699232cade4764" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>isUniversal</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4871005c57fb08b85a15f4ff1547247d"></a><!-- doxytag: member="TTURLNavigatorPattern::isFragment" ref="a4871005c57fb08b85a15f4ff1547247d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>isFragment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2ac75d06c2cc6bec15d4064e51fbf0e4"></a><!-- doxytag: member="TTURLNavigatorPattern::URL" ref="a2ac75d06c2cc6bec15d4064e51fbf0e4" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>URL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3b4347f0497c00ec39e07d21ef3c2075"></a><!-- doxytag: member="TTURLNavigatorPattern::scheme" ref="a3b4347f0497c00ec39e07d21ef3c2075" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>scheme</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac8faebb59d29e2ea512213edae01e054"></a><!-- doxytag: member="TTURLNavigatorPattern::specificity" ref="ac8faebb59d29e2ea512213edae01e054" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>specificity</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a52737296350c66c67bdd136623d35fd1"></a><!-- doxytag: member="TTURLNavigatorPattern::classForInvocation" ref="a52737296350c66c67bdd136623d35fd1" args="" -->
Class&nbsp;</td><td class="memItemRight" valign="bottom"><b>classForInvocation</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acc45aed4a4120330e38d6a3bb72f47fc"></a><!-- doxytag: member="TTURLNavigatorPattern::selector" ref="acc45aed4a4120330e38d6a3bb72f47fc" args="" -->
SEL&nbsp;</td><td class="memItemRight" valign="bottom"><b>selector</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UINavigator/Headers/<a class="el" href="_t_t_u_r_l_navigator_pattern_8h_source.php">TTURLNavigatorPattern.h</a></li>
<li>Three20UINavigator/Sources/TTURLNavigatorPattern.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
