<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTXMLParser Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
  <li><a href="http://forums.three20.info/">Forums</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#properties">Properties</a> &#124;
<a href="#pri-attribs">Private Attributes</a>  </div>
  <div class="headertitle">
<h1>TTXMLParser Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTXMLParser" -->
<p>An implementation of the NSXMLParser object that turns XML into NSObjects.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_x_m_l_parser_8h_source.php">TTXMLParser.h</a>&gt;</code></p>

<p><a href="class_t_t_x_m_l_parser-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">id&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_x_m_l_parser.php#aa7429a4815521a3a988f572e61054151">rootObject</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Only valid after [parser parse] has been called.  <a href="#aa7429a4815521a3a988f572e61054151"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_x_m_l_parser.php#aa2ffa5a06a6b5f25cc4301777544c128">treatDuplicateKeysAsArrayItems</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">When a duplicate key is encountered, the key's value is turned into an array and both the original item and the new duplicate item are added to the array.  <a href="#aa2ffa5a06a6b5f25cc4301777544c128"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pri-attribs"></a>
Private Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4ee35a0f2382c529b139ea74363356f4"></a><!-- doxytag: member="TTXMLParser::_rootObject" ref="a4ee35a0f2382c529b139ea74363356f4" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rootObject</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1e6dc16f00a637cfbd40b0acf2a53954"></a><!-- doxytag: member="TTXMLParser::_treatDuplicateKeysAsArrayItems" ref="a1e6dc16f00a637cfbd40b0acf2a53954" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_treatDuplicateKeysAsArrayItems</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2be9eaf9a19f0c8acc0596d1ae726e78"></a><!-- doxytag: member="TTXMLParser::_objectStack" ref="a2be9eaf9a19f0c8acc0596d1ae726e78" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_objectStack</b></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>An implementation of the NSXMLParser object that turns XML into NSObjects. </p>
<p>Uses a simple stack-based traversal of the XML document to recursively create the objects at each level. Upon successful completion, rootObject will be an <a class="el" href="class_n_s_dictionary.php">NSDictionary</a> object.</p>
<p>To traverse the resulting <a class="el" href="class_n_s_object.php" title="Additions.">NSObject</a> hierarchy, use the <a class="el" href="class_n_s_dictionary.php">NSDictionary</a> additions provided at the end of this file to access the XML entity name, type, and object. For example:</p>
<p>&lt;?xml version="1.0" encoding="UTF-8"?&gt; &lt;issues type="array"&gt; &lt;issue&gt; &lt;number type="integer"&gt;3&lt;/number&gt; &lt;/issue&gt; &lt;issue&gt; &lt;number type="integer"&gt;10&lt;/number&gt; &lt;/issue&gt; &lt;/issues&gt;</p>
<p>Logic to parse the above XML as an NSData* object:</p>
<p>TTXMLParser* parser = [[<a class="el" href="interface_t_t_x_m_l_parser.php" title="An implementation of the NSXMLParser object that turns XML into NSObjects.">TTXMLParser</a> alloc] initWithData:xmlData]; [parser parse];</p>
<p>parser.rootObject will become the following <a class="el" href="class_n_s_object.php" title="Additions.">NSObject</a>:</p>
<p>rootObject =&gt; NSDictionary* (root) &lt;key&gt; </p>
<ul>
<li>___Entity_Name___: "issues"</li>
<li>___Entity_Type___: "array"</li>
<li>___Entity_Value___: <a class="el" href="class_n_s_array.php" title="Additions.">NSArray</a> of NSDictionaries, accessed with [rootObject objectForXMLNode]</li>
</ul>
<p>[rootObject objectForXMLNode] =&gt; NSArray* of NSDictionaries Each item of the <a class="el" href="class_n_s_array.php" title="Additions.">NSArray</a> is an NSDictionary*: foreach item in array:</p>
<ul>
<li>___Entity_Name___: "issue"</li>
<li>___Entity_Type___: kCommonXMLType_Unknown</li>
<li>___Entity_Value___: NSDictionary* etc...</li>
</ul>
<p>Implementation note: This class is designed as a simple means of parsing XML documents. It has not been optimized for speed or memory usage, and has only been tested with documents less than one MB (megabyte) in size. </p>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="aa7429a4815521a3a988f572e61054151"></a><!-- doxytag: member="TTXMLParser::rootObject" ref="aa7429a4815521a3a988f572e61054151" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) rootObject<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Only valid after [parser parse] has been called. </p>
<p>Will return an NSDictionary* after successful parsing. </p>

</div>
</div>
<a class="anchor" id="aa2ffa5a06a6b5f25cc4301777544c128"></a><!-- doxytag: member="TTXMLParser::treatDuplicateKeysAsArrayItems" ref="aa2ffa5a06a6b5f25cc4301777544c128" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) treatDuplicateKeysAsArrayItems<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>When a duplicate key is encountered, the key's value is turned into an array and both the original item and the new duplicate item are added to the array. </p>
<p>Any subsequent duplicates are also added to this array. This is useful for RSS feeds, where feed items are presented inline (and not as array items).</p>
<p>NO </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>extThree20XML/Headers/<a class="el" href="_t_t_x_m_l_parser_8h_source.php">TTXMLParser.h</a></li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
