<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTTextStyle Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTTextStyle Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTTextStyle" --><!-- doxytag: inherits="TTStyle" --><div class="dynheader">
Inheritance diagram for TTTextStyle:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_text_style.png" usemap="#TTTextStyle_map" alt=""/>
  <map id="TTTextStyle_map" name="TTTextStyle_map">
<area href="interface_t_t_style.php" alt="TTStyle" shape="rect" coords="0,56,77,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,77,24"/>
</map>
</div>

<p><a href="class_t_t_text_style-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a82661d758f52e1362f5f9c63e973df5f"></a><!-- doxytag: member="TTTextStyle::initWithNext:" ref="a82661d758f52e1362f5f9c63e973df5f" args="(TTStyle *next)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithNext:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a35952c391b436d3f8f98a441491946bd"></a><!-- doxytag: member="TTTextStyle::next:" ref="a35952c391b436d3f8f98a441491946bd" args="(TTStyle *next)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad86cf830e4be9a236ab3ce8dfce216c1"></a><!-- doxytag: member="TTTextStyle::draw:" ref="ad86cf830e4be9a236ab3ce8dfce216c1" args="(TTStyleContext *context)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>draw:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab7bcf3088626fad6ce719a40490135b6"></a><!-- doxytag: member="TTTextStyle::addToInsets:forSize:" ref="ab7bcf3088626fad6ce719a40490135b6" args="(UIEdgeInsets insets,[forSize] CGSize size)" -->
(UIEdgeInsets)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addToInsets:forSize:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aff87a7a63493d97de1bed39214d5cd48"></a><!-- doxytag: member="TTTextStyle::addToSize:context:" ref="aff87a7a63493d97de1bed39214d5cd48" args="(CGSize size,[context] TTStyleContext *context)" -->
(CGSize)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addToSize:context:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a652f9ece113ba6b6ea1cd5f161438598"></a><!-- doxytag: member="TTTextStyle::addStyle:" ref="a652f9ece113ba6b6ea1cd5f161438598" args="(TTStyle *style)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addStyle:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="add84af70ed0d751fc6979b1712f2d9f4"></a><!-- doxytag: member="TTTextStyle::firstStyleOfClass:" ref="add84af70ed0d751fc6979b1712f2d9f4" args="(Class cls)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>firstStyleOfClass:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9530c3267da5069a4ed5646d1d5bf4eb"></a><!-- doxytag: member="TTTextStyle::styleForPart:" ref="a9530c3267da5069a4ed5646d1d5bf4eb" args="(NSString *name)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>styleForPart:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a48211ce404f1251585e757a90242a31d"></a><!-- doxytag: member="TTTextStyle::newGradientWithColors:locations:count:" ref="a48211ce404f1251585e757a90242a31d" args="(UIColor **colors,[locations] CGFloat *locations,[count] int count)" -->
(CGGradientRef)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>newGradientWithColors:locations:count:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a35a26638a4faa56b3061a91509f02d22"></a><!-- doxytag: member="TTTextStyle::newGradientWithColors:count:" ref="a35a26638a4faa56b3061a91509f02d22" args="(UIColor **colors,[count] int count)" -->
(CGGradientRef)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>newGradientWithColors:count:</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adc15572f7462fb399b6d2e5e2d08c366"></a><!-- doxytag: member="TTTextStyle::styleWithFont:next:" ref="adc15572f7462fb399b6d2e5e2d08c366" args="(UIFont *font,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8c4525f52c7be10e4cfafa8305d1f063"></a><!-- doxytag: member="TTTextStyle::styleWithColor:next:" ref="a8c4525f52c7be10e4cfafa8305d1f063" args="(UIColor *color,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithColor:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1168cda92b9671da33ed3a5d889f21ad"></a><!-- doxytag: member="TTTextStyle::styleWithFont:color:next:" ref="a1168cda92b9671da33ed3a5d889f21ad" args="(UIFont *font,[color] UIColor *color,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:color:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a062be86ac4c3d7938295944a7ed6b9d0"></a><!-- doxytag: member="TTTextStyle::styleWithFont:color:textAlignment:next:" ref="a062be86ac4c3d7938295944a7ed6b9d0" args="(UIFont *font,[color] UIColor *color,[textAlignment] UITextAlignment textAlignment,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:color:textAlignment:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af9ce9daaa75ce849a7059ee6503a4870"></a><!-- doxytag: member="TTTextStyle::styleWithFont:color:shadowColor:shadowOffset:next:" ref="af9ce9daaa75ce849a7059ee6503a4870" args="(UIFont *font,[color] UIColor *color,[shadowColor] UIColor *shadowColor,[shadowOffset] CGSize shadowOffset,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:color:shadowColor:shadowOffset:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4497c3bfed8900f4fd3440159dea4920"></a><!-- doxytag: member="TTTextStyle::styleWithFont:color:minimumFontSize:shadowColor:shadowOffset:next:" ref="a4497c3bfed8900f4fd3440159dea4920" args="(UIFont *font,[color] UIColor *color,[minimumFontSize] CGFloat minimumFontSize,[shadowColor] UIColor *shadowColor,[shadowOffset] CGSize shadowOffset,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:color:minimumFontSize:shadowColor:shadowOffset:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a70b500597f58a356d8945c4492a70fcb"></a><!-- doxytag: member="TTTextStyle::styleWithFont:color:minimumFontSize:shadowColor:shadowOffset:textAlignment:verticalAlignment:lineBreakMode:numberOfLines:next:" ref="a70b500597f58a356d8945c4492a70fcb" args="(UIFont *font,[color] UIColor *color,[minimumFontSize] CGFloat minimumFontSize,[shadowColor] UIColor *shadowColor,[shadowOffset] CGSize shadowOffset,[textAlignment] UITextAlignment textAlignment,[verticalAlignment] UIControlContentVerticalAlignment verticalAlignment,[lineBreakMode] UILineBreakMode lineBreakMode,[numberOfLines] NSInteger numberOfLines,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_text_style.php">TTTextStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFont:color:minimumFontSize:shadowColor:shadowOffset:textAlignment:verticalAlignment:lineBreakMode:numberOfLines:next:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3e290ca605843b43036fc1fa2761d041"></a><!-- doxytag: member="TTTextStyle::_font" ref="a3e290ca605843b43036fc1fa2761d041" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a08c7cbd61deb916ab60701ce165ec244"></a><!-- doxytag: member="TTTextStyle::_color" ref="a08c7cbd61deb916ab60701ce165ec244" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_color</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5b5bf9bf4448c767bf0fac102f98781d"></a><!-- doxytag: member="TTTextStyle::_shadowColor" ref="a5b5bf9bf4448c767bf0fac102f98781d" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_shadowColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3f57c23cf6ba2f137916fc6464558375"></a><!-- doxytag: member="TTTextStyle::_shadowOffset" ref="a3f57c23cf6ba2f137916fc6464558375" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>_shadowOffset</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a934d0530d6e9393e2b6959f3b9ef2e71"></a><!-- doxytag: member="TTTextStyle::_minimumFontSize" ref="a934d0530d6e9393e2b6959f3b9ef2e71" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_minimumFontSize</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5462e7f0c446d8b8635e1539caebe410"></a><!-- doxytag: member="TTTextStyle::_numberOfLines" ref="a5462e7f0c446d8b8635e1539caebe410" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_numberOfLines</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2218b51e2f0ace43e589d72ce00be82d"></a><!-- doxytag: member="TTTextStyle::_textAlignment" ref="a2218b51e2f0ace43e589d72ce00be82d" args="" -->
UITextAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>_textAlignment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a92fbe6fbd3c7b857a6b03c99f2d613e3"></a><!-- doxytag: member="TTTextStyle::_verticalAlignment" ref="a92fbe6fbd3c7b857a6b03c99f2d613e3" args="" -->
UIControlContentVerticalAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>_verticalAlignment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a74a05793ed3a3ee704c86a7073251f49"></a><!-- doxytag: member="TTTextStyle::_lineBreakMode" ref="a74a05793ed3a3ee704c86a7073251f49" args="" -->
UILineBreakMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lineBreakMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa313c161147cde23524a441149e41290"></a><!-- doxytag: member="TTTextStyle::_next" ref="aa313c161147cde23524a441149e41290" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_next</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3c2eb90a657d43764a0dee94c44e96f2"></a><!-- doxytag: member="TTTextStyle::font" ref="a3c2eb90a657d43764a0dee94c44e96f2" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0b99965d87e4638269eb3f34bd783860"></a><!-- doxytag: member="TTTextStyle::color" ref="a0b99965d87e4638269eb3f34bd783860" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>color</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a269a9987f96823449aac4e2946a39a4d"></a><!-- doxytag: member="TTTextStyle::shadowColor" ref="a269a9987f96823449aac4e2946a39a4d" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>shadowColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61ebc15dfcc0cf1275b60378d1b69d24"></a><!-- doxytag: member="TTTextStyle::shadowOffset" ref="a61ebc15dfcc0cf1275b60378d1b69d24" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>shadowOffset</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8e1de7bff5302565be141d1a2fd42923"></a><!-- doxytag: member="TTTextStyle::minimumFontSize" ref="a8e1de7bff5302565be141d1a2fd42923" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>minimumFontSize</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0b56a98fbc5a598fcf4b8b36a23bba0e"></a><!-- doxytag: member="TTTextStyle::numberOfLines" ref="a0b56a98fbc5a598fcf4b8b36a23bba0e" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>numberOfLines</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a70bc99a628fb99d01006a505f7478845"></a><!-- doxytag: member="TTTextStyle::textAlignment" ref="a70bc99a628fb99d01006a505f7478845" args="" -->
UITextAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>textAlignment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a93b35e59709ba8f41e8090daf0aba956"></a><!-- doxytag: member="TTTextStyle::verticalAlignment" ref="a93b35e59709ba8f41e8090daf0aba956" args="" -->
UIControlContentVerticalAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>verticalAlignment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a015e2e03624cbe987089719dabd5c3b9"></a><!-- doxytag: member="TTTextStyle::lineBreakMode" ref="a015e2e03624cbe987089719dabd5c3b9" args="" -->
UILineBreakMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>lineBreakMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3e704cddfe9525e9184a7aec04f9a68c"></a><!-- doxytag: member="TTTextStyle::next" ref="a3e704cddfe9525e9184a7aec04f9a68c" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>next</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_text_style_8h_source.php">TTTextStyle.h</a></li>
<li>Three20Style/Sources/TTTextStyle.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
