<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTStyledLayout Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTStyledLayout Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTStyledLayout" --><!-- doxytag: inherits="NSObject" --><div class="dynheader">
Inheritance diagram for TTStyledLayout:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_styled_layout.png" usemap="#TTStyledLayout_map" alt=""/>
  <map id="TTStyledLayout_map" name="TTStyledLayout_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,99,24"/>
</map>
</div>

<p><a href="class_t_t_styled_layout-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a45943cca529c4a42484dd97e7168f1a1"></a><!-- doxytag: member="TTStyledLayout::initWithRootNode:" ref="a45943cca529c4a42484dd97e7168f1a1" args="(TTStyledNode *rootNode)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithRootNode:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4421899c867247eb06222bbdbfce6f9c"></a><!-- doxytag: member="TTStyledLayout::initWithX:width:height:" ref="a4421899c867247eb06222bbdbfce6f9c" args="(CGFloat x,[width] CGFloat width,[height] CGFloat height)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithX:width:height:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acf8f3217bc9b8ca2a60e6c7bf9505c7b"></a><!-- doxytag: member="TTStyledLayout::layout:" ref="acf8f3217bc9b8ca2a60e6c7bf9505c7b" args="(TTStyledNode *node)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>layout:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0838680261db129f66fe9c899d1473b9"></a><!-- doxytag: member="TTStyledLayout::layout:container:" ref="a0838680261db129f66fe9c899d1473b9" args="(TTStyledNode *node,[container] TTStyledElement *element)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>layout:container:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad2bc01bec1cb6b8c3ac0e9c9453440fa"></a><!-- doxytag: member="TTStyledLayout::_x" ref="ad2bc01bec1cb6b8c3ac0e9c9453440fa" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_x</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a798bf5b4ceff4a6b716cb41012e864a2"></a><!-- doxytag: member="TTStyledLayout::_width" ref="a798bf5b4ceff4a6b716cb41012e864a2" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_width</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6e842a671f461430d693b3796df58bcb"></a><!-- doxytag: member="TTStyledLayout::_height" ref="a6e842a671f461430d693b3796df58bcb" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_height</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4fea7d10ab94e43239a368c517c7fc66"></a><!-- doxytag: member="TTStyledLayout::_lineWidth" ref="a4fea7d10ab94e43239a368c517c7fc66" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lineWidth</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a06a5041dfc9f27563afa95c6dcf1ab86"></a><!-- doxytag: member="TTStyledLayout::_lineHeight" ref="a06a5041dfc9f27563afa95c6dcf1ab86" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lineHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa980ec29ef608a05fd9f343ff7b647fc"></a><!-- doxytag: member="TTStyledLayout::_minX" ref="aa980ec29ef608a05fd9f343ff7b647fc" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_minX</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0820bf95f6e0e221ecb7b87cc5249dc"></a><!-- doxytag: member="TTStyledLayout::_floatLeftWidth" ref="ab0820bf95f6e0e221ecb7b87cc5249dc" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_floatLeftWidth</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aee3f4b8b241a2f49e11ebaeafe57422f"></a><!-- doxytag: member="TTStyledLayout::_floatRightWidth" ref="aee3f4b8b241a2f49e11ebaeafe57422f" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_floatRightWidth</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9340b98554c261d157fe046000a9e188"></a><!-- doxytag: member="TTStyledLayout::_floatHeight" ref="a9340b98554c261d157fe046000a9e188" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_floatHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a73391c82925ad5d4c28e6d4a6ef30270"></a><!-- doxytag: member="TTStyledLayout::_rootFrame" ref="a73391c82925ad5d4c28e6d4a6ef30270" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rootFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af2fb09ee2ed690792e650f73838f225f"></a><!-- doxytag: member="TTStyledLayout::_lineFirstFrame" ref="af2fb09ee2ed690792e650f73838f225f" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lineFirstFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab6a081d929ef76beab6b3bae3395a71d"></a><!-- doxytag: member="TTStyledLayout::_inlineFrame" ref="ab6a081d929ef76beab6b3bae3395a71d" args="" -->
<a class="el" href="interface_t_t_styled_inline_frame.php">TTStyledInlineFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_inlineFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abc5a131db2c7ee754faa3d7e894a0898"></a><!-- doxytag: member="TTStyledLayout::_topFrame" ref="abc5a131db2c7ee754faa3d7e894a0898" args="" -->
<a class="el" href="interface_t_t_styled_box_frame.php">TTStyledBoxFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_topFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ade2e1880fed3641f49caea6f1b6226b3"></a><!-- doxytag: member="TTStyledLayout::_lastFrame" ref="ade2e1880fed3641f49caea6f1b6226b3" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lastFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a51655e6be5b955b74fd30cc27d5ed567"></a><!-- doxytag: member="TTStyledLayout::_font" ref="a51655e6be5b955b74fd30cc27d5ed567" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0962d42dc35c922a9abd6dd3b099cbc3"></a><!-- doxytag: member="TTStyledLayout::_boldFont" ref="a0962d42dc35c922a9abd6dd3b099cbc3" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_boldFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af0d9fb93007979ee4311f18b5d51bba7"></a><!-- doxytag: member="TTStyledLayout::_italicFont" ref="af0d9fb93007979ee4311f18b5d51bba7" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_italicFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a638b346235f5e008e236fe90f3e366e2"></a><!-- doxytag: member="TTStyledLayout::_linkStyle" ref="a638b346235f5e008e236fe90f3e366e2" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_linkStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aab4bdcd94a1cae00333111b858742b9b"></a><!-- doxytag: member="TTStyledLayout::_rootNode" ref="aab4bdcd94a1cae00333111b858742b9b" args="" -->
<a class="el" href="interface_t_t_styled_node.php">TTStyledNode</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rootNode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6febfd7c8b5bc52867055d630fe7997c"></a><!-- doxytag: member="TTStyledLayout::_lastNode" ref="a6febfd7c8b5bc52867055d630fe7997c" args="" -->
<a class="el" href="interface_t_t_styled_node.php">TTStyledNode</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_lastNode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4b79853fe5ef6477194865c2d3e97073"></a><!-- doxytag: member="TTStyledLayout::_invalidImages" ref="a4b79853fe5ef6477194865c2d3e97073" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_invalidImages</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad31757bcba5e22caca2c7e53c6229ec9"></a><!-- doxytag: member="TTStyledLayout::width" ref="ad31757bcba5e22caca2c7e53c6229ec9" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>width</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab5978dca4664add567b5ca38f8ad9979"></a><!-- doxytag: member="TTStyledLayout::height" ref="ab5978dca4664add567b5ca38f8ad9979" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>height</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae8d592fe34d9c66a29fd33d80e4e3b62"></a><!-- doxytag: member="TTStyledLayout::font" ref="ae8d592fe34d9c66a29fd33d80e4e3b62" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4cf61199254c6bac36aac660fbd1109e"></a><!-- doxytag: member="TTStyledLayout::rootFrame" ref="a4cf61199254c6bac36aac660fbd1109e" args="" -->
<a class="el" href="interface_t_t_styled_frame.php">TTStyledFrame</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>rootFrame</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3d6dabfcd7af218b7022567410449bf4"></a><!-- doxytag: member="TTStyledLayout::invalidImages" ref="a3d6dabfcd7af218b7022567410449bf4" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>invalidImages</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_styled_layout_8h_source.php">TTStyledLayout.h</a></li>
<li>Three20Style/Sources/TTStyledLayout.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
