<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTSearchBar Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTSearchBar Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTSearchBar" --><!-- doxytag: inherits="TTView" --><div class="dynheader">
Inheritance diagram for TTSearchBar:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_search_bar.png" usemap="#TTSearchBar_map" alt=""/>
  <map id="TTSearchBar_map" name="TTSearchBar_map">
<area href="interface_t_t_view.php" alt="TTView" shape="rect" coords="64,56,182,80"/>
<area href="class_u_i_view.php" alt="UIView" shape="rect" coords="0,0,118,24"/>
<area href="protocol_t_t_style_delegate-p.php" alt="&lt;TTStyleDelegate&gt;" shape="rect" coords="128,0,246,24"/>
</map>
</div>

<p><a href="class_t_t_search_bar-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aafe19d2323475f86bd30d06bfbf9f605"></a><!-- doxytag: member="TTSearchBar::search" ref="aafe19d2323475f86bd30d06bfbf9f605" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>search</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1b1830739866254043951c1ba38d7201"></a><!-- doxytag: member="TTSearchBar::showSearchResults:" ref="a1b1830739866254043951c1ba38d7201" args="(BOOL show)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>showSearchResults:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad88f3307be7d49bf55b419941a1eabbd"></a><!-- doxytag: member="TTSearchBar::drawContent:" ref="ad88f3307be7d49bf55b419941a1eabbd" args="(CGRect rect)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>drawContent:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6ca8c9a930241745c77280b6e5296a6b"></a><!-- doxytag: member="TTSearchBar::textForLayerWithStyle:" ref="a6ca8c9a930241745c77280b6e5296a6b" args="(TTStyle *style)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>textForLayerWithStyle:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61b305018c41e4b8596d477337614e28"></a><!-- doxytag: member="TTSearchBar::imageForLayerWithStyle:" ref="a61b305018c41e4b8596d477337614e28" args="(TTStyle *style)" -->
(<a class="el" href="class_u_i_image.php">UIImage</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>imageForLayerWithStyle:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a940c09a71f143ac572cf3ebaddeb127e"></a><!-- doxytag: member="TTSearchBar::drawLayer:withStyle:" ref="a940c09a71f143ac572cf3ebaddeb127e" args="(TTStyleContext *context,[withStyle] TTStyle *style)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>drawLayer:withStyle:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae918e449e1fe61dcd4d1ce880297be51"></a><!-- doxytag: member="TTSearchBar::_searchField" ref="ae918e449e1fe61dcd4d1ce880297be51" args="" -->
<a class="el" href="interface_t_t_search_text_field.php">TTSearchTextField</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_searchField</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af52afa1ebea06296600ff1e04e2b443e"></a><!-- doxytag: member="TTSearchBar::_boxView" ref="af52afa1ebea06296600ff1e04e2b443e" args="" -->
<a class="el" href="interface_t_t_view.php">TTView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_boxView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a76870f3a973fc19423f04990a694572f"></a><!-- doxytag: member="TTSearchBar::_cancelButton" ref="a76870f3a973fc19423f04990a694572f" args="" -->
<a class="el" href="interface_t_t_button.php">TTButton</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cancelButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1c389e25c44073d1f4255140a1782ec9"></a><!-- doxytag: member="TTSearchBar::_tintColor" ref="a1c389e25c44073d1f4255140a1782ec9" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_tintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6c52993b79bb1f2edb3b9769bcbeb7b0"></a><!-- doxytag: member="TTSearchBar::_textFieldStyle" ref="a6c52993b79bb1f2edb3b9769bcbeb7b0" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_textFieldStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a39d4003e527deff085f8b36f7443d3a2"></a><!-- doxytag: member="TTSearchBar::_showsCancelButton" ref="a39d4003e527deff085f8b36f7443d3a2" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_showsCancelButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a015ca66e74c1658c705f0bd670ffcade"></a><!-- doxytag: member="TTSearchBar::_showsSearchIcon" ref="a015ca66e74c1658c705f0bd670ffcade" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_showsSearchIcon</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a97853b2c7509081da5ac2fc9cf89976f"></a><!-- doxytag: member="TTSearchBar::_style" ref="a97853b2c7509081da5ac2fc9cf89976f" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_style</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aea5bd0ee9481a7012f50ea91cd7501bf"></a><!-- doxytag: member="TTSearchBar::_layout" ref="aea5bd0ee9481a7012f50ea91cd7501bf" args="" -->
<a class="el" href="interface_t_t_layout.php">TTLayout</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_layout</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a850f10cbbbe937f24f3660b0ad3595cb"></a><!-- doxytag: member="TTSearchBar::text" ref="a850f10cbbbe937f24f3660b0ad3595cb" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a85d3836bbca9a8cb224857b3ebbae1af"></a><!-- doxytag: member="TTSearchBar::placeholder" ref="a85d3836bbca9a8cb224857b3ebbae1af" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>placeholder</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7e8efc452bffc51a73fca43adb634cdd"></a><!-- doxytag: member="TTSearchBar::tableView" ref="a7e8efc452bffc51a73fca43adb634cdd" args="" -->
<a class="el" href="class_u_i_table_view.php">UITableView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a50198dc4067b68e5065aa71a669106f3"></a><!-- doxytag: member="TTSearchBar::boxView" ref="a50198dc4067b68e5065aa71a669106f3" args="" -->
<a class="el" href="interface_t_t_view.php">TTView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>boxView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afa693b3bab34463ba0ee43f34f487090"></a><!-- doxytag: member="TTSearchBar::tintColor" ref="afa693b3bab34463ba0ee43f34f487090" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aebd8672e9ea4096c6e9f0251421c5c44"></a><!-- doxytag: member="TTSearchBar::textColor" ref="aebd8672e9ea4096c6e9f0251421c5c44" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>textColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6aff63c421624d1e32bd5b7cf250d99a"></a><!-- doxytag: member="TTSearchBar::font" ref="a6aff63c421624d1e32bd5b7cf250d99a" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a36fb5683734b6ac87252d0f88b95f006"></a><!-- doxytag: member="TTSearchBar::textFieldStyle" ref="a36fb5683734b6ac87252d0f88b95f006" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>textFieldStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a00002eb6e5ef3a89e20a26d70c98f23d"></a><!-- doxytag: member="TTSearchBar::returnKeyType" ref="a00002eb6e5ef3a89e20a26d70c98f23d" args="" -->
UIReturnKeyType&nbsp;</td><td class="memItemRight" valign="bottom"><b>returnKeyType</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a71d161d9f3f8f6bfcee33096bbdf37e0"></a><!-- doxytag: member="TTSearchBar::rowHeight" ref="a71d161d9f3f8f6bfcee33096bbdf37e0" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>rowHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afa6298e7a28c7d7d3f3af9faef266649"></a><!-- doxytag: member="TTSearchBar::editing" ref="afa6298e7a28c7d7d3f3af9faef266649" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>editing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac41ff10ec2d14367b46eb276a2b45868"></a><!-- doxytag: member="TTSearchBar::searchesAutomatically" ref="ac41ff10ec2d14367b46eb276a2b45868" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>searchesAutomatically</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9495fc83b34928a945f8613d5ded7b07"></a><!-- doxytag: member="TTSearchBar::showsCancelButton" ref="a9495fc83b34928a945f8613d5ded7b07" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsCancelButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a07f89dcc0ebfe3a9852a9ae32587856c"></a><!-- doxytag: member="TTSearchBar::showsDoneButton" ref="a07f89dcc0ebfe3a9852a9ae32587856c" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsDoneButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca972ffce344940de867d3a8035d8c17"></a><!-- doxytag: member="TTSearchBar::showsDarkScreen" ref="aca972ffce344940de867d3a8035d8c17" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsDarkScreen</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a18bda88ca6ff5ce6c1e56b66133f9b57"></a><!-- doxytag: member="TTSearchBar::showsSearchIcon" ref="a18bda88ca6ff5ce6c1e56b66133f9b57" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsSearchIcon</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac57257e9b29d763142f0ee23a8256e49"></a><!-- doxytag: member="TTSearchBar::dataSource" ref="ac57257e9b29d763142f0ee23a8256e49" args="" -->
id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>dataSource</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0ea409fc63517e532dc32036dfb1ba4"></a><!-- doxytag: member="TTSearchBar::delegate" ref="ab0ea409fc63517e532dc32036dfb1ba4" args="" -->
id&lt; UITextFieldDelegate &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a832ab8c5e49539942c6d40c66fc80c78"></a><!-- doxytag: member="TTSearchBar::style" ref="a832ab8c5e49539942c6d40c66fc80c78" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>style</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aae1379b4316b8434d095325bfac7b70a"></a><!-- doxytag: member="TTSearchBar::layout" ref="aae1379b4316b8434d095325bfac7b70a" args="" -->
<a class="el" href="interface_t_t_layout.php">TTLayout</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>layout</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_search_bar_8h_source.php">TTSearchBar.h</a></li>
<li>Three20UI/Sources/TTSearchBar.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
