<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTURLCache Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTURLCache Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTURLCache" --><!-- doxytag: inherits="NSObject" -->
<p>A general purpose URL cache for caching data in memory and on disk.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_u_r_l_cache_8h_source.php">TTURLCache.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTURLCache:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_u_r_l_cache.png" usemap="#TTURLCache_map" alt=""/>
  <map id="TTURLCache_map" name="TTURLCache_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,86,24"/>
</map>
</div>

<p><a href="class_t_t_u_r_l_cache-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a78cbf82ef51653e48af8b020f6af29a7"></a><!-- doxytag: member="TTURLCache::initWithName:" ref="a78cbf82ef51653e48af8b020f6af29a7" args="(NSString *name)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithName:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a364099d9a1f492e97436f51af5f02731"></a><!-- doxytag: member="TTURLCache::keyForURL:" ref="a364099d9a1f492e97436f51af5f02731" args="(NSString *URL)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a364099d9a1f492e97436f51af5f02731">keyForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the key that would be used to cache a URL response. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5d5753453f34e8004d4f718e003ac8d2"></a><!-- doxytag: member="TTURLCache::cachePathForURL:" ref="a5d5753453f34e8004d4f718e003ac8d2" args="(NSString *URL)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a5d5753453f34e8004d4f718e003ac8d2">cachePathForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the path in the cache where a URL may be stored. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2b1cb4ca924ee2144bdcabdac4f6ee74"></a><!-- doxytag: member="TTURLCache::cachePathForKey:" ref="a2b1cb4ca924ee2144bdcabdac4f6ee74" args="(NSString *key)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a2b1cb4ca924ee2144bdcabdac4f6ee74">cachePathForKey:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the path in the cache where a key may be stored. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a5f35c6a68025bc64559a56c58bc0ebd0">etagCachePathForKey:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Etag cache files are stored in the following way: File name: &lt;key&gt; File data: &lt;etag value&gt;=""&gt;  <a href="#a5f35c6a68025bc64559a56c58bc0ebd0"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab5c6cc1d7631a29c2039d3e754bf299a"></a><!-- doxytag: member="TTURLCache::hasDataForURL:" ref="ab5c6cc1d7631a29c2039d3e754bf299a" args="(NSString *URL)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#ab5c6cc1d7631a29c2039d3e754bf299a">hasDataForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if there is a cache entry for a URL. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8c6b16b19a2f1c578e1c6797fb1f9d62"></a><!-- doxytag: member="TTURLCache::hasDataForKey:expires:" ref="a8c6b16b19a2f1c578e1c6797fb1f9d62" args="(NSString *key,[expires] NSTimeInterval expirationAge)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a8c6b16b19a2f1c578e1c6797fb1f9d62">hasDataForKey:expires:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if there is a cache entry for a key. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aebbee649e80e3efa16db0983174dbef8"></a><!-- doxytag: member="TTURLCache::hasImageForURL:fromDisk:" ref="aebbee649e80e3efa16db0983174dbef8" args="(NSString *URL,[fromDisk] BOOL fromDisk)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#aebbee649e80e3efa16db0983174dbef8">hasImageForURL:fromDisk:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if there is an image cache entry for a URL. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_data.php">NSData</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a23a138144b637eaff05ebc6265c0738a">dataForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the data for a URL from the cache if it exists.  <a href="#a23a138144b637eaff05ebc6265c0738a"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_data.php">NSData</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a2fb56c2577ac1491dedae42f406ae265">dataForURL:expires:timestamp:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the data for a URL from the cache if it exists and is newer than a minimum timestamp.  <a href="#a2fb56c2577ac1491dedae42f406ae265"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0d6948ae41ada056d98e176b95d3f846"></a><!-- doxytag: member="TTURLCache::dataForKey:expires:timestamp:" ref="a0d6948ae41ada056d98e176b95d3f846" args="(NSString *key,[expires] NSTimeInterval expirationAge,[timestamp] NSDate **timestamp)" -->
(<a class="el" href="class_n_s_data.php">NSData</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>dataForKey:expires:timestamp:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a6724011388079896acfc7dec95415f81">imageForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets an image from the in-memory image cache.  <a href="#a6724011388079896acfc7dec95415f81"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeb5760c833fc84782e5494192fdcaaaa"></a><!-- doxytag: member="TTURLCache::imageForURL:fromDisk:" ref="aeb5760c833fc84782e5494192fdcaaaa" args="(NSString *URL,[fromDisk] BOOL fromDisk)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>imageForURL:fromDisk:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66e2c79a1704ebe558169bb750c29feb"></a><!-- doxytag: member="TTURLCache::etagForKey:" ref="a66e2c79a1704ebe558169bb750c29feb" args="(NSString *key)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a66e2c79a1704ebe558169bb750c29feb">etagForKey:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Get an etag value for a given cache key. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab90aa8c209dfc64985de3a656400889c"></a><!-- doxytag: member="TTURLCache::storeData:forURL:" ref="ab90aa8c209dfc64985de3a656400889c" args="(NSData *data,[forURL] NSString *URL)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#ab90aa8c209dfc64985de3a656400889c">storeData:forURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Stores a data on disk. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a675bdb3928a4d3726a38b101d6594c1d"></a><!-- doxytag: member="TTURLCache::storeData:forKey:" ref="a675bdb3928a4d3726a38b101d6594c1d" args="(NSData *data,[forKey] NSString *key)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>storeData:forKey:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca5d856ab7094ce6d72cee55e9339380"></a><!-- doxytag: member="TTURLCache::storeImage:forURL:" ref="aca5d856ab7094ce6d72cee55e9339380" args="(UIImage *image,[forURL] NSString *URL)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#aca5d856ab7094ce6d72cee55e9339380">storeImage:forURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Stores an image in the memory cache. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeace0fb3b0b0882148e50ab64ab50d45"></a><!-- doxytag: member="TTURLCache::storeEtag:forKey:" ref="aeace0fb3b0b0882148e50ab64ab50d45" args="(NSString *etag,[forKey] NSString *key)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#aeace0fb3b0b0882148e50ab64ab50d45">storeEtag:forKey:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Stores an etag value in the etag cache. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a38466e8969b44bd07cc3cc355a4293db">storeTemporaryImage:toDisk:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Convenient way to create a temporary URL for some data and cache it in memory.  <a href="#a38466e8969b44bd07cc3cc355a4293db"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a76ceb19bd18c4c5eeff762ff99c3ef49">storeTemporaryData:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Convenient way to create a temporary URL for some data and cache in on disk.  <a href="#a76ceb19bd18c4c5eeff762ff99c3ef49"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a9f372bde9952f3cff0685fed8e2a9171">storeTemporaryFile:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Convenient way to create a temporary URL for a file and move it to the disk cache.  <a href="#a9f372bde9952f3cff0685fed8e2a9171"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a0b6697a9431b45ca772d63ec92a6916b">moveDataForURL:toURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Moves the data currently stored under one URL to another URL.  <a href="#a0b6697a9431b45ca772d63ec92a6916b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9cc2e6ed1b5ee2a2d76d1690dd7527b0"></a><!-- doxytag: member="TTURLCache::moveDataFromPath:toURL:" ref="a9cc2e6ed1b5ee2a2d76d1690dd7527b0" args="(NSString *path,[toURL] NSString *newURL)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>moveDataFromPath:toURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6f6cbee2dff6377361972c76c14f7878"></a><!-- doxytag: member="TTURLCache::moveDataFromPathToTemporaryURL:" ref="a6f6cbee2dff6377361972c76c14f7878" args="(NSString *path)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>moveDataFromPathToTemporaryURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5816cd5f987424e0f2d8e770636b35ff"></a><!-- doxytag: member="TTURLCache::removeURL:fromDisk:" ref="a5816cd5f987424e0f2d8e770636b35ff" args="(NSString *URL,[fromDisk] BOOL fromDisk)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a5816cd5f987424e0f2d8e770636b35ff">removeURL:fromDisk:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Removes the data for a URL from the memory cache and optionally from the disk cache. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a05d3a5968562dd38d52b583d993a5ec9"></a><!-- doxytag: member="TTURLCache::removeKey:" ref="a05d3a5968562dd38d52b583d993a5ec9" args="(NSString *key)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeKey:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a42cbfc3507b1036d2620579489ba6f66"></a><!-- doxytag: member="TTURLCache::removeAll:" ref="a42cbfc3507b1036d2620579489ba6f66" args="(BOOL fromDisk)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a42cbfc3507b1036d2620579489ba6f66">removeAll:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Erases the memory cache and optionally the disk cache. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#ada216804c3476267e995502d62388f6f">invalidateURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Invalidates the file in the disk cache so that its modified timestamp is the current time minus the default cache expiration age.  <a href="#ada216804c3476267e995502d62388f6f"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a872d54ad3f58e9ede6671e5ccc7717af"></a><!-- doxytag: member="TTURLCache::invalidateKey:" ref="a872d54ad3f58e9ede6671e5ccc7717af" args="(NSString *key)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>invalidateKey:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a85ccfcd327dd7701bb05ad061dda2bb7"></a><!-- doxytag: member="TTURLCache::invalidateAll" ref="a85ccfcd327dd7701bb05ad061dda2bb7" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_u_r_l_cache.php#a85ccfcd327dd7701bb05ad061dda2bb7">invalidateAll</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Invalidates all files in the disk cache according to rules explained in `invalidateURL`. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4a2b1dfe01786810f768050a961bae85"></a><!-- doxytag: member="TTURLCache::logMemoryUsage" ref="a4a2b1dfe01786810f768050a961bae85" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>logMemoryUsage</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae99fab5ff227b3cb42a6fc3544932ab9"></a><!-- doxytag: member="TTURLCache::cacheWithName:" ref="ae99fab5ff227b3cb42a6fc3544932ab9" args="(NSString *name)" -->
(<a class="el" href="interface_t_t_u_r_l_cache.php">TTURLCache</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_u_r_l_cache.php#ae99fab5ff227b3cb42a6fc3544932ab9">cacheWithName:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets a shared cache identified with a unique name. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad6f6da8abb412bd604be1395b34346d7"></a><!-- doxytag: member="TTURLCache::sharedCache" ref="ad6f6da8abb412bd604be1395b34346d7" args="()" -->
(<a class="el" href="interface_t_t_u_r_l_cache.php">TTURLCache</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_u_r_l_cache.php#ad6f6da8abb412bd604be1395b34346d7">sharedCache</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the shared cache singleton used across the application. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adf76cf2f618b0618aca4e54e6336e6a1"></a><!-- doxytag: member="TTURLCache::setSharedCache:" ref="adf76cf2f618b0618aca4e54e6336e6a1" args="(TTURLCache *cache)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_u_r_l_cache.php#adf76cf2f618b0618aca4e54e6336e6a1">setSharedCache:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sets the shared cache singleton used across the application. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a312677085095f44054f2876961e67610"></a><!-- doxytag: member="TTURLCache::cachePathWithName:" ref="a312677085095f44054f2876961e67610" args="(NSString *name)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>cachePathWithName:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6b56024b8efc74fca880005ef1fbac8d"></a><!-- doxytag: member="TTURLCache::doubleImageURLPath:" ref="a6b56024b8efc74fca880005ef1fbac8d" args="(NSString *urlPath)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>doubleImageURLPath:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a89c51c6370dc2f196eca3d2a90000f7e"></a><!-- doxytag: member="TTURLCache::_name" ref="a89c51c6370dc2f196eca3d2a90000f7e" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_name</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abae4c7ae595d5704b80c9c8ffc87dfb6"></a><!-- doxytag: member="TTURLCache::_cachePath" ref="abae4c7ae595d5704b80c9c8ffc87dfb6" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cachePath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4e3d743a2c5ba9ed5f29b339996199e5"></a><!-- doxytag: member="TTURLCache::_imageCache" ref="a4e3d743a2c5ba9ed5f29b339996199e5" args="" -->
<a class="el" href="class_n_s_mutable_dictionary.php">NSMutableDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_imageCache</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af2c82212a60fcca0123707ac94e9461a"></a><!-- doxytag: member="TTURLCache::_imageSortedList" ref="af2c82212a60fcca0123707ac94e9461a" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_imageSortedList</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a59aa01225b1e82fd4838fd7e2e85156b"></a><!-- doxytag: member="TTURLCache::_totalPixelCount" ref="a59aa01225b1e82fd4838fd7e2e85156b" args="" -->
NSUInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_totalPixelCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6835186698eb9c42172a3aecb4117197"></a><!-- doxytag: member="TTURLCache::_maxPixelCount" ref="a6835186698eb9c42172a3aecb4117197" args="" -->
NSUInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_maxPixelCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1ecae7d9cf762bea39edfb468b70bdb7"></a><!-- doxytag: member="TTURLCache::_totalLoading" ref="a1ecae7d9cf762bea39edfb468b70bdb7" args="" -->
NSInteger&nbsp;</td><td class="memItemRight" valign="bottom"><b>_totalLoading</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a63b053b43c971e8dabf765c82a2a14e3"></a><!-- doxytag: member="TTURLCache::_invalidationAge" ref="a63b053b43c971e8dabf765c82a2a14e3" args="" -->
NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><b>_invalidationAge</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0e1fdfadb4d214eaefe18d47fbd9031d"></a><!-- doxytag: member="TTURLCache::_disableDiskCache" ref="a0e1fdfadb4d214eaefe18d47fbd9031d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_disableDiskCache</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af9b1d0155b9f1572034904e484262a0e"></a><!-- doxytag: member="TTURLCache::_disableImageCache" ref="af9b1d0155b9f1572034904e484262a0e" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_disableImageCache</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#a2d1220ae6f57ec0c86f5f93351dc0a1b">disableDiskCache</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Disables the disk cache.  <a href="#a2d1220ae6f57ec0c86f5f93351dc0a1b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adbfcc7dd613e62be6a8930f146a2c2bf"></a><!-- doxytag: member="TTURLCache::disableImageCache" ref="adbfcc7dd613e62be6a8930f146a2c2bf" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#adbfcc7dd613e62be6a8930f146a2c2bf">disableImageCache</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Disables the in-memory cache for images. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a52da998d5df61ba519db1469597a54a3"></a><!-- doxytag: member="TTURLCache::cachePath" ref="a52da998d5df61ba519db1469597a54a3" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#a52da998d5df61ba519db1469597a54a3">cachePath</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the path to the directory of the disk cache. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad4c768d564e500fb4a2744244e274fab"></a><!-- doxytag: member="TTURLCache::etagCachePath" ref="ad4c768d564e500fb4a2744244e274fab" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#ad4c768d564e500fb4a2744244e274fab">etagCachePath</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets the path to the directory of the disk cache for etags. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">NSUInteger&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#a6dc964b9bbbd1b7c99af928faaf01992">maxPixelCount</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The maximum number of pixels to keep in memory for cached images.  <a href="#a6dc964b9bbbd1b7c99af928faaf01992"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2bec99453fca73fc8e4942737a9ad263"></a><!-- doxytag: member="TTURLCache::invalidationAge" ref="a2bec99453fca73fc8e4942737a9ad263" args="" -->
NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_u_r_l_cache.php#a2bec99453fca73fc8e4942737a9ad263">invalidationAge</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The amount of time to set back the modification timestamp on files when invalidating them. <br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>A general purpose URL cache for caching data in memory and on disk. </p>
<p>Etags are supported. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a23a138144b637eaff05ebc6265c0738a"></a><!-- doxytag: member="TTURLCache::dataForURL:" ref="a23a138144b637eaff05ebc6265c0738a" args="(NSString *URL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_data.php">NSData</a> *) dataForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the data for a URL from the cache if it exists. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>nil if the URL is not cached. </dd></dl>

</div>
</div>
<a class="anchor" id="a2fb56c2577ac1491dedae42f406ae265"></a><!-- doxytag: member="TTURLCache::dataForURL:expires:timestamp:" ref="a2fb56c2577ac1491dedae42f406ae265" args="(NSString *URL,[expires] NSTimeInterval expirationAge,[timestamp] NSDate **timestamp)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_data.php">NSData</a> *) dataForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
        </tr>
        <tr>
          <td class="paramkey">expires:</td>
          <td></td>
          <td class="paramtype">(NSTimeInterval)&nbsp;</td>
          <td class="paramname"> <em>expirationAge</em></td>
        </tr>
        <tr>
          <td class="paramkey">timestamp:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_date.php">NSDate</a>**)&nbsp;</td>
          <td class="paramname"> <em>timestamp</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the data for a URL from the cache if it exists and is newer than a minimum timestamp. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>nil if hthe URL is not cached or if the cache entry is older than the minimum. </dd></dl>

</div>
</div>
<a class="anchor" id="a5f35c6a68025bc64559a56c58bc0ebd0"></a><!-- doxytag: member="TTURLCache::etagCachePathForKey:" ref="a5f35c6a68025bc64559a56c58bc0ebd0" args="(NSString *key)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) etagCachePathForKey: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>key</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Etag cache files are stored in the following way: File name: &lt;key&gt; File data: &lt;etag value&gt;=""&gt; </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The etag cache path for the given key. </dd></dl>

</div>
</div>
<a class="anchor" id="a6724011388079896acfc7dec95415f81"></a><!-- doxytag: member="TTURLCache::imageForURL:" ref="a6724011388079896acfc7dec95415f81" args="(NSString *URL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) imageForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets an image from the in-memory image cache. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>nil if the URL is not cached. </dd></dl>

</div>
</div>
<a class="anchor" id="ada216804c3476267e995502d62388f6f"></a><!-- doxytag: member="TTURLCache::invalidateURL:" ref="ada216804c3476267e995502d62388f6f" args="(NSString *URL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) invalidateURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Invalidates the file in the disk cache so that its modified timestamp is the current time minus the default cache expiration age. </p>
<p>This ensures that the next time the URL is requested from the cache it will be loaded from the network if the default cache expiration age is used. </p>

</div>
</div>
<a class="anchor" id="a0b6697a9431b45ca772d63ec92a6916b"></a><!-- doxytag: member="TTURLCache::moveDataForURL:toURL:" ref="a0b6697a9431b45ca772d63ec92a6916b" args="(NSString *oldURL,[toURL] NSString *newURL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) moveDataForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>oldURL</em></td>
        </tr>
        <tr>
          <td class="paramkey">toURL:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>newURL</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Moves the data currently stored under one URL to another URL. </p>
<p>This is handy when you are caching data at a temporary URL while the permanent URL is being retrieved from a server. Once you know the permanent URL you can use this to move the data. </p>

</div>
</div>
<a class="anchor" id="a76ceb19bd18c4c5eeff762ff99c3ef49"></a><!-- doxytag: member="TTURLCache::storeTemporaryData:" ref="a76ceb19bd18c4c5eeff762ff99c3ef49" args="(NSData *data)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) storeTemporaryData: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_data.php">NSData</a>*)&nbsp;</td>
          <td class="paramname"> <em>data</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Convenient way to create a temporary URL for some data and cache in on disk. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The temporary URL </dd></dl>

</div>
</div>
<a class="anchor" id="a9f372bde9952f3cff0685fed8e2a9171"></a><!-- doxytag: member="TTURLCache::storeTemporaryFile:" ref="a9f372bde9952f3cff0685fed8e2a9171" args="(NSURL *fileURL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) storeTemporaryFile: </td>
          <td></td>
          <td class="paramtype">(NSURL*)&nbsp;</td>
          <td class="paramname"> <em>fileURL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Convenient way to create a temporary URL for a file and move it to the disk cache. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The temporary URL </dd></dl>

</div>
</div>
<a class="anchor" id="a38466e8969b44bd07cc3cc355a4293db"></a><!-- doxytag: member="TTURLCache::storeTemporaryImage:toDisk:" ref="a38466e8969b44bd07cc3cc355a4293db" args="(UIImage *image,[toDisk] BOOL toDisk)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) storeTemporaryImage: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_u_i_image.php">UIImage</a>*)&nbsp;</td>
          <td class="paramname"> <em>image</em></td>
        </tr>
        <tr>
          <td class="paramkey">toDisk:</td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>toDisk</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Convenient way to create a temporary URL for some data and cache it in memory. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The temporary URL </dd></dl>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="a2d1220ae6f57ec0c86f5f93351dc0a1b"></a><!-- doxytag: member="TTURLCache::disableDiskCache" ref="a2d1220ae6f57ec0c86f5f93351dc0a1b" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) disableDiskCache<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Disables the disk cache. </p>
<p>Disables etag support as well. </p>

</div>
</div>
<a class="anchor" id="a6dc964b9bbbd1b7c99af928faaf01992"></a><!-- doxytag: member="TTURLCache::maxPixelCount" ref="a6dc964b9bbbd1b7c99af928faaf01992" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (NSUInteger) maxPixelCount<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The maximum number of pixels to keep in memory for cached images. </p>
<p>Setting this to zero will allow an unlimited number of images to be cached. The default is zero. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Network/Headers/<a class="el" href="_t_t_u_r_l_cache_8h_source.php">TTURLCache.h</a></li>
<li>Three20Network/Sources/TTURLCache.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
