<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTModelViewController Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fthree20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTModelViewController Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTModelViewController" --><!-- doxytag: inherits="TTViewController,TTModelDelegate-p" -->
<p>A view controller that manages a model in addition to a view.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_model_view_controller_8h_source.php">TTModelViewController.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTModelViewController:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_model_view_controller.png" usemap="#TTModelViewController_map" alt=""/>
  <map id="TTModelViewController_map" name="TTModelViewController_map">
<area href="interface_t_t_view_controller.php" alt="TTViewController" shape="rect" coords="481,168,646,192"/>
<area href="protocol_t_t_model_delegate-p.php" alt="&lt;TTModelDelegate&gt;" shape="rect" coords="656,168,821,192"/>
<area href="interface_t_t_navigator_view_controller.php" alt="TTNavigatorViewController" shape="rect" coords="481,112,646,136"/>
<area href="interface_t_t_base_view_controller.php" alt="TTBaseViewController" shape="rect" coords="481,56,646,80"/>
<area href="class_u_i_view_controller.php" alt="UIViewController" shape="rect" coords="481,0,646,24"/>
<area href="interface_t_t_photo_view_controller.php" alt="TTPhotoViewController" shape="rect" coords="0,280,165,304"/>
<area href="interface_t_t_popup_view_controller.php" alt="TTPopupViewController" shape="rect" coords="262,280,427,304"/>
<area href="interface_t_t_table_view_controller.php" alt="TTTableViewController" shape="rect" coords="875,280,1040,304"/>
<area href="interface_t_t_web_controller.php" alt="TTWebController" shape="rect" coords="1050,280,1215,304"/>
<area href="interface_t_t_action_sheet_controller.php" alt="TTActionSheetController" shape="rect" coords="0,336,165,360"/>
<area href="interface_t_t_alert_view_controller.php" alt="TTAlertViewController" shape="rect" coords="175,336,340,360"/>
<area href="interface_t_t_post_controller.php" alt="TTPostController" shape="rect" coords="350,336,515,360"/>
<area href="interface_t_t_text_bar_controller.php" alt="TTTextBarController" shape="rect" coords="525,336,690,360"/>
<area href="interface_t_t_extension_info_controller.php" alt="TTExtensionInfoController" shape="rect" coords="700,336,865,360"/>
<area href="interface_t_t_extensions_controller.php" alt="TTExtensionsController" shape="rect" coords="875,336,1040,360"/>
<area href="interface_t_t_thumbs_view_controller.php" alt="TTThumbsViewController" shape="rect" coords="1050,336,1215,360"/>
</map>
</div>

<p><a href="class_t_t_model_view_controller-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a277731e4a0b2afacef0f50d052f5a6ee"></a><!-- doxytag: member="TTModelViewController::createModel" ref="a277731e4a0b2afacef0f50d052f5a6ee" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a277731e4a0b2afacef0f50d052f5a6ee">createModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Creates the model that the controller manages. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afe989215479fe730579aa2836f477850"></a><!-- doxytag: member="TTModelViewController::invalidateModel" ref="afe989215479fe730579aa2836f477850" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#afe989215479fe730579aa2836f477850">invalidateModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Releases the current model and forces the creation of a new model. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aefb8faff3f2ee24d25868d538603bef0"></a><!-- doxytag: member="TTModelViewController::isModelCreated" ref="aefb8faff3f2ee24d25868d538603bef0" args="()" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aefb8faff3f2ee24d25868d538603bef0">isModelCreated</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates whether the model has been created. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a11f547cd237948cb6592bdc2bd093ff6">shouldLoad</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that data should be loaded from the model.  <a href="#a11f547cd237948cb6592bdc2bd093ff6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#ac04eb12ba87d7abd890f7276fda9f223">shouldReload</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that data should be reloaded from the model.  <a href="#ac04eb12ba87d7abd890f7276fda9f223"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a991de3bff712c0261cb54ec6a2056e63">shouldLoadMore</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that more data should be loaded from the model.  <a href="#a991de3bff712c0261cb54ec6a2056e63"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a1648848389e0e716f42cbab7ba1bad94">canShowModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Tests if it is possible to show the model.  <a href="#a1648848389e0e716f42cbab7ba1bad94"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24f2409dfa7b20b8f76c9730db192f29"></a><!-- doxytag: member="TTModelViewController::reload" ref="a24f2409dfa7b20b8f76c9730db192f29" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a24f2409dfa7b20b8f76c9730db192f29">reload</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Reloads data from the model. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0fc1f3aeb889a326a6c11e100074023"></a><!-- doxytag: member="TTModelViewController::reloadIfNeeded" ref="ab0fc1f3aeb889a326a6c11e100074023" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#ab0fc1f3aeb889a326a6c11e100074023">reloadIfNeeded</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Reloads data from the model if it has become out of date. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abaf624c169c5663efdd5ccf9ac6575f3"></a><!-- doxytag: member="TTModelViewController::refresh" ref="abaf624c169c5663efdd5ccf9ac6575f3" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#abaf624c169c5663efdd5ccf9ac6575f3">refresh</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Refreshes the model state and loads new data if necessary. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a96f3ef31d4df7409e44a740ced1d91f4">beginUpdates</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Begins a multi-stage update.  <a href="#a96f3ef31d4df7409e44a740ced1d91f4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a54488637f89a309a5de88123257b73bc">endUpdates</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Ends a multi-stage model update and updates the view to reflect the model.  <a href="#a54488637f89a309a5de88123257b73bc"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa035befabec5a8713ea9026f570ac5bd"></a><!-- doxytag: member="TTModelViewController::invalidateView" ref="aa035befabec5a8713ea9026f570ac5bd" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aa035befabec5a8713ea9026f570ac5bd">invalidateView</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the model has changed and schedules the view to be updated to reflect it. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81ef717e98e2876ff9cab2969dcf28f1"></a><!-- doxytag: member="TTModelViewController::updateView" ref="a81ef717e98e2876ff9cab2969dcf28f1" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a81ef717e98e2876ff9cab2969dcf28f1">updateView</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Immediately creates, loads, and displays the model (if it was not already). <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#adc98dbd9f50022bef4c3b27a05744fc7">didRefreshModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called when the model is refreshed.  <a href="#adc98dbd9f50022bef4c3b27a05744fc7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a4efdc6eedf94241adda63d4d1aca36b9">willLoadModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called before the model is asked to load itself.  <a href="#a4efdc6eedf94241adda63d4d1aca36b9"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a358624f7a1dd93c7ae7d627d76a83505">didLoadModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called after the model has loaded, just before it is to be displayed.  <a href="#a358624f7a1dd93c7ae7d627d76a83505"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a23aecc1df4ed6e754be83644b8b3e7a4">didShowModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called just after a model has been loaded and displayed.  <a href="#a23aecc1df4ed6e754be83644b8b3e7a4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#adb70f1b36491c7320769b40e9ffbdff9">showModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent the loaded model's content.  <a href="#adb70f1b36491c7320769b40e9ffbdff9"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a0041c889ed5b9c98a76d824a92436a07">showLoading:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent the model loading.  <a href="#a0041c889ed5b9c98a76d824a92436a07"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aaba45ca7762b8a5ed4e38c066dc46519">showEmpty:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent an empty model.  <a href="#aaba45ca7762b8a5ed4e38c066dc46519"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a36b36cb89ffe7f5c2ff0611980af3e32"></a><!-- doxytag: member="TTModelViewController::showError:" ref="a36b36cb89ffe7f5c2ff0611980af3e32" args="(BOOL show)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a36b36cb89ffe7f5c2ff0611980af3e32">showError:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent an error that occurred while loading the model. <br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1d409c9cfc0a5411003dfe628338cce"></a><!-- doxytag: member="TTModelViewController::_model" ref="ac1d409c9cfc0a5411003dfe628338cce" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_model</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab9291afe449c5fe8ebe3325e13a86fef"></a><!-- doxytag: member="TTModelViewController::_modelError" ref="ab9291afe449c5fe8ebe3325e13a86fef" args="" -->
NSError *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_modelError</b></td></tr>
<tr><td class="memItemLeft" ><a class="anchor" id="ac8968f89da3e15d89b245a50639bbc9f"></a><!-- doxytag: member="TTModelViewController::_flags" ref="ac8968f89da3e15d89b245a50639bbc9f" args="" -->
struct {</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidRefreshInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelWillLoadInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidLoadInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidLoadFirstTimeInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidShowFirstTimeInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isViewInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isViewSuspended</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isUpdatingView</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingEmpty</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingLoading</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingModel</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingError</b>:1</td></tr>
<tr><td class="memItemLeft" valign="top">}&nbsp;</td><td class="memItemRight" valign="bottom"><b>_flags</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61f1378a65641be5991cfb07d7f894e5"></a><!-- doxytag: member="TTModelViewController::model" ref="a61f1378a65641be5991cfb07d7f894e5" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>model</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abf74cd2086bd97dfa34f6e250598bd8f"></a><!-- doxytag: member="TTModelViewController::modelError" ref="abf74cd2086bd97dfa34f6e250598bd8f" args="" -->
NSError *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_model_view_controller.php#abf74cd2086bd97dfa34f6e250598bd8f">modelError</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">An error that occurred while trying to load content. <br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>A view controller that manages a model in addition to a view. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a96f3ef31d4df7409e44a740ced1d91f4"></a><!-- doxytag: member="TTModelViewController::beginUpdates" ref="a96f3ef31d4df7409e44a740ced1d91f4" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) beginUpdates </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Begins a multi-stage update. </p>
<p>You can call this method to make complicated updates more efficient, and to condense multiple changes to your model into a single visual change. Call endUpdate when you are done to update the view with all of your changes. </p>

</div>
</div>
<a class="anchor" id="a1648848389e0e716f42cbab7ba1bad94"></a><!-- doxytag: member="TTModelViewController::canShowModel" ref="a1648848389e0e716f42cbab7ba1bad94" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) canShowModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Tests if it is possible to show the model. </p>
<p>After a model has loaded, this method is called to test whether or not to set the model has content that can be shown. If you return NO, showEmpty: will be called, and if you return YES, showModel: will be called. </p>

</div>
</div>
<a class="anchor" id="a358624f7a1dd93c7ae7d627d76a83505"></a><!-- doxytag: member="TTModelViewController::didLoadModel:" ref="a358624f7a1dd93c7ae7d627d76a83505" args="(BOOL firstTime)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didLoadModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>firstTime</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called after the model has loaded, just before it is to be displayed. </p>
<p>This is not called until after the view has loaded. If your model finishes loading before the view is loaded, this will still be called, but not until after the view is loaded.</p>
<p>If you refresh a model which is already loaded, this will be called, but the firstTime argument will be false.</p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="adc98dbd9f50022bef4c3b27a05744fc7"></a><!-- doxytag: member="TTModelViewController::didRefreshModel" ref="adc98dbd9f50022bef4c3b27a05744fc7" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didRefreshModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called when the model is refreshed. </p>
<p>Subclasses should override this function update parts of the view that may need to changed when there is a new model, or something about the existing model changes. </p>

</div>
</div>
<a class="anchor" id="a23aecc1df4ed6e754be83644b8b3e7a4"></a><!-- doxytag: member="TTModelViewController::didShowModel:" ref="a23aecc1df4ed6e754be83644b8b3e7a4" args="(BOOL firstTime)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didShowModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>firstTime</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called just after a model has been loaded and displayed. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a54488637f89a309a5de88123257b73bc"></a><!-- doxytag: member="TTModelViewController::endUpdates" ref="a54488637f89a309a5de88123257b73bc" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) endUpdates </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Ends a multi-stage model update and updates the view to reflect the model. </p>
<p>You can call this method to make complicated updates more efficient, and to condense multiple changes to your model into a single visual change. </p>

</div>
</div>
<a class="anchor" id="a11f547cd237948cb6592bdc2bd093ff6"></a><!-- doxytag: member="TTModelViewController::shouldLoad" ref="a11f547cd237948cb6592bdc2bd093ff6" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldLoad </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that data should be loaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="a991de3bff712c0261cb54ec6a2056e63"></a><!-- doxytag: member="TTModelViewController::shouldLoadMore" ref="a991de3bff712c0261cb54ec6a2056e63" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldLoadMore </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that more data should be loaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="ac04eb12ba87d7abd890f7276fda9f223"></a><!-- doxytag: member="TTModelViewController::shouldReload" ref="ac04eb12ba87d7abd890f7276fda9f223" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldReload </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that data should be reloaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="aaba45ca7762b8a5ed4e38c066dc46519"></a><!-- doxytag: member="TTModelViewController::showEmpty:" ref="aaba45ca7762b8a5ed4e38c066dc46519" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showEmpty: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent an empty model. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a0041c889ed5b9c98a76d824a92436a07"></a><!-- doxytag: member="TTModelViewController::showLoading:" ref="a0041c889ed5b9c98a76d824a92436a07" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showLoading: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent the model loading. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="adb70f1b36491c7320769b40e9ffbdff9"></a><!-- doxytag: member="TTModelViewController::showModel:" ref="adb70f1b36491c7320769b40e9ffbdff9" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent the loaded model's content. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a4efdc6eedf94241adda63d4d1aca36b9"></a><!-- doxytag: member="TTModelViewController::willLoadModel" ref="a4efdc6eedf94241adda63d4d1aca36b9" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) willLoadModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called before the model is asked to load itself. </p>
<p>This is not called until after the view has loaded. If your model starts loading before the view is loaded, this will still be called, but not until after the view is loaded.</p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_model_view_controller_8h_source.php">TTModelViewController.h</a></li>
<li>Three20UI/Sources/TTModelViewController.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
