<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTSectionedDataSource Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTSectionedDataSource Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTSectionedDataSource" --><!-- doxytag: inherits="TTTableViewDataSource" --><div class="dynheader">
Inheritance diagram for TTSectionedDataSource:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_sectioned_data_source.png" usemap="#TTSectionedDataSource_map" alt=""/>
  <map id="TTSectionedDataSource_map" name="TTSectionedDataSource_map">
<area href="interface_t_t_table_view_data_source.php" alt="TTTableViewDataSource" shape="rect" coords="88,112,254,136"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,56,166,80"/>
<area href="protocol_t_t_table_view_data_source-p.php" alt="&lt;TTTableViewDataSource&gt;" shape="rect" coords="176,56,342,80"/>
<area href="protocol_t_t_model-p.php" alt="&lt;TTModel&gt;" shape="rect" coords="176,0,342,24"/>
</map>
</div>

<p><a href="class_t_t_sectioned_data_source-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca54e8f25190b92ffe59b54851afc630"></a><!-- doxytag: member="TTSectionedDataSource::initWithItems:sections:" ref="aca54e8f25190b92ffe59b54851afc630" args="(NSArray *items,[sections] NSArray *sections)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithItems:sections:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeabf78103cc33db6bb7365a514e1a7a9"></a><!-- doxytag: member="TTSectionedDataSource::indexPathOfItemWithUserInfo:" ref="aeabf78103cc33db6bb7365a514e1a7a9" args="(id userInfo)" -->
(NSIndexPath *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>indexPathOfItemWithUserInfo:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae8e2f6afb296fb65988857099651b063"></a><!-- doxytag: member="TTSectionedDataSource::removeItemAtIndexPath:" ref="ae8e2f6afb296fb65988857099651b063" args="(NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeItemAtIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0d792ca53af589a65ebc584052344231"></a><!-- doxytag: member="TTSectionedDataSource::removeItemAtIndexPath:andSectionIfEmpty:" ref="a0d792ca53af589a65ebc584052344231" args="(NSIndexPath *indexPath,[andSectionIfEmpty] BOOL andSection)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeItemAtIndexPath:andSectionIfEmpty:</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_sectioned_data_source.php#a756f7f746e49ed15b2bbe4399c9f49d6">dataSourceWithObjects:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Objects should be in this format:  <a href="#a756f7f746e49ed15b2bbe4399c9f49d6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_sectioned_data_source.php#a7bf1c5da277aad353af4360a9064e291">dataSourceWithArrays:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Objects should be in this format:  <a href="#a7bf1c5da277aad353af4360a9064e291"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_sectioned_data_source.php#acfe7d8e526b33f5dea06caf3b00b978a">dataSourceWithItems:sections:</a></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a28f70759b47769bce896a2b7275a22bf"></a><!-- doxytag: member="TTSectionedDataSource::_sections" ref="a28f70759b47769bce896a2b7275a22bf" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_sections</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abf62ac62eb3fab69175788e3e7d34b6f"></a><!-- doxytag: member="TTSectionedDataSource::_items" ref="abf62ac62eb3fab69175788e3e7d34b6f" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_items</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae18ad5eee6d910e2e2d7870ae0ee7a2a"></a><!-- doxytag: member="TTSectionedDataSource::items" ref="ae18ad5eee6d910e2e2d7870ae0ee7a2a" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>items</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1978d447d2591561d6788b55e39ddd05"></a><!-- doxytag: member="TTSectionedDataSource::sections" ref="a1978d447d2591561d6788b55e39ddd05" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>sections</b></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a7bf1c5da277aad353af4360a9064e291"></a><!-- doxytag: member="TTSectionedDataSource::dataSourceWithArrays:" ref="a7bf1c5da277aad353af4360a9064e291" args="(id object,[,]...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *) dataSourceWithArrays: </td>
          <td></td>
          <td class="paramtype">(id)&nbsp;</td>
          <td class="paramname"> <em>object</em></td>
        </tr>
        <tr>
          <td class="paramkey">,</td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Objects should be in this format: </p>
<p>"section title", arrayOfItems, @"section title", arrayOfItems, ...</p>
<p>Where arrayOfItems is generally an array of items of type <a class="el" href="interface_t_t_table_item.php">TTTableItem</a>. </p>

</div>
</div>
<a class="anchor" id="acfe7d8e526b33f5dea06caf3b00b978a"></a><!-- doxytag: member="TTSectionedDataSource::dataSourceWithItems:sections:" ref="acfe7d8e526b33f5dea06caf3b00b978a" args="(NSArray *items,[sections] NSArray *sections)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *) dataSourceWithItems: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_array.php">NSArray</a>*)&nbsp;</td>
          <td class="paramname"> <em>items</em></td>
        </tr>
        <tr>
          <td class="paramkey">sections:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_array.php">NSArray</a>*)&nbsp;</td>
          <td class="paramname"> <em>sections</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>items</em>&nbsp;</td><td>An array of arrays, where each array is the contents of a section, to be listed under the section title held in the corresponding index of the `section` array.</td></tr>
    <tr><td valign="top"></td><td valign="top"><em>sections</em>&nbsp;</td><td>An array of strings, where each string is the title of a section.</td></tr>
  </table>
  </dd>
</dl>
<p>The items and sections arrays should be of equal length. </p>

</div>
</div>
<a class="anchor" id="a756f7f746e49ed15b2bbe4399c9f49d6"></a><!-- doxytag: member="TTSectionedDataSource::dataSourceWithObjects:" ref="a756f7f746e49ed15b2bbe4399c9f49d6" args="(id object,[,]...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (<a class="el" href="interface_t_t_sectioned_data_source.php">TTSectionedDataSource</a> *) dataSourceWithObjects: </td>
          <td></td>
          <td class="paramtype">(id)&nbsp;</td>
          <td class="paramname"> <em>object</em></td>
        </tr>
        <tr>
          <td class="paramkey">,</td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Objects should be in this format: </p>
<p>"section title", item, item, @"section title", item, item, ...</p>
<p>Where item is generally a type of <a class="el" href="interface_t_t_table_item.php">TTTableItem</a>. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_sectioned_data_source_8h_source.php">TTSectionedDataSource.h</a></li>
<li>Three20UI/Sources/TTSectionedDataSource.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
