<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTBoxStyle Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fthree20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTBoxStyle Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTBoxStyle" --><!-- doxytag: inherits="TTStyle" --><div class="dynheader">
Inheritance diagram for TTBoxStyle:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_box_style.png" usemap="#TTBoxStyle_map" alt=""/>
  <map id="TTBoxStyle_map" name="TTBoxStyle_map">
<area href="interface_t_t_style.php" alt="TTStyle" shape="rect" coords="0,56,75,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,75,24"/>
</map>
</div>

<p><a href="class_t_t_box_style-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af03c61d0615b9c8794c9dad79f9a11a3"></a><!-- doxytag: member="TTBoxStyle::styleWithMargin:next:" ref="af03c61d0615b9c8794c9dad79f9a11a3" args="(UIEdgeInsets margin,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithMargin:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca4afac7b02d9fe178b6f6cb061af826"></a><!-- doxytag: member="TTBoxStyle::styleWithPadding:next:" ref="aca4afac7b02d9fe178b6f6cb061af826" args="(UIEdgeInsets padding,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithPadding:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8b7183e634eb3d69ebcde817d64f7db7"></a><!-- doxytag: member="TTBoxStyle::styleWithFloats:next:" ref="a8b7183e634eb3d69ebcde817d64f7db7" args="(TTPosition position,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithFloats:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a87b909e654e5ad3504ed0b8ef09966df"></a><!-- doxytag: member="TTBoxStyle::styleWithMargin:padding:next:" ref="a87b909e654e5ad3504ed0b8ef09966df" args="(UIEdgeInsets margin,[padding] UIEdgeInsets padding,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithMargin:padding:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5fd401bdbd1bc347ae1e71aade8d5fbf"></a><!-- doxytag: member="TTBoxStyle::styleWithMargin:padding:minSize:position:next:" ref="a5fd401bdbd1bc347ae1e71aade8d5fbf" args="(UIEdgeInsets margin,[padding] UIEdgeInsets padding,[minSize] CGSize minSize,[position] TTPosition position,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_box_style.php">TTBoxStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithMargin:padding:minSize:position:next:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a39d736eb3cb3374a7aaa89e8bca51fa2"></a><!-- doxytag: member="TTBoxStyle::_margin" ref="a39d736eb3cb3374a7aaa89e8bca51fa2" args="" -->
UIEdgeInsets&nbsp;</td><td class="memItemRight" valign="bottom"><b>_margin</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="add82e52e1866b32c7c5a275d3b14326c"></a><!-- doxytag: member="TTBoxStyle::_padding" ref="add82e52e1866b32c7c5a275d3b14326c" args="" -->
UIEdgeInsets&nbsp;</td><td class="memItemRight" valign="bottom"><b>_padding</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7f7ed23db2971caaf1af2e0acefaaabd"></a><!-- doxytag: member="TTBoxStyle::_minSize" ref="a7f7ed23db2971caaf1af2e0acefaaabd" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>_minSize</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a35dbf5c695e330a0b7a57f443ab9635d"></a><!-- doxytag: member="TTBoxStyle::_position" ref="a35dbf5c695e330a0b7a57f443ab9635d" args="" -->
TTPosition&nbsp;</td><td class="memItemRight" valign="bottom"><b>_position</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a942c3fb153a0e6577ba5367d6493e324"></a><!-- doxytag: member="TTBoxStyle::margin" ref="a942c3fb153a0e6577ba5367d6493e324" args="" -->
UIEdgeInsets&nbsp;</td><td class="memItemRight" valign="bottom"><b>margin</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af5a3e9b2cb0b22fc0dbf9438c11d09cb"></a><!-- doxytag: member="TTBoxStyle::padding" ref="af5a3e9b2cb0b22fc0dbf9438c11d09cb" args="" -->
UIEdgeInsets&nbsp;</td><td class="memItemRight" valign="bottom"><b>padding</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8e5475c9a065ab72adb2ca9438424ff1"></a><!-- doxytag: member="TTBoxStyle::minSize" ref="a8e5475c9a065ab72adb2ca9438424ff1" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>minSize</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af34d37d473ee063758eab5e6eb32653a"></a><!-- doxytag: member="TTBoxStyle::position" ref="af34d37d473ee063758eab5e6eb32653a" args="" -->
TTPosition&nbsp;</td><td class="memItemRight" valign="bottom"><b>position</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_box_style_8h_source.php">TTBoxStyle.h</a></li>
<li>Three20Style/Sources/TTBoxStyle.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
