<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTTableImageItem Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTTableImageItem Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTTableImageItem" --><!-- doxytag: inherits="TTTableTextItem" --><div class="dynheader">
Inheritance diagram for TTTableImageItem:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_table_image_item.png" usemap="#TTTableImageItem_map" alt=""/>
  <map id="TTTableImageItem_map" name="TTTableImageItem_map">
<area href="interface_t_t_table_text_item.php" alt="TTTableTextItem" shape="rect" coords="0,168,140,192"/>
<area href="interface_t_t_table_linked_item.php" alt="TTTableLinkedItem" shape="rect" coords="0,112,140,136"/>
<area href="interface_t_t_table_item.php" alt="TTTableItem" shape="rect" coords="0,56,140,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,140,24"/>
<area href="interface_t_t_table_right_image_item.php" alt="TTTableRightImageItem" shape="rect" coords="0,280,140,304"/>
</map>
</div>

<p><a href="class_t_t_table_image_item-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9ddc7fd9c78e36c4c8dd32493379ff6f"></a><!-- doxytag: member="TTTableImageItem::itemWithText:imageURL:" ref="a9ddc7fd9c78e36c4c8dd32493379ff6f" args="(NSString *text,[imageURL] NSString *imageURL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:imageURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a037f46068b0b8742f5e4f007d9b326d7"></a><!-- doxytag: member="TTTableImageItem::itemWithText:imageURL:URL:" ref="a037f46068b0b8742f5e4f007d9b326d7" args="(NSString *text,[imageURL] NSString *imageURL,[URL] NSString *URL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:imageURL:URL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adf2eb654aeb74ff66f8154af1946f6d3"></a><!-- doxytag: member="TTTableImageItem::itemWithText:imageURL:defaultImage:URL:" ref="adf2eb654aeb74ff66f8154af1946f6d3" args="(NSString *text,[imageURL] NSString *imageURL,[defaultImage] UIImage *defaultImage,[URL] NSString *URL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:imageURL:defaultImage:URL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afc99e14e08517b8961d58ca1dfca361f"></a><!-- doxytag: member="TTTableImageItem::itemWithText:imageURL:defaultImage:imageStyle:URL:" ref="afc99e14e08517b8961d58ca1dfca361f" args="(NSString *text,[imageURL] NSString *imageURL,[defaultImage] UIImage *defaultImage,[imageStyle] TTStyle *imageStyle,[URL] NSString *URL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:imageURL:defaultImage:imageStyle:URL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a1a3c6669b341a49c134cce5c2066b8"></a><!-- doxytag: member="TTTableImageItem::itemWithText:" ref="a7a1a3c6669b341a49c134cce5c2066b8" args="(NSString *text)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac5d0597557c8eae893cf002717e4b545"></a><!-- doxytag: member="TTTableImageItem::itemWithText:URL:" ref="ac5d0597557c8eae893cf002717e4b545" args="(NSString *text,[URL] NSString *URL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:URL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a532ef9a3ae6f9e8a08df07f618c369ac"></a><!-- doxytag: member="TTTableImageItem::itemWithText:URL:accessoryURL:" ref="a532ef9a3ae6f9e8a08df07f618c369ac" args="(NSString *text,[URL] NSString *URL,[accessoryURL] NSString *accessoryURL)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:URL:accessoryURL:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af2908f179fefde4a17bc3d80b1b5e786"></a><!-- doxytag: member="TTTableImageItem::itemWithText:delegate:selector:" ref="af2908f179fefde4a17bc3d80b1b5e786" args="(NSString *text,[delegate] id delegate,[selector] SEL selector)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>itemWithText:delegate:selector:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab7258a54edb28678792c7adb3405e8f6"></a><!-- doxytag: member="TTTableImageItem::_imageURL" ref="ab7258a54edb28678792c7adb3405e8f6" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_imageURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a490fa8f196db378e9a8a53d340a44cd8"></a><!-- doxytag: member="TTTableImageItem::_defaultImage" ref="a490fa8f196db378e9a8a53d340a44cd8" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_defaultImage</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afd8c7fa3443c8922f45df234061e3866"></a><!-- doxytag: member="TTTableImageItem::_imageStyle" ref="afd8c7fa3443c8922f45df234061e3866" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_imageStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a16c685cb0be26ff1287d539aab13ccaf"></a><!-- doxytag: member="TTTableImageItem::_text" ref="a16c685cb0be26ff1287d539aab13ccaf" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1d264f7a01a020c0e7ca82aee4d5653b"></a><!-- doxytag: member="TTTableImageItem::_URL" ref="a1d264f7a01a020c0e7ca82aee4d5653b" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_URL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aff6ad4624fff456b0ff9bbcb0bc5b4b9"></a><!-- doxytag: member="TTTableImageItem::_accessoryURL" ref="aff6ad4624fff456b0ff9bbcb0bc5b4b9" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_accessoryURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a28b76c4e7ea43e4fd85be0edbabebd05"></a><!-- doxytag: member="TTTableImageItem::_delegate" ref="a28b76c4e7ea43e4fd85be0edbabebd05" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9c183702ce0b220819db0203107181af"></a><!-- doxytag: member="TTTableImageItem::_selector" ref="a9c183702ce0b220819db0203107181af" args="" -->
SEL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_selector</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6d7fa24f1f7e650b44a70bfd243e7b56"></a><!-- doxytag: member="TTTableImageItem::_userInfo" ref="a6d7fa24f1f7e650b44a70bfd243e7b56" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>_userInfo</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ace618efee55b63b0141b4009a134195f"></a><!-- doxytag: member="TTTableImageItem::imageURL" ref="ace618efee55b63b0141b4009a134195f" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>imageURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0b15bc1a318a189581fca6ad08192470"></a><!-- doxytag: member="TTTableImageItem::defaultImage" ref="a0b15bc1a318a189581fca6ad08192470" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>defaultImage</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1815e4f98ac1a5753abb6a31bbfcc74"></a><!-- doxytag: member="TTTableImageItem::imageStyle" ref="ac1815e4f98ac1a5753abb6a31bbfcc74" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>imageStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7cb1b3d75b0166f44741f618cb741ff5"></a><!-- doxytag: member="TTTableImageItem::text" ref="a7cb1b3d75b0166f44741f618cb741ff5" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af812057f561e9078045fe54eeb3c195d"></a><!-- doxytag: member="TTTableImageItem::URL" ref="af812057f561e9078045fe54eeb3c195d" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>URL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a6499fbdde7270664c0dc9ef346e3e9"></a><!-- doxytag: member="TTTableImageItem::accessoryURL" ref="a7a6499fbdde7270664c0dc9ef346e3e9" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>accessoryURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1e31b38e92fb6dd00531738d9cfe23d2"></a><!-- doxytag: member="TTTableImageItem::delegate" ref="a1e31b38e92fb6dd00531738d9cfe23d2" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a500dd37b9ee35aaa0cd873944877481d"></a><!-- doxytag: member="TTTableImageItem::selector" ref="a500dd37b9ee35aaa0cd873944877481d" args="" -->
SEL&nbsp;</td><td class="memItemRight" valign="bottom"><b>selector</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3a604b1a44c5f115d699b01f338feb34"></a><!-- doxytag: member="TTTableImageItem::userInfo" ref="a3a604b1a44c5f115d699b01f338feb34" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>userInfo</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_table_image_item_8h_source.php">TTTableImageItem.h</a></li>
<li>Three20UI/Sources/TTTableImageItem.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
