<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTBaseNavigator Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTBaseNavigator Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTBaseNavigator" --><!-- doxytag: inherits="NSObject" -->
<p>A URL-based navigation system with built-in persistence.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_base_navigator_8h_source.php">TTBaseNavigator.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTBaseNavigator:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_base_navigator.png" usemap="#TTBaseNavigator_map" alt=""/>
  <map id="TTBaseNavigator_map" name="TTBaseNavigator_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,109,24"/>
<area href="interface_t_t_navigator.php" alt="TTNavigator" shape="rect" coords="0,112,109,136"/>
</map>
</div>

<p><a href="class_t_t_base_navigator-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a456b09e2237308cac626409c6833d743">openURLAction:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Load and display the view controller with a pattern that matches the URL.  <a href="#a456b09e2237308cac626409c6833d743"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a6bdefc8377db8b250867dd75b244e2b8">openURLs:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Opens a sequence of URLs.  <a href="#a6bdefc8377db8b250867dd75b244e2b8"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#afa745e4007cd0bbf1da9012649cd1ab0">viewControllerForURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets a view controller for the URL without opening it.  <a href="#afa745e4007cd0bbf1da9012649cd1ab0"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#abef44cafee785f081ddc01db4957c8f6">viewControllerForURL:query:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets a view controller for the URL without opening it.  <a href="#abef44cafee785f081ddc01db4957c8f6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a14b4dec5a3b177b66b4003c8c32a1b16">viewControllerForURL:query:pattern:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets a view controller for the URL without opening it.  <a href="#a14b4dec5a3b177b66b4003c8c32a1b16"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#acf439ce30fcfff1ae9e9a52a95064424">beginDelay</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Tells the navigator to delay heavy operations.  <a href="#acf439ce30fcfff1ae9e9a52a95064424"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4c72e1ee89fdefde0a70794fe95f6463"></a><!-- doxytag: member="TTBaseNavigator::endDelay" ref="a4c72e1ee89fdefde0a70794fe95f6463" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a4c72e1ee89fdefde0a70794fe95f6463">endDelay</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Tells controllers that were created during the delay to finish what they were planning to do. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7bf628d499c8d8f974cfca8a7dbc7931"></a><!-- doxytag: member="TTBaseNavigator::cancelDelay" ref="a7bf628d499c8d8f974cfca8a7dbc7931" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a7bf628d499c8d8f974cfca8a7dbc7931">cancelDelay</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Cancels the delay without notifying delayed controllers. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad4c27d2bff652889d9a7e3aec2d5cb76"></a><!-- doxytag: member="TTBaseNavigator::persistViewControllers" ref="ad4c27d2bff652889d9a7e3aec2d5cb76" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#ad4c27d2bff652889d9a7e3aec2d5cb76">persistViewControllers</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Persists all view controllers to user defaults. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae16f367fb06aedc2232817c081541d59"></a><!-- doxytag: member="TTBaseNavigator::restoreViewControllers" ref="ae16f367fb06aedc2232817c081541d59" args="()" -->
(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#ae16f367fb06aedc2232817c081541d59">restoreViewControllers</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Restores all view controllers from user defaults and returns the last one. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a9070bac173ad1468315a77e8596d85f5">persistController:path:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Persists a view controller's state and recursively persists the next view controller after it.  <a href="#a9070bac173ad1468315a77e8596d85f5"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa97fc83e955f8248d6232471be30c00c"></a><!-- doxytag: member="TTBaseNavigator::removeAllViewControllers" ref="aa97fc83e955f8248d6232471be30c00c" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#aa97fc83e955f8248d6232471be30c00c">removeAllViewControllers</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Removes all view controllers from the window and releases them. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ada711e28c02762b11d133f495f7a1c36"></a><!-- doxytag: member="TTBaseNavigator::pathForObject:" ref="ada711e28c02762b11d133f495f7a1c36" args="(id object)" -->
(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#ada711e28c02762b11d133f495f7a1c36">pathForObject:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Gets a navigation path which can be used to locate an object. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a70c3aaa39d43c33f22d3450781d8d769"></a><!-- doxytag: member="TTBaseNavigator::objectForPath:" ref="a70c3aaa39d43c33f22d3450781d8d769" args="(NSString *path)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a70c3aaa39d43c33f22d3450781d8d769">objectForPath:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Finds an object using its navigation path. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8f7c64c4418ca2f3b95840894e659f40"></a><!-- doxytag: member="TTBaseNavigator::resetDefaults" ref="a8f7c64c4418ca2f3b95840894e659f40" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_navigator.php#a8f7c64c4418ca2f3b95840894e659f40">resetDefaults</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Erases all data stored in user defaults. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a397be70e6dfd8005c776771ed0350558"></a><!-- doxytag: member="TTBaseNavigator::presentDependantController:parentController:mode:animated:transition:" ref="a397be70e6dfd8005c776771ed0350558" args="(UIViewController *controller,[parentController] UIViewController *parentController,[mode] TTNavigationMode mode,[animated] BOOL animated,[transition] NSInteger transition)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>presentDependantController:parentController:mode:animated:transition:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aaedaba471bab87dbb228d25c59db6bdc"></a><!-- doxytag: member="TTBaseNavigator::getVisibleChildController:" ref="aaedaba471bab87dbb228d25c59db6bdc" args="(UIViewController *controller)" -->
(<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>getVisibleChildController:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a44e1f347f4bfb6ba1cdfa190441b8891"></a><!-- doxytag: member="TTBaseNavigator::navigationControllerClass" ref="a44e1f347f4bfb6ba1cdfa190441b8891" args="()" -->
(Class)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>navigationControllerClass</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aebbadfcbce3a7d18e43977ee59375817"></a><!-- doxytag: member="TTBaseNavigator::globalNavigator" ref="aebbadfcbce3a7d18e43977ee59375817" args="()" -->
(<a class="el" href="interface_t_t_base_navigator.php">TTBaseNavigator</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>globalNavigator</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae203277ec4958b39add3c8c6a509cc7c"></a><!-- doxytag: member="TTBaseNavigator::setGlobalNavigator:" ref="ae203277ec4958b39add3c8c6a509cc7c" args="(TTBaseNavigator *navigator)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>setGlobalNavigator:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a239f5a83bfc9066aceb8196db7328a57"></a><!-- doxytag: member="TTBaseNavigator::_URLMap" ref="a239f5a83bfc9066aceb8196db7328a57" args="" -->
<a class="el" href="interface_t_t_u_r_l_map.php">TTURLMap</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_URLMap</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeb385cba9cc41f7739a0be0255db1ebb"></a><!-- doxytag: member="TTBaseNavigator::_window" ref="aeb385cba9cc41f7739a0be0255db1ebb" args="" -->
<a class="el" href="class_u_i_window.php">UIWindow</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_window</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7a878d3aed66fcab864925119c4dc30d"></a><!-- doxytag: member="TTBaseNavigator::_rootViewController" ref="a7a878d3aed66fcab864925119c4dc30d" args="" -->
<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rootViewController</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad22d7d51f0e4e29f2a17cba462601789"></a><!-- doxytag: member="TTBaseNavigator::_delayedControllers" ref="ad22d7d51f0e4e29f2a17cba462601789" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delayedControllers</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab673385bc307dd542d807500df377cf3"></a><!-- doxytag: member="TTBaseNavigator::_persistenceMode" ref="ab673385bc307dd542d807500df377cf3" args="" -->
TTNavigatorPersistenceMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>_persistenceMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9494a00ef284a576f60695c242d9148e"></a><!-- doxytag: member="TTBaseNavigator::_persistenceExpirationAge" ref="a9494a00ef284a576f60695c242d9148e" args="" -->
NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><b>_persistenceExpirationAge</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab76478162b0f156463f4906157a14086"></a><!-- doxytag: member="TTBaseNavigator::_delayCount" ref="ab76478162b0f156463f4906157a14086" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delayCount</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2f2a9959b2ed5d35f2eb522f8cddfdf6"></a><!-- doxytag: member="TTBaseNavigator::_supportsShakeToReload" ref="a2f2a9959b2ed5d35f2eb522f8cddfdf6" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_supportsShakeToReload</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1825c9d02a9953d997a944c0f38d897b"></a><!-- doxytag: member="TTBaseNavigator::_opensExternalURLs" ref="a1825c9d02a9953d997a944c0f38d897b" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_opensExternalURLs</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8443ccff44da175057358d46720a105b"></a><!-- doxytag: member="TTBaseNavigator::_delegate" ref="a8443ccff44da175057358d46720a105b" args="" -->
id&lt; <a class="el" href="protocol_t_t_navigator_delegate-p.php">TTNavigatorDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="interface_t_t_u_r_l_map.php">TTURLMap</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a3017d22aba919b66969e863484bb2168">URLMap</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The URL map used to translate between URLs and view controllers.  <a href="#a3017d22aba919b66969e863484bb2168"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_u_i_window.php">UIWindow</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a584f4a80461eea29d39b085acb023704">window</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The window that contains the view controller hierarchy.  <a href="#a584f4a80461eea29d39b085acb023704"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5568a0c8e0a19d26306e9d160d302b6e"></a><!-- doxytag: member="TTBaseNavigator::rootViewController" ref="a5568a0c8e0a19d26306e9d160d302b6e" args="" -->
<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a5568a0c8e0a19d26306e9d160d302b6e">rootViewController</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The controller that is at the root of the view controller hierarchy. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abe08b1203a02a91fe9b81f8dbb6cbda1"></a><!-- doxytag: member="TTBaseNavigator::visibleViewController" ref="abe08b1203a02a91fe9b81f8dbb6cbda1" args="" -->
<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#abe08b1203a02a91fe9b81f8dbb6cbda1">visibleViewController</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The currently visible view controller. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_u_i_view_controller.php">UIViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a9d5c8ea878103dd007eb3012d3749210">topViewController</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The view controller that is currently on top of the navigation stack.  <a href="#a9d5c8ea878103dd007eb3012d3749210"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a1ffbcfbcbefed8badea9d3bcbe21681a">URL</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The URL of the currently visible view controller;.  <a href="#a1ffbcfbcbefed8badea9d3bcbe21681a"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">TTNavigatorPersistenceMode&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#af4584c3f244a628f9986960f5973cb92">persistenceMode</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">How view controllers are automatically persisted on termination and restored on launch.  <a href="#af4584c3f244a628f9986960f5973cb92"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#abe6d7ee14fd1147201694ffdfdb3228d">persistenceExpirationAge</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The age at which persisted view controllers are too old to be restored.  <a href="#abe6d7ee14fd1147201694ffdfdb3228d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#ad49b7a6c9a4820d955a7eaf3687c05f2">supportsShakeToReload</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Causes the current view controller to be reloaded when shaking the phone.  <a href="#ad49b7a6c9a4820d955a7eaf3687c05f2"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#a093b7725f813a2819977991b416df181">opensExternalURLs</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Allows URLs to be opened externally if they don't match any patterns.  <a href="#a093b7725f813a2819977991b416df181"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_navigator.php#aaaa44f8ff42826f21da0fa61bc55e22e">isDelayed</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that we are asking controllers to delay heavy operations until a later time.  <a href="#aaaa44f8ff42826f21da0fa61bc55e22e"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a04b5fce67460de38133d7a497ea39388"></a><!-- doxytag: member="TTBaseNavigator::delegate" ref="a04b5fce67460de38133d7a497ea39388" args="" -->
id&lt; <a class="el" href="protocol_t_t_navigator_delegate-p.php">TTNavigatorDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>A URL-based navigation system with built-in persistence. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="acf439ce30fcfff1ae9e9a52a95064424"></a><!-- doxytag: member="TTBaseNavigator::beginDelay" ref="acf439ce30fcfff1ae9e9a52a95064424" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) beginDelay </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Tells the navigator to delay heavy operations. </p>
<p>Initializing controllers can be very expensive, so if you are going to do some animation while this might be happening, this will tell controllers created through the navigator that they should hold off so as not to slow down the operations. </p>

</div>
</div>
<a class="anchor" id="a456b09e2237308cac626409c6833d743"></a><!-- doxytag: member="TTBaseNavigator::openURLAction:" ref="a456b09e2237308cac626409c6833d743" args="(TTURLAction *URLAction)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *) openURLAction: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_t_t_u_r_l_action.php">TTURLAction</a>*)&nbsp;</td>
          <td class="paramname"> <em>URLAction</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Load and display the view controller with a pattern that matches the URL. </p>
<p>This method replaces all other openURL methods by using the chainable <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object.</p>
<p>If there is not yet a rootViewController, the view controller loaded with this URL will be assigned as the rootViewController and inserted into the keyWindow. If there is not a keyWindow, a <a class="el" href="class_u_i_window.php" title="Additions.">UIWindow</a> will be created and displayed.</p>
<p>Example <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> initialization: [[<a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> actionWithURLPath:"tt://some/path"] applyAnimated:YES]</p>
<p>Each apply* method on the <a class="el" href="interface_t_t_u_r_l_action.php" title="This object bundles up a set of parameters and ships them off to TTBasicNavigator&#39;s openURLAction...">TTURLAction</a> object returns self, allowing you to chain methods when initializing the object. This allows for a flexible method that requires a shifting set of parameters that have specific defaults. The old openURL* methods are being phased out, so please start using openURLAction instead. </p>

</div>
</div>
<a class="anchor" id="a6bdefc8377db8b250867dd75b244e2b8"></a><!-- doxytag: member="TTBaseNavigator::openURLs:" ref="a6bdefc8377db8b250867dd75b244e2b8" args="(NSString *URL,[,]...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *) openURLs: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
        </tr>
        <tr>
          <td class="paramkey">,</td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Opens a sequence of URLs. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The view controller of the last opened URL. </dd></dl>

</div>
</div>
<a class="anchor" id="a9070bac173ad1468315a77e8596d85f5"></a><!-- doxytag: member="TTBaseNavigator::persistController:path:" ref="a9070bac173ad1468315a77e8596d85f5" args="(UIViewController *controller,[path] NSMutableArray *path)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) persistController: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_u_i_view_controller.php">UIViewController</a>*)&nbsp;</td>
          <td class="paramname"> <em>controller</em></td>
        </tr>
        <tr>
          <td class="paramkey">path:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a>*)&nbsp;</td>
          <td class="paramname"> <em>path</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Persists a view controller's state and recursively persists the next view controller after it. </p>
<p>Do not call this directly except from within a view controller that is being directed by the app map to persist itself. </p>

</div>
</div>
<a class="anchor" id="afa745e4007cd0bbf1da9012649cd1ab0"></a><!-- doxytag: member="TTBaseNavigator::viewControllerForURL:" ref="afa745e4007cd0bbf1da9012649cd1ab0" args="(NSString *URL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *) viewControllerForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets a view controller for the URL without opening it. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The view controller mapped to URL. </dd></dl>

</div>
</div>
<a class="anchor" id="abef44cafee785f081ddc01db4957c8f6"></a><!-- doxytag: member="TTBaseNavigator::viewControllerForURL:query:" ref="abef44cafee785f081ddc01db4957c8f6" args="(NSString *URL,[query] NSDictionary *query)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *) viewControllerForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a>*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
        </tr>
        <tr>
          <td class="paramkey">query:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_dictionary.php">NSDictionary</a>*)&nbsp;</td>
          <td class="paramname"> <em>query</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets a view controller for the URL without opening it. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The view controller mapped to URL. </dd></dl>

</div>
</div>
<a class="anchor" id="a14b4dec5a3b177b66b4003c8c32a1b16"></a><!-- doxytag: member="TTBaseNavigator::viewControllerForURL:query:pattern:" ref="a14b4dec5a3b177b66b4003c8c32a1b16" args="(NSString *URL,[query] NSDictionary *query,[pattern] TTURLPattern **pattern)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a>*) viewControllerForURL: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_string.php">NSString</a> *)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
        </tr>
        <tr>
          <td class="paramkey">query:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *)&nbsp;</td>
          <td class="paramname"> <em>query</em></td>
        </tr>
        <tr>
          <td class="paramkey">pattern:</td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_t_t_u_r_l_pattern.php">TTURLPattern</a> **)&nbsp;</td>
          <td class="paramname"> <em>pattern</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets a view controller for the URL without opening it. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>The view controller mapped to URL. </dd></dl>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="aaaa44f8ff42826f21da0fa61bc55e22e"></a><!-- doxytag: member="TTBaseNavigator::isDelayed" ref="aaaa44f8ff42826f21da0fa61bc55e22e" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) isDelayed<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that we are asking controllers to delay heavy operations until a later time. </p>
<p>NO </p>

</div>
</div>
<a class="anchor" id="a093b7725f813a2819977991b416df181"></a><!-- doxytag: member="TTBaseNavigator::opensExternalURLs" ref="a093b7725f813a2819977991b416df181" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) opensExternalURLs<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Allows URLs to be opened externally if they don't match any patterns. </p>
<p>NO </p>

</div>
</div>
<a class="anchor" id="abe6d7ee14fd1147201694ffdfdb3228d"></a><!-- doxytag: member="TTBaseNavigator::persistenceExpirationAge" ref="abe6d7ee14fd1147201694ffdfdb3228d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (NSTimeInterval) persistenceExpirationAge<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The age at which persisted view controllers are too old to be restored. </p>
<p>In some cases, it is a good practice not to restore really old navigation paths, because the user probably won't remember how they got there, and would prefer to start from the beginning.</p>
<p>Set this to 0 to restore from any age.</p>
<p>0 </p>

</div>
</div>
<a class="anchor" id="af4584c3f244a628f9986960f5973cb92"></a><!-- doxytag: member="TTBaseNavigator::persistenceMode" ref="af4584c3f244a628f9986960f5973cb92" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (TTNavigatorPersistenceMode) persistenceMode<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>How view controllers are automatically persisted on termination and restored on launch. </p>
<p>TTNavigatorPersistenceModeNone </p>

</div>
</div>
<a class="anchor" id="ad49b7a6c9a4820d955a7eaf3687c05f2"></a><!-- doxytag: member="TTBaseNavigator::supportsShakeToReload" ref="ad49b7a6c9a4820d955a7eaf3687c05f2" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) supportsShakeToReload<code> [read, write, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Causes the current view controller to be reloaded when shaking the phone. </p>
<p>NO </p>

</div>
</div>
<a class="anchor" id="a9d5c8ea878103dd007eb3012d3749210"></a><!-- doxytag: member="TTBaseNavigator::topViewController" ref="a9d5c8ea878103dd007eb3012d3749210" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_view_controller.php">UIViewController</a> *) topViewController<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The view controller that is currently on top of the navigation stack. </p>
<p>This differs from visibleViewController in that it ignores things like search display controllers which are visible, but not part of navigation. </p>

</div>
</div>
<a class="anchor" id="a1ffbcfbcbefed8badea9d3bcbe21681a"></a><!-- doxytag: member="TTBaseNavigator::URL" ref="a1ffbcfbcbefed8badea9d3bcbe21681a" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a> *) URL<code> [read, write, copy]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The URL of the currently visible view controller;. </p>
<p>Setting this property will open a new URL. </p>

</div>
</div>
<a class="anchor" id="a3017d22aba919b66969e863484bb2168"></a><!-- doxytag: member="TTBaseNavigator::URLMap" ref="a3017d22aba919b66969e863484bb2168" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="interface_t_t_u_r_l_map.php">TTURLMap</a>*) URLMap<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The URL map used to translate between URLs and view controllers. </p>
<dl class="see"><dt><b>See also:</b></dt><dd><a class="el" href="interface_t_t_u_r_l_map.php">TTURLMap</a> </dd></dl>

</div>
</div>
<a class="anchor" id="a584f4a80461eea29d39b085acb023704"></a><!-- doxytag: member="TTBaseNavigator::window" ref="a584f4a80461eea29d39b085acb023704" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_window.php">UIWindow</a> *) window<code> [read, write, retain]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The window that contains the view controller hierarchy. </p>
<p>By default retrieves the keyWindow. If there is no keyWindow, creates a new <a class="el" href="interface_t_t_navigator_window.php" title="Provides support for shake gestures.">TTNavigatorWindow</a>. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UINavigator/Headers/<a class="el" href="_t_t_base_navigator_8h_source.php">TTBaseNavigator.h</a></li>
<li>Three20UINavigator/Sources/TTBaseNavigator.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
