<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: YAJLDocument Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://new.three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://new.three20.info/documentation">Documentation</a></li> 
  <li><a href="http://new.three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://new.three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://new.three20.info/">Three20</a></h1> 
  <h2><a href="http://new.three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>YAJLDocument Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="YAJLDocument" --><!-- doxytag: inherits="NSObject,YAJLParserDelegate-p" --><div class="dynheader">
Inheritance diagram for YAJLDocument:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_y_a_j_l_document.png" usemap="#YAJLDocument_map" alt=""/>
  <map id="YAJLDocument_map" name="YAJLDocument_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,146,24"/>
<area href="protocol_y_a_j_l_parser_delegate-p.php" alt="&lt;YAJLParserDelegate&gt;" shape="rect" coords="156,0,302,24"/>
</map>
</div>

<p><a href="class_y_a_j_l_document-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_y_a_j_l_document.php#a9b206b6d99ed1edd0cbec744ec75ff1b">initWithData:parserOptions:error:</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_y_a_j_l_document.php#a5244e742acee8498bbc4b488ed63ad0c">initWithParserOptions:</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(YAJLParserStatus)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_y_a_j_l_document.php#a535595df957db118207836ca5217509f">parse:error:</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a17d21d8cd1413c4596dd23bcd9e69fb2"></a><!-- doxytag: member="YAJLDocument::_pop" ref="a17d21d8cd1413c4596dd23bcd9e69fb2" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>_pop</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa582b4d02310f594a0f34f186a251581"></a><!-- doxytag: member="YAJLDocument::_popKey" ref="aa582b4d02310f594a0f34f186a251581" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>_popKey</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a68176263236a3ff3f7578816d0ec9e0d"></a><!-- doxytag: member="YAJLDocument::parserDidStartDictionary:" ref="a68176263236a3ff3f7578816d0ec9e0d" args="(YAJLParser *parser)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>parserDidStartDictionary:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24e62f45b73eb271dc0744b6787992ba"></a><!-- doxytag: member="YAJLDocument::parserDidEndDictionary:" ref="a24e62f45b73eb271dc0744b6787992ba" args="(YAJLParser *parser)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>parserDidEndDictionary:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab28667c43cd21dee7500ed3f44137fd2"></a><!-- doxytag: member="YAJLDocument::parserDidStartArray:" ref="ab28667c43cd21dee7500ed3f44137fd2" args="(YAJLParser *parser)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>parserDidStartArray:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2e07bb4fac65e5b329786b6f08efbddc"></a><!-- doxytag: member="YAJLDocument::parserDidEndArray:" ref="a2e07bb4fac65e5b329786b6f08efbddc" args="(YAJLParser *parser)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>parserDidEndArray:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9ad90afbda4e77208c1e61fc2a7175fe"></a><!-- doxytag: member="YAJLDocument::parser:didMapKey:" ref="a9ad90afbda4e77208c1e61fc2a7175fe" args="(YAJLParser *parser,[didMapKey] NSString *key)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>parser:didMapKey:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_y_a_j_l_parser_delegate-p.php#a2f554ab453f9108c0c046a9ad5b2034d">parser:didAdd:</a></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a21c81df73f53b55e8537cdd1b79e21c5"></a><!-- doxytag: member="YAJLDocument::root_" ref="a21c81df73f53b55e8537cdd1b79e21c5" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>root_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5991f280579ffd800d584d378072176a"></a><!-- doxytag: member="YAJLDocument::parser_" ref="a5991f280579ffd800d584d378072176a" args="" -->
<a class="el" href="interface_y_a_j_l_parser.php">YAJLParser</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>parser_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a06b5f4a293ea5369243a0e3ce2025a93"></a><!-- doxytag: member="YAJLDocument::delegate_" ref="a06b5f4a293ea5369243a0e3ce2025a93" args="" -->
__weak id&lt; <a class="el" href="protocol_y_a_j_l_document_delegate-p.php">YAJLDocumentDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3ae30f71f48362d88dade56e01b2b1ca"></a><!-- doxytag: member="YAJLDocument::dict_" ref="a3ae30f71f48362d88dade56e01b2b1ca" args="" -->
__weak <a class="el" href="class_n_s_mutable_dictionary.php">NSMutableDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>dict_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2293b5747edf5a45096b0e0f5a7d77cf"></a><!-- doxytag: member="YAJLDocument::array_" ref="a2293b5747edf5a45096b0e0f5a7d77cf" args="" -->
__weak <a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>array_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae2b1d3de473867aab9ec0a97efaca054"></a><!-- doxytag: member="YAJLDocument::key_" ref="ae2b1d3de473867aab9ec0a97efaca054" args="" -->
__weak <a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>key_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae0359e6f32796cd984a7b798fe88fb22"></a><!-- doxytag: member="YAJLDocument::stack_" ref="ae0359e6f32796cd984a7b798fe88fb22" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>stack_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a82f98010aa36cf24d81d934711c7bcc0"></a><!-- doxytag: member="YAJLDocument::keyStack_" ref="a82f98010aa36cf24d81d934711c7bcc0" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>keyStack_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad7e707c2844259bddd1032bc318de2f4"></a><!-- doxytag: member="YAJLDocument::currentType_" ref="ad7e707c2844259bddd1032bc318de2f4" args="" -->
YAJLDecoderCurrentType&nbsp;</td><td class="memItemRight" valign="bottom"><b>currentType_</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7fc7e61a96b99d2e1cd3c7dc8c25a4b3"></a><!-- doxytag: member="YAJLDocument::parserStatus_" ref="a7fc7e61a96b99d2e1cd3c7dc8c25a4b3" args="" -->
YAJLParserStatus&nbsp;</td><td class="memItemRight" valign="bottom"><b>parserStatus_</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0bccc6527c10176ff7ea8e566ed8a172"></a><!-- doxytag: member="YAJLDocument::root" ref="a0bccc6527c10176ff7ea8e566ed8a172" args="" -->
id&nbsp;</td><td class="memItemRight" valign="bottom"><b>root</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3ef4dae31a36129f29cc48046cdfd97e"></a><!-- doxytag: member="YAJLDocument::parserStatus" ref="a3ef4dae31a36129f29cc48046cdfd97e" args="" -->
YAJLParserStatus&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_y_a_j_l_document.php#a3ef4dae31a36129f29cc48046cdfd97e">parserStatus</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Root element. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8f0312e4c03f935bd8cef8990e5ad97b"></a><!-- doxytag: member="YAJLDocument::delegate" ref="a8f0312e4c03f935bd8cef8990e5ad97b" args="" -->
id&lt; <a class="el" href="protocol_y_a_j_l_document_delegate-p.php">YAJLDocumentDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>delegate</b></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a9b206b6d99ed1edd0cbec744ec75ff1b"></a><!-- doxytag: member="YAJLDocument::initWithData:parserOptions:error:" ref="a9b206b6d99ed1edd0cbec744ec75ff1b" args="(NSData *data,[parserOptions] YAJLParserOptions parserOptions,[error] NSError **error)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) initWithData: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_data.php">NSData</a> *)&nbsp;</td>
          <td class="paramname"> <em>data</em></td>
        </tr>
        <tr>
          <td class="paramkey">parserOptions:</td>
          <td></td>
          <td class="paramtype">(YAJLParserOptions)&nbsp;</td>
          <td class="paramname"> <em>parserOptions</em></td>
        </tr>
        <tr>
          <td class="paramkey">error:</td>
          <td></td>
          <td class="paramtype">(NSError **)&nbsp;</td>
          <td class="paramname"> <em>error</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Create document from data. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>data</em>&nbsp;</td><td>Data to parse </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>parserOptions</em>&nbsp;</td><td>Parse options </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>error</em>&nbsp;</td><td>Error to set on failure </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a5244e742acee8498bbc4b488ed63ad0c"></a><!-- doxytag: member="YAJLDocument::initWithParserOptions:" ref="a5244e742acee8498bbc4b488ed63ad0c" args="(YAJLParserOptions parserOptions)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (id) initWithParserOptions: </td>
          <td></td>
          <td class="paramtype">(YAJLParserOptions)&nbsp;</td>
          <td class="paramname"> <em>parserOptions</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Create empty document with parser options. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>parserOptions</em>&nbsp;</td><td>Parse options </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a535595df957db118207836ca5217509f"></a><!-- doxytag: member="YAJLDocument::parse:error:" ref="a535595df957db118207836ca5217509f" args="(NSData *data,[error] NSError **error)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (YAJLParserStatus) parse: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="class_n_s_data.php">NSData</a> *)&nbsp;</td>
          <td class="paramname"> <em>data</em></td>
        </tr>
        <tr>
          <td class="paramkey">error:</td>
          <td></td>
          <td class="paramtype">(NSError **)&nbsp;</td>
          <td class="paramname"> <em>error</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Parse data. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>data</em>&nbsp;</td><td>Data to parse </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>error</em>&nbsp;</td><td>Error to set on failure </td></tr>
  </table>
  </dd>
</dl>
<dl class="return"><dt><b>Returns:</b></dt><dd>Parser status </dd></dl>

</div>
</div>
<a class="anchor" id="a2f554ab453f9108c0c046a9ad5b2034d"></a><!-- doxytag: member="YAJLDocument::parser:didAdd:" ref="a2f554ab453f9108c0c046a9ad5b2034d" args="(YAJLParser *parser,[didAdd] id value)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) parser: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_y_a_j_l_parser.php">YAJLParser</a> *)&nbsp;</td>
          <td class="paramname"> <em>parser</em></td>
        </tr>
        <tr>
          <td class="paramkey">didAdd:</td>
          <td></td>
          <td class="paramtype">(id)&nbsp;</td>
          <td class="paramname"> <em>value</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Did add value. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>parser</em>&nbsp;</td><td>Sender </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>value</em>&nbsp;</td><td>Value of type NSNull, <a class="el" href="class_n_s_string.php" title="Additions.">NSString</a> or NSNumber </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>extThree20JSON/Vendors/YAJL/<a class="el" href="_y_a_j_l_document_8h_source.php">YAJLDocument.h</a></li>
<li>extThree20JSON/Vendors/YAJL/YAJLDocument.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
