<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTImageStyle Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTImageStyle Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTImageStyle" --><!-- doxytag: inherits="TTStyle" --><div class="dynheader">
Inheritance diagram for TTImageStyle:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_image_style.png" usemap="#TTImageStyle_map" alt=""/>
  <map id="TTImageStyle_map" name="TTImageStyle_map">
<area href="interface_t_t_style.php" alt="TTStyle" shape="rect" coords="0,56,87,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,87,24"/>
</map>
</div>

<p><a href="class_t_t_image_style-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a82661d758f52e1362f5f9c63e973df5f"></a><!-- doxytag: member="TTImageStyle::initWithNext:" ref="a82661d758f52e1362f5f9c63e973df5f" args="(TTStyle *next)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithNext:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a35952c391b436d3f8f98a441491946bd"></a><!-- doxytag: member="TTImageStyle::next:" ref="a35952c391b436d3f8f98a441491946bd" args="(TTStyle *next)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad86cf830e4be9a236ab3ce8dfce216c1"></a><!-- doxytag: member="TTImageStyle::draw:" ref="ad86cf830e4be9a236ab3ce8dfce216c1" args="(TTStyleContext *context)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>draw:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab7bcf3088626fad6ce719a40490135b6"></a><!-- doxytag: member="TTImageStyle::addToInsets:forSize:" ref="ab7bcf3088626fad6ce719a40490135b6" args="(UIEdgeInsets insets,[forSize] CGSize size)" -->
(UIEdgeInsets)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addToInsets:forSize:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aff87a7a63493d97de1bed39214d5cd48"></a><!-- doxytag: member="TTImageStyle::addToSize:context:" ref="aff87a7a63493d97de1bed39214d5cd48" args="(CGSize size,[context] TTStyleContext *context)" -->
(CGSize)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addToSize:context:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a652f9ece113ba6b6ea1cd5f161438598"></a><!-- doxytag: member="TTImageStyle::addStyle:" ref="a652f9ece113ba6b6ea1cd5f161438598" args="(TTStyle *style)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>addStyle:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="add84af70ed0d751fc6979b1712f2d9f4"></a><!-- doxytag: member="TTImageStyle::firstStyleOfClass:" ref="add84af70ed0d751fc6979b1712f2d9f4" args="(Class cls)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>firstStyleOfClass:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9530c3267da5069a4ed5646d1d5bf4eb"></a><!-- doxytag: member="TTImageStyle::styleForPart:" ref="a9530c3267da5069a4ed5646d1d5bf4eb" args="(NSString *name)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>styleForPart:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a48211ce404f1251585e757a90242a31d"></a><!-- doxytag: member="TTImageStyle::newGradientWithColors:locations:count:" ref="a48211ce404f1251585e757a90242a31d" args="(UIColor **colors,[locations] CGFloat *locations,[count] int count)" -->
(CGGradientRef)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>newGradientWithColors:locations:count:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a35a26638a4faa56b3061a91509f02d22"></a><!-- doxytag: member="TTImageStyle::newGradientWithColors:count:" ref="a35a26638a4faa56b3061a91509f02d22" args="(UIColor **colors,[count] int count)" -->
(CGGradientRef)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>newGradientWithColors:count:</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae8bc9fc9a4a4ac3e44c0404c751a36fe"></a><!-- doxytag: member="TTImageStyle::styleWithImageURL:next:" ref="ae8bc9fc9a4a4ac3e44c0404c751a36fe" args="(NSString *imageURL,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImageURL:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adce65a6b626763380561f5fb0d42f48f"></a><!-- doxytag: member="TTImageStyle::styleWithImageURL:defaultImage:next:" ref="adce65a6b626763380561f5fb0d42f48f" args="(NSString *imageURL,[defaultImage] UIImage *defaultImage,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImageURL:defaultImage:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3c877a42650de37b9ed2a9c5f9721caf"></a><!-- doxytag: member="TTImageStyle::styleWithImageURL:defaultImage:contentMode:size:next:" ref="a3c877a42650de37b9ed2a9c5f9721caf" args="(NSString *imageURL,[defaultImage] UIImage *defaultImage,[contentMode] UIViewContentMode contentMode,[size] CGSize size,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImageURL:defaultImage:contentMode:size:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0014c23701f935dcdb3151053a373b2c"></a><!-- doxytag: member="TTImageStyle::styleWithImage:next:" ref="a0014c23701f935dcdb3151053a373b2c" args="(UIImage *image,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImage:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6d02384d7c952b41b59caca4dc16e420"></a><!-- doxytag: member="TTImageStyle::styleWithImage:defaultImage:next:" ref="a6d02384d7c952b41b59caca4dc16e420" args="(UIImage *image,[defaultImage] UIImage *defaultImage,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImage:defaultImage:next:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac484d2e2a7ccfbbfe95c13ebb5c41970"></a><!-- doxytag: member="TTImageStyle::styleWithImage:defaultImage:contentMode:size:next:" ref="ac484d2e2a7ccfbbfe95c13ebb5c41970" args="(UIImage *image,[defaultImage] UIImage *defaultImage,[contentMode] UIViewContentMode contentMode,[size] CGSize size,[next] TTStyle *next)" -->
(<a class="el" href="interface_t_t_image_style.php">TTImageStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>styleWithImage:defaultImage:contentMode:size:next:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3d475e0e16de1e96a3e5cd13a573065c"></a><!-- doxytag: member="TTImageStyle::_imageURL" ref="a3d475e0e16de1e96a3e5cd13a573065c" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_imageURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0c65a3c44cc836f65e64fb7f60fefd99"></a><!-- doxytag: member="TTImageStyle::_image" ref="a0c65a3c44cc836f65e64fb7f60fefd99" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_image</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a37f5adcb5d7047525a9ea02c6672e155"></a><!-- doxytag: member="TTImageStyle::_defaultImage" ref="a37f5adcb5d7047525a9ea02c6672e155" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_defaultImage</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8ff3823f5c85729803db36b5c683f2e5"></a><!-- doxytag: member="TTImageStyle::_size" ref="a8ff3823f5c85729803db36b5c683f2e5" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>_size</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab4ef993daadb9a4a2cf28526b7dedecc"></a><!-- doxytag: member="TTImageStyle::_contentMode" ref="ab4ef993daadb9a4a2cf28526b7dedecc" args="" -->
UIViewContentMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>_contentMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa313c161147cde23524a441149e41290"></a><!-- doxytag: member="TTImageStyle::_next" ref="aa313c161147cde23524a441149e41290" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_next</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa7fd6ed038831c80c120f3d932931e3f"></a><!-- doxytag: member="TTImageStyle::imageURL" ref="aa7fd6ed038831c80c120f3d932931e3f" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>imageURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a47150dd1b0f91cb59b9f80cc6a2de27d"></a><!-- doxytag: member="TTImageStyle::image" ref="a47150dd1b0f91cb59b9f80cc6a2de27d" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>image</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab7c4e1cf976c3f2733296ed09d7914bb"></a><!-- doxytag: member="TTImageStyle::defaultImage" ref="ab7c4e1cf976c3f2733296ed09d7914bb" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>defaultImage</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac6cd4dfaf32610d22b1fa067ea322c28"></a><!-- doxytag: member="TTImageStyle::size" ref="ac6cd4dfaf32610d22b1fa067ea322c28" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>size</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aea812b9d15e829db754f33dc83b8de13"></a><!-- doxytag: member="TTImageStyle::contentMode" ref="aea812b9d15e829db754f33dc83b8de13" args="" -->
UIViewContentMode&nbsp;</td><td class="memItemRight" valign="bottom"><b>contentMode</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3e704cddfe9525e9184a7aec04f9a68c"></a><!-- doxytag: member="TTImageStyle::next" ref="a3e704cddfe9525e9184a7aec04f9a68c" args="" -->
<a class="el" href="interface_t_t_style.php">TTStyle</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>next</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_image_style_8h_source.php">TTImageStyle.h</a></li>
<li>Three20Style/Sources/TTImageStyle.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
