<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTSearchTextField Class Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTSearchTextField Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTSearchTextField" --><div class="dynheader">
Inheritance diagram for TTSearchTextField:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_search_text_field.png" usemap="#TTSearchTextField_map" alt=""/>
  <map id="TTSearchTextField_map" name="TTSearchTextField_map">
<area href="interface_t_t_picker_text_field.php" alt="TTPickerTextField" shape="rect" coords="0,56,118,80"/>
</map>
</div>

<p><a href="class_t_t_search_text_field-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a467b9d2bb22999d4a9445c19e655409e"></a><!-- doxytag: member="TTSearchTextField::search" ref="a467b9d2bb22999d4a9445c19e655409e" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>search</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af0408dcf1fe38ad8ecbdf41944c00ac4"></a><!-- doxytag: member="TTSearchTextField::showSearchResults:" ref="af0408dcf1fe38ad8ecbdf41944c00ac4" args="(BOOL show)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>showSearchResults:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4cec1a7c7b70e0bc153010c6bb683367"></a><!-- doxytag: member="TTSearchTextField::superviewForSearchResults" ref="a4cec1a7c7b70e0bc153010c6bb683367" args="()" -->
(<a class="el" href="class_u_i_view.php">UIView</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>superviewForSearchResults</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac3cdea57c1a96aa87f4deaf3fde2a701"></a><!-- doxytag: member="TTSearchTextField::rectForSearchResults:" ref="ac3cdea57c1a96aa87f4deaf3fde2a701" args="(BOOL withKeyboard)" -->
(CGRect)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>rectForSearchResults:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8dea54f8694d6263651cecee51ba3f98"></a><!-- doxytag: member="TTSearchTextField::shouldUpdate:" ref="a8dea54f8694d6263651cecee51ba3f98" args="(BOOL emptyText)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>shouldUpdate:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4f6d782676f84ca03cfc6fdd1888effa"></a><!-- doxytag: member="TTSearchTextField::_internal" ref="a4f6d782676f84ca03cfc6fdd1888effa" args="" -->
<a class="el" href="interface_t_t_search_text_field_internal.php">TTSearchTextFieldInternal</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_internal</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a471789733ae193f62b2f29d5ab4f2a01"></a><!-- doxytag: member="TTSearchTextField::_tableView" ref="a471789733ae193f62b2f29d5ab4f2a01" args="" -->
<a class="el" href="class_u_i_table_view.php">UITableView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_tableView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad485de0c4b918a2dfbf6e1033a6f5c82"></a><!-- doxytag: member="TTSearchTextField::_shadowView" ref="ad485de0c4b918a2dfbf6e1033a6f5c82" args="" -->
<a class="el" href="interface_t_t_view.php">TTView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_shadowView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae415a6a9cbf3827db89828207690a84f"></a><!-- doxytag: member="TTSearchTextField::_screenView" ref="ae415a6a9cbf3827db89828207690a84f" args="" -->
UIButton *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_screenView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acc3b864ce2783bfb23d9bf0137c099c6"></a><!-- doxytag: member="TTSearchTextField::_previousNavigationItem" ref="acc3b864ce2783bfb23d9bf0137c099c6" args="" -->
UINavigationItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_previousNavigationItem</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae81b2aedee57c6757016f182ac667502"></a><!-- doxytag: member="TTSearchTextField::_previousRightBarButtonItem" ref="ae81b2aedee57c6757016f182ac667502" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_previousRightBarButtonItem</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a73982430faf687ea3e0051692a9358e3"></a><!-- doxytag: member="TTSearchTextField::_searchTimer" ref="a73982430faf687ea3e0051692a9358e3" args="" -->
NSTimer *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_searchTimer</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5c98ffb365cf8de65a2576c49a5b35e7"></a><!-- doxytag: member="TTSearchTextField::_rowHeight" ref="a5c98ffb365cf8de65a2576c49a5b35e7" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_rowHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a90a99550236e2b3fbfe2d0409074a840"></a><!-- doxytag: member="TTSearchTextField::_searchesAutomatically" ref="a90a99550236e2b3fbfe2d0409074a840" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_searchesAutomatically</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9a8efbb45077c4b6a6346aed89a465f3"></a><!-- doxytag: member="TTSearchTextField::_showsDoneButton" ref="a9a8efbb45077c4b6a6346aed89a465f3" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_showsDoneButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a857d88355cc7f3a1e8b8713a05053aed"></a><!-- doxytag: member="TTSearchTextField::_showsDarkScreen" ref="a857d88355cc7f3a1e8b8713a05053aed" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_showsDarkScreen</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aaa0a4974a2c70358604f5963ed3179aa"></a><!-- doxytag: member="TTSearchTextField::_dataSource" ref="aaa0a4974a2c70358604f5963ed3179aa" args="" -->
id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_dataSource</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3fe5959486fb48fa26e87dfe94f2c9fe"></a><!-- doxytag: member="TTSearchTextField::tableView" ref="a3fe5959486fb48fa26e87dfe94f2c9fe" args="" -->
<a class="el" href="class_u_i_table_view.php">UITableView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a13e277fa11fb5a5cd8479afa342ad023"></a><!-- doxytag: member="TTSearchTextField::rowHeight" ref="a13e277fa11fb5a5cd8479afa342ad023" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>rowHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3fe400d4fc0d1ef756e089d6bc80cc8d"></a><!-- doxytag: member="TTSearchTextField::hasText" ref="a3fe400d4fc0d1ef756e089d6bc80cc8d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>hasText</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3a0902c5a2c996b4d9b778d10d3e8e04"></a><!-- doxytag: member="TTSearchTextField::searchesAutomatically" ref="a3a0902c5a2c996b4d9b778d10d3e8e04" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>searchesAutomatically</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a48e966bc731278fb5bbd7421b6e6af7b"></a><!-- doxytag: member="TTSearchTextField::showsDoneButton" ref="a48e966bc731278fb5bbd7421b6e6af7b" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsDoneButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5c4170956b6e2c4eda5e4f136c48e383"></a><!-- doxytag: member="TTSearchTextField::showsDarkScreen" ref="a5c4170956b6e2c4eda5e4f136c48e383" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>showsDarkScreen</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6dd72c064ccd0f57806d2a46b946a0b0"></a><!-- doxytag: member="TTSearchTextField::dataSource" ref="a6dd72c064ccd0f57806d2a46b946a0b0" args="" -->
id&lt; <a class="el" href="interface_t_t_table_view_data_source.php">TTTableViewDataSource</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>dataSource</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_search_text_field_8h_source.php">TTSearchTextField.h</a></li>
<li>Three20UI/Sources/TTSearchTextField.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
