<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTWebController Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/tutorials">Tutorials</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTWebController Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTWebController" --><!-- doxytag: inherits="TTModelViewController" --><div class="dynheader">
Inheritance diagram for TTWebController:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_web_controller.png" usemap="#TTWebController_map" alt=""/>
  <map id="TTWebController_map" name="TTWebController_map">
<area href="interface_t_t_model_view_controller.php" alt="TTModelViewController" shape="rect" coords="87,224,252,248"/>
<area href="interface_t_t_view_controller.php" alt="TTViewController" shape="rect" coords="0,168,165,192"/>
<area href="protocol_t_t_model_delegate-p.php" alt="&lt;TTModelDelegate&gt;" shape="rect" coords="175,168,340,192"/>
<area href="interface_t_t_navigator_view_controller.php" alt="TTNavigatorViewController" shape="rect" coords="0,112,165,136"/>
<area href="interface_t_t_base_view_controller.php" alt="TTBaseViewController" shape="rect" coords="0,56,165,80"/>
<area href="class_u_i_view_controller.php" alt="UIViewController" shape="rect" coords="0,0,165,24"/>
</map>
</div>

<p><a href="class_t_t_web_controller-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae2e3c09cf79447ee0acccb403796f603"></a><!-- doxytag: member="TTWebController::openURL:" ref="ae2e3c09cf79447ee0acccb403796f603" args="(NSURL *URL)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_web_controller.php#ae2e3c09cf79447ee0acccb403796f603">openURL:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Navigate to the given URL. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_web_controller.php#a073bb22ae4eae4ca6b68e895c0a16518">openRequest:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Load the given request using UIWebView's loadRequest:.  <a href="#a073bb22ae4eae4ca6b68e895c0a16518"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a277731e4a0b2afacef0f50d052f5a6ee"></a><!-- doxytag: member="TTWebController::createModel" ref="a277731e4a0b2afacef0f50d052f5a6ee" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a277731e4a0b2afacef0f50d052f5a6ee">createModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Creates the model that the controller manages. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afe989215479fe730579aa2836f477850"></a><!-- doxytag: member="TTWebController::invalidateModel" ref="afe989215479fe730579aa2836f477850" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#afe989215479fe730579aa2836f477850">invalidateModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Releases the current model and forces the creation of a new model. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aefb8faff3f2ee24d25868d538603bef0"></a><!-- doxytag: member="TTWebController::isModelCreated" ref="aefb8faff3f2ee24d25868d538603bef0" args="()" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aefb8faff3f2ee24d25868d538603bef0">isModelCreated</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates whether the model has been created. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a11f547cd237948cb6592bdc2bd093ff6">shouldLoad</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that data should be loaded from the model.  <a href="#a11f547cd237948cb6592bdc2bd093ff6"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#ac04eb12ba87d7abd890f7276fda9f223">shouldReload</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that data should be reloaded from the model.  <a href="#ac04eb12ba87d7abd890f7276fda9f223"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a991de3bff712c0261cb54ec6a2056e63">shouldLoadMore</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that more data should be loaded from the model.  <a href="#a991de3bff712c0261cb54ec6a2056e63"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a1648848389e0e716f42cbab7ba1bad94">canShowModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Tests if it is possible to show the model.  <a href="#a1648848389e0e716f42cbab7ba1bad94"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a24f2409dfa7b20b8f76c9730db192f29"></a><!-- doxytag: member="TTWebController::reload" ref="a24f2409dfa7b20b8f76c9730db192f29" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a24f2409dfa7b20b8f76c9730db192f29">reload</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Reloads data from the model. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0fc1f3aeb889a326a6c11e100074023"></a><!-- doxytag: member="TTWebController::reloadIfNeeded" ref="ab0fc1f3aeb889a326a6c11e100074023" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#ab0fc1f3aeb889a326a6c11e100074023">reloadIfNeeded</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Reloads data from the model if it has become out of date. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abaf624c169c5663efdd5ccf9ac6575f3"></a><!-- doxytag: member="TTWebController::refresh" ref="abaf624c169c5663efdd5ccf9ac6575f3" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#abaf624c169c5663efdd5ccf9ac6575f3">refresh</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Refreshes the model state and loads new data if necessary. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a96f3ef31d4df7409e44a740ced1d91f4">beginUpdates</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Begins a multi-stage update.  <a href="#a96f3ef31d4df7409e44a740ced1d91f4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a54488637f89a309a5de88123257b73bc">endUpdates</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Ends a multi-stage model update and updates the view to reflect the model.  <a href="#a54488637f89a309a5de88123257b73bc"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa035befabec5a8713ea9026f570ac5bd"></a><!-- doxytag: member="TTWebController::invalidateView" ref="aa035befabec5a8713ea9026f570ac5bd" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aa035befabec5a8713ea9026f570ac5bd">invalidateView</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Indicates that the model has changed and schedules the view to be updated to reflect it. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81ef717e98e2876ff9cab2969dcf28f1"></a><!-- doxytag: member="TTWebController::updateView" ref="a81ef717e98e2876ff9cab2969dcf28f1" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a81ef717e98e2876ff9cab2969dcf28f1">updateView</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Immediately creates, loads, and displays the model (if it was not already). <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#adc98dbd9f50022bef4c3b27a05744fc7">didRefreshModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called when the model is refreshed.  <a href="#adc98dbd9f50022bef4c3b27a05744fc7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a4efdc6eedf94241adda63d4d1aca36b9">willLoadModel</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called before the model is asked to load itself.  <a href="#a4efdc6eedf94241adda63d4d1aca36b9"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a358624f7a1dd93c7ae7d627d76a83505">didLoadModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called after the model has loaded, just before it is to be displayed.  <a href="#a358624f7a1dd93c7ae7d627d76a83505"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a23aecc1df4ed6e754be83644b8b3e7a4">didShowModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Called just after a model has been loaded and displayed.  <a href="#a23aecc1df4ed6e754be83644b8b3e7a4"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#adb70f1b36491c7320769b40e9ffbdff9">showModel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent the loaded model's content.  <a href="#adb70f1b36491c7320769b40e9ffbdff9"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a0041c889ed5b9c98a76d824a92436a07">showLoading:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent the model loading.  <a href="#a0041c889ed5b9c98a76d824a92436a07"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#aaba45ca7762b8a5ed4e38c066dc46519">showEmpty:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent an empty model.  <a href="#aaba45ca7762b8a5ed4e38c066dc46519"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a36b36cb89ffe7f5c2ff0611980af3e32"></a><!-- doxytag: member="TTWebController::showError:" ref="a36b36cb89ffe7f5c2ff0611980af3e32" args="(BOOL show)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_model_view_controller.php#a36b36cb89ffe7f5c2ff0611980af3e32">showError:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Shows views to represent an error that occurred while loading the model. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae517ac05a60aff4c64dadfdf5e0be548"></a><!-- doxytag: member="TTWebController::keyboardWillAppear:withBounds:" ref="ae517ac05a60aff4c64dadfdf5e0be548" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#ae517ac05a60aff4c64dadfdf5e0be548">keyboardWillAppear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller before the keyboard slides in. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3b370029749e85fe261726375ba13289"></a><!-- doxytag: member="TTWebController::keyboardWillDisappear:withBounds:" ref="a3b370029749e85fe261726375ba13289" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#a3b370029749e85fe261726375ba13289">keyboardWillDisappear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller before the keyboard slides out. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1405d3b2f2c3d4e1db7c7e29226c2e74"></a><!-- doxytag: member="TTWebController::keyboardDidAppear:withBounds:" ref="a1405d3b2f2c3d4e1db7c7e29226c2e74" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#a1405d3b2f2c3d4e1db7c7e29226c2e74">keyboardDidAppear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller after the keyboard has slid in. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad27dfcbbc6587b779af6231825679be0"></a><!-- doxytag: member="TTWebController::keyboardDidDisappear:withBounds:" ref="ad27dfcbbc6587b779af6231825679be0" args="(BOOL animated,[withBounds] CGRect bounds)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_base_view_controller.php#ad27dfcbbc6587b779af6231825679be0">keyboardDidDisappear:withBounds:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Sent to the controller after the keyboard has slid out. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5df22439eaf4f407a261ad79c03f55c4"></a><!-- doxytag: member="TTWebController::modelDidStartLoad:" ref="a5df22439eaf4f407a261ad79c03f55c4" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidStartLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a68a9663728353e79b48867bbda192d3a"></a><!-- doxytag: member="TTWebController::modelDidFinishLoad:" ref="a68a9663728353e79b48867bbda192d3a" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidFinishLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1d09bbb97be34017532f5705bac1aab0"></a><!-- doxytag: member="TTWebController::model:didFailLoadWithError:" ref="a1d09bbb97be34017532f5705bac1aab0" args="(id&lt; TTModel &gt; model,[didFailLoadWithError] NSError *error)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didFailLoadWithError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0c05ffe2a2e74cea34275819610b3940"></a><!-- doxytag: member="TTWebController::modelDidCancelLoad:" ref="a0c05ffe2a2e74cea34275819610b3940" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidCancelLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a2f3a9659380ba388b9a475d6761e5143">modelDidChange:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model has changed in some fundamental way.  <a href="#a2f3a9659380ba388b9a475d6761e5143"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af16cbcde168b818c04e8f97983ccb435"></a><!-- doxytag: member="TTWebController::model:didUpdateObject:atIndexPath:" ref="af16cbcde168b818c04e8f97983ccb435" args="(id&lt; TTModel &gt; model,[didUpdateObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didUpdateObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae897d061f4b78ef523cb179bcbe498c3"></a><!-- doxytag: member="TTWebController::model:didInsertObject:atIndexPath:" ref="ae897d061f4b78ef523cb179bcbe498c3" args="(id&lt; TTModel &gt; model,[didInsertObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didInsertObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2f4f7858bd3ab9e36b4c54594f09e47e"></a><!-- doxytag: member="TTWebController::model:didDeleteObject:atIndexPath:" ref="a2f4f7858bd3ab9e36b4c54594f09e47e" args="(id&lt; TTModel &gt; model,[didDeleteObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didDeleteObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a58855366f525d711b76767007d99fd43">modelDidBeginUpdates:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model is about to begin a multi-stage update.  <a href="#a58855366f525d711b76767007d99fd43"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a3aa2a5802f68a87df0605342d8b4ca7a">modelDidEndUpdates:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model has completed a multi-stage update.  <a href="#a3aa2a5802f68a87df0605342d8b4ca7a"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">+ <a class="el" href="interface_t_t_view_controller.php#a0e5fe2b34de8a02a7f3f0dccd5156958">doGarbageCollection</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Forcefully initiates garbage collection.  <a href="#a0e5fe2b34de8a02a7f3f0dccd5156958"></a><br/></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8991c689f9a9faadd9714c6ae36a5af2"></a><!-- doxytag: member="TTWebController::_webView" ref="a8991c689f9a9faadd9714c6ae36a5af2" args="" -->
<a class="el" href="class_u_i_web_view.php">UIWebView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_webView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac8265d2481b73da259cc8480516eb955"></a><!-- doxytag: member="TTWebController::_toolbar" ref="ac8265d2481b73da259cc8480516eb955" args="" -->
<a class="el" href="class_u_i_toolbar.php">UIToolbar</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_toolbar</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a919979c9abf8245b3584b34ea24ac4f8"></a><!-- doxytag: member="TTWebController::_headerView" ref="a919979c9abf8245b3584b34ea24ac4f8" args="" -->
<a class="el" href="class_u_i_view.php">UIView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_headerView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa0e326409462ca344dadfdb75c304fb2"></a><!-- doxytag: member="TTWebController::_backButton" ref="aa0e326409462ca344dadfdb75c304fb2" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_backButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1c712da222aa88f25f22c131f94fcf00"></a><!-- doxytag: member="TTWebController::_forwardButton" ref="a1c712da222aa88f25f22c131f94fcf00" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_forwardButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a207235a519a83ce451983f028aedda26"></a><!-- doxytag: member="TTWebController::_refreshButton" ref="a207235a519a83ce451983f028aedda26" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_refreshButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad6fd98522e7781422dd7106483f1d80c"></a><!-- doxytag: member="TTWebController::_stopButton" ref="ad6fd98522e7781422dd7106483f1d80c" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_stopButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adda7f193f56b6d78299582db5813e856"></a><!-- doxytag: member="TTWebController::_actionButton" ref="adda7f193f56b6d78299582db5813e856" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_actionButton</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66170174e8180621d4be7fe0958fad8b"></a><!-- doxytag: member="TTWebController::_activityItem" ref="a66170174e8180621d4be7fe0958fad8b" args="" -->
UIBarButtonItem *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_activityItem</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2e9ce7dcedd6974e7c0c86ae6ebf8fe1"></a><!-- doxytag: member="TTWebController::_loadingURL" ref="a2e9ce7dcedd6974e7c0c86ae6ebf8fe1" args="" -->
NSURL *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_loadingURL</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a41832e4fd9f5b73a5c15d5bbee29ad54"></a><!-- doxytag: member="TTWebController::_actionSheet" ref="a41832e4fd9f5b73a5c15d5bbee29ad54" args="" -->
UIActionSheet *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_actionSheet</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa43364bb00cab333fb3913c058a35f9e"></a><!-- doxytag: member="TTWebController::_delegate" ref="aa43364bb00cab333fb3913c058a35f9e" args="" -->
id&lt; <a class="el" href="protocol_t_t_web_controller_delegate-p.php">TTWebControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_delegate</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1d409c9cfc0a5411003dfe628338cce"></a><!-- doxytag: member="TTWebController::_model" ref="ac1d409c9cfc0a5411003dfe628338cce" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>_model</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab9291afe449c5fe8ebe3325e13a86fef"></a><!-- doxytag: member="TTWebController::_modelError" ref="ab9291afe449c5fe8ebe3325e13a86fef" args="" -->
NSError *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_modelError</b></td></tr>
<tr><td class="memItemLeft" ><a class="anchor" id="aba625f6b2705037c47cd76f7af8f1dfc"></a><!-- doxytag: member="TTWebController::_flags" ref="aba625f6b2705037c47cd76f7af8f1dfc" args="" -->
struct {</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidRefreshInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelWillLoadInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidLoadInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidLoadFirstTimeInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isModelDidShowFirstTimeInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isViewInvalid</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isViewSuspended</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isUpdatingView</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingEmpty</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingLoading</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingModel</b>:1</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;unsigned int&nbsp;&nbsp;&nbsp;<b>isShowingError</b>:1</td></tr>
<tr><td class="memItemLeft" valign="top">}&nbsp;</td><td class="memItemRight" valign="bottom"><b>_flags</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a62bac03420a9ca3fe201915f64c710df"></a><!-- doxytag: member="TTWebController::_searchController" ref="a62bac03420a9ca3fe201915f64c710df" args="" -->
<a class="el" href="interface_t_t_search_display_controller.php">TTSearchDisplayController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_searchController</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af73a75af4a8540e9a0824dfde0ff7ba9"></a><!-- doxytag: member="TTWebController::_frozenState" ref="af73a75af4a8540e9a0824dfde0ff7ba9" args="" -->
<a class="el" href="class_n_s_dictionary.php">NSDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_frozenState</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a043ebeb2719175e6b4fd09ff8e6dc7eb"></a><!-- doxytag: member="TTWebController::_navigationBarStyle" ref="a043ebeb2719175e6b4fd09ff8e6dc7eb" args="" -->
UIBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>_navigationBarStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9539b16b96e55313d37a24a517d91aa1"></a><!-- doxytag: member="TTWebController::_navigationBarTintColor" ref="a9539b16b96e55313d37a24a517d91aa1" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_navigationBarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9ba256d9d10c48e1f20b5ec266186452"></a><!-- doxytag: member="TTWebController::_statusBarStyle" ref="a9ba256d9d10c48e1f20b5ec266186452" args="" -->
UIStatusBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>_statusBarStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a92713568320087178a7ec813edd761fa"></a><!-- doxytag: member="TTWebController::_isViewAppearing" ref="a92713568320087178a7ec813edd761fa" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_isViewAppearing</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a78f0448e948f1157cf6ba0a2d2f21d59"></a><!-- doxytag: member="TTWebController::_hasViewAppeared" ref="a78f0448e948f1157cf6ba0a2d2f21d59" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_hasViewAppeared</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6d7348edcd90eb5573452996da10b0c8"></a><!-- doxytag: member="TTWebController::_autoresizesForKeyboard" ref="a6d7348edcd90eb5573452996da10b0c8" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_autoresizesForKeyboard</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">NSURL *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_web_controller.php#a30b8fa744369bcd1066fb6a386e775ef">URL</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The current web view URL.  <a href="#a30b8fa744369bcd1066fb6a386e775ef"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7da4748d4f6ac4591ac171b77954f3a6"></a><!-- doxytag: member="TTWebController::headerView" ref="a7da4748d4f6ac4591ac171b77954f3a6" args="" -->
<a class="el" href="class_u_i_view.php">UIView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_web_controller.php#a7da4748d4f6ac4591ac171b77954f3a6">headerView</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">A view that is inserted at the top of the web view, within the scroller. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab9a2dd7b03546df421e5dcae2e094799"></a><!-- doxytag: member="TTWebController::delegate" ref="ab9a2dd7b03546df421e5dcae2e094799" args="" -->
id&lt; <a class="el" href="protocol_t_t_web_controller_delegate-p.php">TTWebControllerDelegate</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_web_controller.php#ab9a2dd7b03546df421e5dcae2e094799">delegate</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The web controller delegate, currently does nothing. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a61f1378a65641be5991cfb07d7f894e5"></a><!-- doxytag: member="TTWebController::model" ref="a61f1378a65641be5991cfb07d7f894e5" args="" -->
id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><b>model</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abf74cd2086bd97dfa34f6e250598bd8f"></a><!-- doxytag: member="TTWebController::modelError" ref="abf74cd2086bd97dfa34f6e250598bd8f" args="" -->
NSError *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_model_view_controller.php#abf74cd2086bd97dfa34f6e250598bd8f">modelError</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">An error that occurred while trying to load content. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="interface_t_t_table_view_controller.php">TTTableViewController</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_view_controller.php#aee5cb350b30e5feefffd3f118df21f86">searchViewController</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">A view controller used to display the contents of the search display controller.  <a href="#aee5cb350b30e5feefffd3f118df21f86"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">UIBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a0d8ab3d6c6b655258293c2df842d161b">navigationBarStyle</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The style of the navigation bar when this view controller is pushed onto a navigation controller.  <a href="#a0d8ab3d6c6b655258293c2df842d161b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#af9f360ea82a7008a4cdb785765ca368d">navigationBarTintColor</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The color of the navigation bar when this view controller is pushed onto a navigation controller.  <a href="#af9f360ea82a7008a4cdb785765ca368d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">UIStatusBarStyle&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a9fbdc64e7c1d0e33c6e5c18c637484f7">statusBarStyle</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The style of the status bar when this view controller is appearing.  <a href="#a9fbdc64e7c1d0e33c6e5c18c637484f7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aba404e0d3d915055ce87f45191c2be8d"></a><!-- doxytag: member="TTWebController::hasViewAppeared" ref="aba404e0d3d915055ce87f45191c2be8d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#aba404e0d3d915055ce87f45191c2be8d">hasViewAppeared</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The view has appeared at least once and hasn't been removed due to a memory warning. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afeb4bf49b4efd4199f03e32dc793c87d"></a><!-- doxytag: member="TTWebController::isViewAppearing" ref="afeb4bf49b4efd4199f03e32dc793c87d" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#afeb4bf49b4efd4199f03e32dc793c87d">isViewAppearing</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The view is about to appear and has not appeared yet. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9c53a69ddcc3e4d4f8eef61d51d98c75"></a><!-- doxytag: member="TTWebController::autoresizesForKeyboard" ref="a9c53a69ddcc3e4d4f8eef61d51d98c75" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_base_view_controller.php#a9c53a69ddcc3e4d4f8eef61d51d98c75">autoresizesForKeyboard</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Determines if the view will be resized automatically to fit the keyboard. <br/></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a96f3ef31d4df7409e44a740ced1d91f4"></a><!-- doxytag: member="TTWebController::beginUpdates" ref="a96f3ef31d4df7409e44a740ced1d91f4" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) beginUpdates </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Begins a multi-stage update. </p>
<p>You can call this method to make complicated updates more efficient, and to condense multiple changes to your model into a single visual change. Call endUpdate when you are done to update the view with all of your changes. </p>

</div>
</div>
<a class="anchor" id="a1648848389e0e716f42cbab7ba1bad94"></a><!-- doxytag: member="TTWebController::canShowModel" ref="a1648848389e0e716f42cbab7ba1bad94" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) canShowModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Tests if it is possible to show the model. </p>
<p>After a model has loaded, this method is called to test whether or not to set the model has content that can be shown. If you return NO, showEmpty: will be called, and if you return YES, showModel: will be called. </p>

</div>
</div>
<a class="anchor" id="a358624f7a1dd93c7ae7d627d76a83505"></a><!-- doxytag: member="TTWebController::didLoadModel:" ref="a358624f7a1dd93c7ae7d627d76a83505" args="(BOOL firstTime)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didLoadModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>firstTime</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called after the model has loaded, just before it is to be displayed. </p>
<p>This is not called until after the view has loaded. If your model finishes loading before the view is loaded, this will still be called, but not until after the view is loaded.</p>
<p>If you refresh a model which is already loaded, this will be called, but the firstTime argument will be false.</p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="adc98dbd9f50022bef4c3b27a05744fc7"></a><!-- doxytag: member="TTWebController::didRefreshModel" ref="adc98dbd9f50022bef4c3b27a05744fc7" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didRefreshModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called when the model is refreshed. </p>
<p>Subclasses should override this function update parts of the view that may need to changed when there is a new model, or something about the existing model changes. </p>

</div>
</div>
<a class="anchor" id="a23aecc1df4ed6e754be83644b8b3e7a4"></a><!-- doxytag: member="TTWebController::didShowModel:" ref="a23aecc1df4ed6e754be83644b8b3e7a4" args="(BOOL firstTime)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) didShowModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>firstTime</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called just after a model has been loaded and displayed. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a0e5fe2b34de8a02a7f3f0dccd5156958"></a><!-- doxytag: member="TTWebController::doGarbageCollection" ref="a0e5fe2b34de8a02a7f3f0dccd5156958" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">+ (void) doGarbageCollection </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Forcefully initiates garbage collection. </p>
<p>You may call this in your didReceiveMemoryWarning message if you are worried about garbage collection memory consumption.</p>
<p>See Articles/UI/GarbageCollection.mdown for a more detailed discussion. </p>

</div>
</div>
<a class="anchor" id="a54488637f89a309a5de88123257b73bc"></a><!-- doxytag: member="TTWebController::endUpdates" ref="a54488637f89a309a5de88123257b73bc" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) endUpdates </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Ends a multi-stage model update and updates the view to reflect the model. </p>
<p>You can call this method to make complicated updates more efficient, and to condense multiple changes to your model into a single visual change. </p>

</div>
</div>
<a class="anchor" id="a58855366f525d711b76767007d99fd43"></a><!-- doxytag: member="TTWebController::modelDidBeginUpdates:" ref="a58855366f525d711b76767007d99fd43" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidBeginUpdates: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model is about to begin a multi-stage update. </p>
<p>Models should use this method to condense multiple updates into a single visible update. This avoids having the view update multiple times for each change. Instead, the user will only see the end result of all of your changes when you call modelDidEndUpdates. </p>

</div>
</div>
<a class="anchor" id="a2f3a9659380ba388b9a475d6761e5143"></a><!-- doxytag: member="TTWebController::modelDidChange:" ref="a2f3a9659380ba388b9a475d6761e5143" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidChange: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model has changed in some fundamental way. </p>
<p>The change is not described specifically, so the delegate must assume that the entire contents of the model may have changed, and react almost as if it was given a new model. </p>

</div>
</div>
<a class="anchor" id="a3aa2a5802f68a87df0605342d8b4ca7a"></a><!-- doxytag: member="TTWebController::modelDidEndUpdates:" ref="a3aa2a5802f68a87df0605342d8b4ca7a" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidEndUpdates: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model has completed a multi-stage update. </p>
<p>The exact nature of the change is not specified, so the receiver should investigate the new state of the model by examining its properties. </p>

</div>
</div>
<a class="anchor" id="a073bb22ae4eae4ca6b68e895c0a16518"></a><!-- doxytag: member="TTWebController::openRequest:" ref="a073bb22ae4eae4ca6b68e895c0a16518" args="(NSURLRequest *request)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) openRequest: </td>
          <td></td>
          <td class="paramtype">(NSURLRequest*)&nbsp;</td>
          <td class="paramname"> <em>request</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Load the given request using UIWebView's loadRequest:. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>request</em>&nbsp;</td><td>A URL request identifying the location of the content to load. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a11f547cd237948cb6592bdc2bd093ff6"></a><!-- doxytag: member="TTWebController::shouldLoad" ref="a11f547cd237948cb6592bdc2bd093ff6" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldLoad </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that data should be loaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="a991de3bff712c0261cb54ec6a2056e63"></a><!-- doxytag: member="TTWebController::shouldLoadMore" ref="a991de3bff712c0261cb54ec6a2056e63" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldLoadMore </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that more data should be loaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="ac04eb12ba87d7abd890f7276fda9f223"></a><!-- doxytag: member="TTWebController::shouldReload" ref="ac04eb12ba87d7abd890f7276fda9f223" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) shouldReload </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates that data should be reloaded from the model. </p>
<p>Do not call this directly. Subclasses should implement this method. </p>

</div>
</div>
<a class="anchor" id="aaba45ca7762b8a5ed4e38c066dc46519"></a><!-- doxytag: member="TTWebController::showEmpty:" ref="aaba45ca7762b8a5ed4e38c066dc46519" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showEmpty: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent an empty model. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a0041c889ed5b9c98a76d824a92436a07"></a><!-- doxytag: member="TTWebController::showLoading:" ref="a0041c889ed5b9c98a76d824a92436a07" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showLoading: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent the model loading. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="adb70f1b36491c7320769b40e9ffbdff9"></a><!-- doxytag: member="TTWebController::showModel:" ref="adb70f1b36491c7320769b40e9ffbdff9" args="(BOOL show)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) showModel: </td>
          <td></td>
          <td class="paramtype">(BOOL)&nbsp;</td>
          <td class="paramname"> <em>show</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Shows views to represent the loaded model's content. </p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<a class="anchor" id="a4efdc6eedf94241adda63d4d1aca36b9"></a><!-- doxytag: member="TTWebController::willLoadModel" ref="a4efdc6eedf94241adda63d4d1aca36b9" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) willLoadModel </td>
          <td></td>
          <td class="paramname"></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Called before the model is asked to load itself. </p>
<p>This is not called until after the view has loaded. If your model starts loading before the view is loaded, this will still be called, but not until after the view is loaded.</p>
<p>The default implementation of this method does nothing. Subclasses may override this method to take an appropriate action. </p>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="a0d8ab3d6c6b655258293c2df842d161b"></a><!-- doxytag: member="TTWebController::navigationBarStyle" ref="a0d8ab3d6c6b655258293c2df842d161b" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (UIBarStyle) navigationBarStyle<code> [read, write, assign, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The style of the navigation bar when this view controller is pushed onto a navigation controller. </p>
<p>UIBarStyleDefault </p>

</div>
</div>
<a class="anchor" id="af9f360ea82a7008a4cdb785765ca368d"></a><!-- doxytag: member="TTWebController::navigationBarTintColor" ref="af9f360ea82a7008a4cdb785765ca368d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_u_i_color.php">UIColor</a>*) navigationBarTintColor<code> [read, write, retain, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The color of the navigation bar when this view controller is pushed onto a navigation controller. </p>
<p>TTSTYLEVAR(navigationBarTintColor) </p>

</div>
</div>
<a class="anchor" id="aee5cb350b30e5feefffd3f118df21f86"></a><!-- doxytag: member="TTWebController::searchViewController" ref="aee5cb350b30e5feefffd3f118df21f86" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="interface_t_t_table_view_controller.php">TTTableViewController</a> *) searchViewController<code> [read, write, retain, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>A view controller used to display the contents of the search display controller. </p>
<p>If you assign a view controller to this property, it will automatically create a search display controller which you can access through this view controller's searchDisplaController property. You can then take the searchBar from that controller and add it to your views. The search bar will then search the data source of the view controller that you assigned here. </p>

</div>
</div>
<a class="anchor" id="a9fbdc64e7c1d0e33c6e5c18c637484f7"></a><!-- doxytag: member="TTWebController::statusBarStyle" ref="a9fbdc64e7c1d0e33c6e5c18c637484f7" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (UIStatusBarStyle) statusBarStyle<code> [read, write, assign, inherited]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The style of the status bar when this view controller is appearing. </p>
<p>UIStatusBarStyleDefault </p>

</div>
</div>
<a class="anchor" id="a30b8fa744369bcd1066fb6a386e775ef"></a><!-- doxytag: member="TTWebController::URL" ref="a30b8fa744369bcd1066fb6a386e775ef" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (NSURL *) URL<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>The current web view URL. </p>
<p>If the web view is currently loading a URL, then the loading URL is returned instead. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_web_controller_8h_source.php">TTWebController.h</a></li>
<li>Three20UI/Sources/TTWebController.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
