<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTRequestLoader Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://dev.three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fdev.three20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTRequestLoader Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTRequestLoader" --><!-- doxytag: inherits="NSObject" -->
<p>The loader manages a set of TTURLRequests and makes the necessary callbacks for each.  
<a href="#_details">More...</a></p>

<p><code>#import &lt;<a class="el" href="_t_t_request_loader_8h_source.php">TTRequestLoader.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for TTRequestLoader:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_request_loader.png" usemap="#TTRequestLoader_map" alt=""/>
  <map id="TTRequestLoader_map" name="TTRequestLoader_map">
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,110,24"/>
</map>
</div>

<p><a href="class_t_t_request_loader-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae198412b81cf9c9e6e69ab0907732e96"></a><!-- doxytag: member="TTRequestLoader::initForRequest:queue:" ref="ae198412b81cf9c9e6e69ab0907732e96" args="(TTURLRequest *request,[queue] TTURLRequestQueue *queue)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initForRequest:queue:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a80e53e7e043439a4318efaaf0041923e"></a><!-- doxytag: member="TTRequestLoader::addRequest:" ref="a80e53e7e043439a4318efaaf0041923e" args="(TTURLRequest *request)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_request_loader.php#a80e53e7e043439a4318efaaf0041923e">addRequest:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Duplication is possible due to the use of an <a class="el" href="class_n_s_array.php" title="Additions.">NSArray</a> for the request list. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab39ce0ed071430e83044272faf2d5e75"></a><!-- doxytag: member="TTRequestLoader::removeRequest:" ref="ab39ce0ed071430e83044272faf2d5e75" args="(TTURLRequest *request)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>removeRequest:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab0adf69252f9b71af69549ccf12caf5e"></a><!-- doxytag: member="TTRequestLoader::load:" ref="ab0adf69252f9b71af69549ccf12caf5e" args="(NSURL *URL)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_request_loader.php#ab0adf69252f9b71af69549ccf12caf5e">load:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">If the loader isn't already active, create the NSURLRequest from the first <a class="el" href="interface_t_t_u_r_l_request.php" title="The Three20 network request object, built to work with the Three20 cache and co.">TTURLRequest</a> added to this loader and fire it off. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_request_loader.php#af55154b4f51bcf3da52d955fd8e850c3">loadSynchronously:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">As with load:, will create the NSURLRequest from the first <a class="el" href="interface_t_t_u_r_l_request.php" title="The Three20 network request object, built to work with the Three20 cache and co.">TTURLRequest</a> added to the loader.  <a href="#af55154b4f51bcf3da52d955fd8e850c3"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="interface_t_t_request_loader.php#a41f21a57f28ebf81b3ce99343c5e8ea7">cancel:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Cancel only the given request.  <a href="#a41f21a57f28ebf81b3ce99343c5e8ea7"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7d62026b7741e6cc455be0f41b0cbe0e"></a><!-- doxytag: member="TTRequestLoader::processResponse:data:" ref="a7d62026b7741e6cc455be0f41b0cbe0e" args="(NSHTTPURLResponse *response,[data] id data)" -->
(NSError *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>processResponse:data:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a05e78b3b1d4daaf52d90815522694e6d"></a><!-- doxytag: member="TTRequestLoader::dispatchError:" ref="a05e78b3b1d4daaf52d90815522694e6d" args="(NSError *error)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>dispatchError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a633cc4273bc6cced2ad9b2fe199fcfbe"></a><!-- doxytag: member="TTRequestLoader::dispatchLoaded:" ref="a633cc4273bc6cced2ad9b2fe199fcfbe" args="(NSDate *timestamp)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>dispatchLoaded:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aaabb091bee67560a446913907a10b3bc"></a><!-- doxytag: member="TTRequestLoader::dispatchAuthenticationChallenge:" ref="aaabb091bee67560a446913907a10b3bc" args="(NSURLAuthenticationChallenge *challenge)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>dispatchAuthenticationChallenge:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca8cfb6761c2cea8a7eaea6856e71078"></a><!-- doxytag: member="TTRequestLoader::cancel" ref="aca8cfb6761c2cea8a7eaea6856e71078" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>cancel</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9dc73dcc8253d316ed439b9ca835b02b"></a><!-- doxytag: member="TTRequestLoader::_urlPath" ref="a9dc73dcc8253d316ed439b9ca835b02b" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_urlPath</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1fb37e3cf1f42c549e5c9f9a93d43037"></a><!-- doxytag: member="TTRequestLoader::_queue" ref="a1fb37e3cf1f42c549e5c9f9a93d43037" args="" -->
<a class="el" href="interface_t_t_u_r_l_request_queue.php">TTURLRequestQueue</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_queue</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afe54139bf5ac295a52bc96eb1bcbb4f2"></a><!-- doxytag: member="TTRequestLoader::_cacheKey" ref="afe54139bf5ac295a52bc96eb1bcbb4f2" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cacheKey</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1e2e153e0a7301f4398332805c42640"></a><!-- doxytag: member="TTRequestLoader::_cachePolicy" ref="ac1e2e153e0a7301f4398332805c42640" args="" -->
TTURLRequestCachePolicy&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cachePolicy</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a27933e0a7643823aa4b2febbb10aa261"></a><!-- doxytag: member="TTRequestLoader::_cacheExpirationAge" ref="a27933e0a7643823aa4b2febbb10aa261" args="" -->
NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><b>_cacheExpirationAge</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a26ff4b3e97d7a628fd9b60d42a1e2457"></a><!-- doxytag: member="TTRequestLoader::_requests" ref="a26ff4b3e97d7a628fd9b60d42a1e2457" args="" -->
<a class="el" href="class_n_s_mutable_array.php">NSMutableArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_requests</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a747cba731991cd96b30fe8405395be7f"></a><!-- doxytag: member="TTRequestLoader::_connection" ref="a747cba731991cd96b30fe8405395be7f" args="" -->
NSURLConnection *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_connection</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1986bd1ebaa7c4e69c9ca533f36a23c3"></a><!-- doxytag: member="TTRequestLoader::_response" ref="a1986bd1ebaa7c4e69c9ca533f36a23c3" args="" -->
NSHTTPURLResponse *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_response</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af5dde8ebaa5fa38c73b7515839dbbacc"></a><!-- doxytag: member="TTRequestLoader::_responseData" ref="af5dde8ebaa5fa38c73b7515839dbbacc" args="" -->
NSMutableData *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_responseData</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1cc65bcca993cbe5e3c1f5657185cc9d"></a><!-- doxytag: member="TTRequestLoader::_retriesLeft" ref="a1cc65bcca993cbe5e3c1f5657185cc9d" args="" -->
int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#a1cc65bcca993cbe5e3c1f5657185cc9d">_retriesLeft</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">When load requests fail we'll attempt the request again, as many as 2 times by default. <br/></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a812d3c16cac62020a431ac4e46853041"></a><!-- doxytag: member="TTRequestLoader::requests" ref="a812d3c16cac62020a431ac4e46853041" args="" -->
<a class="el" href="class_n_s_array.php">NSArray</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#a812d3c16cac62020a431ac4e46853041">requests</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The list of TTURLRequests currently attached to this loader. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae05ab957f8610bdf6d8dc6c55561cf18"></a><!-- doxytag: member="TTRequestLoader::urlPath" ref="ae05ab957f8610bdf6d8dc6c55561cf18" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#ae05ab957f8610bdf6d8dc6c55561cf18">urlPath</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The common urlPath shared by every request. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afc70c6b8ef860ee13fef091dae10ca41"></a><!-- doxytag: member="TTRequestLoader::cacheKey" ref="afc70c6b8ef860ee13fef091dae10ca41" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#afc70c6b8ef860ee13fef091dae10ca41">cacheKey</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The common cacheKey shared by every request. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a73a04e9934fd4e34b369c60c31578227"></a><!-- doxytag: member="TTRequestLoader::cachePolicy" ref="a73a04e9934fd4e34b369c60c31578227" args="" -->
TTURLRequestCachePolicy&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#a73a04e9934fd4e34b369c60c31578227">cachePolicy</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The common cache policy shared by every request. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a91e393e0d058d3a789e3d782bbd02357"></a><!-- doxytag: member="TTRequestLoader::cacheExpirationAge" ref="a91e393e0d058d3a789e3d782bbd02357" args="" -->
NSTimeInterval&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#a91e393e0d058d3a789e3d782bbd02357">cacheExpirationAge</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">The common cache expiration age shared by ever request. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a26e45bc2d7677cfbae03d6a20905f78a"></a><!-- doxytag: member="TTRequestLoader::isLoading" ref="a26e45bc2d7677cfbae03d6a20905f78a" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#a26e45bc2d7677cfbae03d6a20905f78a">isLoading</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Whether or not any of the requests in this loader are loading. <br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_n_s_string.php">NSString</a> *URL&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_t_t_request_loader.php#aec8806d4912142a8fef5a28e8be5c089">__TTDEPRECATED_METHOD</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Deprecated due to name ambiguity.  <a href="#aec8806d4912142a8fef5a28e8be5c089"></a><br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>The loader manages a set of TTURLRequests and makes the necessary callbacks for each. </p>
<p>It implements the NSURLConnectionDelegate protocol and calls the required operations on the queue as the protocol methods are invoked.</p>
<p>NSURLErrorCannotFindHost errors are retried at least twice before completely giving up.</p>
<p>The loader collects identical GET TTURLRequests into a single object. This logic is handled in TTURLRequestQueue's sendRequest. For all other <a class="el" href="interface_t_t_u_r_l_request.php" title="The Three20 network request object, built to work with the Three20 cache and co.">TTURLRequest</a> types, they will each have their own loader. </p>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a41f21a57f28ebf81b3ce99343c5e8ea7"></a><!-- doxytag: member="TTRequestLoader::cancel:" ref="a41f21a57f28ebf81b3ce99343c5e8ea7" args="(TTURLRequest *request)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (BOOL) cancel: </td>
          <td></td>
          <td class="paramtype">(<a class="el" href="interface_t_t_u_r_l_request.php">TTURLRequest</a>*)&nbsp;</td>
          <td class="paramname"> <em>request</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Cancel only the given request. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>NO If there are no requests left. YES If there are any requests left. </dd></dl>

</div>
</div>
<a class="anchor" id="af55154b4f51bcf3da52d955fd8e850c3"></a><!-- doxytag: member="TTRequestLoader::loadSynchronously:" ref="af55154b4f51bcf3da52d955fd8e850c3" args="(NSURL *URL)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) loadSynchronously: </td>
          <td></td>
          <td class="paramtype">(NSURL*)&nbsp;</td>
          <td class="paramname"> <em>URL</em></td>
          <td>&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>As with load:, will create the NSURLRequest from the first <a class="el" href="interface_t_t_u_r_l_request.php" title="The Three20 network request object, built to work with the Three20 cache and co.">TTURLRequest</a> added to the loader. </p>
<p>Unlike load:, this method will not return until the request has been fully completed.</p>
<p>This is useful for threads that need to block while waiting for resources from the net. </p>

</div>
</div>
<hr/><h2>Property Documentation</h2>
<a class="anchor" id="aec8806d4912142a8fef5a28e8be5c089"></a><!-- doxytag: member="TTRequestLoader::__TTDEPRECATED_METHOD" ref="aec8806d4912142a8fef5a28e8be5c089" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (<a class="el" href="class_n_s_string.php">NSString</a>* URL) __TTDEPRECATED_METHOD<code> [read, assign]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Deprecated due to name ambiguity. </p>
<p>Use urlPath instead. Remove after May 6, 2010. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Network/Headers/<a class="el" href="_t_t_request_loader_8h_source.php">TTRequestLoader.h</a></li>
<li>Three20Network/Sources/TTRequestLoader.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
