<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTDefaultStyleSheet Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTDefaultStyleSheet Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTDefaultStyleSheet" --><!-- doxytag: inherits="TTStyleSheet" --><div class="dynheader">
Inheritance diagram for TTDefaultStyleSheet:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_default_style_sheet.png" usemap="#TTDefaultStyleSheet_map" alt=""/>
  <map id="TTDefaultStyleSheet_map" name="TTDefaultStyleSheet_map">
<area href="interface_t_t_style_sheet.php" alt="TTStyleSheet" shape="rect" coords="0,56,151,80"/>
<area href="class_n_s_object.php" alt="NSObject" shape="rect" coords="0,0,151,24"/>
<area href="interface_t_t_default_c_s_s_style_sheet.php" alt="TTDefaultCSSStyleSheet" shape="rect" coords="0,168,151,192"/>
</map>
</div>

<p><a href="class_t_t_default_style_sheet-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a161443a42a5b7bf76f0669ea37f7722d"></a><!-- doxytag: member="TTDefaultStyleSheet::selectionFillStyle:" ref="a161443a42a5b7bf76f0669ea37f7722d" args="(TTStyle *next)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>selectionFillStyle:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac8393bd8448d06123d09fbdac74df4dc"></a><!-- doxytag: member="TTDefaultStyleSheet::toolbarButtonForState:shape:tintColor:font:" ref="ac8393bd8448d06123d09fbdac74df4dc" args="(UIControlState state,[shape] TTShape *shape,[tintColor] UIColor *tintColor,[font] UIFont *font)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>toolbarButtonForState:shape:tintColor:font:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a08a8dcc0c459c9d453c12897df4d8586"></a><!-- doxytag: member="TTDefaultStyleSheet::pageDotWithColor:" ref="a08a8dcc0c459c9d453c12897df4d8586" args="(UIColor *color)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>pageDotWithColor:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4c91256af880ce80796ba67f366896ea"></a><!-- doxytag: member="TTDefaultStyleSheet::styleWithSelector:" ref="a4c91256af880ce80796ba67f366896ea" args="(NSString *selector)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>styleWithSelector:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a944da18158918ed45f51fb75b9c15a5f"></a><!-- doxytag: member="TTDefaultStyleSheet::styleWithSelector:forState:" ref="a944da18158918ed45f51fb75b9c15a5f" args="(NSString *selector,[forState] UIControlState state)" -->
(<a class="el" href="interface_t_t_style.php">TTStyle</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>styleWithSelector:forState:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5d679bdf2168819e073a0cce68e4c961"></a><!-- doxytag: member="TTDefaultStyleSheet::freeMemory" ref="a5d679bdf2168819e073a0cce68e4c961" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>freeMemory</b></td></tr>
<tr><td colspan="2"><h2><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa2c7922d423e9863646ee104289f0e15"></a><!-- doxytag: member="TTDefaultStyleSheet::globalStyleSheet" ref="aa2c7922d423e9863646ee104289f0e15" args="()" -->
(<a class="el" href="interface_t_t_style_sheet.php">TTStyleSheet</a> *)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>globalStyleSheet</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a39335a19e323c16c27e96f50e6c267be"></a><!-- doxytag: member="TTDefaultStyleSheet::setGlobalStyleSheet:" ref="a39335a19e323c16c27e96f50e6c267be" args="(TTStyleSheet *styleSheet)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">+ <b>setGlobalStyleSheet:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aea250de8617f56f00d8a401480df3a90"></a><!-- doxytag: member="TTDefaultStyleSheet::_styles" ref="aea250de8617f56f00d8a401480df3a90" args="" -->
<a class="el" href="class_n_s_mutable_dictionary.php">NSMutableDictionary</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_styles</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1e8b153381e84d59d7fcf2f43a3305c4"></a><!-- doxytag: member="TTDefaultStyleSheet::textColor" ref="a1e8b153381e84d59d7fcf2f43a3305c4" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>textColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aec1d1d4cd85648821727c87741d1099b"></a><!-- doxytag: member="TTDefaultStyleSheet::highlightedTextColor" ref="aec1d1d4cd85648821727c87741d1099b" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>highlightedTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6260ce5a19569f4f62374001b38be3c6"></a><!-- doxytag: member="TTDefaultStyleSheet::font" ref="a6260ce5a19569f4f62374001b38be3c6" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81df455d30b17e4b9a847161c44e7c56"></a><!-- doxytag: member="TTDefaultStyleSheet::backgroundColor" ref="a81df455d30b17e4b9a847161c44e7c56" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>backgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a31c011aa2f5a195abf37fba2b970ec7d"></a><!-- doxytag: member="TTDefaultStyleSheet::navigationBarTintColor" ref="a31c011aa2f5a195abf37fba2b970ec7d" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>navigationBarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3e0763d283d4e2054d5e6b5feb599caf"></a><!-- doxytag: member="TTDefaultStyleSheet::toolbarTintColor" ref="a3e0763d283d4e2054d5e6b5feb599caf" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>toolbarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aeeed75c6978504a748e09d35978eed38"></a><!-- doxytag: member="TTDefaultStyleSheet::searchBarTintColor" ref="aeeed75c6978504a748e09d35978eed38" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>searchBarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adef7cf4611a4d654cd06e68bd7908979"></a><!-- doxytag: member="TTDefaultStyleSheet::tablePlainBackgroundColor" ref="adef7cf4611a4d654cd06e68bd7908979" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tablePlainBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af31ec90f9a54f1913a2eeb36a237e15a"></a><!-- doxytag: member="TTDefaultStyleSheet::tableGroupedBackgroundColor" ref="af31ec90f9a54f1913a2eeb36a237e15a" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableGroupedBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a08c8c68eacbf0bf2578cf72d646c7b86"></a><!-- doxytag: member="TTDefaultStyleSheet::searchTableBackgroundColor" ref="a08c8c68eacbf0bf2578cf72d646c7b86" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>searchTableBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a963b957ac7c843a65b6d5ff07d194e5c"></a><!-- doxytag: member="TTDefaultStyleSheet::searchTableSeparatorColor" ref="a963b957ac7c843a65b6d5ff07d194e5c" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>searchTableSeparatorColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1133e99c6adb0ee6afd6687dc320b471"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderTextColor" ref="a1133e99c6adb0ee6afd6687dc320b471" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae56db54831f5808c5075372f94946637"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderShadowColor" ref="ae56db54831f5808c5075372f94946637" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderShadowColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a95885209fbf18f789a07097c696cc814"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderShadowOffset" ref="a95885209fbf18f789a07097c696cc814" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderShadowOffset</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa1da9806ac6a61abc42c22b9c07f972f"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderTintColor" ref="aa1da9806ac6a61abc42c22b9c07f972f" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7c82f8f53f02d82e68e6e37ee0afeb26"></a><!-- doxytag: member="TTDefaultStyleSheet::photoCaptionTextColor" ref="a7c82f8f53f02d82e68e6e37ee0afeb26" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>photoCaptionTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4bd5c478587a1f7bf446893e4ff71ad7"></a><!-- doxytag: member="TTDefaultStyleSheet::photoCaptionTextShadowColor" ref="a4bd5c478587a1f7bf446893e4ff71ad7" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>photoCaptionTextShadowColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad4c7dfa960a4d0cb5422fb07c312a983"></a><!-- doxytag: member="TTDefaultStyleSheet::photoCaptionTextShadowOffset" ref="ad4c7dfa960a4d0cb5422fb07c312a983" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>photoCaptionTextShadowOffset</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afd8862901d55bf463aff4cc23eec7366"></a><!-- doxytag: member="TTDefaultStyleSheet::timestampTextColor" ref="afd8862901d55bf463aff4cc23eec7366" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>timestampTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a83a7294e8ac246d357d6273d4c88d615"></a><!-- doxytag: member="TTDefaultStyleSheet::linkTextColor" ref="a83a7294e8ac246d357d6273d4c88d615" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>linkTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66c00efe2dbd5f5d72686847a524e303"></a><!-- doxytag: member="TTDefaultStyleSheet::moreLinkTextColor" ref="a66c00efe2dbd5f5d72686847a524e303" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>moreLinkTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aab56445cc1951cea1734d9a80f22e387"></a><!-- doxytag: member="TTDefaultStyleSheet::screenBackgroundColor" ref="aab56445cc1951cea1734d9a80f22e387" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>screenBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a26ffdcf80bfd8c9d2714a81fff8014ba"></a><!-- doxytag: member="TTDefaultStyleSheet::tableActivityTextColor" ref="a26ffdcf80bfd8c9d2714a81fff8014ba" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableActivityTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5ada9e5b736f137937435dce696c3076"></a><!-- doxytag: member="TTDefaultStyleSheet::tableErrorTextColor" ref="a5ada9e5b736f137937435dce696c3076" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableErrorTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3e6b4c0c516d023f79332f528221d034"></a><!-- doxytag: member="TTDefaultStyleSheet::tableSubTextColor" ref="a3e6b4c0c516d023f79332f528221d034" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableSubTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abfe663c115552e97dba0247acb3ceedf"></a><!-- doxytag: member="TTDefaultStyleSheet::tableTitleTextColor" ref="abfe663c115552e97dba0247acb3ceedf" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableTitleTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6c9fd041d6e31e2a117f3cd9aeb02513"></a><!-- doxytag: member="TTDefaultStyleSheet::tabTintColor" ref="a6c9fd041d6e31e2a117f3cd9aeb02513" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tabTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab930f69675868175c1d3b6bc5c291ae6"></a><!-- doxytag: member="TTDefaultStyleSheet::tabBarTintColor" ref="ab930f69675868175c1d3b6bc5c291ae6" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tabBarTintColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac3784eefa0d6edbf02bc21c69efee035"></a><!-- doxytag: member="TTDefaultStyleSheet::messageFieldTextColor" ref="ac3784eefa0d6edbf02bc21c69efee035" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>messageFieldTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a00475f6ab616e57be9c289f00d957989"></a><!-- doxytag: member="TTDefaultStyleSheet::messageFieldSeparatorColor" ref="a00475f6ab616e57be9c289f00d957989" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>messageFieldSeparatorColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac75856a15ceb0778ae57a3116a416215"></a><!-- doxytag: member="TTDefaultStyleSheet::thumbnailBackgroundColor" ref="ac75856a15ceb0778ae57a3116a416215" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>thumbnailBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81f0e86a89d899625fb06cfaaf6a7312"></a><!-- doxytag: member="TTDefaultStyleSheet::postButtonColor" ref="a81f0e86a89d899625fb06cfaaf6a7312" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>postButtonColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="abce771c96419749f3a7ad9e5e82c4f67"></a><!-- doxytag: member="TTDefaultStyleSheet::buttonFont" ref="abce771c96419749f3a7ad9e5e82c4f67" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>buttonFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a343ee6d08c2340555aba31397dd08229"></a><!-- doxytag: member="TTDefaultStyleSheet::tableFont" ref="a343ee6d08c2340555aba31397dd08229" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66776104286740c0549a3cb9b8da0b6e"></a><!-- doxytag: member="TTDefaultStyleSheet::tableSmallFont" ref="a66776104286740c0549a3cb9b8da0b6e" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableSmallFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4772d7de1d1d0d4e358f70c12064c85a"></a><!-- doxytag: member="TTDefaultStyleSheet::tableTitleFont" ref="a4772d7de1d1d0d4e358f70c12064c85a" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableTitleFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a725af9e2ac18e73f0d8adaf6345909ea"></a><!-- doxytag: member="TTDefaultStyleSheet::tableTimestampFont" ref="a725af9e2ac18e73f0d8adaf6345909ea" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableTimestampFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a46de4f810b999e552a81cfdc99bd8e60"></a><!-- doxytag: member="TTDefaultStyleSheet::tableButtonFont" ref="a46de4f810b999e552a81cfdc99bd8e60" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableButtonFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afa4bcf74fb3adccfe67cf66510d35166"></a><!-- doxytag: member="TTDefaultStyleSheet::tableSummaryFont" ref="afa4bcf74fb3adccfe67cf66510d35166" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableSummaryFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a90bcefc33aa19b068c9f26ee7f25d1aa"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderPlainFont" ref="a90bcefc33aa19b068c9f26ee7f25d1aa" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderPlainFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a98a3d7bb0dfb54f99f3d4daff5f02713"></a><!-- doxytag: member="TTDefaultStyleSheet::tableHeaderGroupedFont" ref="a98a3d7bb0dfb54f99f3d4daff5f02713" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableHeaderGroupedFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a274b17a18d53d8fd40e01e3276853239"></a><!-- doxytag: member="TTDefaultStyleSheet::tableBannerViewHeight" ref="a274b17a18d53d8fd40e01e3276853239" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableBannerViewHeight</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3bcf19ba6206adf5ce0711f8b5dfdb2b"></a><!-- doxytag: member="TTDefaultStyleSheet::photoCaptionFont" ref="a3bcf19ba6206adf5ce0711f8b5dfdb2b" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>photoCaptionFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae5950524d88a3df056c82b02c4c92b3d"></a><!-- doxytag: member="TTDefaultStyleSheet::messageFont" ref="ae5950524d88a3df056c82b02c4c92b3d" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>messageFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a67a58503e67be9efbc52abd746a0f402"></a><!-- doxytag: member="TTDefaultStyleSheet::errorTitleFont" ref="a67a58503e67be9efbc52abd746a0f402" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>errorTitleFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab3240d3d33f5703d68190cf12868b283"></a><!-- doxytag: member="TTDefaultStyleSheet::errorSubtitleFont" ref="ab3240d3d33f5703d68190cf12868b283" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>errorSubtitleFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a04c070cb0eb197c74c5d93eb467d4842"></a><!-- doxytag: member="TTDefaultStyleSheet::activityLabelFont" ref="a04c070cb0eb197c74c5d93eb467d4842" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>activityLabelFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1bcd4301800d633003ee793d44498c3d"></a><!-- doxytag: member="TTDefaultStyleSheet::activityBannerFont" ref="a1bcd4301800d633003ee793d44498c3d" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>activityBannerFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a81c3943b224b592169e6035b83fc2ba8"></a><!-- doxytag: member="TTDefaultStyleSheet::tableSelectionStyle" ref="a81c3943b224b592169e6035b83fc2ba8" args="" -->
UITableViewCellSelectionStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableSelectionStyle</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3f18a798c0aadca89cadf0218d507f86"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderLastUpdatedFont" ref="a3f18a798c0aadca89cadf0218d507f86" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderLastUpdatedFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac1cd6d155b1ccd0ae508bad3dbd48328"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderStatusFont" ref="ac1cd6d155b1ccd0ae508bad3dbd48328" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderStatusFont</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9a27743c0752e41f14f87c492efd529c"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderBackgroundColor" ref="a9a27743c0752e41f14f87c492efd529c" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderBackgroundColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a84b5722d570fadf6850d7f955a4b89d0"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderTextColor" ref="a84b5722d570fadf6850d7f955a4b89d0" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderTextColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5191ea4b2eb3e98653d26f800f610a57"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderTextShadowColor" ref="a5191ea4b2eb3e98653d26f800f610a57" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderTextShadowColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac0a97081779936aeddec58a64643b708"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderTextShadowOffset" ref="ac0a97081779936aeddec58a64643b708" args="" -->
CGSize&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderTextShadowOffset</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a049907d79f3d5cde42604015f6d3e65b"></a><!-- doxytag: member="TTDefaultStyleSheet::tableRefreshHeaderArrowImage" ref="a049907d79f3d5cde42604015f6d3e65b" args="" -->
<a class="el" href="class_u_i_image.php">UIImage</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>tableRefreshHeaderArrowImage</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20Style/Headers/<a class="el" href="_t_t_default_style_sheet_8h_source.php">TTDefaultStyleSheet.h</a></li>
<li>Three20Style/Sources/TTDefaultStyleSheet.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
