<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: TTActivityLabel Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://dev.three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://dev.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div id="fb-root"></div> 
<script> 
  window.fbAsyncInit = function() {
    FB.init({
      appId   : '165692500131929',
      session : {"access_token":"165692500131929|2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446|7YjdqHOYyL6MXMHd-udsP0EbTsg","base_domain":"three20.info","expires":"1298952000","secret":"Hcv3uGki22DI7f_imqBhgQ__","session_key":"2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446","sig":"fdaa725c7cf196ce9579d1b232a16e64","uid":"122605446"}, // don't refetch the session when PHP already has it
      status  : true, // check login status
      cookie  : true, // enable cookies to allow the server to access the session
      xfbml   : true // parse XFBML
    });
 
    // whenever the user logs in, we refresh the page
    FB.Event.subscribe('auth.login', function() {
      window.location.reload();
    });
  };
 
  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script> 
 
<ul class="right-links"> 
<li><img class="profileimg" width="25" height="25" valign="bottom" src="https://graph.facebook.com/122605446/picture?type=square">Jeff Verkoeyen</li> 
<li><a href="https://www.facebook.com/logout.php?next=http%3A%2F%2Fdev.three20.info%2F&access_token=165692500131929%7C2.cwAeriJtimeS2wNxeTCEqQ__.3600.1298952000-122605446%7C7YjdqHOYyL6MXMHd-udsP0EbTsg" onclick="FB.logout(function() { window.location.reload();}); return false;">Log out</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTActivityLabel Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTActivityLabel" --><!-- doxytag: inherits="UIView" --><div class="dynheader">
Inheritance diagram for TTActivityLabel:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_activity_label.png" usemap="#TTActivityLabel_map" alt=""/>
  <map id="TTActivityLabel_map" name="TTActivityLabel_map">
<area href="class_u_i_view.php" alt="UIView" shape="rect" coords="0,0,99,24"/>
</map>
</div>

<p><a href="class_t_t_activity_label-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2f0a095fe12d8fcc94f6d7a688160473"></a><!-- doxytag: member="TTActivityLabel::initWithFrame:style:" ref="a2f0a095fe12d8fcc94f6d7a688160473" args="(CGRect frame,[style] TTActivityLabelStyle style)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithFrame:style:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a62dd9fdd7ae635a07f464ebabdf47a3a"></a><!-- doxytag: member="TTActivityLabel::initWithFrame:style:text:" ref="a62dd9fdd7ae635a07f464ebabdf47a3a" args="(CGRect frame,[style] TTActivityLabelStyle style,[text] NSString *text)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithFrame:style:text:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a732ec02ea19497c199d2c645d14a0397"></a><!-- doxytag: member="TTActivityLabel::initWithStyle:" ref="a732ec02ea19497c199d2c645d14a0397" args="(TTActivityLabelStyle style)" -->
(id)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>initWithStyle:</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a221966d99b2135208130e15e41a45c3e"></a><!-- doxytag: member="TTActivityLabel::_style" ref="a221966d99b2135208130e15e41a45c3e" args="" -->
TTActivityLabelStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>_style</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa5085d54fc6212ca36b7279a760b887c"></a><!-- doxytag: member="TTActivityLabel::_bezelView" ref="aa5085d54fc6212ca36b7279a760b887c" args="" -->
<a class="el" href="interface_t_t_view.php">TTView</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_bezelView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4d2feb7fb305f756e8cade1494f0bb6b"></a><!-- doxytag: member="TTActivityLabel::_progressView" ref="a4d2feb7fb305f756e8cade1494f0bb6b" args="" -->
UIProgressView *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_progressView</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3cd98d3ad140aab511eda52fd001dcdb"></a><!-- doxytag: member="TTActivityLabel::_activityIndicator" ref="a3cd98d3ad140aab511eda52fd001dcdb" args="" -->
UIActivityIndicatorView *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_activityIndicator</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2d43d2e1152d4173d7ca6ccd4fd905a6"></a><!-- doxytag: member="TTActivityLabel::_label" ref="a2d43d2e1152d4173d7ca6ccd4fd905a6" args="" -->
UILabel *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_label</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa40bc8640fb0542acb90b0a6552c7db1"></a><!-- doxytag: member="TTActivityLabel::_progress" ref="aa40bc8640fb0542acb90b0a6552c7db1" args="" -->
float&nbsp;</td><td class="memItemRight" valign="bottom"><b>_progress</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a97c60a3646913fdb2a2f75bb02e56943"></a><!-- doxytag: member="TTActivityLabel::_smoothesProgress" ref="a97c60a3646913fdb2a2f75bb02e56943" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>_smoothesProgress</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a380e0c448250c0dfdb5a6174c9e37106"></a><!-- doxytag: member="TTActivityLabel::_smoothTimer" ref="a380e0c448250c0dfdb5a6174c9e37106" args="" -->
NSTimer *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_smoothTimer</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a322631041ac1cd44f9eef39c9027454a"></a><!-- doxytag: member="TTActivityLabel::style" ref="a322631041ac1cd44f9eef39c9027454a" args="" -->
TTActivityLabelStyle&nbsp;</td><td class="memItemRight" valign="bottom"><b>style</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8ae872a4669b61b712eee8e111f6983f"></a><!-- doxytag: member="TTActivityLabel::text" ref="a8ae872a4669b61b712eee8e111f6983f" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a25ca2d4ba2de3e356626f4e695da8aa4"></a><!-- doxytag: member="TTActivityLabel::font" ref="a25ca2d4ba2de3e356626f4e695da8aa4" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3dc7525dba9195380cc2cf61d9caf69a"></a><!-- doxytag: member="TTActivityLabel::progress" ref="a3dc7525dba9195380cc2cf61d9caf69a" args="" -->
float&nbsp;</td><td class="memItemRight" valign="bottom"><b>progress</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0bf4babad37eba997b9a7097c53db9a2"></a><!-- doxytag: member="TTActivityLabel::isAnimating" ref="a0bf4babad37eba997b9a7097c53db9a2" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>isAnimating</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a968f483016aba15f3916a56bae966764"></a><!-- doxytag: member="TTActivityLabel::smoothesProgress" ref="a968f483016aba15f3916a56bae966764" args="" -->
BOOL&nbsp;</td><td class="memItemRight" valign="bottom"><b>smoothesProgress</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_activity_label_8h_source.php">TTActivityLabel.h</a></li>
<li>Three20UI/Sources/TTActivityLabel.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
