<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: TTSearchlightLabel Class Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<!-- HEADER --> 
 
<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://api.three20.info/">API</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<ul class="right-links"> 
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#properties">Properties</a>  </div>
  <div class="headertitle">
<h1>TTSearchlightLabel Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTSearchlightLabel" --><!-- doxytag: inherits="UIView" --><div class="dynheader">
Inheritance diagram for TTSearchlightLabel:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_t_t_searchlight_label.png" usemap="#TTSearchlightLabel_map" alt=""/>
  <map id="TTSearchlightLabel_map" name="TTSearchlightLabel_map">
<area href="class_u_i_view.php" alt="UIView" shape="rect" coords="0,0,121,24"/>
</map>
</div>

<p><a href="class_t_t_searchlight_label-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aafe9e67bfa63ab29e67b1f071310d7ac"></a><!-- doxytag: member="TTSearchlightLabel::startAnimating" ref="aafe9e67bfa63ab29e67b1f071310d7ac" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>startAnimating</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a64303e85fdf718dfbfb3bc7954bda445"></a><!-- doxytag: member="TTSearchlightLabel::stopAnimating" ref="a64303e85fdf718dfbfb3bc7954bda445" args="()" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>stopAnimating</b></td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a50a2c2def5fda998d729e8aeb6a01d16"></a><!-- doxytag: member="TTSearchlightLabel::_text" ref="a50a2c2def5fda998d729e8aeb6a01d16" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1e04b1b9b7c1cc451c2c11db2f462993"></a><!-- doxytag: member="TTSearchlightLabel::_font" ref="a1e04b1b9b7c1cc451c2c11db2f462993" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a4d1aaac3ddd1b066a7a156b6d7ad72ab"></a><!-- doxytag: member="TTSearchlightLabel::_textColor" ref="a4d1aaac3ddd1b066a7a156b6d7ad72ab" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_textColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a82fce079d5505030af0e58a76014005b"></a><!-- doxytag: member="TTSearchlightLabel::_spotlightColor" ref="a82fce079d5505030af0e58a76014005b" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_spotlightColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad024c9c495588284acffca75a4725a53"></a><!-- doxytag: member="TTSearchlightLabel::_textAlignment" ref="ad024c9c495588284acffca75a4725a53" args="" -->
UITextAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>_textAlignment</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a06501cb746fe0f489f3020af6335be77"></a><!-- doxytag: member="TTSearchlightLabel::_timer" ref="a06501cb746fe0f489f3020af6335be77" args="" -->
NSTimer *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_timer</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa959638593cc3e1208fc78982e54201d"></a><!-- doxytag: member="TTSearchlightLabel::_spotlightPoint" ref="aa959638593cc3e1208fc78982e54201d" args="" -->
CGFloat&nbsp;</td><td class="memItemRight" valign="bottom"><b>_spotlightPoint</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5c9ba2775a5f9d98c685b9c2ea9c9380"></a><!-- doxytag: member="TTSearchlightLabel::_maskContext" ref="a5c9ba2775a5f9d98c685b9c2ea9c9380" args="" -->
CGContextRef&nbsp;</td><td class="memItemRight" valign="bottom"><b>_maskContext</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa4f36534612013b296b92cc5f42474d8"></a><!-- doxytag: member="TTSearchlightLabel::_maskData" ref="aa4f36534612013b296b92cc5f42474d8" args="" -->
void *&nbsp;</td><td class="memItemRight" valign="bottom"><b>_maskData</b></td></tr>
<tr><td colspan="2"><h2><a name="properties"></a>
Properties</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8f3a5ea168cb4a50d588f0f66ae6fc48"></a><!-- doxytag: member="TTSearchlightLabel::text" ref="a8f3a5ea168cb4a50d588f0f66ae6fc48" args="" -->
<a class="el" href="class_n_s_string.php">NSString</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>text</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af7884b224b015a397c315f62fe388f8d"></a><!-- doxytag: member="TTSearchlightLabel::font" ref="af7884b224b015a397c315f62fe388f8d" args="" -->
<a class="el" href="class_u_i_font.php">UIFont</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>font</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac40a583aee375b5cd2ebb36fa3511c6f"></a><!-- doxytag: member="TTSearchlightLabel::textColor" ref="ac40a583aee375b5cd2ebb36fa3511c6f" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>textColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0dac183dff87f7855471d162f1dd2759"></a><!-- doxytag: member="TTSearchlightLabel::spotlightColor" ref="a0dac183dff87f7855471d162f1dd2759" args="" -->
<a class="el" href="class_u_i_color.php">UIColor</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><b>spotlightColor</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5cc4e1cc6d90d40d37e4024da434bc8d"></a><!-- doxytag: member="TTSearchlightLabel::textAlignment" ref="a5cc4e1cc6d90d40d37e4024da434bc8d" args="" -->
UITextAlignment&nbsp;</td><td class="memItemRight" valign="bottom"><b>textAlignment</b></td></tr>
</table>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_searchlight_label_8h_source.php">TTSearchlightLabel.h</a></li>
<li>Three20UI/Sources/TTSearchlightLabel.m</li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
