<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta property="fb:app_id" content="114720825217072"/>
  <meta property="fb:admins" content="122605446"/>
  <meta property="og:title" content="three20.info"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://three20.info/"/>
  <meta property="og:image" content="http://github.com/facebook/three20/raw/06cd0abe33ac39d1f509e278e286c6bf1e45e821/samples/Resources/Icon.png"/>
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" />
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
  <title>Three20: &lt;TTScrollViewDelegate&gt; Protocol Reference</title>
<link href="http://new.three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/global.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/article.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/>
<link href="http://new.three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>

<div id="page-wrapper">

<div id="header">
<div class="fixed-width">
<ul class="left-links">
  <li>&larr; <a href="http://new.three20.info/">Home</a></li>
</ul>
<ul class="right-links">
  <li><a href="http://<?= $_SERVER['SERVER_NAME']?><?= $_SERVER['REQUEST_URI'] ?>#disqus_thread">Comments</a></li>
</ul>
</div> <!-- .fixed-width -->
</div>

<div id="content">
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.php"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<h1>&lt;TTScrollViewDelegate&gt; Protocol Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTScrollViewDelegate-p" --><div class="dynheader">
Inheritance diagram for &lt;TTScrollViewDelegate&gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="protocol_t_t_scroll_view_delegate-p.png" usemap="#&lt;TTScrollViewDelegate&gt;_map" alt=""/>
  <map id="&lt;TTScrollViewDelegate&gt;_map" name="&lt;TTScrollViewDelegate&gt;_map">
<area href="interface_t_t_photo_view_controller.php" alt="TTPhotoViewController" shape="rect" coords="0,56,151,80"/>
</map>
</div>

<p><a href="protocol_t_t_scroll_view_delegate-p-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad76ed9fd2cb508a51522c11d3b3079c2"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollView:didMoveToPageAtIndex:" ref="ad76ed9fd2cb508a51522c11d3b3079c2" args="(TTScrollView *scrollView,[didMoveToPageAtIndex] NSInteger pageIndex)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollView:didMoveToPageAtIndex:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ab11ebb2e5c6a6b3e497f305f9266909a"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewWillRotate:toOrientation:" ref="ab11ebb2e5c6a6b3e497f305f9266909a" args="(TTScrollView *scrollView,[toOrientation] UIInterfaceOrientation orientation)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewWillRotate:toOrientation:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6b9dc55a7de89e18f2251629cfeebbd0"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidRotate:" ref="a6b9dc55a7de89e18f2251629cfeebbd0" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidRotate:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8685d98c7bf5f7ffdd6edeebd57dcf87"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewWillBeginDragging:" ref="a8685d98c7bf5f7ffdd6edeebd57dcf87" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewWillBeginDragging:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a6507d16e8b2d2315953fe87e3d016827"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidEndDragging:willDecelerate:" ref="a6507d16e8b2d2315953fe87e3d016827" args="(TTScrollView *scrollView,[willDecelerate] BOOL willDecelerate)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidEndDragging:willDecelerate:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad97c75373200e1c6c347612a385170cc"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewWillBeginDecelerating:" ref="ad97c75373200e1c6c347612a385170cc" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewWillBeginDecelerating:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac51be0badb69e53d1a4692949deccde4"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidEndDecelerating:" ref="ac51be0badb69e53d1a4692949deccde4" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidEndDecelerating:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa97d32502bc9a5c994e568fc298c9d6e"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewShouldZoom:" ref="aa97d32502bc9a5c994e568fc298c9d6e" args="(TTScrollView *scrollView)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewShouldZoom:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a66309c9dcd11ee04a1205cd86667679e"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidBeginZooming:" ref="a66309c9dcd11ee04a1205cd86667679e" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidBeginZooming:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a13fb403137d85c4c7c2653efb4ca9e97"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidEndZooming:" ref="a13fb403137d85c4c7c2653efb4ca9e97" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidEndZooming:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aab6b115f36bda540238088a88b1bb22d"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollView:touchedDown:" ref="aab6b115f36bda540238088a88b1bb22d" args="(TTScrollView *scrollView,[touchedDown] UITouch *touch)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollView:touchedDown:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1974807c92c1e4ade3a22cec9fa495e2"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollView:touchedUpInside:" ref="a1974807c92c1e4ade3a22cec9fa495e2" args="(TTScrollView *scrollView,[touchedUpInside] UITouch *touch)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollView:touchedUpInside:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="acf9957c0ca91d7746b93b70b1345a88a"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollView:tapped:" ref="acf9957c0ca91d7746b93b70b1345a88a" args="(TTScrollView *scrollView,[tapped] UITouch *touch)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollView:tapped:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9eb190153531cc37c7181cc7784b39f8"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidBeginHolding:" ref="a9eb190153531cc37c7181cc7784b39f8" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidBeginHolding:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a398ebd7a59c54d02e7848a27c42cf50c"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollViewDidEndHolding:" ref="a398ebd7a59c54d02e7848a27c42cf50c" args="(TTScrollView *scrollView)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollViewDidEndHolding:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a347b887dd4c49bef2b3f01ce06017c71"></a><!-- doxytag: member="TTScrollViewDelegate&#45;p::scrollView:shouldAutorotateToInterfaceOrientation:" ref="a347b887dd4c49bef2b3f01ce06017c71" args="(TTScrollView *scrollView,[shouldAutorotateToInterfaceOrientation] UIInterfaceOrientation orientation)" -->
(BOOL)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>scrollView:shouldAutorotateToInterfaceOrientation:</b></td></tr>
</table>
<hr/>The documentation for this protocol was generated from the following file:<ul>
<li>Three20UI/Headers/<a class="el" href="_t_t_scroll_view_delegate_8h_source.php">TTScrollViewDelegate.h</a></li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>


</div> <!-- .fixed-width -->

<div class="fixed-width">
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div> <!-- .fixed-width -->

</div> <!-- #content -->
</div> <!-- #page-wrapper -->

<noscript><p><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/155532ns.gif" /></p></noscript>

<script type="text/javascript">//<![CDATA[

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

//]]>
</script>

<script type="text/javascript" src="http://static.getclicky.com/js"></script>

<script type="text/javascript">//<![CDATA[
clicky.init(155532);
//]]>
</script>

<script type="text/javascript">//<![CDATA[

try {
var pageTracker = _gat._getTracker("UA-11762059-1");
pageTracker._trackPageview();
} catch(err) {}
//]]>
</script>

<script type="text/javascript">
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
