<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://opengraphprotocol.org/schema/"
      xmlns:fb="http://www.facebook.com/2008/fbml" xml:lang="en" lang="en"> 
<head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
  <meta property="fb:app_id" content="114720825217072"/> 
  <meta property="fb:admins" content="122605446"/> 
  <meta property="og:title" content="three20.info"/> 
  <meta property="og:type" content="website"/> 
  <meta property="og:url" content="http://three20.info/"/> 
  <meta property="og:image" content="http://github.com/facebook/three20/raw/master/samples/Resources/Icon.png"/> 
  <meta name="keywords" content="three20 iPhone api open source library uikit tt" /> 
  <meta name="description" content="API documentation, articles, and tutorials related to the three20 iPhone library." />
<title>Three20 API: &lt;TTModelDelegate&gt; Protocol Reference</title>
<link href="http://three20.info/css/reset.css" rel="stylesheet" type="text/css"/>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="http://three20.info/css/global.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/article.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/headerbar.css" rel="stylesheet" type="text/css"/> 
<link href="http://three20.info/css/api.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<div id="page-wrapper"> 

<!-- HEADER -->

<div id="header"> 
<div class="fixed-width"> 
 
<ul class="right-links"> 
  <li><a href="http://three20.info/roadmap">Roadmap</a></li> 
  <li><a href="http://three20.info/documentation">Documentation</a></li> 
  <li><a href="http://three20.info/extensions">Extensions</a></li> 
  <li><a href="http://three20.info/community">Community</a></li> 
</ul> 
 
<div class="leadin"> 
  <h1><a href="http://three20.info/">Three20</a></h1> 
  <h2><a href="http://three20.info/">An open-source library for iOS applications</a></h2> 
</div> <!-- .leadin --> 
 
</div> <!-- .fixed-width --> 
</div> <!-- #header --> 

<!-- CONTENT -->

<div id="content"> 
<div class="fixed-width">
<!-- Generated by Doxygen 1.7.1 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li><a href="examples.php"><span>Examples</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.php"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<h1>&lt;TTModelDelegate&gt; Protocol Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TTModelDelegate-p" --><div class="dynheader">
Inheritance diagram for &lt;TTModelDelegate&gt;:</div>
<div class="dyncontent">
 <div class="center">
  <img src="protocol_t_t_model_delegate-p.png" usemap="#&lt;TTModelDelegate&gt;_map" alt=""/>
  <map id="&lt;TTModelDelegate&gt;_map" name="&lt;TTModelDelegate&gt;_map">
<area href="interface_mock_model_delegate.php" alt="MockModelDelegate" shape="rect" coords="0,56,157,80"/>
<area href="interface_t_t_model_view_controller.php" alt="TTModelViewController" shape="rect" coords="542,56,699,80"/>
<area href="interface_t_t_photo_view_controller.php" alt="TTPhotoViewController" shape="rect" coords="0,112,157,136"/>
<area href="interface_t_t_popup_view_controller.php" alt="TTPopupViewController" shape="rect" coords="250,112,407,136"/>
<area href="interface_t_t_table_view_controller.php" alt="TTTableViewController" shape="rect" coords="835,112,992,136"/>
<area href="interface_t_t_web_controller.php" alt="TTWebController" shape="rect" coords="1002,112,1159,136"/>
<area href="interface_t_t_action_sheet_controller.php" alt="TTActionSheetController" shape="rect" coords="0,168,157,192"/>
<area href="interface_t_t_alert_view_controller.php" alt="TTAlertViewController" shape="rect" coords="167,168,324,192"/>
<area href="interface_t_t_post_controller.php" alt="TTPostController" shape="rect" coords="334,168,491,192"/>
<area href="interface_t_t_text_bar_controller.php" alt="TTTextBarController" shape="rect" coords="501,168,658,192"/>
<area href="interface_t_t_extension_info_controller.php" alt="TTExtensionInfoController" shape="rect" coords="668,168,825,192"/>
<area href="interface_t_t_extensions_controller.php" alt="TTExtensionsController" shape="rect" coords="835,168,992,192"/>
<area href="interface_t_t_thumbs_view_controller.php" alt="TTThumbsViewController" shape="rect" coords="1002,168,1159,192"/>
</map>
</div>

<p><a href="protocol_t_t_model_delegate-p-members.php">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a5df22439eaf4f407a261ad79c03f55c4"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidStartLoad:" ref="a5df22439eaf4f407a261ad79c03f55c4" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidStartLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a68a9663728353e79b48867bbda192d3a"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidFinishLoad:" ref="a68a9663728353e79b48867bbda192d3a" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidFinishLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a1d09bbb97be34017532f5705bac1aab0"></a><!-- doxytag: member="TTModelDelegate&#45;p::model:didFailLoadWithError:" ref="a1d09bbb97be34017532f5705bac1aab0" args="(id&lt; TTModel &gt; model,[didFailLoadWithError] NSError *error)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didFailLoadWithError:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0c05ffe2a2e74cea34275819610b3940"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidCancelLoad:" ref="a0c05ffe2a2e74cea34275819610b3940" args="(id&lt; TTModel &gt; model)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>modelDidCancelLoad:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a2f3a9659380ba388b9a475d6761e5143">modelDidChange:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model has changed in some fundamental way.  <a href="#a2f3a9659380ba388b9a475d6761e5143"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af16cbcde168b818c04e8f97983ccb435"></a><!-- doxytag: member="TTModelDelegate&#45;p::model:didUpdateObject:atIndexPath:" ref="af16cbcde168b818c04e8f97983ccb435" args="(id&lt; TTModel &gt; model,[didUpdateObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didUpdateObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ae897d061f4b78ef523cb179bcbe498c3"></a><!-- doxytag: member="TTModelDelegate&#45;p::model:didInsertObject:atIndexPath:" ref="ae897d061f4b78ef523cb179bcbe498c3" args="(id&lt; TTModel &gt; model,[didInsertObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didInsertObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a2f4f7858bd3ab9e36b4c54594f09e47e"></a><!-- doxytag: member="TTModelDelegate&#45;p::model:didDeleteObject:atIndexPath:" ref="a2f4f7858bd3ab9e36b4c54594f09e47e" args="(id&lt; TTModel &gt; model,[didDeleteObject] id object,[atIndexPath] NSIndexPath *indexPath)" -->
(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <b>model:didDeleteObject:atIndexPath:</b></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a58855366f525d711b76767007d99fd43">modelDidBeginUpdates:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model is about to begin a multi-stage update.  <a href="#a58855366f525d711b76767007d99fd43"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">(void)&nbsp;</td><td class="memItemRight" valign="bottom">- <a class="el" href="protocol_t_t_model_delegate-p.php#a3aa2a5802f68a87df0605342d8b4ca7a">modelDidEndUpdates:</a></td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Informs the delegate that the model has completed a multi-stage update.  <a href="#a3aa2a5802f68a87df0605342d8b4ca7a"></a><br/></td></tr>
</table>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a58855366f525d711b76767007d99fd43"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidBeginUpdates:" ref="a58855366f525d711b76767007d99fd43" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidBeginUpdates: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model is about to begin a multi-stage update. </p>
<p>Models should use this method to condense multiple updates into a single visible update. This avoids having the view update multiple times for each change. Instead, the user will only see the end result of all of your changes when you call modelDidEndUpdates. </p>

</div>
</div>
<a class="anchor" id="a2f3a9659380ba388b9a475d6761e5143"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidChange:" ref="a2f3a9659380ba388b9a475d6761e5143" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidChange: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model has changed in some fundamental way. </p>
<p>The change is not described specifically, so the delegate must assume that the entire contents of the model may have changed, and react almost as if it was given a new model. </p>

</div>
</div>
<a class="anchor" id="a3aa2a5802f68a87df0605342d8b4ca7a"></a><!-- doxytag: member="TTModelDelegate&#45;p::modelDidEndUpdates:" ref="a3aa2a5802f68a87df0605342d8b4ca7a" args="(id&lt; TTModel &gt; model)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">- (void) modelDidEndUpdates: </td>
          <td></td>
          <td class="paramtype">(id&lt; <a class="el" href="interface_t_t_model.php">TTModel</a> &gt;)&nbsp;</td>
          <td class="paramname"> <em>model</em></td>
          <td>&nbsp;</td>
          <td><code> [optional]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Informs the delegate that the model has completed a multi-stage update. </p>
<p>The exact nature of the change is not specified, so the receiver should investigate the new state of the model by examining its properties. </p>

</div>
</div>
<hr/>The documentation for this protocol was generated from the following file:<ul>
<li>Three20Network/Headers/<a class="el" href="_t_t_model_delegate_8h_source.php">TTModelDelegate.h</a></li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Properties</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="disqus_thread"></div> 
<script type="text/javascript"> 
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http://three20info2.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=three20info2">comments powered by Disqus.</a></noscript> 
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a> 
</div> <!-- .fixed-width --> 
 
</div> <!-- #content --> 
</div> <!-- #page-wrapper --> 
 
 
 
<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19295672-1']);
  _gaq.push(['_setDomainName', '.three20.info']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script> 
 
<script type="text/javascript"> 
var disqus_shortname = 'three20info2';
(function () {
  var s = document.createElement('script'); s.async = true;
  s.src = 'http://disqus.com/forums/three20info2/count.js';
  (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script> 
 
 
</body> 
</html>
